project:
  type: book
  output-dir: docs


book:
  title: "UN Handbook on Remote Sensing for Agricultural Statistics"
  reader-mode: true

  page-footer:
    background: "#21618c"
    left: |
      Edited by Gilberto Camara, Lorenzo de Simone and Ronald Jansen.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  site-url: https://FAO-EOSTAT.github.io/UN-Handbook/
  repo-url: https://github.com/FAO-EOSTAT/UN-Handbook
  repo-branch: quarto
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - howto.qmd
    - introduction.qmd
    - part: theory.qmd
      chapters: 
        - th_remote_sensing.qmd
        - th_data_sources.qmd
        - th_data_cubes.qmd
        - th_lucc.qmd
        - th_quality_control.qmd
        - th_machine_learning.qmd
        - th_uncertainty.qmd
        - th_validation.qmd
        - th_design_frames.qmd
        - th_alignment.qmd
        - th_parcel_extraction.qmd
    - part: crop_type_mapping.qmd
      chapters:
        - ct_poland.qmd
        - ct_mexico.qmd
        - ct_zimbabwe.qmd
        - ct_china.qmd
        - ct_chile.qmd
        - ct_digital_earth_africa.qmd
    - part: crop_yield_estimation.qmd
      chapters:
        - cy_finland.qmd
        - cy_indonesia.qmd
        - cy_colombia.qmd
        - cy_poland.qmd
        - cy_china.qmd
    - part: crop_statistics.qmd
      chapters:
        - crop_statistics_area.qmd
        - crop_statistics_regression.qmd
        - crop_statistics_calibration.qmd
        - crop_statistics_ppi.qmd
    - part: uav_agriculture.qmd
      chapters:
        - uav_field_parcels.qmd
        - uav_wheat_growth.qmd
        - uav_crop_growth.qmd
        - uav_agriculture_cook_islands.qmd
    - part: disaster_response.qmd
      chapters:
        - dis_china_floods.qmd
    - part: additional.qmd
      chapters:
        - ad_world_cereal.qmd
        - ad_learning.qmd
format:
  html:
    theme:
      - litera
      - handbook.scss
    code-link: true
    author-meta: "Gilberto Camara, Lorenzo de Simone, Ronald Jansen"
    callout-appearance: simple

bibliography:
    - bibliography/un-handbook.bib
    - bibliography/colombia.bib
    - bibliography/references-ibge.bib
    - bibliography/e-sensing.bib
    - bibliography/indonesia.bib
    - bibliography/mexico.bib
    - bibliography/deafrica.bib
    - bibliography/chile.bib
    - bibliography/ad-ppi.bib
    - bibliography/finland.bib
    - bibliography/cook-islands.bib
    - bibliography/zimbabwe.bib
    - bibliography/world-cereal.bib

csl: ieee.csl

filters:
  - cslovell/reproducible
  - handbook/reproducible-local
