# About the Authors {-}


## Editors{-}

**Gilberto Camara** is a Senior Researcher at Brazil’s National Institute for Space Research (INPE) and at the Center for Agri-business Studies at Fundação Getúlio Vargas (FGV). Gilberto was INPE's Director from 2005 to 2012 and Secretariat Director of the Group on Earth Observations (GEO) from 2018 to 2021. His areas of expertise are Geoinformatics, GIScience, Land Use Change, Land Use Policy, Remote Sensing, and Big Earth Observation Analytics. He has advised 57 graduate students and received more than 19,000 citations, with an H-index of 61 (Google Scholar, November/2025). He is a *Doctor honoris causa* by the University of Münster (Germany) and received the William T. Pecora award from NASA and USGS for *"leadership to the broad and open access to remote sensing data"*.  

## Chapter Authors {-}

**Luis Ambrosio-Flores** is professor of Statistics at Universidade Politecnica de Madrid, Spain. He is an expert in agricultural and environmental statistics, econometric modeling, climate impact assessment, and EU biodiversity frameworks. He has led 30 research projects and served as consultant (ESA, FAO, EU). Key projects: SEN4Stat - Sentinels for Agricultural Statistics;  Global Strategy (GS)-Improving Agricultural & Rural Statistics; Econometric models for assessing climate change impact on agriculture and environment (Spanish Ministry of Science and Technology). Author of 50 publications with 404 citations on Google Scholar.

**Edemir Andrade** is a Data Science consultant at the Brazilian Institute of Geography and Statistics (IBGE). He holds a PhD in Computer Science (UFMG, 2023). His major areas of expertise are in  visual pattern recognition, deep learning, and machine learning.  His goal is to advance research and applied technologies in computer vision, bridging the gap between scientific knowledge and real-world impact.


**Inbal Becker-Reshef** is Co-Director of NASA Harvest, NASA's Global program on food supply and agriculture, and a Research Professor in the Department of Geographical Sciences at the University of Maryland, a Fellow at University of Strasbourg's Institute for Advanced Studies, and Managing Director for Microsoft's AI for Good Lab. She leads multidisciplinary research and initiatives focused on advancing agricultural monitoring, sustainability and food security at local to global scales, with an emphasis on co-development with partners across the public and private sectors. Her contributions have been recognized with several awards, including the NASA Exceptional Public Service Medal, US APEC Science Prize for Innovation, Research, and Education (ASPIRE), and the Arrell Food Prize.

**Sophie Bontemps** is a Senior Scientist and Project Manager at UCLouvain (Belgium). She graduated as a bio-engineer in land use planning from UCLouvain in 2004 and earned her PhD in 2010 on land cover change detection using high-temporal-resolution satellite data at continental scales. Sophie played a key role in several ESA initiatives, including the GlobCover, GlobCorine, and CCI-LandCover projects, contributing to both land cover mapping and validation. Since 2014, her work has focused on agriculture, leading major international projects such as ESA’s Sen2-Agri, Sen4CAP and Sen4Stat, as well as FAO EOSTAT initiatives, developing innovative methods for crop mapping, monitoring farming practices, and supporting agricultural statistics. She has extensive experience in national field campaign design and user community engagement. Sophie also served as co-chair of the CEOS Land Product Validation Subgroup and is a member of the GEOGLAM Executive Committee. 

**Anthony Burgard** is a consultant for the  Data Division, Economic Research and Development Impact Department, Asian Development Bank. He has more than 16 years of expertise in the design and implementation of agricultural censuses and surveys across the Asia-Pacific region. His work leverages cost-effective technologies like digital data collection using tablets and drones, geographic information systems, and remote sensing. Anthony holds degrees in Economics from the University of California, Berkeley, and Chulalongkorn University.

**Tao Cheng** is professor at Nanjing Agricultural University. His main research interests include crop mapping and monitoring, crop phenotyping, imaging and non-imaging spectroscopy of vegetation, quantitative remote sensing, machine learning, and image analysis. He has served as a Guest Editor of a Special Issue in Remote Sensing and has been serving on the Editorial Board of ISPRS International Journal of Geo-Information since 2015. 

**Phibion Chiwara** is the Remote Sensing and GIS Specialist with the Food and Agriculture Organization of the United Nations (FAO) in the Zimbabwe Country Office. He is an active contributor to the FAO-EOSTAT project, where he has led in-situ data collection, automated quality control of field data, and time-series analysis of satellite imagery for crop type and land cover mapping in Zimbabwe. Phibion is an Erasmus Mundus scholar and holds a double master’s degree in Geo-information Science and Earth Observation for Environmental Modelling and Management from the University of Southampton and Lund University.

**Abel Coronado** is the Deputy Director of Research in Data Science at Mexico's National Institute of Statistics and Geography (INEGI). As a national expert in satellite imagery and large-scale Earth Observation (EO) data, he leads remote sensing initiatives to contribute to the improvement of the country's agricultural statistics. His scientific expertise spans data science, machine learning, and spatial data integration, fields in which he has authored several publications.

**Pierre Defourny** is founding president of the UCLouvain Earth and Life Institute and full professor at the Faculty of Bioscience Engineering. He leads the Geomatics Research Laboratory at the Université catholique de Louvain (Belgium). As the scientific leader of the open-source systems Sen2Agri, Sen4CAP, and Sen4Stat, supported by ESA, he is a co-lead of the global JECAM network and a member of GEOGLAM. For the past 15 years, he has coordinated the longest global land cover map time series. Previously, he worked at the Institute of Technology in Thailand, was a visiting scientist at NASA’s Goddard Space Flight Center (USA), and collaborated with several international institutions in Africa and Mexico. He also serves as an independent expert for several ESA satellite missions."

**Xing Du** received the Ph.D. degree in cartography and geographical information systems from the Institute of Remote Sensing Applications, Chinese Academy of Sciences, Beijing, China, in 2011. He is currently an Associate Professor with the Aerospace Information Research Institute, Chinese Academy of Sciences. His research interests include remote sensing Big Data intelligent modeling, smart agriculture and remote sensing, and ecological and environmental remote sensing.

**Anna Christine Durante** is a consultant at the Data Division, Economic Research and Development Impact Department, Asian Development Bank. She specializes in innovative methodologies to support policymaking in the agriculture sector. She holds a degree in Agricultural Engineering from the University of the Philippines, and a master’s degree in Environment and Natural Resources Management from the same institution. Prior to joining ADB, she worked on agricultural policy analysis and development assistance projects at the Philippine Department of Agriculture.


**Achmad Fauzi Bagus Firmansyah** is a data scientist and analyst at Statistics Indonesia (BPS) who develops, implements, and evaluates algorithms for statistical indicators. He collaborates with international organizations, including FAO and UNESCAP. His current focus is the application of satellite imagery and machine learning for paddy-phase classification, contributing significantly to agricultural official statistics.

**Alexis Gamboa-Maldonado** is a geographer and holder of a Diploma in Data Science for Public Policy UAI. He has extensive experience as a geospatial analyst and technical coordinator in remote sensing projects for public and private institutions, both nationally and internationally. Currently, he works as Methodological Analyst at the National Institute of Statistics of Chile, supporting the development of a national LCLU map with emphasis on agricultural areas, data integration, and methodological innovation.  

**Zhi Gao** is a Professor of the School of Remote Sensing and Information Engineering and the Deputy Dean of the College of Elite Engineers at Wuhan University. He has served as a Researcher and Principal Investigator (PI) at the National University of Singapore. Professor Gao was selected for the National High-Level Overseas Talent Program, Distinguished Professor under the Chutian Scholars Program of Hubei Province. His research primarily focuses on remote sensing image interpretation, detection and diagnosis of surface anomalies.

**Xiaohe Gu** is an Associate Research Fellow at the National Engineering Research Center for Information Technology in Agriculture, Beijing, China. 
He obtained in PhD in Cartography and GIS from the School of Resources, Beijing Normal University in 2008. His research interests include Spatial Analysis, Remote Sensing for Agriculture, Land-Use Management, and Satellite Image Analysis.


**Rui Guo** earned her Ph.D. in 2025 from Beijing Normal University's Faculty of Geographical Science. Her research specializes in agricultural remote sensing and the monitoring of natural disasters. Her doctoral work leveraged multi-source remote sensing data and deep learning techniques to develop methods for crop growth monitoring, as well as for the identification and temporal tracking of natural disaster impacts. Findings from this research have been presented in journals including Computers and Electronics in Agriculture.

**Jacinta Holloway-Brown** is a Lecturer in the School of Computer and Mathematical Sciences at the University of Adelaide, Australia. She hold a PhD in Statistics and Remote Sensing from Queensland University of Technology, Australia. She was a Senior Project Officer with the Australian Bureau of Statistics (ABS), working with the UN Satellite Imagery and Geospatial Data Task Team. She is an author and editor of the UN Statistics Commission report on Satellite Imagery data for official statistics, published in 2017.

**Jinfeng Huang** is a professor Zhejiang University, China. His research focuses on agricultural remote sensing.  His  team has published nearly 400 papers in prominent academic journals. He has authored a series of scientific monographs on agricultural remote sensing and information technology.

**Dan Kluger** is a Michael Hammer Postdoctoral Fellow at the MIT Institute for Data Systems and Society, hosted by Professors Sherrie Wang and Stephen Bates. He is broadly interested in developing statistical methods for applications in agriculture and remote sensing. His current research is on methods for conducting reliable statistical analyses that leverage widely available, yet error-prone proxies. He completed his PhD in Statistics at Stanford University, advised by Professors Art Owen and David Lobell.

**Natalia Kotulak** is a consultant at the Statistical Office in Olsztyn, part of Poland’s Central Statistical Office. She specializes in applying satellite remote sensing and geospatial analysis to agriculture, sustainable development, and environmental monitoring presented her research at conferences on the use of remote sensing in public statistics. A graduate in Geodesy and Cartography from the University of Warmia and Mazury in Olsztyn, she has co-authored scientific publications on radar-based land displacement.

**Artur Łączyński** is a consultant in Department of Agriculture and Environment in Statistics Poland. He is a former director of Agriculture Department (2010-2023), works in agriculture, statistics, modern methods of data collection, methodology of surveys, and particularly use of satellite data in agricultural statistics. From 2018 to 2025, he was responsible for establishing a system that uses remote sensing data for crop monitoring in Poland. He is an international expert of European Commission, FAO, ILO, World Bank and has worked in several countries such as Azerbaijan, Croatia, Israel, Jordan, Kazakhstan, and Moldova.

**Pamela Lapitan** is a Statistics Officer, Data Division, Economic Research and Development Impact Department, Asian Development Bank. She has a degree in Statistics from the University of the Philippines Los Baños. Prior to joining ADB, she was officer-in-charge and statistical coordination officer of Regional Division IV of the National Statistical Coordination Board. She was also an instructor at the Rural High School and the Institute of Statistics of UPLB and worked for Bayer Philippines. Her interests include statistical analysis, planning and conducting surveys and experimental designs, geographic information systems, poverty statistics, national accounts, and small area estimation.

**Qiangzi Li** is a Professor at the Aerospace Information Research Institute of the Chinese Academy of Sciences, specially appointed professor of the Chinese Academy of Sciences, and foreign academician of the Russian Academy of Sciences. He has been engaged in fundamental research and monitoring practices of remote sensing applications in agriculture, natural resources, ecological environment, and public security. He has led or participated in more than 80 projects, including National Key Research and Development Programs and National Natural Science Foundation grants, and has published over 200 journal articles.

**Yifeng Luo** is a researcher at Zhejiang University, China, who
primarily focuses on remote sensing-based estimation and dynamic
monitoring of paddy rice planting area, providing data support for food
security.

**Xinming Ma** is a researcher at the College of Agronomy, Henan Agricultural University, Zhengzhou, China. 

**Takaaki Masaki** is Senior Economist (Data Science) on the Data Division, Economic Research and Development Impact Department of the Asian Development Bank. His work focuses on leveraging GIS, big data, and machine learning to enhance development statistics, support spatial targeting, and evaluate the distributional impact of policy interventions. Prior to joining ADB, he served as a Senior Economist in the World Bank’s Poverty and Equity Global Practice and previously worked at AidData. His research has been published in journals such as the Journal of Development Economics, World Bank Economic Review, World Development, and the Journal of Politics. He holds a PhD in Political Science from Cornell University.




**Tomasz Milewski** is deputy director of Department of Agriculture and Environment in Statistics Poland, organizational leader and expert concerning modern methods of data collection, particularly use of satellite data in agricultural and environmental statistics. In 2018-2021, he was responsible for organization of the system for satellite identification and monitoring of crops for the purposes of agricultural statistics, which delivers crucial information on crop area and yielding. He is the representative of Statistics Poland in UN-CEBD/UN-CEAG Task team on the use of EO data.

**Freddy Martinez** is an expert in Geomatics and Geodata Science who holds a MSc from the National University of Colombia. He leads the remote sensing laboratory at Colombia's FEDEARROZ (National Federation of Rice Producers) and works in close collaboration with DANE Colombia (National Statistics Office). His areas of knowledge are remote sensing (SAR & optical), GIS, spatial analysis, machine learning, and deep learning for crop monitoring (rice), developing packages in Python, R and Rust. 

**Kerrie Mengersen** is a Distinguished Professor of Statistics and Founding Director of the Centre for Data Science at the Queensland University of Technology in Brisbane, Australia. Her expertise is in the development and application of statistical and machine learning methods to address challenges in environment, health and society. She has a strong interest in agriculture and the use of satellite and other remotely sensed imagery. She is a long-standing member of the UN Task Team. 

**Nelson Mupfugami** is an statistician with the Zimbabwe National Statistics Agency (ZIMSTAT). He has more than 15 years of experience in production of official statistics within the National Statistics System. Currently, he is the manager responsible  for Agriculture and Environment Statistics and has contributed significantly  in the production of agriculture statistics in various fora. Nelson Mupfugami is a holder of Masters in Statistics and Operations Research from the National University of Science and Technology (NUST), Zimbabwe as well as Masters in Demography and Population Studies (Great Zimbabwe University).

**Boris Norgaard** is a PhD student in the Geomatics Lab at UCLouvain (Belgium). As part of the ESA Sen4Stat project, his doctoral work focuses on integrating Earth Observation data into agricultural statistics, with a particular emphasis on improving area estimation methods. He has collaborated with the Food and Agriculture Organization (FAO) and the World Bank in several countries on initiatives to design area sampling frame surveys for crop area estimation and to collect Earth Observation compatible ground data.

**Ian Nunes** is a Data Scientist and Researcher at IBGE, Brazil's National Institute of Geography and Statistics. He holds a Ph.D. in Computer Science from PUC-Rio. He serves as Leader in Data Intelligence and Innovation for Agricultural Statistics at IBGE, where he coordinates the methodological modernization of the Official Agricultural Statistics. He develops AI-based solutions for crop mapping, field operation optimization, and multimodal data analysis.

**Hugo Oliveira** is a Computer Science Professor at Universidade Federal de Viçosa (UFV). He holds a Ph.D. from Universidade Federal de Minas Gerais (UFMG). His research areas include Machine/Deep Learning, Computer Vision, Few-Shot Learning, Meta-Learning, Self-Supervised Learning, Foundational Models for Computer Vision, Generative Models, and Open-Set Recognition. These computational methods are applied to imaging domains such as remote sensing, medical imaging, and natural images.

**Octavio Oliveira** is a technologist in Geographic and Statistics Information at the Brazilian Institute of Geography and Statistics (IBGE). He holds a PhD (2000) in Agronomy, specialized in Soil Sciences from the Federal Rural University of Rio de Janeiro (UFRRJ, 1988). He is a contributor to the planning of Brazil's Agricultural Censuses (2006, 2017 and 2027). He was head of the Livestock division (2006-2015) and Coordinator of Agricultural Statistics (2016-2025) at IBGE.

**Yaozhong Pan** is a distinguished scholar and leading figure in the field of remote sensing in China. He is the Director of the Institute of Remote Sensing Science and Engineering at Beijing Normal University. He has authored more than 200 SCI-indexed papers in renowned international journals in remote sensing theory and applications, including agriculture, statistics, environment, disaster mitigation, and financial insurance. As a member of several national-level expert committees, he provides vital academic support and strategic advice for the development of remote sensing science and technology, policy-making, and the implementation of major national projects in China. He has led over 20 national key research programs and projects. He has received a First Prize of the Beijing Science and Technology Award. 

**Jonathan Paredes-Báez** is a statistician with over 20 years of experience in survey methodology, sampling design, and national statistics. He is Coordinator of the Section of Frame and Sample Studies in the Department of Statistical Methodologies and Innovation at the National Statistics Institute of Chile. His work includes integrating remote sensing data into sampling frames and leading process automation. He also holds postgraduate diplomas in Big Data & Machine Learning, Data Analysis, and Business Agility. 

**Estefanía Pizarro-Arias** is an Agronomic Engineer with an MSc in Agricultural Sciences. She specializes in remote sensing, applied geomatics, and data science, with experience in integrating satellite image time series, accuracy assessment, and area estimation for land-use/land-cover maps. She currently serves as a Methodology Analyst at Chile’s National Institute of Statistics, where she promotes the adoption of remote sensing across National Statistical Offices, aligning standards and building capacity for its use in official statistics. 

**Abdul Qadir** is a Postdoctoral Associate in the Department of Geographical Sciences (GEOG) at the University of Maryland, working with NASA Harvest. He completed his Ph.D. in the use SAR remote sensing for agricultural monitoring. His current research involves developing innovative methods to leverage Earth observation data for advancing agricultural monitoring and sustainability. He has received several prestigious awards, including the NASA FINESST Fellowship and the Robert N. Colwell Memorial Award from ASPRS.



**Lisa-Maria Rebelo** is Lead Scientist at Digital Earth Africa where she provides leadership and strategic guidance for the scientific and technical operations of the DE Africa program including deep knowledge and expertise on the development, evaluation and use of earth observations and geospatial data across the African continent.

**Sergii Skakun** is an Associate Professor at University of Maryland with a joint appointment at the Department of Geographical Sciences and the College of Information (INFO). He received a PhD in Computer Science from the National Academy of Sciences of Ukraine in 2005. His current research focus is to advance methods, models, and emerging technologies in the area of data science for heterogeneous remote sensing data fusion, processing, and analysis, as well as their applications to Earth System Science and areas of societal benefit. He is currently an Associate Editor for the journal Remote Sensing of Environment.

**Przemysław Slesiński** is a geodesy and remote-sensing specialist with a Master’s in Geodesy and Satellite Navigation. Since 2011 he has been Chief Specialist at the Statistical Office in Olsztyn, developing spatial databases, performing network analyses, and processing satellite data for agricultural statistics. 

**Amy Stringer** is a Senior Data Engineer at WearOptimo in Brisbane, Australia, where she leads architecture design and software implementation of scalable, secure and compliant data pipelines for the company’s AI and biosensor R&D. She holds a Graduate Certificate in Computational Neuroscience and Mathematics, and a Bachelor of Science/Bachelor of Mathematics, Physics and Computational Mathematics from Queensland University of Technology, Australia. Her expertise includes data acquisition and management, programming, machine learning and statistical analysis.

**Josef Wagner** is a PhD student at University of Strasbourg (France), and part of the NASA Harvest research consortium. His research is focused on building operational approaches for in-season crop mapping and sample-based planted area estimation in conflict-zones. He has been strongly involved in the collective NASA Harvest effort to monitor and track winter crop planted areas in Ukraine, both in Government- and Russian-held territories.

**Hongyan Wang** is Associate Professor with the Aerospace Information Research Institute, Chinese Academy of Sciences.Her research interests include crop mapping, crop yield estimation, applications of remote sensing in precision agriculture, and monitoring and evaluation of land degradation.
 
**Sherrie Wang** is the d’Arbeloff Career Development Assistant Professor at the Massachusetts Institute of Technology in the Department of Mechanical Engineering and Institute for Data, Systems, and Society. Her research integrates machine learning and remote sensing to advance Earth observation analytics, with applications in agriculture, climate, and policy. She earned her Ph.D. in Computational & Mathematical Engineering from Stanford and was a Ciriacy-Wantrup Postdoctoral Fellow at UC Berkeley.

**Michael Wellington** is an Earth Observation Scientist at Digital Earth Africa, employed by Geoscience Australia. He works on scientific and platform initiatives to ensure users can adopt and apply Earth Observation technology for their own purposes through Digital Earth Africa. Michael has a PhD in remote sensing of irrigated agriculture in Africa. 

**Maria Yli-Heikkilä** is a research scientist at the Natural Resources Institute Finland. Since 2018 she has been working extensively on applying machine learning and satellite remote sensing technologies for agricultural monitoring. She holds an M.Sc. (Tech.) in Industrial Engineering and Management (2003), an MA in Humanities (2013), and a PhD in remote sensing and data science (2025) from the University of Helsinki. Her research interests lie in food security and knowledge discovery through data fusion. 

**Juanjuan Zhang** is a researcher at the College of Agronomy, Henan Agricultural University, Zhengzhou, China.

**Jinshui Zhang** is a researcher at the Institute of Remote Sensing Science and Engineering, Faculty of Geographical Science, Beijing Normal University, China. His research interests are Remote Sensing, Spatial Statistics, Satellite Image Analysis and Geospatial Science. 

**Xiufang Zhu** is a professor of Beijing Normal University in China. Her research addresses  agricultural disaster monitoring by focusing on remote sensing-based investigation of disaster-affected entities, real-time monitoring using multi-source data, and developing assessment models for various stages and scenarios. She has led over 10 provincial/ministerial projects, including key programs under the National Key R&D Program and the NSFC. With 190+ publications, 4 monographs, 12 patents, 6 software copyrights, and multiple awards such as the Beijing Science and Technology Progress Award, she was listed in the 2024 World's Top 2% Scientists.




