<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Gilberto Camara, Lorenzo de Simone, Ronald Jansen">
<title>UN Handbook on Remote Sensing for Agricultural Statistics - 27&nbsp; Estimating crop statistics for list frame data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./crop_statistics_ppi.html" rel="next">
<link href="./crop_statistics_regression.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./crop_statistics.html">Extraction of crop statistics from crop type and crop yield maps</a></li><li class="breadcrumb-item"><a href="./crop_statistics_calibration.html"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Estimating crop statistics for list frame data</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">UN Handbook on Remote Sensing for Agricultural Statistics</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/FAO-EOSTAT/UN-Handbook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Welcome</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./howto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">How to use this handbook</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_remote_sensing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Remote sensing images: optical, SAR</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_data_sources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Earth observation big data sources</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_data_cubes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Earth observation data cubes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_lucc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Land cover and crop classification schemas</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_quality_control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Quality control of training sets for agricultural statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_machine_learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Machine learning algorithms for image time series</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_uncertainty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Spatial map uncertainty estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Map validation and use of maps for area estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_design_frames.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Remote Sensing in the Design of Sampling Frames</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_alignment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Alignment of field data collection to EO statistical requirements</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_semantic_segmentation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Semantic Segmentation for Remote Sensing in Agriculture</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_parcel_extraction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Automatic Extraction of Parcels</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./crop_type_mapping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Use Cases in Crop Type Mapping</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_poland.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Crop monitoring with Sentinel-1 and Sentinel-2 images in Poland</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_mexico.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Crop classification in Mexico</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_zimbabwe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Crop classification in Zimbabwe</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_china.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Efficient and Reliable Paddy Rice Classification</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_chile.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Crop classification and land use mapping in Chile</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_digital_earth_africa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Agricultural Mapping with Digital Earth Africa</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./crop_yield_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Crop yield estimation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_finland.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Early-season crop yield mapping in Finland</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_indonesia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Mapping crop phenology in Indonesia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_poland.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Yield forecasting in Poland</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_china.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Remote Sensing Estimation of Soybean Yield</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./crop_statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Extraction of crop statistics from crop type and crop yield maps</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./crop_statistics_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Estimating crop statistics using survey-calibrated methods</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./crop_statistics_calibration.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Estimating crop statistics for list frame data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./crop_statistics_ppi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Prediction-Powered Inference (PPI) for Agricultural Decision-Making</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./uav_agriculture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">UAV applications in agricultural statistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uav_field_parcels.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Field Parcel Identification Using UAV Imagery Based on the DCP-MTL Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uav_wheat_growth.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Application of UAV in Wheat Growth Monitoring</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uav_crop_growth.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Automated Monitoring of Crop Growth Index (CGI) using UAV</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./disaster_response.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Remote Sensing for Agricultural Disaster Response</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dis_china_floods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">An Automated Flood Detection Algorithm for Post-Disaster Assessment</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./additional.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Additional Topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ad_world_cereal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">WorldCereal - A Global Effort for Crop Mapping</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ad_governance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Data Governance for Agricultural Statistics</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">27.1</span> Introduction</a></li>
  <li><a href="#national-level-estimators" id="toc-national-level-estimators" class="nav-link" data-scroll-target="#national-level-estimators"><span class="header-section-number">27.2</span> National-level estimators</a></li>
  <li><a href="#crop-type-maps" id="toc-crop-type-maps" class="nav-link" data-scroll-target="#crop-type-maps"><span class="header-section-number">27.3</span> Crop type maps</a></li>
  <li><a href="#model-parameter-estimates" id="toc-model-parameter-estimates" class="nav-link" data-scroll-target="#model-parameter-estimates"><span class="header-section-number">27.4</span> Model parameter estimates</a></li>
  <li><a href="#crop-acreage-estimates" id="toc-crop-acreage-estimates" class="nav-link" data-scroll-target="#crop-acreage-estimates"><span class="header-section-number">27.5</span> Crop acreage estimates</a></li>
  <li><a href="#crop-type-map-relative-efficiency" id="toc-crop-type-map-relative-efficiency" class="nav-link" data-scroll-target="#crop-type-map-relative-efficiency"><span class="header-section-number">27.6</span> Crop type map relative efficiency</a></li>
  <li><a href="#district-level-estimates" id="toc-district-level-estimates" class="nav-link" data-scroll-target="#district-level-estimates"><span class="header-section-number">27.7</span> District-level estimates</a></li>
  <li><a href="#concluding-remarks" id="toc-concluding-remarks" class="nav-link" data-scroll-target="#concluding-remarks"><span class="header-section-number">27.8</span> Concluding remarks</a></li>
  <li><a href="#about-the-authors" id="toc-about-the-authors" class="nav-link" data-scroll-target="#about-the-authors">About the authors</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul><div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/FAO-EOSTAT/UN-Handbook/edit/quarto/crop_statistics_calibration.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/FAO-EOSTAT/UN-Handbook/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">
<span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Estimating crop statistics for list frame data</span>
</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Luis Ambrosio Flores </p>
          </div>
  </div>
    
  
    
  </div>
  

</header><section id="introduction" class="level2" data-number="27.1"><h2 data-number="27.1" class="anchored" data-anchor-id="introduction">
<span class="header-section-number">27.1</span> Introduction</h2>
<p>This chapter provides guidance for estimating crop statistics when the sample data is organised as a list frame, with one labeled centroid per parcel without direct measurement of parcel areas <span class="citation" data-cites="Ambrosio2023"><a href="#ref-Ambrosio2023" role="doc-biblioref">[1]</a></span>. In Senegal, the National Statistical Office (NSO) utilizes a list frame based on census data to select a sample of agricultural holdings. Ground data on crop types and agricultural practices are collected from parcels within this sample during the Annual Agricultural Survey (AAS). The observed crop type at each sampled parcel is linked to the pixel containing the centroid and recorded in the database. Consequently, the ground data is not continuous but categorical (crop type) and limited to a single point per sampled parcel, with no information on parcel area.</p>
</section><section id="national-level-estimators" class="level2" data-number="27.2"><h2 data-number="27.2" class="anchored" data-anchor-id="national-level-estimators">
<span class="header-section-number">27.2</span> National-level estimators</h2>
<p>We define the survey vector as <span id="eq-survey"><span class="math display">\[
  \mathbf{y_i} = \begin{pmatrix}y_{i1}\\ .. \\
  y_{ik} \\ .. \\y_{iK} \end{pmatrix}
\tag{27.1}\]</span></span></p>
<p>where <span class="math inline">\(y_{ik}\)</span> is 1 if the crop <span class="math inline">\(k\)</span> covers pixel <span class="math inline">\(i\)</span> and 0 otherwise. The total number of crop categories is <span class="math inline">\(K\)</span> so that <span id="eq-sumy"><span class="math display">\[
  \sum_{k=1}^{K} y_{ik} = 1
\tag{27.2}\]</span></span></p>
<p>We focus on high-resolution satellite images where the population size <span class="math inline">\(N\)</span> is the total number of pixels in the study area <span class="math inline">\(A = aN\)</span>, and each pixel represents a fixed land area <span class="math inline">\(a\)</span>.</p>
<p>The population total of the survey vector is <span id="eq-poptotal"><span class="math display">\[
  \mathbf{y_N} = \sum_{i=1}^{N} \mathbf{y_i} = \begin{pmatrix} \sum_{i=1}^{N}y_{i1} \\ .. \\ \sum_{i=1}^{N}y_{ik}  \\ .. \\ \sum_{i=1}^{N}y_{iK} \end{pmatrix} = \begin{pmatrix} y_{N1} \\ .. \\ y_{Nk} \\ .. \\ y_{NK} \end{pmatrix}
\tag{27.3}\]</span></span></p>
<p>where <span class="math inline">\(y_{Nk}\)</span> is the number of pixels covered by crop <span class="math inline">\(k\)</span>. Assuming each pixel is covered by only one crop (or mixed classes are defined), the area covered by crop <span class="math inline">\(k\)</span> is <span class="math inline">\(A_k = a*y_{Nk}\)</span> and the total area is <span id="eq-area"><span class="math display">\[
  A = \sum_{k=1}^{K} A_k
\tag{27.4}\]</span></span> Our goal is to estimate the total <span class="math inline">\(\mathbf{y_N}\)</span> or the mean value <span id="eq-meany"><span class="math display">\[
  \overline{\mathbf{y}}_N = \frac{1}{N}\sum_{i=1}^{N}\mathbf{y_i} = \begin{pmatrix} \frac{y_{N1}}{N}\\ .. \\ \frac{y_{Nk}}{N} \\ .. \\ \frac{y_NK}{N} \end{pmatrix}
\tag{27.5}\]</span></span></p>
<p>where <span class="math inline">\(y_{Nk}/N\)</span> is the proportion of pixels covered by class <span class="math inline">\(k\)</span>.</p>
<p>We assume the survey vector <span class="math inline">\(\mathbf{y_i}\)</span> follows a multinomial distribution <span id="eq-multinom"><span class="math display">\[
\mathbf{y_i} \sim MN(1,\boldsymbol{\mu_i})
\tag{27.6}\]</span></span></p>
<p>where <span id="eq-muvec"><span class="math display">\[
  \boldsymbol{\mu_i} = \begin{pmatrix}\mu_{i1}\\ .. \\ \mu_{ik} \\ .. \\\mu_{iK} \end{pmatrix}
\tag{27.7}\]</span></span> and <span class="math inline">\(\mu_{ik}\)</span> is the probability that unit <span class="math inline">\(i\)</span> belongs to category <span class="math inline">\(k\)</span>, i.e., the probability of <span class="math inline">\(y_{ik} = 1\)</span> and <span class="math inline">\(y_{ik'} = 0, \forall k' \neq k\)</span>, subject to the constraint <span id="eq-summu"><span class="math display">\[
  \sum_{k=1}^{K}\mu_{ik} = 1.
\tag{27.8}\]</span></span></p>
<p>The probabilities <span class="math inline">\(\mu_{ik}\)</span> are estimated using a sample of pixels <span class="math inline">\(\{(\mathbf{y_i}, \mathbf{x_i}), i = 1, 2, ..., n\}\)</span> whose total number is <span class="math inline">\(n\)</span> selected with known inclusion probabilities <span class="math inline">\(\pi_i\)</span>, together with the associated remote sensing data vector which has <span class="math inline">\(L\)</span> components <span id="eq-xrow"><span class="math display">\[
  \mathbf{x_i} = \left(\begin{array}{c} x_{i1}, .., x_{il}, .., x_{iL} \end{array}\right)
\tag{27.9}\]</span></span></p>
<p>To link <span class="math inline">\(\mu_{ik}\)</span> with remote sensing data, we use a multinomial logit model <span id="eq-multimu"><span class="math display">\[
  \boldsymbol{\mu_{ik}} = \frac{exp(\mathbf{x_i}\boldsymbol{\beta_k})}{\sum_{k=1}^{K}exp(\mathbf{x_i}\boldsymbol{\beta_k})}
\tag{27.10}\]</span></span></p>
<p>where <span id="eq-betavec"><span class="math display">\[
  \boldsymbol{\beta_k} = \begin{pmatrix}\beta_{k1}\\ .. \\ \beta_{kl} \\ .. \\\beta_{kL} \end{pmatrix}
\tag{27.11}\]</span></span></p>
<p>is the parameter vector for crop <span class="math inline">\(k\)</span>. To estimate the probability <span class="math inline">\(\mu_{ik}\)</span> that the cover of pixel <span class="math inline">\(i\)</span> is crop <span class="math inline">\(k = 1, 2, ..., K\)</span> it is sufficient to acquire estimates of <span class="math inline">\(\boldsymbol{\beta_k}\)</span> for <span class="math inline">\(k = 1, 2, ..., K-1\)</span>. The probability of category <span class="math inline">\(K\)</span> is <span id="eq-muk"><span class="math display">\[
  \mu_{iK} = 1 - \sum_{k=1}^{K-1}\mu_{ik}
\tag{27.12}\]</span></span> which can be computed using the estimates <span class="math inline">\(\mathbf{\hat{B}}_{\pi k}\)</span> for <span class="math inline">\(k = 1, 2, ..., K-1\)</span>.</p>
<p>The design-based estimator (where <span class="math inline">\(\pi\)</span> indicates that the estimator depends on the inclusion probabilities defined by the NSO in the sampling design)<br><span id="eq-design"><span class="math display">\[
  \mathbf{\hat{B}}_\pi = \begin{pmatrix} \mathbf{\hat{B}}_{\pi 1} \\ .. \\ \mathbf{\hat{B}}_{\pi k} \\ .. \\ \mathbf{\hat{B}}_{\pi K} \end{pmatrix}
\tag{27.13}\]</span></span> is design-consistent for the maximum likelihood estimator of <span class="math inline">\(\boldsymbol{\beta}\)</span>, expressed as <span id="eq-mlest"><span class="math display">\[
  \boldsymbol{\beta} = \begin{pmatrix}\boldsymbol{\beta}_{1}\\ .. \\ \boldsymbol{\beta}_{k} \\ .. \\ \boldsymbol{\beta}_{K} \end{pmatrix}
\tag{27.14}\]</span></span></p>
<p>based on the population data <span class="math inline">\(\{(\mathbf{y_i}, \mathbf{x_i}), i = 1, 2, ..., N\}\)</span>, under the assumption that the population behaves like a simple random sample from the multinomial model. Estimation is performed iteratively using weighted likelihood equations based on inclusion probabilities <span class="citation" data-cites="Fuller2011"><a href="#ref-Fuller2011" role="doc-biblioref">[2]</a></span> <span id="eq-wlike"><span class="math display">\[
  \mathbf{\hat{B}}_{\pi}^{(m+1)} = \mathbf{\hat{B}}_{\pi}^{(m)} + \left[ \sum_{i = 1}^{n}\frac{\mathbf{H}(y_i,\boldsymbol{\beta})}{{\pi_i}} \Bigg|_{\boldsymbol{\beta} = \mathbf{\hat{B}}_{\pi}^{(m)}} \right]_{}^{-1} \sum_{i = 1}^{n}\frac{\mathbf{b}(y_i,\boldsymbol{\beta})}{{\pi_i}}\Bigg|_{\boldsymbol{\beta} = \mathbf{\hat{B}}_{\pi}^{(m)}}
\tag{27.15}\]</span></span> where <span id="eq-blike"><span class="math display">\[
  \mathbf{b}(y_i,\boldsymbol{\beta}) =  col_{1 \leq k \leq K-1}row_{1 \leq l \leq L}\Bigl[ (y_{ik} - \mu_{ik})x_{il} \Bigr]
\tag{27.16}\]</span></span> and <span id="eq-hlike"><span class="math display">\[
  \mathbf{H}(y_i,\boldsymbol{\beta}) = col_{1 \leq k \leq K-1}row_{1 \leq k' \leq K -1 }\Bigl[(\delta_{kk'}\mu_{ik} - \mu_{ik}\mu_{ik'})\otimes \mathbf{x}_{i}^\top\mathbf{x}_{i}\Bigr]
\tag{27.17}\]</span></span> with <span class="math inline">\(\delta_{kk'} = 1\)</span> if <span class="math inline">\(k = k'\)</span> and <span class="math inline">\(\delta_{kk'} = 0\)</span> otherwise.</p>
<p>A design-consistent estimator of the total number of pixels covered by each crop <span id="eq-pixcrop"><span class="math display">\[
  \mathbf{y}_{N} = \begin{pmatrix}y_{N1}\\ .. \\ y_{Nk} \\ .. \\y_{NK} \end{pmatrix}
\tag{27.18}\]</span></span> is given by <span id="eq-estpixcrop"><span class="math display">\[
  \mathbf{\hat{y}}_{N} = \sum_{i=1}^{N}\boldsymbol{\hat{\mu}_i} + \frac{N}{\hat{N}_p} \sum_{i=1}^{n}\frac{\mathbf{y}_i - \boldsymbol{\hat{\mu}_i}}{\pi_i}
\tag{27.19}\]</span></span> In <a href="#eq-estpixcrop">Equation&nbsp;<span>27.19</span></a>, <span class="math inline">\(\boldsymbol{\hat{\mu_i}}\)</span> is a column vector, expressed as <span id="eq-estmu"><span class="math display">\[
    \boldsymbol{\hat{\mu}}_i = \begin{pmatrix} \hat{\mu}_{i1}\\ .. \\ \hat{\mu}_{ik} \\ .. \\ \hat{\mu}_{iK-1} \end{pmatrix}
\tag{27.20}\]</span></span> For classes <span class="math inline">\(k=1,..., K-1\)</span>, each of the terms of <span class="math inline">\(\boldsymbol{\hat{\mu_i}}\)</span> in <a href="#eq-estpixcrop">Equation&nbsp;<span>27.19</span></a> is estimated by <span id="eq-estmu1"><span class="math display">\[
\hat{\mu}_{ik} = \frac{exp(\mathbf{x}_i\mathbf{\hat{B}}_{\pi k})}{ 1 + exp(\mathbf{x}_i\mathbf{\hat{B}}_{\pi k})}, \quad k = 1,2, ..., K-1
\tag{27.21}\]</span></span> For class <span class="math inline">\(k=K\)</span>, the estimator of <span class="math inline">\(\boldsymbol{\hat{\mu_i}}\)</span> is <span id="eq-estmu1"><span class="math display">\[
\hat{\mu}_{iK} = 1 - \sum_{k=1}^{K-1}\hat{\mu}_{ik}.
\tag{27.22}\]</span></span> In <a href="#eq-estpixcrop">Equation&nbsp;<span>27.19</span></a>, the normalization factor <span class="math inline">\(\hat{N}_p\)</span> is given by <span id="eq-estnp-hat"><span class="math display">\[
  \hat{N}_p = \sum_{i=1}^{n}\frac{1}{\pi_i}.
\tag{27.23}\]</span></span> Based on the above, we can compute the estimator of the total number of pixels covered by crop <span class="math inline">\(k \le K-1\)</span>, given by <span id="eq-pixcrop1"><span class="math display">\[
    \hat{y}_{Nk} = \sum_{i=1}^{N}\hat{\mu}_{ki} + \frac{N}{\hat{N}_p} \sum_{i=1}^{n}\frac{y_{ki} - \hat{\mu}_{ki}}{\pi_i}, \quad k = 1,2, ..., K-1
\tag{27.24}\]</span></span></p>
<p>and for crop <span class="math inline">\(K\)</span> the estimator is <span id="eq-pixcrop2"><span class="math display">\[
  \hat{y}_{NK} = N - \sum_{k=1}^{K-1} \hat{y}_{Nk}.
\tag{27.25}\]</span></span></p>
<p>The sampling covariance matrix of <span class="math inline">\(\mathbf{\hat{y}}_{N}\)</span> is approximated by <span id="eq-sampcov"><span class="math display">\[
  \mathbf{V\hat{y}}_N \approx N^2\mathbf{V}\frac{1}{\hat{N}_p}\sum_{i=1}^{n}\frac{\mathbf{y}_i - \boldsymbol{\mu}_i}{\pi_i}
\tag{27.26}\]</span></span> which can also be expressed as <span id="eq-sampcov2"><span class="math display">\[
  \mathbf{V\hat{y}}_N \approx col_{1 \leq k \leq K-1}row_{1 \leq k' \leq K -1 }\Bigl(N^2Cov(\hat{y}_{rk}, \hat{y}_{rk'}) \Bigr)
\tag{27.27}\]</span></span> To compute the covariance matrix for elements <span class="math inline">\(\hat{y}_{rk}\)</span> in <a href="#eq-sampcov2">Equation&nbsp;<span>27.27</span></a>, we consider that <span id="eq-covelem"><span class="math display">\[
  \hat{y}_{rk} = \frac{1}{\hat{N}_p}\sum_{i=1}^{n}\frac{y_{ki} - \mu_{ki}}{\pi_i}.
\tag{27.28}\]</span></span> Each estimator <span class="math inline">\(\hat{y}_{rk}\)</span> is a function of the estimators of the total number of sampling units of category <span class="math inline">\(k\)</span>, given by <span id="eq-estnpk"><span class="math display">\[
  \hat{N}_{pk} = \sum_{i=1}^{n}\frac{y_{ki}}{\pi_i}, \quad k = 1,2, ..., K
\tag{27.29}\]</span></span> noting that <span id="eq-estnp"><span class="math display">\[
  \hat{N}_p = \sum_{k=1}^{K}\hat{N}_{pk}.
\tag{27.30}\]</span></span> The estimators <span class="math inline">\(\hat{y}_{rk}\)</span> also depend on the total residuals of class <span class="math inline">\(k\)</span>, estimated by the second term of <a href="#eq-covelem">Equation&nbsp;<span>27.28</span></a> <span id="eq-resid"><span class="math display">\[
  \hat{r}_{kN} = \sum_{i=1}^{n}\frac{y_{ki} - \mu_{ki}}{\pi_i}
\tag{27.31}\]</span></span> for each class <span class="math inline">\(k\)</span>.</p>
<p>The diagonal elements of the variance matrix <span class="math inline">\(\mathbf{V\hat{y}}_N\)</span> provide the sampling variance <span class="math inline">\(V\hat{y}_{Nk}\)</span> for each crop class <span class="math inline">\(k = 1,2,..., K-1\)</span>. Let the row vector <span class="math inline">\(\mathbf{\hat{G}}_k\)</span> be such that its <span class="math inline">\(K+1\)</span> components are the estimators on which <span class="math inline">\(\hat{y}_{rk}\)</span> depends, and be given by <span id="eq-ghat"><span class="math display">\[
  \mathbf{\hat{G}}_k = \Bigl[ \hat{r}_{kN}, \hat{N}_{p1}, \hat{N}_{p2}, ..., \hat{N}_{pK} \Bigr].
\tag{27.32}\]</span></span></p>
<p>Let <span class="math inline">\(g_1 = \hat{r}_{KN}, g_2 = \hat{N}_{p1}, g_3 = \hat{N}_{p2}, ..., g_{N+1} = \hat{N}_{pK}\)</span>. The sampling variance <span class="math inline">\(\hat{y}_{Nk}\)</span> is approximated by <span id="eq-ysamplvar"><span class="math display">\[
  V\hat{y}_{Nk} \approx row_{1 \leq j \leq K+1} \biggl(\frac{\partial\hat{y}_{rk}}{\partial{g_j}}\biggr)\enspace \mathbf{V\hat{G}}_k \enspace  col_{1 \leq j \leq K+1}\biggl(\frac{\partial\hat{y}_{rk}}{\partial{g_j}}\biggr)
\tag{27.33}\]</span></span> where <span id="eq-designcov"><span class="math display">\[
  \mathbf{V\hat{G}}_k = col_{1 \leq j \leq K+1} row_{1 \leq j' \leq K+1} \biggl(Cov\bigl(g_j,g_{j'} \bigr) \biggr)
\tag{27.34}\]</span></span></p>
<p>is the design-based covariance matrix of <span class="math inline">\(\mathbf{\hat{G}}_k\)</span>. The sampling covariance matrix <span class="math inline">\(\mathbf{\hat{y}}_N\)</span> is estimated replacing <span class="math inline">\(\boldsymbol{\mu}_i\)</span> by <span class="math inline">\(\boldsymbol{\hat{\mu}}_i\)</span> in <span class="math inline">\(V\hat{y}_{N}\)</span> <span class="citation" data-cites="Fuller2011"><a href="#ref-Fuller2011" role="doc-biblioref">[2]</a></span>.</p>
</section><section id="crop-type-maps" class="level2" data-number="27.3"><h2 data-number="27.3" class="anchored" data-anchor-id="crop-type-maps">
<span class="header-section-number">27.3</span> Crop type maps</h2>
<p>To generate the crop-type map for the Nioro region, a random forest classifier was applied (see chapter 17 for full details) identifying four primary crop classes: maize, millet, groundnut, and other crops. Pixels not associated with these four classes were classified into a non-agricultural land-use category and excluded from crop-specific analysis (<a href="#fig-nioro-map">Figure&nbsp;<span>27.1</span></a>).</p>
<p>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-nioro-map" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="./images/crop_statistics_calibration/nioro.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;27.1: Crop type map for Nioro, 2021</figcaption></figure>
</div>
</div>
</div>
<p>The map data are encoded according to the Earth Observation (EO) crop type assigned to each pixel: we use the row vector <span class="math inline">\(\mathbf{x}_i = (1, 0, 0, 0)\)</span> for any pixel <span class="math inline">\(i\)</span> in the EO class maize, <span class="math inline">\(\mathbf{x}_i = (0, 1, 0, 0)\)</span> for any pixel in the EO class millet, <span class="math inline">\(\mathbf{x}_i = (0, 0, 1, 0)\)</span> for any pixel in the EO class groundnut, and <span class="math inline">\(\mathbf{x}_i = (0, 0, 0, 1)\)</span> for any pixel in the EO class other crops.</p>
</section><section id="model-parameter-estimates" class="level2" data-number="27.4"><h2 data-number="27.4" class="anchored" data-anchor-id="model-parameter-estimates">
<span class="header-section-number">27.4</span> Model parameter estimates</h2>
<p>This section focuses on the two main crops observed in the field sample: millet and groundnut. All other crops (primarily maize) are grouped into the third category labeled others. The estimated probability for this residual category is computed as one minus the sum of the probabilities for millet and groundnut. Table 1 below presents the estimated coefficients for each crop type, indicating the strength and direction of association between EO classifications and ground-truth crop types (Annex 1 contains the R scripts to compute these estimates using the database provided in Annex 6a).</p>
<div id="tbl-parameters" class="anchored">
<table class="table">
<caption>Table&nbsp;27.1: Model parameter estimate (<span class="math inline">\(\mathbf{\hat{B}}_{\pi,millet}\)</span> and <span class="math inline">\(\mathbf{\hat{B}}_{\pi, groundnut}\)</span>)</caption>
<colgroup>
<col style="width: 17%">
<col style="width: 24%">
<col style="width: 19%">
<col style="width: 18%">
<col style="width: 19%">
</colgroup>
<thead><tr class="header">
<th>Crop</th>
<th>EO crop type map</th>
<th></th>
<th></th>
<th></th>
</tr></thead>
<tbody>
<tr class="odd">
<td></td>
<td>Maize</td>
<td>Millet</td>
<td>Groundnut</td>
<td>Other crops</td>
</tr>
<tr class="even">
<td>Millet</td>
<td>-0.010655</td>
<td>1.47958334</td>
<td>0.88931346</td>
<td>8.76504093</td>
</tr>
<tr class="odd">
<td>Groundnut</td>
<td>-0.659204</td>
<td>-0.59871700</td>
<td>2.89873948</td>
<td>1.21898514</td>
</tr>
</tbody>
</table>
</div>
<p>These coefficients reflect how strongly each EO classification predicts the presence of a given crop type in the field. The EO classification “millet” has a strong positive association (1.4796) with the ground-truth millet class. The EO classification “groundnut” is highly predictive ( 2.8987) of the ground-truth groundnut class. The “other crops” EO class shows a strong association with both millet (8.76504093) and groundnut (1.21898514), suggesting potential overlap or classification uncertainty.</p>
</section><section id="crop-acreage-estimates" class="level2" data-number="27.5"><h2 data-number="27.5" class="anchored" data-anchor-id="crop-acreage-estimates">
<span class="header-section-number">27.5</span> Crop acreage estimates</h2>
<p>Crop acreage estimates for millet and groundnut, derived from the integration of ground and RS data, are shown in Table 2 (Annex 2 contains the R scripts to compute these estimates, using the database provided in Annex 6a, and Annex 3 contains the R Scripts to compute the standard errors, coefficients of variation, and confidence intervals, using the database provided in Annex 6b).</p>
<div id="tbl-acreage-estimates" class="anchored">
<table class="table">
<caption>Table&nbsp;27.2: Crop acreage estimates, Nioro. Senegal, 2021.</caption>
<colgroup>
<col style="width: 11%">
<col style="width: 18%">
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 22%">
<col style="width: 7%">
<col style="width: 8%">
</colgroup>
<thead><tr class="header">
<th>Crop type</th>
<th>Acreage (Hectare)</th>
<th>Uncertainty</th>
<th></th>
<th></th>
<th></th>
<th></th>
</tr></thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td>Standard error</td>
<td>Coefficient of variation (%)</td>
<td>Limits of 95% confidence interval</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
<td></td>
<td>Lower</td>
<td>Upper</td>
<td>Amplitude</td>
</tr>
<tr class="odd">
<td>Millet</td>
<td>89215</td>
<td>3661.103</td>
<td>4.11</td>
<td>81978.88</td>
<td>96330.4</td>
<td>14351.52</td>
</tr>
<tr class="even">
<td>Groundnut</td>
<td>78815</td>
<td>2923.94</td>
<td>3.71</td>
<td>73089.15</td>
<td>84550.98</td>
<td>11461.82</td>
</tr>
</tbody>
</table>
</div>
<p>We compare the results of our design-based approach (shown in <a href="#tbl-acreage-estimates">Table&nbsp;<span>27.2</span></a>) with estimates directly based on the crop-type map. The comparison is necessarily limited to the crop acreage estimates because the usual algorithms used for crop-type map generation do not provide measures of uncertainty comparable to those of <a href="#tbl-acreage-estimates">Table&nbsp;<span>27.2</span></a>.</p>
<p>Both the number of pixels in EO crop type millet (9470572, i.e., 94705.72 ha, as a pixel represents 100 <span class="math inline">\(m^2\)</span>) and in EO crop type groundnut (8076448, i.e., 80764.48 ha) are larger than the design-based number estimates: 8921492 (89214.92 ha) for millet and 7881468 (78814.68 ha) for groundnut. For millet, the difference was 5490.8 ha (6.2%) and for groundnut 1949.8 ha (2.5%). For the former, the difference is greater than the design-based standard error (3661.10 ha) and the coefficient of variation (4.11%). For the latter, the difference is smaller than the design-based standard error (2923.94 ha) and the coefficient of variation (3.71%). These differences are not statistically significant, since the estimates directly based on the EO crop-type classes are within the design-based confidence limits, namely, [81978.88, 96330.4] ha for millet and [73089.15, 84550.98] ha for groundnut.</p>
<p>However, the comparison must focus not on the results, which are always uncertain, but on the methods. The methods make the major difference; whereas the design-based estimators are in the mainstream of official statistics, the estimators based directly on crop-type maps are not. The proposed approach provides design-consistent estimates together with the usual measures of uncertainty (sampling error, coefficient of variation, and confidence intervals). The two main objections to estimators based directly on the crop-type map are that (i) they are not design-consistent and (ii) the usual uncertainty measures are not available.</p>
</section><section id="crop-type-map-relative-efficiency" class="level2" data-number="27.6"><h2 data-number="27.6" class="anchored" data-anchor-id="crop-type-map-relative-efficiency">
<span class="header-section-number">27.6</span> Crop type map relative efficiency</h2>
<p>When comparing a set of sampling strategies developed for estimating the same characteristic in a given population, cost efficiency is a key criterion. Let <span class="math inline">\(C_{GD}\)</span> be the cost and <span class="math inline">\(V_{GD}\)</span> the sampling error of the current sampling strategy using only ground data, and let <span class="math inline">\(C_{GD+RS}\)</span> and <span class="math inline">\(V_{GD+RS}\)</span> be the cost and sampling error, respectively, of the strategy integrating ground and remote sensing (RS) data. The cost efficiency is <span class="math inline">\(C_{GD}V_{GD}\)</span> for the former and <span class="math inline">\(C_{GD+RS}V_{GD+RS}\)</span> for the latter.</p>
<p>Although Sentinel images and processing software are freely provided by ESA, NSOs still incur costs such as expert time and cloud computing services for data storage and analysis. Additionally, replacing parcel centroids with georeferenced polygons introduces further operational costs. Given the difficulty of estimating these additional costs, we assume in the following that <span class="math inline">\(C_{GD+RS} \approx C_{GD}\)</span> , simplifying the comparison to a focus on criterion relative efficiency.</p>
<p>The sampling variance of the <span class="math inline">\(y_{Nk}\)</span> estimator based on ground data alone is <span id="eq-vgdsamplvar"><span class="math display">\[
  V_{GD} = N^2V\frac{1}{\hat{N}_p}\sum_{i=1}^{n}\frac{y_{ki}}{\pi_i}
\tag{27.35}\]</span></span></p>
<p>and that based on its integration with RS data is <span id="eq-vgdrssamplvar"><span class="math display">\[
V_{GD+RS} = N^2V\frac{1}{\hat{N}_p}\sum_{i=1}^{n}\frac{y_{ki} - \mu_{ki}}{\pi_i}.
\tag{27.36}\]</span></span></p>
<p>The relative efficiency of RS data for estimating the total number of pixels covered by crop <span class="math inline">\(k\)</span> is <span id="eq-rers"><span class="math display">\[
  RE_{RSk} = V\frac{1}{\hat{N}_p}\sum_{i=1}^{n}\frac{y_{ki}}{\pi_i}\biggl( V\frac{1}{\hat{N}_p}\sum_{i=1}^{n}\frac{y_{ki} - \mu_{ki}}{\pi_i}\biggr)^{-1}.
\tag{27.37}\]</span></span></p>
<p>We evaluate the RS data efficiency <span class="math inline">\(RE_{RSk}\)</span> for the acreage estimation of millet and groundnut. Results are in <a href="#tbl-efficiency">Table&nbsp;<span>27.3</span></a> (Annex 3 contains the R scripts to generate these results using the database provided in Annex 6b).</p>
<div id="tbl-efficiency" class="anchored">
<table class="table">
<caption>Table&nbsp;27.3: Efficiency of RS data for crop acreage estimation, Nioro, Senegal.</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 36%">
<col style="width: 12%">
<col style="width: 30%">
</colgroup>
<thead><tr class="header">
<th>Crop type</th>
<th>Std errors of proportion estimators</th>
<th></th>
<th>Relative efficiency of RS data</th>
</tr></thead>
<tbody>
<tr class="odd">
<td></td>
<td>Ground data</td>
<td>Ground &amp; RS data</td>
<td></td>
</tr>
<tr class="even">
<td>Millet</td>
<td>3.37</td>
<td>1.90</td>
<td>3.13</td>
</tr>
<tr class="odd">
<td>Groundnut</td>
<td>3.34</td>
<td>1.52</td>
<td>4.80</td>
</tr>
</tbody>
</table>
</div>
<p>The effect of integrating RS data in the ground sample data was a reduction in the sampling error of millet and groundnut and, as a result, in the confidence interval of these two crops, without loss of design-based consistency. In other words, using RS data, the cost of estimating millet and groundnut acreage could be reduced to less than a third of the current cost, without loss of accuracy.</p>
</section><section id="district-level-estimates" class="level2" data-number="27.7"><h2 data-number="27.7" class="anchored" data-anchor-id="district-level-estimates">
<span class="header-section-number">27.7</span> District-level estimates</h2>
<p>The total of survey vector in the domain <span class="math inline">\(R\)</span> of size <span class="math inline">\(N_R\)</span> pixels is <span id="eq-totalsurvey"><span class="math display">\[
  \mathbf{y}_{N_{R}} = \sum_{i=1}^{N_R}\mathbf{y}_i = col_{1 \leq k \leq K}\biggl( \sum_{i=1}^{N_R} y_{ik}\ \biggr) = \begin{pmatrix}y_{N_R1}\\ .. \\ y_{N_Rk} \\ .. \\y_{N_RK} \end{pmatrix}
\tag{27.38}\]</span></span></p>
<p>In <a href="#eq-totalsurvey">Equation&nbsp;<span>27.38</span></a>, <span class="math inline">\(y_{N_Rk}\)</span> is the number of pixels in <span class="math inline">\(R\)</span> covered by crop <span class="math inline">\(k\)</span>. To estimate <span class="math inline">\(\mathbf{y}_{N_{R}}\)</span>, we use the sample <span class="math inline">\(s\)</span> of size <span class="math inline">\(n\)</span> selected from the population with inclusion probabilities <span class="math inline">\({\pi_i, i = 1, 2,..., N}\)</span> and the estimator <span id="eq-est-region"><span class="math display">\[
  \mathbf{\hat{y}}_{N_{R}} = \sum_{i=1}^{N_R}\boldsymbol{\hat{\mu}}_i + \frac{N_R}{\hat{N}_{R_p}}\sum_{i=1}^{n_R}\frac{\mathbf{\hat{y}}_i - \boldsymbol{\hat{\mu}}_i}{\pi_i}
\tag{27.39}\]</span></span></p>
<p>The parameter <span class="math inline">\(n_R\)</span> is the number of units in the sample belonging to the study domain, given by <span id="eq-nr"><span class="math display">\[
  n_R = \sum_{i=1}^{n}I_i
\tag{27.40}\]</span></span> where the indicator variable <span class="math inline">\(I_i\)</span> is 1 if the pixel belongs to the region <span class="math inline">\(R\)</span> and 0 otherwise.</p>
<p>and <span id="eq-nrp"><span class="math display">\[
  \hat{N}_{Rp} = \sum_{i=1}^{n_R}\frac{I_i}{\pi_i}.
\tag{27.41}\]</span></span></p>
<p>The sampling covariance of <span class="math inline">\(\mathbf{\hat{y}}_{N_R}\)</span> is given approximately by <span id="eq-sampcov-reg"><span class="math display">\[
  \mathbf{V\hat{y}}_{N_R} \approx N_R^2\mathbf{V}\frac{1}{\hat{N}_{R_p}}\sum_{i=1}^{n_R}\frac{\mathbf{y}_i - \boldsymbol{\mu}_i}{\pi_i}.
\tag{27.42}\]</span></span> also expressed as</p>
<p><span class="math display">\[
\mathbf{V\hat{y}}_{N_R} = col_{1 \leq k \leq K-1}\enspace row_{1 \leq k' \leq K-1} \enspace \Bigl( N_R^2 Cov(\hat{y}_{Rrk}, \hat{y}_{Rrk'}) \Bigr)
\]</span></p>
<p>Let <span id="eq-y-rkr"><span class="math display">\[
  \hat{y}_{Rrk} = \frac{1}{\hat{N}_{Rp}}\sum_{i=1}^{n_R}\frac{y_{ki} - \mu_{ki}}{\pi_i}
\tag{27.43}\]</span></span></p>
<p>and <span id="eq-grk"><span class="math display">\[
  \mathbf{\hat{G}}_{Rk} = \Bigl[ \hat{r}_{kN_R}\enspace \hat{N}_{N_Rp1} \enspace  \hat{N}_{N_Rp2} \enspace  ... \enspace \hat{N}_{N_RpK} \Bigr].
\tag{27.44}\]</span></span> Let $$</p>
<p>g_{R1} = <em>{kN_R}, g</em>{R2} = <em>{N_Rp1}, , …, g</em>{RK+1} = <em>{N_RpK} <span class="math display">\[{#eq-gest}
The sampling variance of $\hat{y}_{N_Rk}$ is given approximately by
\]</span> V</em>{N_Rk} row_{1 j K+1} ( )<em>{Rk} col</em>{1 j K+1}() $${#eq-ysamplvarrk}</p>
<p>where <span id="eq-vgrk"><span class="math display">\[
  \mathbf{V\hat{G}}_{Rk} = col_{1 \leq j \leq K+1} row_{1 \leq j' \leq K+1} \biggl(Cov\bigl(g_{Rj},g_{Rj'} \bigr) \biggr)
\tag{27.45}\]</span></span> The sampling covariance matrix <span class="math inline">\(\mathbf{\hat{y}}_{N_R}\)</span> is estimated replacing <span class="math inline">\(\boldsymbol{\mu}_i\)</span> by <span class="math inline">\(\boldsymbol{\hat{\mu}}_i\)</span>in <a href="#eq-sampcov-reg">Equation&nbsp;<span>27.42</span></a>.</p>
<p>To illustrate the application of point sampling and multinomial logit models at sub-national scale, crop acreage estimates were generated for three districts (Arrondissements) within the Nioro region: Medina Sabakh, Paoskoto, and Wack Ngouna. The estimates are in <a href="#tbl-district">Table&nbsp;<span>27.4</span></a> (Annex 4 contains the R scripts to compute these estimates using the database provided in Annex 6a, and Annex 5 contains the R Scripts to compute the standard errors and coefficients of variation, using the database provided in Annex 6c).</p>
<div id="tbl-district" class="anchored">
<table class="table">
<caption>Table&nbsp;27.4: Crop acreage estimates at the district level, Nioro, Senegal, 2021.</caption>
<thead><tr class="header">
<th style="text-align: left;">Arrondissement</th>
<th style="text-align: left;">Millet</th>
<th style="text-align: left;">Groundnut</th>
<th></th>
<th></th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Acreage (has.)</td>
<td style="text-align: left;">Error (CV%)</td>
<td>Acreage (has.)</td>
<td>Error (CV%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Medina Sabakh</td>
<td style="text-align: left;">20067.21</td>
<td style="text-align: left;">8.6</td>
<td>19765.36</td>
<td>7.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Paoskoto</td>
<td style="text-align: left;">38316.02</td>
<td style="text-align: left;">5.3</td>
<td>35018.23</td>
<td>4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wack Ngouna</td>
<td style="text-align: left;">30831.77</td>
<td style="text-align: left;">11.9</td>
<td>24030.71</td>
<td>10.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total Nioro</td>
<td style="text-align: left;">89215,00</td>
<td style="text-align: left;">4.11</td>
<td>78815,00</td>
<td>3.71</td>
</tr>
</tbody>
</table>
</div>
<p>The estimated accuracy at district (arrondissement) level is, as expected, lower than at the national level. However, the sampling error is within the standard limit (coefficient of variation <span class="math inline">\(\lt\)</span> 20%) for labeling as official statistics.</p>
<p>The differences between the number of pixels in the EO crop type millet and the design-based estimate of the number of pixels covered by millet are smaller than the sampling error in Medina Sabakh (0.7%) and Paoskoto (4.1%), and larger than the design-based estimate in Wack Ngouna (12.4%). The differences between the number of pixels in the EO crop type groundnut and the design-based estimate of the number of pixels covered by groundnut are smaller than sampling error in the three districts: Medina Sabakh (3.4%), Paoskoto (2.5%), and Wack Ngouna (1.2%).</p>
</section><section id="concluding-remarks" class="level2" data-number="27.8"><h2 data-number="27.8" class="anchored" data-anchor-id="concluding-remarks">
<span class="header-section-number">27.8</span> Concluding remarks</h2>
<p>We have shown how to integrate RS and categorical ground data collected in complex samples, selected from non-georeferenced list frames, to produce agricultural statistics, along with measures of accuracy that take into account any source of uncertainty, including classification errors. We developed and tested prototypes for this integration at both national and district levels in Senegal. These prototypes are based on the design of a probabilistic scheme to select the sample from which to collect the ground data and rely on multinomial logit models to incorporate RS-derived crop-type information. We show how to estimate the model parameters, and how to use RS data to compute the required statistics, as well as their accuracy measures. The resulting statistics are design-consistent and robust, meaning they depend on the sampling design rather than on the model assumptions.</p>
<p>We also evaluated the efficiency gains from integrating RS data into the current statistical workflow, and we have found it to be high: using RS data, the current sample size at the level of large areas could be reduced between one third and one fifth, without loss of neither robustness nor accuracy.</p>
</section><section id="about-the-authors" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="about-the-authors">About the authors</h2>
<p>Luis Ambrosio Flores (luis.ambrosio@upm.es) is professor of Statistics. Expert in agricultural and environmental statistics, econometric modeling, climate impact assessment, and EU biodiversity frameworks. Led 30 research projects and served as consultant (ESA, FAO, EU). Key projects: SEN4Stat - Sentinels for Agricultural Statistics; Global Strategy (GS)-Improving Agricultural &amp; Rural Statistics; Econometric models for assessing climate change impact on agriculture and environment (Spanish Ministry of Science and Technology). Author of 50 publications with 404 citations on Google Scholar.</p>
</section><section id="references" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="references">References</h2>


<div id="refs" class="references csl-bib-body" role="list">
<div id="ref-Ambrosio2023" class="csl-entry" role="listitem">
<div class="csl-left-margin">[1] </div>
<div class="csl-right-inline">L. Ambrosio, L. Iglesias, C. Marín, and N. Deffense, <span>“Integration of remote sensing data into national statistical office sampling designs for agriculture,”</span> <em>Statistical Journal of the IAOS</em>, vol. 39, no. 2, pp. 473–489, 2023, doi: <a href="https://doi.org/10.3233/SJI-220116">10.3233/SJI-220116</a>.</div>
</div>
<div id="ref-Fuller2011" class="csl-entry" role="listitem">
<div class="csl-left-margin">[2] </div>
<div class="csl-right-inline">W. A. Fuller, <em>Sampling statistics</em>. John Wiley &amp; Sons, 2011.</div>
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./crop_statistics_regression.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Estimating crop statistics using survey-calibrated methods</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./crop_statistics_ppi.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Prediction-Powered Inference (PPI) for Agricultural Decision-Making</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">Edited by Gilberto Camara, Lorenzo de Simone and Ronald Jansen.</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">This book was built with <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>


</body></html>