<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Gilberto Camara, Lorenzo de Simone, Ronald Jansen">
<title>15&nbsp; Efficient and Reliable Paddy Rice Classification – UN Handbook on Remote Sensing for Agricultural Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./ct_chile.html" rel="next">
<link href="./ct_zimbabwe.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-931bd9de4a2e97c797357f31cd37fa94.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./crop_type_mapping.html">Use Cases in Crop Type Mapping</a></li><li class="breadcrumb-item"><a href="./ct_china.html"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Efficient and Reliable Paddy Rice Classification</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">UN Handbook on Remote Sensing for Agricultural Statistics</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/FAO-EOSTAT/UN-Handbook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About the Authors</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./howto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">How to Use the Handbook</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_remote_sensing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">An Overview of Remote Sensing Satellites for Agricultural Applications</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_data_sources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Big Earth Observation Data Cloud Services</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_data_cubes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Earth observation data cubes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_lucc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Land Cover and Crop Classification Schemas for Agricultural Statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_quality_control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Quality Control of Training Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_machine_learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Machine Learning Algorithms for Image Time Series Classification</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_uncertainty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Spatial Map Uncertainty Estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Map Validation and Use of Maps for Area Estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_design_frames.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Remote Sensing in the Design of Sampling Frames</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_alignment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Alignment of Field Data Collection to EO Statistical Requirements</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_parcel_extraction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Semantic Segmentation for Automatic Field Boundary Delineation</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./crop_type_mapping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Use Cases in Crop Type Mapping</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_poland.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Crop Monitoring with Sentinel-1 and Sentinel-2 Images in Poland</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_mexico.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Crop Classification in Mexico</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_zimbabwe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Crop Classification in Zimbabwe</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_china.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Efficient and Reliable Paddy Rice Classification</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_chile.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Crop Classification and Land Use Mapping in Chile</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_digital_earth_africa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Agricultural Mapping with Digital Earth Africa</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./crop_yield_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Crop Yield Estimation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_finland.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Early-season Crop Yield Mapping in Finland</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_indonesia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Mapping Crop Phenology in Indonesia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_colombia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Rice Phenology Mapping in Colombia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_poland.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Yield Forecasting in Poland</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_china.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Remote Sensing Estimation of Soybean Yield Based on Multi-Scenario Simulation</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./crop_statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Extraction of Crop Statistics from Crop Type Maps</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./crop_statistics_area.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Crop Statistics using Weighted Area Estimators</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./crop_statistics_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Crop Statistics using Survey Calibrated Mapping</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./crop_statistics_calibration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Estimating Crop statistics for List Frame Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./crop_statistics_ppi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Prediction-Powered Inference for Agricultural Decision-Making</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./uav_agriculture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">UAV applications in agricultural statistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uav_field_parcels.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Field Parcel Identification Using UAV Imagery Based on the DCP-MTL Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uav_wheat_growth.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Application of UAV in Wheat Growth Monitoring</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uav_crop_growth.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Automated Monitoring of Crop Growth Index using UAV</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uav_agriculture_cook_islands.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Integrating UAV Imagery into Agricultural Statistics in the Cook Islands</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./disaster_response.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Remote Sensing for Agricultural Disaster Response</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dis_china_floods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">An Automated Flood Detection Algorithm for Post-Disaster Assessment</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./additional.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Additional Topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ad_world_cereal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">WorldCereal - A Global Effort for Crop Mapping</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ad_learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Personalised Learning Program for Training in the Use of Earth Observation for Agricultural Statistics</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">15.1</span> Introduction</a></li>
  <li><a href="#experimental-area-and-data" id="toc-experimental-area-and-data" class="nav-link" data-scroll-target="#experimental-area-and-data"><span class="header-section-number">15.2</span> Experimental Area and Data</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><span class="header-section-number">15.3</span> Methods</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">15.4</span> Results</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">15.5</span> Discussion</a></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions"><span class="header-section-number">15.6</span> Conclusions</a></li>
  <li><a href="#code-and-data-availability" id="toc-code-and-data-availability" class="nav-link" data-scroll-target="#code-and-data-availability">Code and data availability</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/FAO-EOSTAT/UN-Handbook/edit/quarto/ct_china.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/FAO-EOSTAT/UN-Handbook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./crop_type_mapping.html">Use Cases in Crop Type Mapping</a></li><li class="breadcrumb-item"><a href="./ct_china.html"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Efficient and Reliable Paddy Rice Classification</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title">
<span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Efficient and Reliable Paddy Rice Classification</span>
</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jingfeng Huang, Yifeng Lou </p>
          </div>
  </div>
    
  
    
  </div>
  


</header><section id="introduction" class="level2" data-number="15.1"><h2 data-number="15.1" class="anchored" data-anchor-id="introduction">
<span class="header-section-number">15.1</span> Introduction</h2>
<p>Paddy rice is a key component of global food security, particularly in Asia, where it serves as the staple food for billions of people and sustains rural livelihoods <span class="citation" data-cites="FAO2021"><a href="#ref-FAO2021" role="doc-biblioref">[1]</a></span>. However, rice cultivation is resource intensive, requiring substantial irrigation and contributing significantly to methane emissions <span class="citation" data-cites="Yan2009"><a href="#ref-Yan2009" role="doc-biblioref">[2]</a></span>. Timely and accurate information on the distribution of paddy rice is therefore essential for production monitoring, environmental sustainability, water resource management, and climate change mitigation <span class="citation" data-cites="Carrasco2022"><a href="#ref-Carrasco2022" role="doc-biblioref">[3]</a></span>.</p>
<p>This section introduces a paddy rice identification index that combines optical and Synthetic Aperture Radar (SAR) features—PRICOS (Paddy Rice Index Combining Optical and SAR features) <span class="citation" data-cites="Lou2025"><a href="#ref-Lou2025" role="doc-biblioref">[4]</a></span>, which integrates optical data with Synthetic Aperture Radar (SAR) observations. By combining these data sources, PRICOS reduces common challenges in remote sensing, such as cloud cover and speckle noise, thereby improving classification reliability. Using time-series data from Sentinel-1 and Sentinel-2, the method identifies key rice phenological stages and can perform effectively even in areas with limited ground samples. PRICOS enhances the timeliness, spatial resolution, and reliability of rice statistics, providing support for agricultural planning and policy development.</p>
</section><section id="experimental-area-and-data" class="level2" data-number="15.2"><h2 data-number="15.2" class="anchored" data-anchor-id="experimental-area-and-data">
<span class="header-section-number">15.2</span> Experimental Area and Data</h2>
<p>PRICOS was validated in two experimental areas, as shown in <a href="#fig-1-ct-china" class="quarto-xref">Figure&nbsp;<span>15.1</span></a> and <a href="#fig-2-ct-china" class="quarto-xref">Figure&nbsp;<span>15.2</span></a>. Site A is Huachuan County, Jiamusi City, Heilongjiang Province, China (130°16′–131°34′E, 46°37′–47°14′N), with an area of approximately 2,268 km². It is a typical single-cropping rice area in Northeast China. The terrain is flat, and the region has a temperate continental monsoon climate, with an average annual temperature of about 3.5 °C and annual precipitation of around 550 mm. A single-cropping rice system is practiced, with transplanting usually in mid-May and harvesting in early October.</p>
<p>Site B is Colusa County, California, United States (121°47′–122°47′W, 38°55′–39°24′N), covering an area of approximately 2,995 km². It is located in the Sacramento Valley, one of the major rice-producing regions in the United States. The area has a Mediterranean climate, characterized by hot, dry summers and mild, wet winters. The average annual temperature is about 16.5 °C, and annual precipitation is around 400 mm, mainly from November to March. A single-cropping rice system is also practiced here, with sowing generally from late April to early May and harvesting from late September to early October.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-1-ct-china" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-1-ct-china-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/ct_china/image1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-1-ct-china-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15.1: Huachuan County, Jiamusi City, Heilongjiang Province, China. Sentinel-2 median composite image using false color synthesis (red: B8, green: B4, blue:B3).
</figcaption></figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-2-ct-china" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-2-ct-china-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/ct_china/image2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2-ct-china-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15.2: Colusa County, California, United States. Sentinel-2 median composite image using false color synthesis (red: B8, green: B4, blue:B3).
</figcaption></figure>
</div>
</div>
</div>
<p>The input data for this case study consists of Sentinel-1 Synthetic Aperture Radar (SAR) images covering the rice-growing season in 2019 and Sentinel-2 multispectral images from the corresponding period. For Sentinel-1, data selection was based on the Interferometric Wide (IW) mode and descending orbit, with only VH polarization retained. Speckle noise was addressed using local mean and variance within a 7×7 neighborhood, with the signal-to-noise ratio (SNR) calculated as the ratio of variance to the squared mean. Pixels with SNR greater than or equal to 1 were masked to suppress high-noise areas, and a Gaussian kernel was subsequently applied for smoothing. The images were reprojected to a unified coordinate system and spatial resolution (Coordinate reference system: WGS 1984 (EPSG:4326). Spatial resolution: 10 m), clipped to the study area, and augmented with a day-of-year (DOY) band for time-series analysis.</p>
<p>For Sentinel-2 optical imagery, cloud masking was performed using the cloud probability band (cs_cdf) provided by Google Cloud Score Plus, retaining pixels with cs_cdf values greater than or equal to 0.5. For each acquisition, the Normalized Difference Vegetation Index (NDVI) and the Modified Normalized Difference Water Index (MNDWI) were calculated. A third-order harmonic regression model was then applied to generate smoothed NDVI and MNDWI time-series curves.</p>
</section><section id="methods" class="level2" data-number="15.3"><h2 data-number="15.3" class="anchored" data-anchor-id="methods">
<span class="header-section-number">15.3</span> Methods</h2>
<p>As shown in <a href="#fig-3-ct-china" class="quarto-xref">Figure&nbsp;<span>15.3</span></a>, the PRICOS mapping framework consists of five main steps:</p>
<p>Step 1: Determine the rice growth period based on a limited number of samples. Specifically, the mean NDVI, MNDWI, and VH time series were derived from a small set of paddy rice sample points in GEE. By combining the water signal during the transplanting stage with the vegetation signal during the maturity stage, the sowing phase was defined as the 15 days prior to the point when MNDWI exceeded 0 and VH began to show a rapid decline. Subsequently, the maturity–harvest phase was defined as the period when NDVI decreased from its maximum value to 0.3. The duration from the onset of sowing to the end of harvest was defined as the rice growth period. For regions with available rice cropping calendars, the corresponding period was directly specified in the code.</p>
<p>Step 2: Extract seven key phenological indicators from the smoothed time series: the minimum NDVI during the transplanting stage (p1), the maximum NDVI during the peak growth stage (p2), the maximum MNDWI during the transplanting stage (p3), the minimum VH during the transplanting stage (p4) along with its corresponding day of year (<span class="math inline">\({p4}_{doy}\)</span>), and the maximum VH during the peak growth stage (p5) along with its corresponding day of year (<span class="math inline">\({p5}_{doy}\)</span>).</p>
<p>Step 3: Define four normalization functions—f(a), f(b), f(c), and f(h)—based on the extracted phenological features, and construct the PRICOS index through their multiplicative combination. The formulas are defined as follows: <span class="math display">\[
f(a) = 1 - {p1}^{2}
\]</span> <span class="math display">\[
  f(b) = 1 - (1 - p2)^{2},p2 &gt; 0,\ \ f(b) = 0,\ p2 \leq 0
\]</span> <span class="math display">\[
  f(c) = 1 + p3,p3 \leq 0,\ \ f(c) = 0,\ p3 &gt; 0
\]</span></p>
<p><span class="math display">\[
  f(h) = \frac{2\alpha}{\pi},{\alpha = arctan}\left( \frac{30h}{l} \right),h = p5 - p4,l = {p5}_{doy} - {p4}_{doy}
  \]</span> <span class="math display">\[
PRICOS = f(a) \times f(b) \times f(c) \times f(h)\
\]</span> Step 5: Validate the results using reference datasets from China and the United States. In China, the 10-meter resolution paddy rice dataset constructed by Shen et al.&nbsp;[<span class="citation" data-cites="Shen2023"><a href="#ref-Shen2023" role="doc-biblioref">[5]</a></span>] was used. In the United States, the 30-meter resolution Cropland Data Layer (CDL, https://croplandcros.scinet.usda.gov/) served as the reference. Classification accuracy was evaluated using five commonly adopted metrics: Overall Accuracy (OA), Precision, Recall, F1-Score, and Intersection over Union (IoU).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-3-ct-china" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-3-ct-china-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/ct_china/image3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-3-ct-china-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15.3: PRICOS rice mapping workflow.
</figcaption></figure>
</div>
</div>
</div>
<p>The validation procedure was conducted as follows: first, clip both the predicted paddy rice map and the reference map using the same administrative boundary to ensure spatial consistency; next, resample all data to a uniform spatial resolution of 10 meters; finally, conduct a pixel-wise comparison (1 for paddy rice, 0 for non-rice) to calculate the accuracy metrics.</p>
</section><section id="results" class="level2" data-number="15.4"><h2 data-number="15.4" class="anchored" data-anchor-id="results">
<span class="header-section-number">15.4</span> Results</h2>
<p><a href="#tbl-accuracy" class="quarto-xref">Table&nbsp;<span>15.1</span></a> summarizes the classification accuracy metrics for Sites A and B, including IoU, OA, Precision, Recall, and F1-Score. The results indicate that the PRICOS method achieved high classification performance in both regions. Specifically, IoU values for Sites A and B were 0.8237 and 0.8682, respectively, indicating a high spatial agreement between the predicted and reference paddy rice distributions. The OA values reached 0.9678 at Site A and 0.9838 at Site B, showing that over 96% of pixels were correctly classified, with overall classification errors being minimal. Regarding Precision, the values of 0.8812 (Site A) and 0.9720 (Site B) suggest that between 88% and 97% of pixels classified as paddy rice correspond to actual rice areas, implying a low false positive rate. Recall values were 0.9267 and 0.8905, respectively, suggesting that 89%–93% of the actual paddy rice pixels were successfully detected by the model, with a controlled false negative rate. The F1-Scores were 0.9034 and 0.9295, reflecting a well-balanced trade-off between Precision and Recall. Comparatively, the classification results for Site B outperformed Site A, which may be partly attributed to differences in reference data quality.</p>
<div id="tbl-accuracy" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-accuracy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;15.1: Accuracy evaluation
</figcaption><div aria-describedby="tbl-accuracy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 16%">
<col style="width: 14%">
<col style="width: 16%">
</colgroup>
<thead><tr class="header">
<th>Experimental area</th>
<th>IoU</th>
<th>OA</th>
<th>Precision</th>
<th>Recall</th>
<th>F1 score</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>0.8237</td>
<td>0.9678</td>
<td>0.8812</td>
<td>0.9267</td>
<td>0.9034</td>
</tr>
<tr class="even">
<td>B</td>
<td>0.8682</td>
<td>0.9838</td>
<td>0.9720</td>
<td>0.8905</td>
<td>0.9295</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-4-ct-china" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-4-ct-china-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/ct_china/image4.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-4-ct-china-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15.4: Comparison of rice extraction results with reference data and Sentinel-2 images in Huachuan County, China: (a) PRICOS results; (b) Reference data; (c) Satellite images.
</figcaption></figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-5-ct-china" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-5-ct-china-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/ct_china/image5.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5-ct-china-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15.5: Comparison of rice extraction results in Colusa County with reference data and Sentinel-2 images: (a) PRICOS results; (b) Reference data; (c) Satellite images.
</figcaption></figure>
</div>
</div>
</div>
<p>In this study, a threshold of 0.6 was applied to the PRICOS-derived maps for paddy rice extraction. Since the PRICOS results represent normalized probabilities of rice cultivation, with values closer to 1 indicating a higher likelihood of paddy rice, researchers may adjust this threshold according to specific mapping requirements.</p>
<p><a href="#fig-4-ct-china" class="quarto-xref">Figure&nbsp;<span>15.4</span></a> and <a href="#fig-5-ct-china" class="quarto-xref">Figure&nbsp;<span>15.5</span></a> present the paddy rice distribution maps for Sites A and B extracted using a 0.6 threshold. Compared with the reference maps and satellite imagery, PRICOS demonstrated high reliability in both regions. At the field scale, Site A showed particularly accurate delineation. Although some paddy rice pixels were missed in Site B, the high spatial resolution of the satellite imagery allowed for relatively precise depiction of field boundaries. Specifically, in Site A, PRICOS successfully reconstructed complete rectangular paddy rice fields with clear boundaries, as shown in <a href="#fig-4-ct-china" class="quarto-xref">Figure&nbsp;<span>15.4</span></a> (a1) and (a2), consistent with field features visible in satellite imagery (<a href="#fig-4-ct-china" class="quarto-xref">Figure&nbsp;<span>15.4</span></a> (c1) and (c2)). In contrast, the TWDTW-derived reference map exhibited patchy “gaps” and isolated small areas, with some actual rice fields omitted (<a href="#fig-4-ct-china" class="quarto-xref">Figure&nbsp;<span>15.4</span></a> (b1) and (b2) <span class="citation" data-cites="Shen2023"><a href="#ref-Shen2023" role="doc-biblioref">[5]</a></span>. In Site B, PRICOS captured field boundaries more accurately in the northern zoomed-in area as shown <a href="#fig-5-ct-china" class="quarto-xref">Figure&nbsp;<span>15.5</span></a> (a1) and (a2), as confirmed by both satellite imagery, as per <a href="#fig-5-ct-china" class="quarto-xref">Figure&nbsp;<span>15.5</span></a> (c1) and (c2), and the CDL reference map, shown in <a href="#fig-5-ct-china" class="quarto-xref">Figure&nbsp;<span>15.5</span></a> (b1) and (b2). In the southern zoomed-in area (<a href="#fig-5-ct-china" class="quarto-xref">Figure&nbsp;<span>15.5</span></a> (a2)), some paddy rice pixels were still missed, indicating minor under-detection in that region.</p>
</section><section id="discussion" class="level2" data-number="15.5"><h2 data-number="15.5" class="anchored" data-anchor-id="discussion">
<span class="header-section-number">15.5</span> Discussion</h2>
<p>PRICOS offers significant practical value within agricultural statistical systems, mainly in the following three aspects:</p>
<ol type="1">
<li><p>Improving estimation accuracy and adaptability: By integrating optical and SAR time-series data, PRICOS effectively overcomes common limitations in remote sensing, such as cloud cover and complex terrain. Compared with traditional methods, this approach provides a substantial improvement in overall accuracy. It offers a reliable and efficient technical solution for large-scale paddy rice area estimation, while greatly reducing the manpower and time required for field surveys.</p></li>
<li><p>Promoting standardization and automation of monitoring workflows: Conventional rice mapping methods often rely on empirical thresholds or complex parameter tuning, limiting their general applicability. PRICOS extracts key phenological features using harmonic fitting, ensuring stable performance across different agricultural landscapes. This facilitates the establishment of unified national remote sensing monitoring standards and automated processing workflows, enhancing the consistency and sustainability of monitoring operations.</p></li>
<li><p>Supporting resource management and the development of a green statistical system: Rice cultivation is closely linked to methane emissions and water resource consumption. With a high spatial resolution of 10 meters and frequent temporal coverage, PRICOS enables detailed mapping of dynamic changes in rice-growing areas. It provides critical data for farmland protection, carbon emission accounting, and irrigation optimization, laying the foundation for an environmentally oriented agricultural statistical system.</p></li>
</ol>
<p>Extensive validation across multiple regions yielded the following key findings and suggested future improvements:</p>
<ol type="1">
<li><p>Multi-source feature fusion enhances classification performance: The combined use of NDVI, MNDWI, and VH backscatter significantly improved rice classification accuracy, confirming the effectiveness of multi-source data integration.</p></li>
<li><p>Regional differences in SAR feature applicability: SAR-based indicators performed well in flat terrain but were prone to confusion with wetland vegetation in complex or fragmented landscapes. Introducing terrain correction and auxiliary optical validation is recommended to enhance applicability in heterogeneous environments.</p></li>
<li><p>Lightweight design suitable for areas with scarce samples: PRICOS constructs models based on time-series features without requiring extensive ground samples, ensuring high transferability and robustness. This makes it particularly suitable for areas with limited samples and highlights its potential for global rice monitoring.</p></li>
<li><p>Limitations due to dependence on optical data: The harmonic fitting process relies heavily on high-quality optical time-series data, which may be affected in regions with persistent cloud cover. Future research should explore SAR-dominated alternatives to strengthen all-weather monitoring capabilities.</p></li>
<li><p>Adaptive strategies for regions with diverse phenology: In mountainous or phenologically heterogeneous areas, feature extraction strategies should be dynamically adjusted based on local cropping calendars to improve regional adaptability and classification accuracy.</p></li>
</ol></section><section id="conclusions" class="level2" data-number="15.6"><h2 data-number="15.6" class="anchored" data-anchor-id="conclusions">
<span class="header-section-number">15.6</span> Conclusions</h2>
<p>This study demonstrates that the PRICOS method, which integrates optical and SAR time-series features, enables efficient and reliable identification and mapping of paddy rice. In two representative study areas—Huachuan County, China, and Colusa County, United States—PRICOS achieved excellent classification accuracy, with IoU values of 0.8237 and 0.8682, OA values of 0.9678 and 0.9838, and F1-scores above 0.90. These results indicate that PRICOS provides stable performance and strong generalization capability. In addition, PRICOS does not rely on extensive ground samples, offering advantages of being lightweight and highly transferable, which makes it particularly suitable for application in regions with limited field data.</p>
</section><section id="code-and-data-availability" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="code-and-data-availability">Code and data availability</h2>
<p>The PRICOS code is available in the <a href="https://github.com/JokoLou/A-Paddy-Rice-Index-Combining-Optical-and-SAR-Features-PRICOS">GitHub link</a>. Due to the large amount of input data, only part of Colusa County is shown. In this study, Python 3.12 was used. The main code was developed and executed in a Windows 11 environment, relying on multiple third-party libraries for remote sensing image reading, processing, visualization, and classification accuracy evaluation. To ensure stability and compatibility in spatial data processing, it is recommended to create a virtual environment on the Anaconda platform for unified management of library versions.</p>
<p>The code is also available in <a href="https://code.earthengine.google.com/eb4f07a4d990934a55022941e722ec3f">Google Earth Engine (GEE)</a>. Due to GEE memory limitations, only part of Colusa County is shown.</p>
</section><section id="references" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="references">References</h2>


<div id="refs" class="references csl-bib-body" data-entry-spacing="0" role="list">
<div id="ref-FAO2021" class="csl-entry" role="listitem">
<div class="csl-left-margin">[1] </div>
<div class="csl-right-inline">FAO, <em><a href="https://openknowledge.fao.org/handle/20.500.14283/cb4477en">World <span>Food</span> and <span>Agriculture</span> – <span>Statistical Yearbook</span> 2021</a></em>. FAO ;, 2021.</div>
</div>
<div id="ref-Yan2009" class="csl-entry" role="listitem">
<div class="csl-left-margin">[2] </div>
<div class="csl-right-inline">X. Yan, H. Akiyama, K. Yagi, and H. Akimoto, <span>“Global estimations of the inventory and mitigation potential of methane emissions from rice cultivation conducted using the 2006 <span>Intergovernmental Panel</span> on <span>Climate Change Guidelines</span>,”</span> <em>Global Biogeochemical Cycles</em>, vol. 23, no. 2, 2009, doi: <a href="https://doi.org/10.1029/2008GB003299">10.1029/2008GB003299</a>.</div>
</div>
<div id="ref-Carrasco2022" class="csl-entry" role="listitem">
<div class="csl-left-margin">[3] </div>
<div class="csl-right-inline">L. Carrasco, G. Fujita, K. Kito, and T. Miyashita, <span>“Historical mapping of rice fields in <span>Japan</span> using phenology and temporally aggregated <span>Landsat</span> images in <span>Google Earth Engine</span>,”</span> <em>ISPRS Journal of Photogrammetry and Remote Sensing</em>, vol. 191, pp. 277–289, 2022, doi: <a href="https://doi.org/10.1016/j.isprsjprs.2022.07.018">10.1016/j.isprsjprs.2022.07.018</a>.</div>
</div>
<div id="ref-Lou2025" class="csl-entry" role="listitem">
<div class="csl-left-margin">[4] </div>
<div class="csl-right-inline">Y. Lou <em>et al.</em>, <span>“<span>PRICOS</span>: <span>A Robust Paddy Rice Index Combining Optical</span> and <span>Synthetic Aperture Radar Features</span> for <span>Improved Mapping Efficiency</span>,”</span> <em>Remote Sensing</em>, vol. 17, no. 4, p. 692, 2025, doi: <a href="https://doi.org/10.3390/rs17040692">10.3390/rs17040692</a>.</div>
</div>
<div id="ref-Shen2023" class="csl-entry" role="listitem">
<div class="csl-left-margin">[5] </div>
<div class="csl-right-inline">R. Shen <em>et al.</em>, <span>“High-resolution distribution maps of single-season rice in <span>China</span> from 2017 to 2022,”</span> <em>Earth System Science Data</em>, vol. 15, no. 7, pp. 3203–3222, 2023, doi: <a href="https://doi.org/10.5194/essd-15-3203-2023">10.5194/essd-15-3203-2023</a>.</div>
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/FAO-EOSTAT\.github\.io\/UN-Handbook\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./ct_zimbabwe.html" class="pagination-link" aria-label="Crop Classification in Zimbabwe">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Crop Classification in Zimbabwe</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./ct_chile.html" class="pagination-link" aria-label="Crop Classification and Land Use Mapping in Chile">
        <span class="nav-page-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Crop Classification and Land Use Mapping in Chile</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>Edited by Gilberto Camara, Lorenzo de Simone and Ronald Jansen.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/FAO-EOSTAT/UN-Handbook/edit/quarto/ct_china.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/FAO-EOSTAT/UN-Handbook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>


</body></html>