<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Gilberto Camara, Lorenzo de Simone, Ronald Jansen">
<title>UN Handbook on Remote Sensing for Agricultural Statistics - 23&nbsp; Rice Phenology Mapping in Colombia</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./cy_poland.html" rel="next">
<link href="./cy_indonesia.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./crop_yield_estimation.html">Crop yield estimation</a></li><li class="breadcrumb-item"><a href="./cy_colombia.html"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Rice Phenology Mapping in Colombia</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">UN Handbook on Remote Sensing for Agricultural Statistics</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/FAO-EOSTAT/UN-Handbook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Welcome</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./howto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">How to use this handbook</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_remote_sensing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Remote sensing images: optical, SAR</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_data_sources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Earth observation big data sources</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_data_cubes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Earth observation data cubes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_lucc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Land cover and crop classification schemas</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_quality_control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Quality control of training sets for agricultural statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_machine_learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Machine learning algorithms for image time series</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_uncertainty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Spatial map uncertainty estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Map validation and use of maps for area estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_design_frames.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Remote Sensing in the Design of Sampling Frames</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_alignment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Alignment of field data collection to EO statistical requirements</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_parcel_extraction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Semantic Segmentation for Automatic Field Boundary Delineation</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./crop_type_mapping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Use Cases in Crop Type Mapping</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_poland.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Crop monitoring with Sentinel-1 and Sentinel-2 images in Poland</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_mexico.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Crop classification in Mexico</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_zimbabwe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Crop classification in Zimbabwe</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_china.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Efficient and Reliable Paddy Rice Classification</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_chile.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Crop classification and land use mapping in Chile</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_digital_earth_africa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Agricultural Mapping with Digital Earth Africa</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./crop_yield_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Crop yield estimation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_finland.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Early-season crop yield mapping in Finland</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_indonesia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Mapping crop phenology in Indonesia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_colombia.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Rice Phenology Mapping in Colombia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_poland.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Yield forecasting in Poland</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_china.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Remote Sensing Estimation of Soybean Yield Based on Multi-Scenario Simulation</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./crop_statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Extraction of crop statistics from crop type and crop yield maps</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./crop_statistics_area.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Crop Statistics using Weighted Area Estimators</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./crop_statistics_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Estimating crop statistics using survey-calibrated methods</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./crop_statistics_calibration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Estimating crop statistics for list frame data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./crop_statistics_ppi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Prediction-Powered Inference (PPI) for Agricultural Decision-Making</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./uav_agriculture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">UAV applications in agricultural statistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uav_field_parcels.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Field Parcel Identification Using UAV Imagery Based on the DCP-MTL Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uav_wheat_growth.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Application of UAV in Wheat Growth Monitoring</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uav_crop_growth.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Automated Monitoring of Crop Growth Index using UAV</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./disaster_response.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Remote Sensing for Agricultural Disaster Response</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dis_china_floods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">An Automated Flood Detection Algorithm for Post-Disaster Assessment</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./additional.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Additional Topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ad_world_cereal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">WorldCereal - A Global Effort for Crop Mapping</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ad_learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Personalised Learning Program for Training in the Use of Earth Observation for Agricultural Statistics</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">23.1</span> Introduction</a></li>
  <li><a href="#dual-polarimetric-radar-vegetation-index-dprvi" id="toc-dual-polarimetric-radar-vegetation-index-dprvi" class="nav-link" data-scroll-target="#dual-polarimetric-radar-vegetation-index-dprvi"><span class="header-section-number">23.2</span> Dual-polarimetric radar vegetation index (DpRVI)</a></li>
  <li>
<a href="#rice-crop-phenology" id="toc-rice-crop-phenology" class="nav-link" data-scroll-target="#rice-crop-phenology"><span class="header-section-number">23.3</span> Rice crop phenology</a>
  <ul class="collapse">
<li><a href="#dprvi-across-rice-stages" id="toc-dprvi-across-rice-stages" class="nav-link" data-scroll-target="#dprvi-across-rice-stages"><span class="header-section-number">23.3.1</span> DpRVI across rice stages</a></li>
  </ul>
</li>
  <li>
<a href="#workflow" id="toc-workflow" class="nav-link" data-scroll-target="#workflow"><span class="header-section-number">23.4</span> Workflow</a>
  <ul class="collapse">
<li><a href="#data-cube-creation" id="toc-data-cube-creation" class="nav-link" data-scroll-target="#data-cube-creation"><span class="header-section-number">23.4.1</span> Data cube creation</a></li>
  <li><a href="#field-data-collection" id="toc-field-data-collection" class="nav-link" data-scroll-target="#field-data-collection"><span class="header-section-number">23.4.2</span> Field data collection</a></li>
  <li><a href="#extracting-dprvi-values-from-the-data-cube" id="toc-extracting-dprvi-values-from-the-data-cube" class="nav-link" data-scroll-target="#extracting-dprvi-values-from-the-data-cube"><span class="header-section-number">23.4.3</span> Extracting DpRVI values from the data cube</a></li>
  <li><a href="#data-quality-control" id="toc-data-quality-control" class="nav-link" data-scroll-target="#data-quality-control"><span class="header-section-number">23.4.4</span> Data quality control</a></li>
  <li><a href="#noisy-sample-detection" id="toc-noisy-sample-detection" class="nav-link" data-scroll-target="#noisy-sample-detection"><span class="header-section-number">23.4.5</span> Noisy sample detection</a></li>
  <li><a href="#random-forest-classification" id="toc-random-forest-classification" class="nav-link" data-scroll-target="#random-forest-classification"><span class="header-section-number">23.4.6</span> Random Forest classification</a></li>
  </ul>
</li>
  <li>
<a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">23.5</span> Results</a>
  <ul class="collapse">
<li><a href="#model-performance-evaluation" id="toc-model-performance-evaluation" class="nav-link" data-scroll-target="#model-performance-evaluation"><span class="header-section-number">23.5.1</span> Model performance evaluation</a></li>
  <li><a href="#validation-protocol" id="toc-validation-protocol" class="nav-link" data-scroll-target="#validation-protocol"><span class="header-section-number">23.5.2</span> Validation Protocol</a></li>
  <li><a href="#classification" id="toc-classification" class="nav-link" data-scroll-target="#classification"><span class="header-section-number">23.5.3</span> Classification</a></li>
  <li><a href="#final-classification-results" id="toc-final-classification-results" class="nav-link" data-scroll-target="#final-classification-results"><span class="header-section-number">23.5.4</span> Final classification results</a></li>
  </ul>
</li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">23.6</span> Discussion</a></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions"><span class="header-section-number">23.7</span> Conclusions</a></li>
  <li><a href="#acknowledgements" id="toc-acknowledgements" class="nav-link" data-scroll-target="#acknowledgements">Acknowledgements</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul><div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/FAO-EOSTAT/UN-Handbook/edit/quarto/cy_colombia.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/FAO-EOSTAT/UN-Handbook/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">
<span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Rice Phenology Mapping in Colombia</span>
</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Freddy Martinez </p>
          </div>
  </div>
    
  
    
  </div>
  

</header><section id="introduction" class="level2" data-number="23.1"><h2 data-number="23.1" class="anchored" data-anchor-id="introduction">
<span class="header-section-number">23.1</span> Introduction</h2>
<p>Rice is a staple crop central to food security and national economies, including Colombia’s. Monitoring its spatial–temporal dynamics—particularly phenological stages—enables early production estimates and informs research, environmental assessments, and competitiveness analyses <span class="citation" data-cites="Dong_Xiao_rev Dong2016"><a href="#ref-Dong_Xiao_rev" role="doc-biblioref">[1]</a>, <a href="#ref-Dong2016" role="doc-biblioref">[2]</a></span>. Timely crop information also supports decisions on imports, price regulation, and sectoral policies, while phenology underpins agronomic management, crop identification, yield estimation, and input optimization <span class="citation" data-cites="ZHENG2016131 Waldini2021"><a href="#ref-ZHENG2016131" role="doc-biblioref">[3]</a>, <a href="#ref-Waldini2021" role="doc-biblioref">[4]</a></span>.</p>
<p>Obtaining accurate, timely information on cultivated area and phenological stages remains challenging because field surveys are costly and time‑consuming <span class="citation" data-cites="mosleh2015application"><a href="#ref-mosleh2015application" role="doc-biblioref">[5]</a></span>. In Colombia, heterogeneity further complicates monitoring: irrigated and rainfed systems coexist; field sizes range from &lt;10 to &gt;200 ha; and land preparation spans from leveled paddies to sloped plots <span class="citation" data-cites="CENSO_GENERAL"><a href="#ref-CENSO_GENERAL" role="doc-biblioref">[6]</a></span>.</p>
<p>Remote sensing offers a scalable alternative. Time‑series imagery supports large‑area monitoring and phenology mapping more efficiently than ground surveys <span class="citation" data-cites="Waldini2021"><a href="#ref-Waldini2021" role="doc-biblioref">[4]</a></span>. Optical indices such as NDVI are widely used <span class="citation" data-cites="palakuru2021exploring"><a href="#ref-palakuru2021exploring" role="doc-biblioref">[7]</a></span>, but in Colombia’s rainfed systems persistent cloud cover during the crop season limits optical observations. Synthetic Aperture Radar (SAR) overcomes cloud and illumination constraints <span class="citation" data-cites="YANG2021112394"><a href="#ref-YANG2021112394" role="doc-biblioref">[8]</a></span>. This work exploits dual‑polarization Sentinel‑1 data via the Dual‑polarimetric Radar Vegetation Index (DpRVI) to track rice phenology; detailed polarimetric rationale and processing appear in the dedicated DpRVI section.</p>
</section><section id="dual-polarimetric-radar-vegetation-index-dprvi" class="level2" data-number="23.2"><h2 data-number="23.2" class="anchored" data-anchor-id="dual-polarimetric-radar-vegetation-index-dprvi">
<span class="header-section-number">23.2</span> Dual-polarimetric radar vegetation index (DpRVI)</h2>
<p>The Dual-polarimetric Radar Vegetation Index (DpRVI) is an innovative vegetation index designed for monitoring crop growth using dual-polarization SAR data, such as that provided by the Sentinel-1 mission <span class="citation" data-cites="mandal2020dual"><a href="#ref-mandal2020dual" role="doc-biblioref">[9]</a></span>. It was developed to robustly and sensitively characterize vegetation dynamics, outperforming traditional backscatter-based approaches. Unlike other indices, DpRVI is normalized between 0 and 1, making it easier to interpret, particularly for users without radar expertise <span class="citation" data-cites="mandal2021radar"><a href="#ref-mandal2021radar" role="doc-biblioref">[10]</a></span>.</p>
<p>The DpRVI’s effectiveness stems from its fundamental design as a composite metric that captures both polarimetric complexity (degree of polarization, m) and scattering mechanism dominance (β = λ₁/Span) <span class="citation" data-cites="mandal2020dual"><a href="#ref-mandal2020dual" role="doc-biblioref">[9]</a></span>. Unlike conventional backscatter ratios (σ°VH/σ°VV) or simple polarimetric parameters, DpRVI encodes the complete second-order statistical characterization of the scattering process through the covariance matrix eigenvalue decomposition <span class="citation" data-cites="mandal2021radar"><a href="#ref-mandal2021radar" role="doc-biblioref">[10]</a></span>.</p>
<p>As illustrated in <a href="#fig-DpRVI">Figure&nbsp;<span>23.1</span></a>, the preprocessing workflow for Sentinel-1 Single Look Complex (SLC) data follows the approach in <span class="citation" data-cites="mandal2019sentinel"><a href="#ref-mandal2019sentinel" role="doc-biblioref">[11]</a></span>. Images were initially split into three subswaths to facilitate processing. Precise orbit files were then applied, followed by radiometric calibration, keeping outputs in complex format as required to form polarimetric matrices <span class="citation" data-cites="mandal2020dual"><a href="#ref-mandal2020dual" role="doc-biblioref">[9]</a></span>. The DpRVI index was generated using the SNAP software (version 11.0) from the European Space Agency (ESA), which provides advanced support for polarimetric processing and dual-polarization index computation from Sentinel-1 SLC data.</p>
<div class="cell" data-layout-align="center" data-hash="cy_colombia_cache/html/fig-DpRVI_ad918552713dc38828f3b8c5590ad88a">
<div class="cell-output-display">
<div id="fig-DpRVI" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/cy_colombia/dprvi.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;23.1: Process diagram for generating the DpRVI index</figcaption></figure>
</div>
</div>
</div>
<p>Following <span class="citation" data-cites="mandal2019sentinel"><a href="#ref-mandal2019sentinel" role="doc-biblioref">[11]</a></span>, images were co-registered with sub-pixel accuracy using the Sentinel-1 Back-Geocoding operator and the SRTM 1Sec Grid as DEM. Subswaths were then recombined using TOPS Deburst and Merge. A multilooking step (4×1, range×azimuth) produced square ground-range pixels. Polarimetric matrix elements were derived—limited to the <span class="math inline">\(2\times2\)</span> covariance matrix <span class="math inline">\([\mathbf{C2}]\)</span> from dual-polarization data—and despeckled using the Refined Lee filter with a <span class="math inline">\(5\times5\)</span> window <span class="citation" data-cites="mandal2019sentinel"><a href="#ref-mandal2019sentinel" role="doc-biblioref">[11]</a></span>. The complex-valued representation enables computing <span class="math inline">\(C_{11}\)</span>, <span class="math inline">\(C_{22}\)</span>, <span class="math inline">\(\Re(C_{12})\)</span>, and <span class="math inline">\(\Im(C_{12})\)</span>, which are required for DpRVI estimation <span class="citation" data-cites="mandal2020dual"><a href="#ref-mandal2020dual" role="doc-biblioref">[9]</a></span>.</p>
<p>The covariance matrix <span class="math inline">\(\mathbf{C2}\)</span> (<a href="#eq-1">Equation&nbsp;<span>23.1</span></a>), is essential for DpRVI and captures second-order statistics of the VV and VH radar channels <span class="citation" data-cites="mandal2021radar"><a href="#ref-mandal2021radar" role="doc-biblioref">[10]</a></span>:</p>
<p><span id="eq-1"><span class="math display">\[
\mathbf{C2} =
\begin{bmatrix}
C_{11} &amp; C_{12} \\
C_{21} &amp; C_{22}
\end{bmatrix}
=
\begin{bmatrix}
\langle |S_{VV}|^2 \rangle &amp; \langle S_{VV} S_{VH}^* \rangle \\
\langle S_{VH} S_{VV}^* \rangle &amp; \langle |S_{VH}|^2 \rangle
\end{bmatrix}
\tag{23.1}\]</span></span></p>
<p>Each term reflects:</p>
<ul>
<li><p><span class="math inline">\(\langle |S_{VV}|^2 \rangle\)</span>: Power of the co-polarized channel.</p></li>
<li><p><span class="math inline">\(\langle |S_{VH}|^2 \rangle\)</span>: Power of the cross-polarized channel.</p></li>
<li><p><span class="math inline">\(\langle S_{VV} S_{VH}^* \rangle\)</span>, <span class="math inline">\(\langle S_{VH} S_{VV}^* \rangle\)</span>: Complex cross-correlation between polarizations.</p></li>
</ul>
<p><span class="math display">\[\text{DpRVI} = 1 - m\beta\]</span> where <span class="math inline">\(m\)</span> is the degree of polarization, and <span class="math inline">\(\beta\)</span> the normalized dominant eigenvalue.</p>
<p>For dual‑pol <span class="math inline">\(\mathbf{C2}\)</span>, <span class="math inline">\(m\)</span> is computed from the covariance matrix as <span class="math inline">\(m = \sqrt{1 - \dfrac{4\,|\mathbf{C2}|}{\big(\mathrm{Tr}(\mathbf{C2})\big)^2}}\)</span>, and <span class="math inline">\(\beta\)</span> is set to <span class="math inline">\(\lambda_1/\mathrm{Span}\)</span> with <span class="math inline">\(\mathrm{Span}=\mathrm{Tr}(\mathbf{C2})\)</span> <span class="citation" data-cites="mandal2020dual"><a href="#ref-mandal2020dual" role="doc-biblioref">[9]</a></span>.</p>
<p>DpRVI jointly captures polarization purity and scattering dominance through <span class="math inline">\(m\)</span> and <span class="math inline">\(\beta = \lambda_1/\text{Span}\)</span> <span class="citation" data-cites="mandal2020dual"><a href="#ref-mandal2020dual" role="doc-biblioref">[9]</a></span>. This coupling provides a robust link to crop structure and its temporal evolution:</p>
<ul>
<li>Bare or smooth surfaces (Bragg-like) exhibit a dominant scattering mechanism with high polarization purity (<span class="math inline">\(m \approx 1\)</span>, <span class="math inline">\(\beta \approx 1\)</span>), yielding low DpRVI values near 0 <span class="citation" data-cites="mandal2020dual"><a href="#ref-mandal2020dual" role="doc-biblioref">[9]</a></span>.</li>
<li>Fully developed vegetation canopies behave as partially depolarizing, random media (<span class="math inline">\(m \approx 0\)</span>, <span class="math inline">\(\beta \approx 0.5\)</span>), producing high DpRVI values near 1 <span class="citation" data-cites="mandal2020dual"><a href="#ref-mandal2020dual" role="doc-biblioref">[9]</a></span>.</li>
<li>Through the growing season, <span class="math inline">\(m\)</span> and <span class="math inline">\(\beta\)</span> show differential sensitivity: both tend to decrease from early to advanced vegetative stages, and their divergence at later stages enhances the index’s ability to track phenology across crops <span class="citation" data-cites="mandal2020dual"><a href="#ref-mandal2020dual" role="doc-biblioref">[9]</a></span>.</li>
<li>DpRVI is bounded between 0 and 1 by construction and is invariant to roll and polarization basis rotation, facilitating inter-date comparability and interpretation across acquisition geometries <span class="citation" data-cites="mandal2020dual mandal2021radar"><a href="#ref-mandal2020dual" role="doc-biblioref">[9]</a>, <a href="#ref-mandal2021radar" role="doc-biblioref">[10]</a></span>.</li>
</ul>
<p>Operationally, increasing DpRVI indicates canopy development and structural complexity, whereas persistently low DpRVI is consistent with bare soil or very early growth.</p>
<p>Let <span class="math inline">\(\mathbf{k} = [S_{VV}, S_{VH}]^{\mathrm{T}}\)</span> denote the dual-pol scattering vector. The covariance <span class="math inline">\(\mathbf{C2} = \langle \mathbf{k}\,\mathbf{k}^{\dagger} \rangle\)</span> is estimated after spatial averaging (multilooking and refined Lee filtering), which reduces speckle and stabilizes the computation of <span class="math inline">\(m\)</span> and the eigenvalues used in <span class="math inline">\(\beta = \lambda_1/\text{Span}\)</span> <span class="citation" data-cites="mandal2019sentinel mandal2020dual"><a href="#ref-mandal2020dual" role="doc-biblioref">[9]</a>, <a href="#ref-mandal2019sentinel" role="doc-biblioref">[11]</a></span>. This second-order characterization is what enables DpRVI to respond consistently to structural changes in the canopy.</p>
<p>ENL (equivalent number of looks) quantifies speckle reduction achieved by spatial averaging; in homogeneous areas it can be estimated as the squared mean‑to‑standard‑deviation ratio of intensity, with larger ENL indicating lower speckle and more stable covariance estimates. Window size therefore controls the trade‑off between speckle suppression and spatial detail. Following <span class="citation" data-cites="mandal2019sentinel"><a href="#ref-mandal2019sentinel" role="doc-biblioref">[11]</a></span>, a <span class="math inline">\(5\times5\)</span> refined Lee filter yields sufficient ENL to robustly estimate <span class="math inline">\(C_{11}\)</span>, <span class="math inline">\(C_{22}\)</span>, <span class="math inline">\(\Re(C_{12})\)</span>, and <span class="math inline">\(\Im(C_{12})\)</span> while preserving field boundaries. In mosaics with smaller, heterogeneous rice parcels, a <span class="math inline">\(3\times3\)</span> window may better preserve edges, whereas <span class="math inline">\(7\times7\)</span> increases smoothing; here a <span class="math inline">\(5\times5\)</span> window is adopted as a balanced choice for Casanare.</p>
<p>DpRVI exhibits a clear monotonic increase during vegetative development and aligns with annotated phenological transitions in cereal crops <span class="citation" data-cites="mandal2020dual"><a href="#ref-mandal2020dual" role="doc-biblioref">[9]</a></span>. Compared with simple backscatter ratios (<span class="math inline">\(\sigma^\circ_{VH}/\sigma^\circ_{VV}\)</span>) and Radar Vegetation Index (RVI), DpRVI provides a more stable and interpretable temporal trajectory from dual-pol data <span class="citation" data-cites="mandal2020dual"><a href="#ref-mandal2020dual" role="doc-biblioref">[9]</a></span>. Reported correlations with canopy descriptors such as Plant Area Index (PAI), vegetation water content (VWC), and dry biomass support its sensitivity to structural changes <span class="citation" data-cites="mandal2020dual mandal2021radar"><a href="#ref-mandal2020dual" role="doc-biblioref">[9]</a>, <a href="#ref-mandal2021radar" role="doc-biblioref">[10]</a></span>. Finally, terrain correction was applied using UTM Zone 18N. All outputs were standardized to 14×14 m resolution and clipped to each study area. The final product was a multitemporal DpRVI database.</p>
</section><section id="rice-crop-phenology" class="level2" data-number="23.3"><h2 data-number="23.3" class="anchored" data-anchor-id="rice-crop-phenology">
<span class="header-section-number">23.3</span> Rice crop phenology</h2>
<p>Rice phenology refers to the sequence of growth and development stages that the plant undergoes from sowing to harvest. Understanding these stages is essential for managing agronomic practices such as irrigation, fertilization, and harvesting. <a href="#tbl-phenology">Table&nbsp;<span>23.1</span></a> presents the principal phenological stages of rice as defined by the BBCH scale <span class="citation" data-cites="meier1997growth"><a href="#ref-meier1997growth" role="doc-biblioref">[12]</a></span>:</p>
<div id="tbl-phenology" class="anchored">
<table class="table">
<caption>Table&nbsp;23.1: Phenological growth stages of rice</caption>
<colgroup>
<col style="width: 26%">
<col style="width: 73%">
</colgroup>
<thead><tr class="header">
<th>Principal Stage</th>
<th>Description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Germination</td>
<td>Dry seed; seed imbibition begins and completes; radicle and coleoptile emerge; imperfect leaf appears</td>
</tr>
<tr class="even">
<td>Leaf development</td>
<td>Unrolling of the imperfect leaf; unfolding of successive true leaves</td>
</tr>
<tr class="odd">
<td>Tillering</td>
<td>First tiller detectable; number of tillers increases up to maximum</td>
</tr>
<tr class="even">
<td>Stem elongation</td>
<td>Panicle initiation; internode elongation; flag leaf development</td>
</tr>
<tr class="odd">
<td>Booting</td>
<td>Stem thickening; flag leaf sheath elongates and opens</td>
</tr>
<tr class="even">
<td>Inflorescence emergence</td>
<td>Panicle gradually emerges from the sheath until fully visible</td>
</tr>
<tr class="odd">
<td>Flowering (Anthesis)</td>
<td>Anthers become visible; flowering progresses and completes</td>
</tr>
<tr class="even">
<td>Fruit development</td>
<td>Grains develop from watery ripe to late milk stage</td>
</tr>
<tr class="odd">
<td>Ripening</td>
<td>Grains progress from early dough to fully ripe and hard</td>
</tr>
<tr class="even">
<td>Senescence</td>
<td>Grains overripe; plant dries and collapses</td>
</tr>
</tbody>
</table>
</div>
<section id="dprvi-across-rice-stages" class="level3" data-number="23.3.1"><h3 data-number="23.3.1" class="anchored" data-anchor-id="dprvi-across-rice-stages">
<span class="header-section-number">23.3.1</span> DpRVI across rice stages</h3>
<p>By analogy with cereals reported in <span class="citation" data-cites="mandal2020dual"><a href="#ref-mandal2020dual" role="doc-biblioref">[9]</a></span>, DpRVI is expected to rise from land preparation and early leaf development (low structural complexity) through tillering and stem elongation, reflecting increasing canopy volume scattering. Around booting to heading, DpRVI typically remains high as the canopy reaches maximum structural complexity, while late‑season senescence may slightly reduce polarization purity and alter scattering balance. This qualitative behavior guides stage interpretation but should be validated with local field observations.</p>
</section></section><section id="workflow" class="level2" data-number="23.4"><h2 data-number="23.4" class="anchored" data-anchor-id="workflow">
<span class="header-section-number">23.4</span> Workflow</h2>
<section id="data-cube-creation" class="level3" data-number="23.4.1"><h3 data-number="23.4.1" class="anchored" data-anchor-id="data-cube-creation">
<span class="header-section-number">23.4.1</span> Data cube creation</h3>
<p>For this work, Sentinel-1 SLC images covering the municipality of Nunchía (Casanare, Colombia)—where rainfed rice is predominant—were used (see <a href="#fig-dprvi-cube">Figure&nbsp;<span>23.2</span></a>). The Dual‑polarimetric Radar Vegetation Index (DpRVI) was computed from these images.</p>
<p>In line with sits, analyses rely on regular Earth observation data cubes that ensure consistent dimensionality for machine learning: seamless spatial coverage, regular temporal cadence, and no gaps. When ARD collections are irregular in time or space, they must be converted to regular cubes prior to classification; national implementations such as Brazil Data Cube provide regular cubes by default <span class="citation" data-cites="Simoes2021 Ferreira2020 data4030092 SITSBOOK"><a href="#ref-Simoes2021" role="doc-biblioref">[13]</a>–<a href="#ref-SITSBOOK" role="doc-biblioref">[16]</a></span>. Unlike single‑tile cube definitions, sits supports cubes spanning multiple tiles, removing tiling restrictions during analysis <span class="citation" data-cites="data4030092 SITSBOOK"><a href="#ref-data4030092" role="doc-biblioref">[15]</a>, <a href="#ref-SITSBOOK" role="doc-biblioref">[16]</a></span>.</p>
<p>Note: Although DpRVI is derived from Sentinel‑1 SLC data via the <span class="math inline">\(\mathbf{C2}\)</span> workflow described above <span class="citation" data-cites="mandal2019sentinel mandal2020dual"><a href="#ref-mandal2020dual" role="doc-biblioref">[9]</a>, <a href="#ref-mandal2019sentinel" role="doc-biblioref">[11]</a></span>, in practice precomputed DpRVI rasters are loaded into a <code>sits</code> cube for analysis. This separation keeps heavy polarimetric processing in SNAP and downstream time‑series analytics in R.</p>
<p>A local data cube was created using the <code>sits</code> package in R <span class="citation" data-cites="Simoes2021"><a href="#ref-Simoes2021" role="doc-biblioref">[13]</a></span> to enable time-series analysis and support crop monitoring and classification workflows. The <code>sits</code> package follows a time-first, space-later paradigm: it classifies per-pixel time series to produce probability cubes, and then applies spatial smoothing to improve map consistency. It also provides tools for training-sample quality control and class noise reduction <span class="citation" data-cites="Santos2021a"><a href="#ref-Santos2021a" role="doc-biblioref">[17]</a></span>, and interoperates with on-demand EO data cube processing backends such as gdalcubes <span class="citation" data-cites="data4030092"><a href="#ref-data4030092" role="doc-biblioref">[15]</a></span> and national implementations <span class="citation" data-cites="Ferreira2020"><a href="#ref-Ferreira2020" role="doc-biblioref">[14]</a></span>. The implementation follows these steps:</p>
<p>To ensure reproducibility in the time‑first workflow, training samples should provide location, temporal range, and label per observation, and their timeline should match the cube’s number of intervals and date range <span class="citation" data-cites="SITSBOOK Simoes2021"><a href="#ref-Simoes2021" role="doc-biblioref">[13]</a>, <a href="#ref-SITSBOOK" role="doc-biblioref">[16]</a></span>.</p>
<ol type="1">
<li>First, load the required libraries for data manipulation and visualization:</li>
</ol>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Load required packages for data cube creation and analysis</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/e-sensing/sits/">sits</a></span><span class="op">)</span>      <span class="co"># Satellite time series analysis</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://r-spatial.github.io/sf/">sf</a></span><span class="op">)</span>        <span class="co"># Spatial data handling</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span>   <span class="co"># Data visualization</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/hadley/reshape">reshape2</a></span><span class="op">)</span>  <span class="co"># Data reshaping</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span>     <span class="co"># Data manipulation</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyr.tidyverse.org">tidyr</a></span><span class="op">)</span>     <span class="co"># Data tidying</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tibble.tidyverse.org/">tibble</a></span><span class="op">)</span>    <span class="co"># Enhanced data frames</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://yihui.org/knitr/">knitr</a></span><span class="op">)</span>     <span class="co"># Dynamic report generation</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/topepo/caret/">caret</a></span><span class="op">)</span>     <span class="co"># Validation metrics</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li>Next, create the DpRVI data cube:</li>
</ol>
<div class="cell" data-hash="cy_colombia_cache/html/create-dprvi-cube_d5983295b2d0f46a333ca828a5034439">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Define the directory containing DpRVI images</span></span>
<span><span class="va">dir_imgs</span> <span class="op">&lt;-</span> <span class="st">"data/cy_colombia/dprvi/dprvi_reg/"</span></span>
<span></span>
<span><span class="co"># Create the data cube with sits</span></span>
<span><span class="va">cube_dprvi</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://e-sensing.github.io/sits/reference/sits_cube.html">sits_cube</a></span><span class="op">(</span></span>
<span>  source <span class="op">=</span> <span class="st">"MPC"</span>,</span>
<span>  collection <span class="op">=</span> <span class="st">"SENTINEL-1-GRD"</span>,</span>
<span>  bands <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"DPRVI"</span><span class="op">)</span>,</span>
<span>  data_dir <span class="op">=</span> <span class="va">dir_imgs</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This data cube contains DpRVI images with a temporal resolution of 12 days and is organized chronologically from January 04 to July 03, 2025. The timeline of the data cube can be visualized as follows:</p>
<div class="cell" data-caption="Timeline of DpRVI data cube acquisitions" data-hash="cy_colombia_cache/html/caption-dprvi-timeline_f95264fce72eb13a529325c77dadd64b">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Visualize the temporal distribution of images</span></span>
<span><span class="fu"><a href="https://e-sensing.github.io/sits/reference/sits_timeline.html">sits_timeline</a></span><span class="op">(</span><span class="va">cube_dprvi</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-caption="Timeline of DpRVI data cube acquisitions">
<div class="cell-output cell-output-stdout">
<pre><code> [1] "2025-01-04" "2025-01-16" "2025-01-28" "2025-02-09" "2025-02-21"
 [6] "2025-03-05" "2025-03-17" "2025-03-29" "2025-04-10" "2025-04-22"
[11] "2025-05-04" "2025-05-16" "2025-05-28" "2025-06-09" "2025-06-21"
[16] "2025-07-03"</code></pre>
</div>
</div>
<p><a href="#fig-dprvi-cube">Figure&nbsp;<span>23.2</span></a> shows an RGB composite of the last three acquisitions, illustrating temporal variation in DpRVI across rice areas. This view helps identify growth patterns and spatial heterogeneity in vegetation conditions.</p>
<div class="cell" data-layout-align="center" data-hash="cy_colombia_cache/html/unnamed-chunk-2_47440d72b8d044512bed799909da7f7a">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Plot RGB composite visualization of DpRVI data cube</span></span>
<span><span class="co"># using the three most recent acquisition dates</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">cube_dprvi</span>, band <span class="op">=</span> <span class="st">"DPRVI"</span>, palette <span class="op">=</span> <span class="st">"Greys"</span>, scale <span class="op">=</span> <span class="fl">1.0</span>,</span>
<span>     dates <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"2025-07-03"</span>, <span class="st">"2025-06-21"</span>, <span class="st">"2025-06-09"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center" data-hash="cy_colombia_cache/html/fig-dprvi-cube_f7a0c463c5de4a44753ec1e980b7e7e3">
<div class="cell-output-display">
<div id="fig-dprvi-cube" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/cy_colombia/fig-dprvi-cube.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;23.2: DpRVI cube RGB visualization using three acquisition dates</figcaption></figure>
</div>
</div>
</div>
</section><section id="field-data-collection" class="level3" data-number="23.4.2"><h3 data-number="23.4.2" class="anchored" data-anchor-id="field-data-collection">
<span class="header-section-number">23.4.2</span> Field data collection</h3>
<p>Field data were collected in the municipality of Nunchía (Casanare, Colombia). The campaign ran from May to June 2025, coinciding with peak crop development. In this region:</p>
<ul>
<li>Sowing period: March to May</li>
<li>Land preparation: Precedes sowing</li>
<li>Average crop cycle: Approximately 120 days</li>
</ul>
<p>A stratified random sampling approach was implemented to ensure: 1. Representative coverage of different rice phenological stages 2. Adequate sampling of dominant land cover types</p>
<p>Phenological stages were classified using the standardized BBCH scale <span class="citation" data-cites="meier1997growth"><a href="#ref-meier1997growth" role="doc-biblioref">[12]</a></span> (see <a href="#tbl-phenology">Table&nbsp;<span>23.1</span></a>).</p>
<p>Data were collected using QField mobile application, which provided Standardized data entry interface, precise georeferencing capabilities and field validation tools. The collected data were stored in a GeoPackage (GPKG) format, containing spatial information, associated attributes for each sampling point, and generated polygons representing observation areas. <a href="#fig-field-data">Figure&nbsp;<span>23.3</span></a> presents the spatial distribution of the collected field data. The visualization includes training and validation polygons, color-coded by phenological class or land cover category.</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Define path to field data</span></span>
<span><span class="va">field_data</span> <span class="op">&lt;-</span> <span class="st">"data/cy_colombia/samples/data.gpkg"</span></span>
<span></span>
<span><span class="co"># Load the field data</span></span>
<span><span class="va">data_train</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_read.html">st_read</a></span><span class="op">(</span><span class="va">field_data</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Create field data visualization</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">data_train</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>fill <span class="op">=</span> <span class="va">class</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Field Data Distribution"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span></span>
<span>    legend.position <span class="op">=</span> <span class="st">"right"</span>,</span>
<span>    plot.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>hjust <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_brewer.html">scale_fill_brewer</a></span><span class="op">(</span>palette <span class="op">=</span> <span class="st">"Set1"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center" data-hash="cy_colombia_cache/html/fig-field-data_49cdd0e626da211e4e177bd586f0200a">
<div class="cell-output-display">
<div id="fig-field-data" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/cy_colombia/fig-field-data.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;23.3: Spatial distribution of field data samples colored by class</figcaption></figure>
</div>
</div>
</div>
</section><section id="extracting-dprvi-values-from-the-data-cube" class="level3" data-number="23.4.3"><h3 data-number="23.4.3" class="anchored" data-anchor-id="extracting-dprvi-values-from-the-data-cube">
<span class="header-section-number">23.4.3</span> Extracting DpRVI values from the data cube</h3>
<p>To extract DpRVI values from the data cube for the field data, the <code>sits_get_data</code> function from the <code>sits</code> package can be used. This function samples the DpRVI values at the locations specified in the field data. The following code snippet demonstrates how to perform this extraction:</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Extract DpRVI values from the data cube for field data samples</span></span>
<span><span class="co"># This function samples the DpRVI values at locations specified in field data</span></span>
<span><span class="co"># Parameters:</span></span>
<span><span class="co"># - cube: DpRVI data cube containing temporal imagery</span></span>
<span><span class="co"># - samples: field data with spatial polygons and class labels</span></span>
<span><span class="co"># - bands: spectral bands to extract (DPRVI in this case)</span></span>
<span><span class="co"># - multicores: number of CPU cores for parallel processing</span></span>
<span><span class="co"># - n_sam_pol: number of samples per polygon for training</span></span>
<span><span class="co"># - label_attr: attribute containing class labels</span></span>
<span></span>
<span><span class="va">training</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://e-sensing.github.io/sits/reference/sits_get_data.html">sits_get_data</a></span><span class="op">(</span></span>
<span>  cube <span class="op">=</span> <span class="va">cube_dprvi</span>,</span>
<span>  samples <span class="op">=</span> <span class="va">data_train</span>,</span>
<span>  bands <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"DPRVI"</span><span class="op">)</span>,</span>
<span>  multicores <span class="op">=</span> <span class="fl">4</span>,</span>
<span>  n_sam_pol <span class="op">=</span> <span class="fl">100</span>,</span>
<span>  label_attr <span class="op">=</span> <span class="st">"class"</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><a href="#fig-dprvi-multitemporal">Figure&nbsp;<span>23.4</span></a> presents temporal DpRVI signatures revealing three biophysically distinct behavioral categories essential for automated discrimination. Perennial vegetation covers exhibit stable, high-value profiles: forest maintains consistent values (~0.60 ± 0.02) with minimal seasonal variation, reflecting persistent volume scattering from mature canopy structure where randomly distributed scattering elements generate high depolarization. The slight decline toward July (~0.49) indicates seasonal changes in foliar moisture content, affecting dielectric properties and consequently the degree of polarization of radar waves.</p>
<p>In contrast, grasslands show slightly higher values (~0.63 ± 0.03) with gradual increase through the observation period. This behavior results from a less complex canopy structure but with sufficient aerial biomass to generate significant depolarization. The temporal increase observed reflects vegetative growth during the rainy season, increasing the anisotropy of the scattering medium and enhancing volume scattering contributions.</p>
<p>Phenological interpretation uses the fact that rice stages exhibit characteristic dynamic patterns aligned with crop development cycles. All stages initiate with elevated DpRVI values (~0.50–0.60) before March, attributed to pre-existing vegetation or crop residues, followed by sharp declines to minimum values (~0.30–0.40) between April and May, corresponding to soil preparation and early sowing phases when surface scattering dominates over bare soils. The high degree of polarization during this phase reflects the absence of depolarizing elements. Subsequent DpRVI recovery (May–July) documents the transition toward volume scattering as rice canopy architecture develops, with each phenological stage showing distinct recovery trajectories that enable machine learning discrimination.</p>
<p>These temporally-offset recovery patterns provide the biophysical foundation for machine learning discrimination: <em>Germination</em> shows modest increase (Δ=+0.09 from April–May minimum), reflecting initial emergence with limited structural complexity. <em>Leaf development</em> exhibits steeper recovery (Δ=+0.11), consistent with rapid leaf area expansion that increases volume scattering components. <em>Stem elongation</em> demonstrates pronounced increases (Δ=+0.15–0.17) reflecting advanced canopy development where multiple scattering layers generate complex depolarization patterns.</p>
<p><em>Tillering</em> exhibits the most complex polarimetric behavior with similar recovery magnitude but intermediate structural characteristics that overlap with adjacent phenological stages, explaining subsequent classification challenges. The emergence of secondary stems creates intermediate scattering complexity between single-stem (leaf development) and mature multi-layered canopies (stem elongation), generating overlapping degree of polarization values that complicate automated discrimination.</p>
<div class="cell" data-layout-align="center" data-hash="cy_colombia_cache/html/unnamed-chunk-4_dcb3e3ae56bae21216909e982b4af5b1">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Plot the temporal patterns of DpRVI values for each class</span></span>
<span><span class="co"># This creates a multi-panel time series visualization showing</span></span>
<span><span class="co"># how DpRVI values change over time for different land cover types</span></span>
<span><span class="co"># and rice phenological stages</span></span>
<span></span>
<span><span class="va">training</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://e-sensing.github.io/sits/reference/sits_patterns.html">sits_patterns</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center" data-hash="cy_colombia_cache/html/fig-dprvi-multitemporal_81db21abb07c1885c4a39d454ddbd424">
<div class="cell-output-display">
<div id="fig-dprvi-multitemporal" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/cy_colombia/fig-dprvi-multitemporal.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;23.4: Spatial distribution of field data samples colored by class</figcaption></figure>
</div>
</div>
</div>
</section><section id="data-quality-control" class="level3" data-number="23.4.4"><h3 data-number="23.4.4" class="anchored" data-anchor-id="data-quality-control">
<span class="header-section-number">23.4.4</span> Data quality control</h3>
<p>To evaluate the quality of the training samples and detect possible labeling errors in the time series, a methodology combining Self Organizing Maps (SOM) and Bayesian Inference was applied. SOM is an unsupervised neural network technique that groups time series of satellite images according to their similarity, projecting high dimensional multitemporal data onto a two dimensional grid, where each neuron represents a cluster of similar temporal profiles and preserves topological relationships between inputs <span class="citation" data-cites="Santos2021a"><a href="#ref-Santos2021a" role="doc-biblioref">[17]</a></span>.</p>
<p>Each training sample is assigned to a specific neuron based on its temporal similarity; consistent samples from the same class tend to cluster in neighboring regions of the SOM grid, while noisy samples often appear isolated or in unexpected areas, facilitating the visual detection of anomalies. After constructing the SOM, Bayesian Inference is used within and between clusters to assess the consistency and coherence of the samples, quantifying intra and inter cluster similarity, which allows for the identification of outliers or misclassified samples <span class="citation" data-cites="Santos2021a"><a href="#ref-Santos2021a" role="doc-biblioref">[17]</a></span>. This combined approach is efficient and interpretable for validating the quality of the training data and helps reduce the risk of classification errors in subsequent modeling stages.</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Clustering time series using SOM (Self-Organizing Maps)</span></span>
<span><span class="co"># Parameters:</span></span>
<span><span class="co"># - training: time series data for different classes</span></span>
<span><span class="co"># - alpha: learning rate for SOM training (1.0 = full learning rate)</span></span>
<span><span class="co"># - distance: distance metric used for clustering ("dtw" = Dynamic Time Warping)</span></span>
<span><span class="co"># - rlen: number of training iterations (20 iterations)</span></span>
<span></span>
<span><span class="va">som_cluster</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://e-sensing.github.io/sits/reference/sits_som_map.html">sits_som_map</a></span><span class="op">(</span><span class="va">training</span>,</span>
<span>  alpha <span class="op">=</span> <span class="fl">1.0</span>,</span>
<span>  distance <span class="op">=</span> <span class="st">"dtw"</span>,</span>
<span>  rlen <span class="op">=</span> <span class="fl">20</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><a href="#fig-som-plot">Figure&nbsp;<span>23.5</span></a> shows that natural land covers, such as forest and pasture, tend to cluster in specific areas of the SOM grid, reflecting their more homogeneous temporal profiles. In contrast, the phenological stages of rice cultivation are more dispersed throughout the map, due to the rapid and dynamic changes in rice growth. However, some early phenological stages including germination, leaf development, tillering, and stem elongation often appear in adjacent regions of the SOM grid, indicating that growth stages which are temporally close may also share similar temporal growth patterns.</p>
<div class="cell" data-layout-align="center" data-hash="cy_colombia_cache/html/unnamed-chunk-5_382e03c3fdc10dfe89d6d4a9a139c122">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Plot the SOM clusters</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">som_cluster</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center" data-hash="cy_colombia_cache/html/fig-som-plot_98c1e69e6477905ca8f4f142f4f859a5">
<div class="cell-output-display">
<div id="fig-som-plot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/cy_colombia/fig-som-plot.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;23.5: Spatial distribution of field data samples colored by class</figcaption></figure>
</div>
</div>
</div>
<p><a href="#fig-evaluate-clusters">Figure&nbsp;<span>23.6</span></a> illustrates a stacked bar chart showing the distribution of classes within each cluster generated by the model. Each row represents a class, and the colored bars within each row display how the elements of that class are distributed across the different clusters. The ideal goal is for each bar to exhibit a single predominant color, indicating that a class maps almost exclusively to a single cluster.</p>
<p>The forest class showed the highest purity, with 97% of its samples assigned to a single dominant cluster, and only slight confusion with other classes. Similarly, grass had 91% of its samples correctly grouped, although a 5% overlap with forest was observed and a small fraction was erroneously placed as germination. For the stem elongation class, 80% of the samples were correctly assigned, but 14% of the tillering samples were also located in this cluster.</p>
<p>In the case of germination, 76% of the samples were correctly located, although there was 13% from leaf development and 9% from tillering. The confusion with leaf development is reasonable due to their immediate sequence in the crop cycle and the similarity in their temporal DpRVI behaviors. Leaf development presented 74% correct assignments, with errors mainly associated with the presence of tillering (14%) and germination (7%).</p>
<p>Finally, tillering was the class with the highest level of confusion, with 67% of the samples correctly located. Mixtures were observed with 18% of leaf development and 11% of stem elongation. These confusions are expected given that consecutive phenological stages present similar structural characteristics, which is reflected in similar responses of the DpRVI index due to their radar polarization degree patterns.</p>
<div class="cell" data-layout-align="center" data-hash="cy_colombia_cache/html/unnamed-chunk-6_25b70f583d45693443b9681aeef13d55">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Evaluate the quality and confusion of SOM clusters</span></span>
<span><span class="co"># This function assesses how well the SOM clustering performed by analyzing</span></span>
<span><span class="co"># the distribution of classes within each cluster and identifying potential</span></span>
<span><span class="co"># misclassifications or overlapping patterns between different classes</span></span>
<span><span class="va">evaluate_clusters</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://e-sensing.github.io/sits/reference/sits_som_evaluate_cluster.html">sits_som_evaluate_cluster</a></span><span class="op">(</span><span class="va">som_cluster</span><span class="op">)</span></span>
<span><span class="co"># plot the SOM cluster evaluation</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">evaluate_clusters</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center" data-hash="cy_colombia_cache/html/fig-evaluate-clusters_dc5cf05cf9d26bd5de9f7c09a774621c">
<div class="cell-output-display">
<div id="fig-evaluate-clusters" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/cy_colombia/fig-evaluate-clusters.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;23.6: Confusion of SOM clusters</figcaption></figure>
</div>
</div>
</div>
</section><section id="noisy-sample-detection" class="level3" data-number="23.4.5"><h3 data-number="23.4.5" class="anchored" data-anchor-id="noisy-sample-detection">
<span class="header-section-number">23.4.5</span> Noisy sample detection</h3>
<p>To detect noisy samples within the dataset, a combination of Self-Organizing Maps (SOM) and Bayesian inference techniques was used. Noisy samples are identified using SOM and Bayesian inference techniques. Homogeneous neurons with a high frequency of a single class are considered high quality, while heterogeneous neurons with multiple significant classes likely contain noise <span class="citation" data-cites="Santos2021a"><a href="#ref-Santos2021a" role="doc-biblioref">[17]</a></span>.</p>
<p>Two probabilities are calculated for each sample:</p>
<ol type="1">
<li>
<em>Prior probability:</em> Measures the likelihood that a sample’s label is correct based on frequencies within its neuron.</li>
<li>
<em>Posterior probability:</em> Estimates the likelihood that the label is correct by considering neighboring neurons using Bayesian inference.</li>
</ol>
<p>Samples are categorized into three groups:</p>
<ul>
<li>Noisy (<code>remove</code>): Low prior probability.</li>
<li>Clean (<code>clean</code>): High prior and posterior probabilities.</li>
<li>To analyze (<code>analyze</code>): High prior but low posterior probability, indicating inconsistency with neighbors.</li>
</ul>
<p>It is recommended to remove noisy samples to improve dataset quality, reducing errors in subsequent models. Clean samples are retained, while <code>analyze</code> samples should be manually reviewed.</p>
<p>The <code><a href="https://e-sensing.github.io/sits/reference/sits_som_clean_samples.html">sits_som_clean_samples()</a></code> function uses <code>prior_threshold</code> and <code>posterior_threshold</code> thresholds (both with a default value of 60%). Now, noisy samples are removed to improve the quality of the training dataset. <a href="#tbl-som-cleaned">Table&nbsp;<span>23.2</span></a> presents a summary of the samples by label or class after the cleaning process based on SOM evaluation. Forest and grass are the classes with the highest number of samples. Together, they represent almost half of the dataset (0.21 + 0.21 = 0.42 or 42%). This indicates that they are the most frequent categories in the cleaned dataset.</p>
<p>Germination and leaf development have moderate representation, with proportions ranging between 0.17 and 0.11. Stem elongation is also in this middle range, with a proportion of 0.14. Tillering is the class with the smallest number of samples, representing only 0.09 or 9% of the total. This makes it a minority or imbalanced class compared to the others.</p>
<div class="cell" data-tbl-cap="Summary of cleaned samples by class" data-hash="cy_colombia_cache/html/unnamed-chunk-7_d4c6a15a0e17fb89bf96a5a902501a4c">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Load cleaned samples using SOM evaluation</span></span>
<span><span class="co"># This function retains only 'clean' and 'analyze'</span></span>
<span><span class="co"># samples from the SOM clustering,</span></span>
<span><span class="co"># removing noisy samples to improve training data quality</span></span>
<span><span class="co"># Parameters:</span></span>
<span><span class="co"># - som_map: SOM clustering results from previous analysis</span></span>
<span><span class="co"># - prior_threshold: minimum probability threshold for sample quality (60%)</span></span>
<span><span class="co"># - posterior_threshold: minimum probability</span></span>
<span><span class="co"># threshold considering neighbors (60%)</span></span>
<span><span class="co"># - keep: categories of samples to retain ("clean", "analyze")</span></span>
<span></span>
<span><span class="va">new_samples</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://e-sensing.github.io/sits/reference/sits_som_clean_samples.html">sits_som_clean_samples</a></span><span class="op">(</span>som_map <span class="op">=</span> <span class="va">som_cluster</span>,</span>
<span>  prior_threshold <span class="op">=</span> <span class="fl">0.6</span>,</span>
<span>  posterior_threshold <span class="op">=</span> <span class="fl">0.6</span>,</span>
<span>  keep <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"clean"</span>, <span class="st">"analyze"</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Display summary table of cleaned sample distribution by class</span></span>
<span><span class="co"># Shows count and proportion of samples for each land cover/phenological class</span></span>
<span><span class="co"># after quality control filtering</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">new_samples</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="tbl-som-cleaned" class="anchored">
<table class="table">
<caption>Table&nbsp;23.2: Summary of cleaned samples by class</caption>
<thead><tr class="header">
<th style="text-align: left;">label</th>
<th style="text-align: right;">count</th>
<th style="text-align: right;">prop</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">forest</td>
<td style="text-align: right;">94</td>
<td style="text-align: right;">0.2175926</td>
</tr>
<tr class="even">
<td style="text-align: left;">germination</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">0.1759259</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grass</td>
<td style="text-align: right;">92</td>
<td style="text-align: right;">0.2129630</td>
</tr>
<tr class="even">
<td style="text-align: left;">leaf development</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">0.1157407</td>
</tr>
<tr class="odd">
<td style="text-align: left;">stem elongation</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">0.1851852</td>
</tr>
<tr class="even">
<td style="text-align: left;">tillering</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">0.0925926</td>
</tr>
</tbody>
</table>
</div>
</section><section id="random-forest-classification" class="level3" data-number="23.4.6"><h3 data-number="23.4.6" class="anchored" data-anchor-id="random-forest-classification">
<span class="header-section-number">23.4.6</span> Random Forest classification</h3>
<p>Random Forest (RF) is a powerful machine learning algorithm that is widely used for classification tasks, including remote sensing applications <span class="citation" data-cites="RODRIGUEZGALIANO201293"><a href="#ref-RODRIGUEZGALIANO201293" role="doc-biblioref">[18]</a></span>. It operates by constructing multiple decision trees during training and outputs the mode of the classes (classification) or mean prediction (regression) of the individual trees <span class="citation" data-cites="breiman2001random"><a href="#ref-breiman2001random" role="doc-biblioref">[19]</a></span>. RF is particularly effective in handling high dimensional data and can capture complex relationships between features <span class="citation" data-cites="James2013"><a href="#ref-James2013" role="doc-biblioref">[20]</a></span>.</p>
<p>The Random Forest model was trained using the cleaned samples, which were previously validated through SOM evaluation. The model was configured with 500 trees, a common choice that balances performance and computational efficiency.</p>
<div class="cell" data-layout-align="center" data-hash="cy_colombia_cache/html/unnamed-chunk-8_2be7a60270bdcd35d46f0a4643300e31">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span></span>
<span><span class="co"># Train the Random Forest model with cleaned samples</span></span>
<span><span class="co"># Parameters:</span></span>
<span><span class="co"># - samples: cleaned training samples from SOM evaluation</span></span>
<span><span class="co"># - ml_method: Random Forest algorithm with 500 trees</span></span>
<span><span class="va">probs_cube</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://e-sensing.github.io/sits/reference/sits_train.html">sits_train</a></span><span class="op">(</span>samples <span class="op">=</span> <span class="va">new_samples</span>,</span>
<span>                         ml_method <span class="op">=</span> <span class="fu"><a href="https://e-sensing.github.io/sits/reference/sits_rfor.html">sits_rfor</a></span><span class="op">(</span>num_trees <span class="op">=</span> <span class="fl">500</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co"># Plot the feature importance from the trained Random Forest model</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">probs_cube</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center" data-hash="cy_colombia_cache/html/fig-importance-cleaned_0217c78ea82ff7e234bccec81c184c72">
<div class="cell-output-display">
<div id="fig-importance-cleaned" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/cy_colombia/fig-importance-cleaned.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;23.7: Random Forest importance of discriminatory variables</figcaption></figure>
</div>
</div>
</div>
<p>Variable importance analysis reveals a temporally coherent hierarchy aligned with critical agricultural management periods (<a href="#fig-importance-cleaned">Figure&nbsp;<span>23.7</span></a>). The most influential variables cluster around two key polarimetric discrimination windows that maximize separability between land cover classes based on distinct scattering mechanisms.</p>
<p>Early-season critical period (March): DPRVI8 (March 29, depth=2.42) and DPRVI6 (March 5, depth=2.47) represent the optimal polarimetric discrimination window when land preparation activities create maximum contrast between prepared agricultural fields and natural vegetation covers. During this period, recently disturbed soils exhibit low DpRVI values (~0.3–0.4) due to surface scattering dominance, while established vegetation maintains high DpRVI values (~0.6) from volume scattering, generating clear polarimetric separability essential for subsequent classification accuracy.</p>
<p>Mid-season development window (May–June): Secondary-importance variables DPRVI15 (June 21), DPRVI13 (May 28), and DPRVI12 (May 16) all cluster at depth ~2.64–2.66, capturing the rapid structural transitions during active crop development. These dates correspond to maximum phenological differentiation when tillering, stem elongation, and leaf development stages exhibit distinct canopy architecture patterns detectable through polarimetric radar signatures and varying degrees of polarization.</p>
<p>Temporal specificity validation: The concentration of variable importance during agriculturally meaningful periods (rather than arbitrary calendar dates) provides strong evidence that the Random Forest model identifies genuine biophysical patterns rather than spurious correlations.</p>
<p>January–February low relevance: Early season variables (DPRVI5–7, depth &gt;3.0) show reduced importance because during the dry season, all vegetation covers exhibit polarimetrically convergent values (~0.5–0.6) due to: (i) reduced water content homogenizing dielectric properties, (ii) minimal structural contrast between classes, and (iii) convergence of degree of polarization across land covers, limiting discriminative power.</p>
<p>This temporal consistency supports model transferability across different growing seasons and validates that DpRVI captures physical polarimetric processes rather than seasonal artifacts.</p>
</section></section><section id="results" class="level2" data-number="23.5"><h2 data-number="23.5" class="anchored" data-anchor-id="results">
<span class="header-section-number">23.5</span> Results</h2>
<section id="model-performance-evaluation" class="level3" data-number="23.5.1"><h3 data-number="23.5.1" class="anchored" data-anchor-id="model-performance-evaluation">
<span class="header-section-number">23.5.1</span> Model performance evaluation</h3>
<p>The performance of the Random Forest model was evaluated using k‑fold cross‑validation, a robust technique that helps assess the model’s generalization ability <span class="citation" data-cites="raschka2019python"><a href="#ref-raschka2019python" role="doc-biblioref">[21]</a></span>. In this case, 10 folds were used: the dataset was split into 10 equal parts, the model was trained on 9 parts and validated on the remaining part, repeating this process 10 times so that each part served as a validation set once.</p>
<p>The results of the k-fold cross-validation are stored in a list, where each element corresponds to the accuracy of the model on each fold. The accuracy is calculated as the proportion of correctly classified samples out of the total number of samples in the validation.</p>
<div class="cell" data-caption="K-fold cross-validation results">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Perform k-fold cross-validation to assess model performance</span></span>
<span><span class="co"># This validation technique splits the dataset into k folds (10 in this case)</span></span>
<span><span class="co"># and trains the model k times, using k-1 folds</span></span>
<span><span class="co"># for training and 1 fold for validation</span></span>
<span><span class="co"># The process is repeated k times, with each fold serving as validation set once</span></span>
<span><span class="co"># create a list to store the results</span></span>
<span><span class="va">results</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">acc_rfor</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://e-sensing.github.io/sits/reference/sits_kfold_validate.html">sits_kfold_validate</a></span><span class="op">(</span><span class="va">new_samples</span>,</span>
<span>  folds <span class="op">=</span> <span class="fl">10</span>,</span>
<span>  multicores <span class="op">=</span> <span class="fl">1</span>,</span>
<span>  ml_method <span class="op">=</span> <span class="fu"><a href="https://e-sensing.github.io/sits/reference/sits_rfor.html">sits_rfor</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span><span class="va">acc_rfor</span><span class="op">$</span><span class="va">name</span> <span class="op">&lt;-</span> <span class="st">"Random Forest"</span></span>
<span><span class="va">results</span><span class="op">[[</span><span class="st">"Random Forest"</span><span class="op">]</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="va">acc_rfor</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Following best practices for satellite image time series classification, the model is evaluated using confusion‑matrix based metrics <span class="citation" data-cites="Simoes2021"><a href="#ref-Simoes2021" role="doc-biblioref">[13]</a></span>. The primary indicators are:</p>
<ul>
<li>Overall Accuracy (OA): proportion of correctly classified samples across all classes.</li>
<li>Producer’s Accuracy (Recall/Sensitivity) and User’s Accuracy (Precision): per-class omission and commission perspectives, respectively <span class="citation" data-cites="SOKOLOVA2009427"><a href="#ref-SOKOLOVA2009427" role="doc-biblioref">[22]</a></span>.</li>
<li>F1-score: harmonic mean of precision and recall, summarizing class-wise performance under imbalanced conditions <span class="citation" data-cites="SOKOLOVA2009427"><a href="#ref-SOKOLOVA2009427" role="doc-biblioref">[22]</a></span>.</li>
<li>Cohen’s κ: agreement beyond chance, reported as a complementary global index.</li>
</ul>
<p>For reporting, OA and κ are provided at map level, with macro‑averaged Precision, Recall, and F1 across classes, alongside per‑class metrics to capture phenology‑dependent variability in separability. Probability outputs are primarily used for smoothing and labeling.</p>
</section><section id="validation-protocol" class="level3" data-number="23.5.2"><h3 data-number="23.5.2" class="anchored" data-anchor-id="validation-protocol">
<span class="header-section-number">23.5.2</span> Validation Protocol</h3>
<p>To ensure reliable generalization and avoid information leakage, a field‑level, stratified evaluation protocol is adopted:</p>
<ul>
<li>Grouped data split: samples are grouped by agricultural parcel (field ID) and split into train/test partitions so that pixels from the same field do not appear in both sets, mitigating spatial autocorrelation leakage <span class="citation" data-cites="Simoes2021"><a href="#ref-Simoes2021" role="doc-biblioref">[13]</a></span>. An 80/20 split is used, stratified by class to preserve phenological-stage proportions.</li>
<li>Model selection: within the training partition, hyperparameters are chosen via 10-fold stratified cross-validation. This procedure balances bias–variance trade-offs and provides robust estimates for tuning <span class="citation" data-cites="James2013"><a href="#ref-James2013" role="doc-biblioref">[20]</a></span>.</li>
<li>Final assessment: the model is refit on the full training partition with selected hyperparameters and evaluated on the independent test partition, reporting OA, κ, and macro-averaged Precision/Recall/F1, together with class-wise metrics <span class="citation" data-cites="RODRIGUEZGALIANO201293"><a href="#ref-RODRIGUEZGALIANO201293" role="doc-biblioref">[18]</a></span>.</li>
<li>Probability-based diagnostics: not used in this work; probability outputs were employed to produce probability cubes and for Bayesian smoothing prior to labeling <span class="citation" data-cites="Simoes2021 Santos2021a"><a href="#ref-Simoes2021" role="doc-biblioref">[13]</a>, <a href="#ref-Santos2021a" role="doc-biblioref">[17]</a></span>.</li>
</ul>
<p>The following metrics are reported using macro-averaging across classes, alongside per-class values where relevant <span class="citation" data-cites="SOKOLOVA2009427"><a href="#ref-SOKOLOVA2009427" role="doc-biblioref">[22]</a></span>:</p>
<table class="table">
<colgroup>
<col style="width: 13%">
<col style="width: 60%">
<col style="width: 25%">
</colgroup>
<thead><tr class="header">
<th>Metric</th>
<th>Definition</th>
<th>Formula (per class c)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Precision</td>
<td>Correct positives among predicted positives</td>
<td><span class="math inline">\(\mathrm{Precision}_c = \dfrac{TP_c}{TP_c + FP_c}\)</span></td>
</tr>
<tr class="even">
<td>Recall</td>
<td>Correct positives among actual positives</td>
<td><span class="math inline">\(\mathrm{Recall}_c = \dfrac{TP_c}{TP_c + FN_c}\)</span></td>
</tr>
<tr class="odd">
<td>F1-score</td>
<td>Harmonic mean of Precision and Recall</td>
<td><span class="math inline">\(\mathrm{F1}_c = 2\,\cdot\, \dfrac{\mathrm{Precision}_c\,\mathrm{Recall}_c}{\mathrm{Precision}_c + \mathrm{Recall}_c}\)</span></td>
</tr>
<tr class="even">
<td>OA</td>
<td>Overall proportion of correctly classified samples</td>
<td><span class="math inline">\(\mathrm{OA} = \dfrac{\sum_c TP_c}{N}\)</span></td>
</tr>
<tr class="odd">
<td>Cohen’s <span class="math inline">\(\kappa\)</span>
</td>
<td>Agreement beyond chance</td>
<td>
<span class="math inline">\(\kappa = \dfrac{p_o - p_e}{1 - p_e}\)</span> where <span class="math inline">\(p_o = \mathrm{OA}\)</span> and <span class="math inline">\(p_e\)</span> is expected agreement by chance</td>
</tr>
</tbody>
</table>
<p>Where TP, FP, FN are computed from the confusion matrix, N is the total number of validation samples. Macro-averaging computes the unweighted mean across classes to balance class imbalance <span class="citation" data-cites="SOKOLOVA2009427"><a href="#ref-SOKOLOVA2009427" role="doc-biblioref">[22]</a></span>.</p>
<p>Performance is summarized with a confusion matrix, cross‑tabulating predictions and references to quantify errors and biases <span class="citation" data-cites="SOKOLOVA2009427"><a href="#ref-SOKOLOVA2009427" role="doc-biblioref">[22]</a></span>.</p>
<div class="cell" data-hash="cy_colombia_cache/html/unnamed-chunk-9_fbbfb6bf13e699d7d0f1da7bb2d5b137">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Confusion matrix visualization function</span></span>
<span><span class="co"># Generates visualization from validation results</span></span>
<span><span class="va">create_confusion_matrix_plot</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">result</span>, <span class="va">model_name</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="co"># Extract confusion matrix</span></span>
<span>  <span class="va">cm_mat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">as.matrix</a></span><span class="op">(</span><span class="va">result</span><span class="op">$</span><span class="va">table</span><span class="op">)</span></span>
<span></span>
<span>  <span class="co"># Transform to data frame for ggplot</span></span>
<span>  <span class="va">cm_long</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html">as.table</a></span><span class="op">(</span><span class="va">cm_mat</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span>  <span class="co"># Order Prediction factor levels</span></span>
<span>  <span class="va">cm_long</span><span class="op">$</span><span class="va">Prediction</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">cm_long</span><span class="op">$</span><span class="va">Prediction</span>,</span>
<span>    levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">cm_long</span><span class="op">$</span><span class="va">Prediction</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span>  <span class="co"># Order Reference factor levels</span></span>
<span>  <span class="va">cm_long</span><span class="op">$</span><span class="va">Reference</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">cm_long</span><span class="op">$</span><span class="va">Reference</span>,</span>
<span>    levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">cm_long</span><span class="op">$</span><span class="va">Reference</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span>  <span class="co"># Create visualization with ggplot</span></span>
<span>  <span class="va">p</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">cm_long</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="va">Reference</span>, y <span class="op">=</span> <span class="va">Prediction</span>,</span>
<span>    fill <span class="op">=</span> <span class="va">Freq</span></span>
<span>  <span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_tile.html">geom_tile</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">"white"</span>, size <span class="op">=</span> <span class="fl">1.2</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_text.html">geom_text</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>label <span class="op">=</span> <span class="va">Freq</span><span class="op">)</span>,</span>
<span>      color <span class="op">=</span> <span class="st">"black"</span>,</span>
<span>      size <span class="op">=</span> <span class="fl">4.2</span>, fontface <span class="op">=</span> <span class="st">"bold"</span></span>
<span>    <span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_gradient.html">scale_fill_gradient</a></span><span class="op">(</span></span>
<span>      low <span class="op">=</span> <span class="st">"#f1f3f4"</span>, high <span class="op">=</span> <span class="st">"#1976d2"</span>,</span>
<span>      name <span class="op">=</span> <span class="st">"Cases"</span>, trans <span class="op">=</span> <span class="st">"sqrt"</span></span>
<span>    <span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_discrete.html">scale_y_discrete</a></span><span class="op">(</span>limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rev.html">rev</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">cm_long</span><span class="op">$</span><span class="va">Prediction</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span>base_size <span class="op">=</span> <span class="fl">14</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span></span>
<span>      plot.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span></span>
<span>        hjust <span class="op">=</span> <span class="fl">0.5</span>, size <span class="op">=</span> <span class="fl">16</span>, face <span class="op">=</span> <span class="st">"bold"</span>,</span>
<span>        margin <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">margin</a></span><span class="op">(</span>b <span class="op">=</span> <span class="fl">20</span><span class="op">)</span></span>
<span>      <span class="op">)</span>,</span>
<span>      axis.text.x <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span></span>
<span>        angle <span class="op">=</span> <span class="fl">45</span>, hjust <span class="op">=</span> <span class="fl">1</span>, size <span class="op">=</span> <span class="fl">11</span>,</span>
<span>        face <span class="op">=</span> <span class="st">"bold"</span></span>
<span>      <span class="op">)</span>,</span>
<span>      axis.text.y <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">11</span>, face <span class="op">=</span> <span class="st">"bold"</span><span class="op">)</span>,</span>
<span>      axis.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span></span>
<span>        size <span class="op">=</span> <span class="fl">13</span>, face <span class="op">=</span> <span class="st">"bold"</span>,</span>
<span>        margin <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">margin</a></span><span class="op">(</span>t <span class="op">=</span> <span class="fl">10</span><span class="op">)</span></span>
<span>      <span class="op">)</span>,</span>
<span>      legend.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">12</span>, face <span class="op">=</span> <span class="st">"bold"</span><span class="op">)</span>,</span>
<span>      legend.text <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">11</span><span class="op">)</span>,</span>
<span>      panel.grid <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>      plot.margin <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">margin</a></span><span class="op">(</span><span class="fl">20</span>, <span class="fl">20</span>, <span class="fl">20</span>, <span class="fl">20</span><span class="op">)</span></span>
<span>    <span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span></span>
<span>      title <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"Confusion Matrix -"</span>, <span class="va">model_name</span><span class="op">)</span>,</span>
<span>      x <span class="op">=</span> <span class="st">"Actual Class (Reference)"</span>,</span>
<span>      y <span class="op">=</span> <span class="st">"Predicted Class"</span></span>
<span>    <span class="op">)</span></span>
<span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="va">p</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span><span class="co"># plot the confusion matrix</span></span>
<span><span class="fu">create_confusion_matrix_plot</span><span class="op">(</span><span class="va">results</span><span class="op">[[</span><span class="st">"Random Forest"</span><span class="op">]</span><span class="op">]</span>, <span class="st">"Random Forest"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center" data-hash="cy_colombia_cache/html/fig-confusion-matrix-function_1b857ac6d99d154954443f054b1c5276">
<div class="cell-output-display">
<div id="fig-confusion-matrix-function" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/cy_colombia/fig-confusion-matrix-function.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;23.8: Confusion matrix for different crop stages mapped by DPRVI index.</figcaption></figure>
</div>
</div>
</div>
<p><a href="#fig-confusion-matrix-function">Figure&nbsp;<span>23.8</span></a> reveals biophysically interpretable error patterns that validate model behavior rather than indicate systematic failures. Classification errors concentrate exclusively between adjacent phenological stages, with no confusions observed between rice crops and permanent vegetation covers (forest/grass), confirming robust discrimination between agricultural and natural land uses based on distinct polarimetric signatures.</p>
<p>Permanent covers demonstrate near-perfect performance: Forest achieves exceptional accuracy (94/98 samples, 96% correct) with only one tillering sample misclassified, while grass shows similar excellence (92/94 samples, 98% correct). The perfect separation between forest–grass and rice stages validates that DpRVI effectively discriminates between stable volume-scattering patterns (permanent covers) and dynamic agricultural signatures.</p>
<p>Phenological confusion patterns follow biological logic: The most critical finding is that all crop stage confusions occur between adjacent phases, reflecting gradual rather than discrete structural transitions. Tillering demonstrates highest confusion (27/38 samples correctly classified, 71% accuracy) with primary errors involving adjacent growth stages: 8 samples confused with stem elongation and 3 with leaf development.</p>
<p>Polarimetric explanation: The bidirectional confusion between tillering and stem elongation (8 tillering→stem elongation, 2 stem elongation→tillering) indicates overlapping canopy architecture during transition periods. During tillering, increasing tiller density generates volume-scattering patterns similar to early stem elongation, where degree of polarization values overlap (~0.4–0.6) between stages, creating polarimetric ambiguity.</p>
<p>The 68% user accuracy for tillering suggests operational monitoring systems should incorporate temporal context or auxiliary variables (coherence, backscatter) to improve discrimination during this critical phenological window.</p>
<div class="cell" data-tbl-cap="Overall statistics for the Random Forest model">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Print the overall accuracy and kappa statistic</span></span>
<span><span class="va">overall_vec</span> <span class="op">&lt;-</span> <span class="va">results</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span><span class="op">$</span><span class="va">overall</span></span>
<span></span>
<span><span class="va">overall_long</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  Metric <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">overall_vec</span><span class="op">)</span>,</span>
<span>  Value <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">overall_vec</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span><span class="co"># Multiply by 100 to convert to percentage</span></span>
<span><span class="va">overall_long</span><span class="op">$</span><span class="va">Value</span> <span class="op">&lt;-</span> <span class="va">overall_long</span><span class="op">$</span><span class="va">Value</span> <span class="op">*</span> <span class="fl">100</span></span>
<span><span class="co"># round the values to 2 decimal places</span></span>
<span><span class="va">overall_long</span><span class="op">$</span><span class="va">Value</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">overall_long</span><span class="op">$</span><span class="va">Value</span>, <span class="fl">2</span><span class="op">)</span></span>
<span><span class="co"># Visualize the overall statistics as table</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="va">overall_long</span>, digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="tbl-overall-statistic" class="anchored">
<table class="table">
<caption>Table&nbsp;23.3: Overall statistics for the Random Forest model</caption>
<thead><tr class="header">
<th>Metric</th>
<th>Value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Accuracy</td>
<td>91.90</td>
</tr>
<tr class="even">
<td>Kappa</td>
<td>90.08</td>
</tr>
<tr class="odd">
<td>AccuracyLower</td>
<td>88.91</td>
</tr>
<tr class="even">
<td>AccuracyUpper</td>
<td>94.29</td>
</tr>
<tr class="odd">
<td>AccuracyNull</td>
<td>21.76</td>
</tr>
<tr class="even">
<td>AccuracyPValue</td>
<td>0.00</td>
</tr>
<tr class="odd">
<td>McnemarPValue</td>
<td>NaN</td>
</tr>
</tbody>
</table>
</div>
<p><a href="#tbl-overall-statistic">Table&nbsp;<span>23.3</span></a> presents the global performance metrics of the model, which has an overall accuracy of 91.90%, meaning that in almost 92% of cases, the model correctly classified the samples. This is a very high value, indicating excellent performance. Cohen’s Kappa coefficient is a more robust metric than accuracy, as it takes into account the possibility that the accuracy is due to chance. A value of 90.08% is considered very strong. It indicates that the model not only performs well, but its performance is significantly better than random classification.</p>
<p>At the aggregate level, macro‑averaged Precision, Recall, and F1 corroborate this global performance, with consistently high values across classes. The remaining variability aligns with class structure: permanent covers yield very stable scores, while transitional crop stages show expected reductions due to phenological overlap.</p>
<p>The exceptional classification performance achieved in this work (91.90% overall accuracy, κ=90.08%) establishes DpRVI as a strong alternative to conventional radar vegetation indices for tropical crop monitoring, demonstrating robustness under conditions of high atmospheric moisture, variable precipitation, and diverse soil conditions.</p>
<p>The AccuracyLower and AccuracyUpper (88.91 and 94.29) represent the 95% confidence interval for the model’s accuracy, indicating that the true accuracy lies between 88.91% and 94.29%. The AccuracyNull (21.76) is the accuracy that would be obtained if the model simply predicted the most frequent class in the dataset, meaning the most common class represents approximately 22% of the data. The model’s accuracy (91.90%) is much higher than this null accuracy, confirming that the model is learning useful patterns.</p>
<p>The AccuracyPValue (0.00) is the p-value of the hypothesis test that compares the model’s accuracy with the null accuracy. A value of 0.00 (p &lt; 0.05) means that the difference between the model’s accuracy and the null accuracy is statistically significant. In simple terms, the model is genuinely better than guessing. The model has excellent and statistically significant performance for the classification task, with high accuracy and a strong Kappa coefficient.</p>
<p><a href="#fig-metrics-by-class">Figure&nbsp;<span>23.9</span></a> provides class-wise Precision, Recall (Sensitivity), F1, Specificity, and Balanced Accuracy, highlighting how performance varies by structural stability and phenological transitions:</p>
<ul>
<li>Permanent covers (Forest, Grass): F1 ≈ 0.98, Sensitivity ≈ 1.00, Precision ≈ 0.96–0.97, consistent with stable volume‑scattering and minimal confusion with crops.</li>
<li>Germination: F1 ≈ 0.89 with Precision ≈ 0.86; clear separation from permanent covers and early‑season soil conditions.</li>
<li>Stem elongation: F1 ≈ 0.91 with Precision ≈ 0.90; robust discrimination due to mature canopy structure.</li>
<li>Tillering: F1 ≈ 0.77 (Sensitivity ≈ 0.68); lower scores reflect transitional canopy architecture and overlap with adjacent stages.</li>
<li>Specificity: all rice stages &gt; 0.97, limiting false positives in crop mapping.</li>
</ul>
<p>These patterns are coherent with the polarimetric interpretation: stable, highly depolarizing canopies (forest/grass) yield consistently high metrics, while transitional crop stages (tillering) show partial overlap in polarimetric responses that reduces separability.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Function to visualize metrics by class</span></span>
<span><span class="co"># Heatmap of performance by class</span></span>
<span><span class="va">create_metrics_by_class_plot</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">result</span>, <span class="va">model_name</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="co"># Extract metrics by class</span></span>
<span>  <span class="va">by_class</span> <span class="op">&lt;-</span> <span class="va">result</span><span class="op">$</span><span class="va">byClass</span></span>
<span></span>
<span>  <span class="co"># Convert to data frame</span></span>
<span>  <span class="va">by_class_long</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>    Class <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">by_class</span><span class="op">)</span>,</span>
<span>    <span class="va">by_class</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span>  <span class="co"># Convert to tidy long format</span></span>
<span>  <span class="va">by_class_long_tidy</span> <span class="op">&lt;-</span> <span class="va">by_class_long</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer</a></span><span class="op">(</span></span>
<span>      cols <span class="op">=</span> <span class="op">-</span><span class="va">Class</span>,</span>
<span>      names_to <span class="op">=</span> <span class="st">"Metric"</span>,</span>
<span>      values_to <span class="op">=</span> <span class="st">"Value"</span></span>
<span>    <span class="op">)</span></span>
<span></span>
<span>  <span class="co"># Important metrics for visualization</span></span>
<span>  <span class="va">important_metrics</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>    <span class="st">"Sensitivity"</span>, <span class="st">"Specificity"</span>,</span>
<span>    <span class="st">"Pos.Pred.Value"</span>, <span class="st">"Neg.Pred.Value"</span>,</span>
<span>    <span class="st">"F1"</span>, <span class="st">"Balanced.Accuracy"</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span>  <span class="va">by_class_filtered</span> <span class="op">&lt;-</span> <span class="va">by_class_long_tidy</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">Metric</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="va">important_metrics</span><span class="op">)</span></span>
<span></span>
<span>  <span class="co"># Rename metrics for presentation</span></span>
<span>  <span class="va">metric_names</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>    <span class="st">"Sensitivity"</span> <span class="op">=</span> <span class="st">"Sensitivity"</span>,</span>
<span>    <span class="st">"Specificity"</span> <span class="op">=</span> <span class="st">"Specificity"</span>,</span>
<span>    <span class="st">"Pos.Pred.Value"</span> <span class="op">=</span> <span class="st">"Precision"</span>,</span>
<span>    <span class="st">"Neg.Pred.Value"</span> <span class="op">=</span> <span class="st">"NPV"</span>,</span>
<span>    <span class="st">"F1"</span> <span class="op">=</span> <span class="st">"F1-Score"</span>,</span>
<span>    <span class="st">"Balanced.Accuracy"</span> <span class="op">=</span> <span class="st">"Balanced Accuracy"</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span>  <span class="va">by_class_filtered</span><span class="op">$</span><span class="va">Metric</span> <span class="op">&lt;-</span> <span class="va">metric_names</span><span class="op">[</span><span class="va">by_class_filtered</span><span class="op">$</span><span class="va">Metric</span><span class="op">]</span></span>
<span></span>
<span>  <span class="co"># Create heatmap of metrics by class</span></span>
<span>  <span class="va">p</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">by_class_filtered</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="va">Metric</span>, y <span class="op">=</span> <span class="va">Class</span>,</span>
<span>    fill <span class="op">=</span> <span class="va">Value</span></span>
<span>  <span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_tile.html">geom_tile</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">"white"</span>, size <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_gradient.html">scale_fill_gradient2</a></span><span class="op">(</span></span>
<span>      low <span class="op">=</span> <span class="st">"#d32f2f"</span>, mid <span class="op">=</span> <span class="st">"#fff9c4"</span>,</span>
<span>      high <span class="op">=</span> <span class="st">"#388e3c"</span>, midpoint <span class="op">=</span> <span class="fl">0.5</span>,</span>
<span>      name <span class="op">=</span> <span class="st">"Value"</span>,</span>
<span>      limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span>,</span>
<span>      breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span>, <span class="fl">0.2</span><span class="op">)</span>,</span>
<span>      labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span>, <span class="fl">0.2</span><span class="op">)</span> <span class="op">*</span> <span class="fl">100</span>, <span class="st">"%"</span><span class="op">)</span></span>
<span>    <span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_text.html">geom_text</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>label <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">Value</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span>,</span>
<span>      size <span class="op">=</span> <span class="fl">3.8</span>,</span>
<span>      fontface <span class="op">=</span> <span class="st">"bold"</span>, color <span class="op">=</span> <span class="st">"black"</span></span>
<span>    <span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span></span>
<span>      title <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"Metrics by Class -"</span>, <span class="va">model_name</span><span class="op">)</span>,</span>
<span>      x <span class="op">=</span> <span class="st">"Metric"</span>,</span>
<span>      y <span class="op">=</span> <span class="st">"Phenological Class"</span></span>
<span>    <span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span>base_size <span class="op">=</span> <span class="fl">14</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span></span>
<span>      plot.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span></span>
<span>        hjust <span class="op">=</span> <span class="fl">0.5</span>, size <span class="op">=</span> <span class="fl">16</span>,</span>
<span>        face <span class="op">=</span> <span class="st">"bold"</span>,</span>
<span>        margin <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">margin</a></span><span class="op">(</span>b <span class="op">=</span> <span class="fl">15</span><span class="op">)</span></span>
<span>      <span class="op">)</span>,</span>
<span>      axis.text.x <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span></span>
<span>        angle <span class="op">=</span> <span class="fl">45</span>, hjust <span class="op">=</span> <span class="fl">1</span>,</span>
<span>        size <span class="op">=</span> <span class="fl">11</span>, face <span class="op">=</span> <span class="st">"bold"</span></span>
<span>      <span class="op">)</span>,</span>
<span>      axis.text.y <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">11</span>, face <span class="op">=</span> <span class="st">"bold"</span><span class="op">)</span>,</span>
<span>      axis.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span></span>
<span>        size <span class="op">=</span> <span class="fl">13</span>, face <span class="op">=</span> <span class="st">"bold"</span>,</span>
<span>        margin <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">margin</a></span><span class="op">(</span>t <span class="op">=</span> <span class="fl">10</span><span class="op">)</span></span>
<span>      <span class="op">)</span>,</span>
<span>      legend.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">12</span>, face <span class="op">=</span> <span class="st">"bold"</span><span class="op">)</span>,</span>
<span>      legend.text <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">11</span><span class="op">)</span>,</span>
<span>      panel.grid <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>      plot.margin <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">margin</a></span><span class="op">(</span><span class="fl">15</span>, <span class="fl">15</span>, <span class="fl">15</span>, <span class="fl">15</span><span class="op">)</span></span>
<span>    <span class="op">)</span></span>
<span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="va">p</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span><span class="fu">create_metrics_by_class_plot</span><span class="op">(</span><span class="va">results</span><span class="op">[[</span><span class="st">"Random Forest"</span><span class="op">]</span><span class="op">]</span>, <span class="st">"Random Forest"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center" data-hash="cy_colombia_cache/html/fig-metrics-by-class_ed9b38ef51ae39e2f9c467320e19ba96">
<div class="cell-output-display">
<div id="fig-metrics-by-class" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/cy_colombia/fig-metrics-by-class.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;23.9: Metrics by class (Precision, Recall, F1, Specificity, Balanced Accuracy)</figcaption></figure>
</div>
</div>
</div>
</section><section id="classification" class="level3" data-number="23.5.3"><h3 data-number="23.5.3" class="anchored" data-anchor-id="classification">
<span class="header-section-number">23.5.3</span> Classification</h3>
<p>After training and evaluation of the Random Forest model, the DpRVI data cube is classified. The process is carried out in two stages: first, the model is applied to generate an initial classification (probability cube), and then the results are smoothed using a Bayesian spatial smoothing step to reduce noise and improve spatial coherence <span class="citation" data-cites="Simoes2021"><a href="#ref-Simoes2021" role="doc-biblioref">[13]</a></span>.</p>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Make an output directory</span></span>
<span><span class="va">output_dir</span> <span class="op">&lt;-</span> <span class="st">"data/cy_colombia/results/"</span></span>
<span><span class="co"># Create output directory if it does not exist</span></span>
<span><span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/files2.html">dir.exists</a></span><span class="op">(</span><span class="va">output_dir</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/files2.html">dir.create</a></span><span class="op">(</span><span class="va">output_dir</span>, recursive <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span><span class="va">rf_classify</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://e-sensing.github.io/sits/reference/sits_classify.html">sits_classify</a></span><span class="op">(</span></span>
<span>  data <span class="op">=</span> <span class="va">cube_dprvi</span>,</span>
<span>  ml_model <span class="op">=</span> <span class="va">probs_cube</span>,</span>
<span>  output_dir <span class="op">=</span> <span class="va">output_dir</span>,</span>
<span>  version <span class="op">=</span> <span class="st">"rf-raster"</span>,</span>
<span>  multicores <span class="op">=</span> <span class="fl">4</span>,</span>
<span>  memsize <span class="op">=</span> <span class="fl">12</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Bayesian smoothing constitutes an advanced post-processing technique designed to optimize spatial coherence in classifications derived from remote sensing data, which starts from a probability cube generated by the initial classification model. This method systematically addresses the spatial inconsistencies typical of pixel-by-pixel classifications, including isolated pixels, small-scale misclassifications, and fragmented spatial patterns <span class="citation" data-cites="Santos2021a"><a href="#ref-Santos2021a" role="doc-biblioref">[17]</a></span>.</p>
<p>The implementation of Bayesian smoothing is based on the premise that land cover classes tend to exhibit spatial coherence, where neighboring pixels have a high probability of belonging to the same class or related classes. The algorithm incorporates contextual information from adjacent pixels to refine initial classification probabilities, applying Bayesian inference principles that combine local spectral evidence with spatial neighborhood knowledge <span class="citation" data-cites="Santos2021a"><a href="#ref-Santos2021a" role="doc-biblioref">[17]</a></span>.</p>
<p>The evaluation of local logit variance constitutes an essential component of the Bayesian smoothing process, providing a quantitative measure of spatial uncertainty in classification predictions. For each pixel and class, this calculation is executed through the analysis of a moving window of specific dimensions (typically 7×7 pixels), where classification probabilities are transformed to logit space using the function <span class="math inline">\(\ln(\frac{p}{(1-p)})\)</span>, where <span class="math inline">\(p\)</span> is the probability of belonging to a specific class, and subsequently the variance of these logit values is computed considering only the upper fraction of most similar neighboring pixels (generally 50% with highest spectral similarity) <span class="citation" data-cites="Santos2021a"><a href="#ref-Santos2021a" role="doc-biblioref">[17]</a></span>.</p>
<p>This methodology allows the identification of areas with high spatial uncertainty, where land cover classes present diffuse transitions or mixed edges, facilitating the detection of confusion zones and improving the accuracy of Bayesian smoothing. Local logit variance is used to adjust classification probabilities, prioritizing those areas with lower uncertainty and favoring spatial coherence in final predictions.</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Calculate the local logit variance for the classification</span></span>
<span><span class="co"># TODO</span></span>
<span><span class="va">var_cube</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://e-sensing.github.io/sits/reference/sits_variance.html">sits_variance</a></span><span class="op">(</span></span>
<span>  cube <span class="op">=</span> <span class="va">rf_classify</span>,</span>
<span>  window_size <span class="op">=</span> <span class="fl">7</span>,</span>
<span>  neigh_fraction <span class="op">=</span> <span class="fl">0.5</span>,</span>
<span>  multicores <span class="op">=</span> <span class="fl">4</span>,</span>
<span>  memsize <span class="op">=</span> <span class="fl">12</span>,</span>
<span>  output_dir <span class="op">=</span> <span class="va">output_dir</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Plot the variance of the classification for forest and grass</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">var_cube</span>, labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"forest"</span>, <span class="st">"grass"</span><span class="op">)</span>, palette <span class="op">=</span> <span class="st">"Spectral"</span>,</span>
<span>     rev <span class="op">=</span> <span class="cn">TRUE</span>, legend_position <span class="op">=</span> <span class="st">"outside"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center" data-hash="cy_colombia_cache/html/fig-variance-forest-grass_7b08abab9e9a9e23ce5550c85eb7a4df">
<div class="cell-output-display">
<div id="fig-variance-forest-grass" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/cy_colombia/fig-variance-forest-grass.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;23.10: Variance of forest and grass classes</figcaption></figure>
</div>
</div>
</div>
<p><a href="#fig-variance-forest-grass">Figure&nbsp;<span>23.10</span></a> shows that the forest and grass classes exhibit relatively homogeneous variance throughout the study area, characterized by the predominance of low values distributed continuously across the territory. This spatial distribution is consistent with the territorial occupation of these covers in the region, where forest and pasture are distributed as extensive and relatively homogeneous areas.</p>
<p>The observed pattern can be attributed to two main factors: the inherent noise characteristic of SAR data, which introduces random variability in the signal, and the nature of transitions between these dominant covers. The absence of marked variance gradients suggests that the boundaries between forest and pasture are not spectrally abrupt in terms of the DpRVI index response, which may indicate gradual transition zones. These covers exhibit temporal stability, remaining constant during the analysis period.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Plot the variance of the classification for the phenological stages of rice</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">var_cube</span>, labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"germination"</span>, <span class="st">"leaf development"</span>,</span>
<span>                          <span class="st">"tillering"</span>, <span class="st">"stem elongation"</span><span class="op">)</span>,</span>
<span>     palette <span class="op">=</span> <span class="st">"Spectral"</span>, rev <span class="op">=</span> <span class="cn">TRUE</span>, legend_position <span class="op">=</span> <span class="st">"outside"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center" data-hash="cy_colombia_cache/html/fig-variance-phenology_125e8641e7fdbbe52974ddef4c33dd67">
<div class="cell-output-display">
<div id="fig-variance-phenology" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/cy_colombia/fig-variance-phenology.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;23.11: Variance of the phenological stages of rice.</figcaption></figure>
</div>
</div>
</div>
<p><a href="#fig-variance-phenology">Figure&nbsp;<span>23.11</span></a> reveals an interesting spatial pattern where, despite the characteristic noise of SAR images, regions of lowest variance are identified that spatially correspond to rice cultivation areas in the lower right portion of the images. These zones of lower variability present defined edges of higher variance toward the boundaries of agricultural plots, suggesting spatial coherence within some of the cultivated parcels. The spatial distribution of variance in rice phenological stages evidences that agricultural management practices, such as uniform land preparation, synchronized sowing, and integrated crop management, generate spatially coherent patterns that facilitate crop differentiation.</p>
<div>
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># print variance values</span></span>
<span><span class="va">variances</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">var_cube</span><span class="op">)</span></span>
<span><span class="co"># print variances</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="va">variances</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-variance" class="cell tbl-parent quarto-layout-panel anchored" data-tbl-cap="Summary of the logit variance">
<div class="panel-caption table-caption">
<p><strong>?(caption)</strong></p>
</div>
</div>
</div>
<div id="tbl-variance" class="anchored">
<table class="table">
<caption>Table&nbsp;23.4: Summary of the logit variance</caption>
<colgroup>
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 16%">
<col style="width: 11%">
<col style="width: 18%">
<col style="width: 17%">
<col style="width: 14%">
</colgroup>
<thead><tr class="header">
<th></th>
<th style="text-align: right;">forest</th>
<th style="text-align: right;">germination</th>
<th style="text-align: right;">grass</th>
<th style="text-align: right;">leaf development</th>
<th style="text-align: right;">stem elongation</th>
<th style="text-align: right;">tillering</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>75%</td>
<td style="text-align: right;">0.71</td>
<td style="text-align: right;">0.59</td>
<td style="text-align: right;">0.5800</td>
<td style="text-align: right;">0.680</td>
<td style="text-align: right;">0.46</td>
<td style="text-align: right;">0.64</td>
</tr>
<tr class="even">
<td>80%</td>
<td style="text-align: right;">0.87</td>
<td style="text-align: right;">0.76</td>
<td style="text-align: right;">0.7100</td>
<td style="text-align: right;">0.902</td>
<td style="text-align: right;">0.54</td>
<td style="text-align: right;">0.84</td>
</tr>
<tr class="odd">
<td>85%</td>
<td style="text-align: right;">1.08</td>
<td style="text-align: right;">1.01</td>
<td style="text-align: right;">0.8900</td>
<td style="text-align: right;">1.330</td>
<td style="text-align: right;">0.67</td>
<td style="text-align: right;">1.23</td>
</tr>
<tr class="even">
<td>90%</td>
<td style="text-align: right;">1.44</td>
<td style="text-align: right;">1.57</td>
<td style="text-align: right;">1.1900</td>
<td style="text-align: right;">2.140</td>
<td style="text-align: right;">0.92</td>
<td style="text-align: right;">2.11</td>
</tr>
<tr class="odd">
<td>95%</td>
<td style="text-align: right;">2.19</td>
<td style="text-align: right;">2.81</td>
<td style="text-align: right;">1.7905</td>
<td style="text-align: right;">3.000</td>
<td style="text-align: right;">1.86</td>
<td style="text-align: right;">3.01</td>
</tr>
<tr class="even">
<td>100%</td>
<td style="text-align: right;">11.50</td>
<td style="text-align: right;">11.46</td>
<td style="text-align: right;">12.3600</td>
<td style="text-align: right;">11.260</td>
<td style="text-align: right;">10.40</td>
<td style="text-align: right;">10.88</td>
</tr>
</tbody>
</table>
</div>
<p><a href="#tbl-variance">Table&nbsp;<span>23.4</span></a> shows the high quantiles (75–100%) of local logit variance by class, calculated over non‑isotropic neighborhoods, describing the upper part of the distribution, which is the most informative for detecting confusion zones and edges between classes. In all classes, the 75th percentile values are low (≈ 0.46–0.71), indicating that most of the territory consists of compact and homogeneous patches where a single class clearly dominates. Toward the 90–95 percentiles, variances increase, signaling mixed neighborhoods and boundaries between classes.</p>
<p>Regarding patterns by class, the transitional leaf development and tillering classes present the highest tails (P90 ≈ 2.1–2.14 and P95 ≈ 3.0), consistent with the appearance of edges or mixed patches. Germination also shows elevated variance in the tail (P95 ≈ 2.81), above forest (≈ 2.19) and grass (≈ 1.79). In contrast, stem elongation is the most homogeneous, with P75 = 0.46, P90 ≈ 0.92 and P95 ≈ 1.86, suggesting compact patches and less confusion with adjacent classes. The maximum values (100%) are around 10–12 in all classes and correspond to extreme cases or outliers very noisy pixels or singular edges, so they should not guide modeling decisions.</p>
<p>These observations provide a quantitative basis for adjusting variance hyperparameters by class in Bayesian smoothing. The selection of a robust quantile (P90–P95) as reference is methodologically appropriate, considering that classes with greater spatial variability, such as leaf development and tillering, require higher hyperparameters (≈ 2–3) to preserve their intrinsic heterogeneity without incurring over-smoothing that eliminates valid spatial patterns.</p>
<p>In contrast, classes with greater spatial homogeneity (grass, forest, stem elongation) benefit from lower values (≈ 1–2), which reinforces intra-class coherence and prioritizes the most reliable probabilistic assignments. This differentiated strategy allows optimizing the balance between reducing spectral noise characteristic of SAR images and preserving genuine spatial variability associated with each land cover class.</p>
<p>Pixel‑based classification often exhibits local inconsistencies and edge noise. Sits’ empirical Bayesian smoothing is adopted to adjust per‑pixel class probabilities using neighborhood statistics, reinforcing spatial coherence and reducing outliers; this step typically improves class borders and removes isolated misclassifications <span class="citation" data-cites="SITSBOOK"><a href="#ref-SITSBOOK" role="doc-biblioref">[16]</a></span>.</p>
<p>The smoothing is applied with a 7x7 pixel window considering the 50% most similar neighbors, which improves spatial coherence between adjacent classes.</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">rf_smooth</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://e-sensing.github.io/sits/reference/sits_smooth.html">sits_smooth</a></span><span class="op">(</span></span>
<span>  cube <span class="op">=</span> <span class="va">rf_classify</span>,</span>
<span>  window_size <span class="op">=</span> <span class="fl">7</span>,</span>
<span>  neigh_fraction <span class="op">=</span> <span class="fl">0.5</span>,</span>
<span>  smoothness <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>    <span class="st">"germination"</span> <span class="op">=</span> <span class="fl">2.0</span>,</span>
<span>    <span class="st">"leaf development"</span> <span class="op">=</span> <span class="fl">2.0</span>,</span>
<span>    <span class="st">"tillering"</span> <span class="op">=</span> <span class="fl">2.0</span>,</span>
<span>    <span class="st">"stem elongation"</span> <span class="op">=</span> <span class="fl">1.0</span>,</span>
<span>    <span class="st">"forest"</span> <span class="op">=</span> <span class="fl">1.0</span>,</span>
<span>    <span class="st">"grass"</span> <span class="op">=</span> <span class="fl">1.0</span></span>
<span>  <span class="op">)</span>,</span>
<span>  output_dir <span class="op">=</span> <span class="va">output_dir</span>,</span>
<span>  version <span class="op">=</span> <span class="st">"rf-raster"</span>,</span>
<span>  multicores <span class="op">=</span> <span class="fl">4</span>,</span>
<span>  memsize <span class="op">=</span> <span class="fl">12</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The smoothing process generates a new data cube where classification probabilities are adjusted considering the spatial and temporal context of each pixel, significantly improving the spatial coherence of classification results. <a href="#fig-rf-smooth-stages">Figure&nbsp;<span>23.12</span></a> presents the smoothed classification of rice phenological stages, clearly showing spatial coherence between classes and the spatial distribution of cultivation areas consistent with actual field conditions.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Plot the legend for the smoothed classification</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">rf_smooth</span>,</span>
<span>     labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"germination"</span>, <span class="st">"leaf development"</span>,</span>
<span>                <span class="st">"tillering"</span>, <span class="st">"stem elongation"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center" data-hash="cy_colombia_cache/html/fig-rf-smooth-stages_9c488a9aa15d6e02d8bb41c06fde61d7">
<div class="cell-output-display">
<div id="fig-rf-smooth-stages" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/cy_colombia/fig-rf-smooth-stages.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;23.12: Probability of occurrence of phenological stages</figcaption></figure>
</div>
</div>
</div>
<p>Similarly, <a href="#fig-rf-smooth-forest-grass">Figure&nbsp;<span>23.13</span></a> displays the smoothed classification for forest and grass covers, demonstrating clear spatial separation between both classes with well-defined homogeneous areas. Using the adjusted probabilities, the labeled map is produced by assigning to each pixel the maximum‑probability class; optional map reclassification rules can enforce cartographic constraints when needed <span class="citation" data-cites="SITSBOOK"><a href="#ref-SITSBOOK" role="doc-biblioref">[16]</a></span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">rf_smooth</span>,</span>
<span>     labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"forest"</span>, <span class="st">"grass"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center" data-hash="cy_colombia_cache/html/fig-rf-smooth-forest-grass_fb22dfcdace61141c571199c14f7733c">
<div class="cell-output-display">
<div id="fig-rf-smooth-forest-grass" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/cy_colombia/fig-rf-smooth-forest-grass.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;23.13: Probability of occurrence of forest and grassland</figcaption></figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">rf_class</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://e-sensing.github.io/sits/reference/sits_label_classification.html">sits_label_classification</a></span><span class="op">(</span></span>
<span>  cube <span class="op">=</span> <span class="va">rf_smooth</span>,</span>
<span>  multicores <span class="op">=</span> <span class="fl">4</span>,</span>
<span>  memsize <span class="op">=</span> <span class="fl">12</span>,</span>
<span>  output_dir <span class="op">=</span> <span class="va">output_dir</span>,</span>
<span>  version <span class="op">=</span> <span class="st">"rf-raster"</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Following sits’ time‑first, space‑later paradigm, per‑pixel time series are classified to obtain probability cubes (one probability band per class), which then support spatial post‑processing and final labeling <span class="citation" data-cites="SITSBOOK Simoes2021"><a href="#ref-Simoes2021" role="doc-biblioref">[13]</a>, <a href="#ref-SITSBOOK" role="doc-biblioref">[16]</a></span>.</p>
</section><section id="final-classification-results" class="level3" data-number="23.5.4"><h3 data-number="23.5.4" class="anchored" data-anchor-id="final-classification-results">
<span class="header-section-number">23.5.4</span> Final classification results</h3>
<p><a href="#fig-rf-classification-plot">Figure&nbsp;<span>23.14</span></a> shows the Random Forest classification over the DpRVI cube, mapping rice phenological stages and land cover in Nunchía (Casanare). The map exhibits spatially coherent patterns consistent with known land use and crop development in the region. The performance metrics are shown in <a href="#tbl-metrics">Table&nbsp;<span>23.5</span></a>.</p>
<div id="tbl-metrics" class="anchored">
<table class="table">
<caption>Table&nbsp;23.5: Key performance metrics</caption>
<thead><tr class="header">
<th>Metric</th>
<th>Value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Overall Accuracy (OA)</td>
<td>91.90%</td>
</tr>
<tr class="even">
<td>Cohen’s κ</td>
<td>90.08%</td>
</tr>
<tr class="odd">
<td>Accuracy 95% CI</td>
<td>88.91% – 94.29%</td>
</tr>
</tbody>
</table>
</div>
<p>As shown in <a href="#fig-metrics-by-class">Figure&nbsp;<span>23.9</span></a>, performance varies with land‑cover stability and structural complexity:</p>
<ul>
<li>Permanent covers: consistently high metrics reflecting stable volume‑scattering and minimal confusion with crops.</li>
<li>Crop stages: germination and stem elongation are well separated; tillering is lower due to transitional canopy structure.</li>
<li>Specificity: rice stages maintain high specificity, limiting false positives.</li>
<li>Operational benchmarking: stage‑level F1 values exceed common operational targets (F1 &gt; 0.70).</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">rf_class</span>, legend_position <span class="op">=</span> <span class="st">"outside"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center" data-hash="cy_colombia_cache/html/fig-rf-classification-plot_a006e8b83218af732feabfc15b84b893">
<div class="cell-output-display">
<div id="fig-rf-classification-plot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/cy_colombia/fig-rf-classification-plot.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;23.14: Random Forest classification of the DpRVI data cube</figcaption></figure>
</div>
</div>
</div>
</section></section><section id="discussion" class="level2" data-number="23.6"><h2 data-number="23.6" class="anchored" data-anchor-id="discussion">
<span class="header-section-number">23.6</span> Discussion</h2>
<p>The high classification performance supports DpRVI as a strong alternative to conventional radar vegetation indices for tropical crop monitoring, demonstrating robustness under conditions of high atmospheric moisture, variable precipitation, and diverse soil conditions. The DpRVI index integrates polarization purity (m) and scattering dominance (β = λ₁/Span) from the dual‑pol covariance, providing sensitivity to structural change beyond simple backscatter ratios <span class="citation" data-cites="mandal2020dual mandal2021radar"><a href="#ref-mandal2020dual" role="doc-biblioref">[9]</a>, <a href="#ref-mandal2021radar" role="doc-biblioref">[10]</a></span>.</p>
<p>During rice phenological development, the progressive transition from surface-dominated scattering (bare soil post-preparation) to volume-dominated mechanisms (developed canopy) manifests as systematic changes in both m and β parameters. The April DpRVI minima (~0.30) observed across all phenological stages correspond to peak soil contribution periods when polarimetric coherence remains high due to limited vegetation interference. The subsequent recovery reflects increasing canopy structural complexity, which enhances depolarization mechanisms and yields higher DpRVI values.</p>
<p>This physical interpretation aligns with theoretical polarimetric scattering models and explains the observed classification success, particularly the effective discrimination between temporally proximate phenological stages (e.g., germination vs.&nbsp;leaf development).</p>
<p>The classification successfully captures the characteristic land use mosaic of the Casanare region:</p>
<ul>
<li><p>Forest distribution: Spatial continuity validates the model’s ability to distinguish mature vegetation structure from agricultural systems through consistent volume-scattering signatures and stable DpRVI patterns (~0.6) throughout the observation period.</p></li>
<li><p>Pastoral systems: Grasslands occupy transitional zones between forest and agricultural sectors, representing established cattle ranching systems typical of Colombian Llanos. These areas exhibit moderate DpRVI variability, reflecting less dense vegetation structure than forests but with sufficient biomass to generate detectable depolarization by radar sensors.</p></li>
<li><p>Agricultural concentration: Rice cultivation concentrates in the southeastern sector where topographic conditions (slopes &lt;3%) create optimal conditions for rainfed rice production. This spatial concentration aligns with known agricultural zoning in the region, providing external validation of classification accuracy.</p></li>
</ul>
<p>Within agricultural areas, the classification reveals heterogeneous spatial distribution of phenological stages without dominant clustering of any single phase. This pattern reflects:</p>
<ul>
<li>Management unit coherence: Despite overall heterogeneity, individual agricultural parcels show internal phenological consistency, indicating synchronized management within farms while maintaining diversity across the landscape. This spatial coherence reflects uniform agricultural practices in soil preparation and early-stage management.</li>
</ul>
<p>Multitemporal SAR with a 12‑day Sentinel‑1 revisit provides all‑weather, sufficiently frequent observations to capture phenological transitions; polarimetric sensitivity enables discrimination between adjacent crop stages. Stage discrimination at landscape scale (&gt;10,000 ha) demonstrates the scalability of DpRVI‑based monitoring for agricultural surveillance. Increasing canopy complexity elevates depolarization, enabling detection of subtle developmental changes. The observed spatial coherence supports operational use for crop area estimation and early warning where optical systems suffer persistent cloud cover.</p>
<p>These results have significant implications for operational crop monitoring and agricultural management in Colombia:</p>
<ul>
<li><p>National-scale implementation: The methodology can be scaled to support national assessments of sown area, early warning systems, and other agricultural applications where consistent, weather-independent monitoring is essential.</p></li>
<li><p>Decision support: Although this work focused on a specific portion of the rice cultivation cycle and a particular region, it successfully identified six land cover classes including four distinct rice phenological stages, enabling farmers and policy makers to make informed and anticipatory decisions about resource management and allocation.</p></li>
</ul></section><section id="conclusions" class="level2" data-number="23.7"><h2 data-number="23.7" class="anchored" data-anchor-id="conclusions">
<span class="header-section-number">23.7</span> Conclusions</h2>
<p>The incorporation of supplementary polarimetric variables, such as temporal coherence and multitemporal backscatter from SAR data, could further improve classification accuracy, particularly in areas with complex phenological transitions or mixed pixel environments. The implementation of this SAR-based monitoring approach represents a significant advancement in Colombian agricultural monitoring, offering comprehensive early-season assessments across large areas with consistent quality standards.</p>
<p>This work demonstrates the effective use of multitemporal DpRVI from Sentinel‑1 to monitor rice phenology in Colombian rainfed systems, with high accuracy across six classes (four phenological stages plus permanent covers). Our key findings are:</p>
<ol type="1">
<li>Polarimetric discrimination: DpRVI captures biophysical changes in canopy architecture, enabling separation of adjacent phenological stages.</li>
<li>Operational viability: Freely available Sentinel‑1 data and open‑source tooling (sits in R) support cost‑effective implementation.</li>
<li>Temporal specificity: Variable importance aligns with agriculturally meaningful periods, reinforcing the physical basis of discrimination.</li>
<li>Spatial scalability: Landscape‑scale classification (&gt;10,000 ha) with coherent maps supports national surveillance potential.</li>
</ol>
<p>This framework advances SAR‑based agricultural monitoring and strengthens rice mapping where cloud cover limits optical data, providing a robust foundation for operational crop monitoring in tropical regions.</p>
<p>Best‑practice validation avoids spatial leakage by splitting train/test at the parcel level and reports OA, κ, and class‑wise Precision/Recall/F1 from the confusion matrix; map‑level accuracy assessment complements cross‑validation where applicable <span class="citation" data-cites="Simoes2021 SOKOLOVA2009427 SITSBOOK"><a href="#ref-Simoes2021" role="doc-biblioref">[13]</a>, <a href="#ref-SITSBOOK" role="doc-biblioref">[16]</a>, <a href="#ref-SOKOLOVA2009427" role="doc-biblioref">[22]</a></span>.</p>
</section><section id="acknowledgements" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="acknowledgements">Acknowledgements</h2>
<p>The author thanks the Federación Nacional de Arroceros and the Fondo Nacional del Arroz (Fedearroz‑FNA) for their support and collaboration, which were fundamental to the development of this work.</p>
</section><section id="references" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="references">References</h2>


<div id="refs" class="references csl-bib-body" role="list">
<div id="ref-Dong_Xiao_rev" class="csl-entry" role="listitem">
<div class="csl-left-margin">[1] </div>
<div class="csl-right-inline">J. Dong and X. Xiao, <span>“Evolution of regional to global paddy rice mapping methods: A review,”</span> <em>ISPRS Journal of Photogrammetry and Remote Sensing</em>, vol. 119, pp. 214–227, 2016, doi: <a href="https://doi.org/10.1016/j.isprsjprs.2016.05.010">10.1016/j.isprsjprs.2016.05.010</a>.</div>
</div>
<div id="ref-Dong2016" class="csl-entry" role="listitem">
<div class="csl-left-margin">[2] </div>
<div class="csl-right-inline">J. Dong <em>et al.</em>, <span>“Mapping paddy rice planting area in northeastern asia with landsat 8 images, phenology-based algorithm and google earth engine,”</span> <em>Remote Sensing of Environment</em>, vol. 185, pp. 142–154, 2016, doi: <a href="https://doi.org/10.1016/j.rse.2016.02.016">10.1016/j.rse.2016.02.016</a>.</div>
</div>
<div id="ref-ZHENG2016131" class="csl-entry" role="listitem">
<div class="csl-left-margin">[3] </div>
<div class="csl-right-inline">H. Zheng <em>et al.</em>, <span>“Detection of rice phenology through time series analysis of ground-based spectral index data,”</span> <em>Field Crops Research</em>, vol. 198, pp. 131–139, 2016, doi: <a href="https://doi.org/10.1016/j.fcr.2016.08.027">10.1016/j.fcr.2016.08.027</a>.</div>
</div>
<div id="ref-Waldini2021" class="csl-entry" role="listitem">
<div class="csl-left-margin">[4] </div>
<div class="csl-right-inline">H. Waldini, I. Ash Shidiq, R. Rokhmatuloh, and S. Supriatna, <span>“Rice crop phenology model to monitor rice planting and harvesting time using remote sensing approach,”</span> <em>E3S Web of Conferences</em>, vol. 232, p. 03020, Jan. 2021, doi: <a href="https://doi.org/10.1051/e3sconf/202123203020">10.1051/e3sconf/202123203020</a>.</div>
</div>
<div id="ref-mosleh2015application" class="csl-entry" role="listitem">
<div class="csl-left-margin">[5] </div>
<div class="csl-right-inline">M. K. Mosleh, Q. K. Hassan, and E. H. Chowdhury, <span>“Application of remote sensors in mapping rice area and forecasting its production: A review,”</span> <em>Sensors</em>, vol. 15, no. 1, pp. 769–791, 2015, doi: <a href="https://doi.org/10.3390/s150100769">10.3390/s150100769</a>.</div>
</div>
<div id="ref-CENSO_GENERAL" class="csl-entry" role="listitem">
<div class="csl-left-margin">[6] </div>
<div class="csl-right-inline">FEDEARROZ-FNA, Ed., <em><a href="https://fedearroz-website.s3.amazonaws.com/media/documents/bol-5toCNA-2023_1ra_Entrega_2023.pdf">V CENSO NACIONAL ARROCERO 2023</a></em>. Bogotá D. C., Colombia: FEDERACIÓN NACIONAL DE ARROCEROS FONDO NACIONAL DEL ARROZ, División de Investigaciones Económicas, 2023.</div>
</div>
<div id="ref-palakuru2021exploring" class="csl-entry" role="listitem">
<div class="csl-left-margin">[7] </div>
<div class="csl-right-inline">M. Palakuru, S. Khadar Babu, and N. R. Chaube, <span>“Exploring potential of c band synthetic aperture radar imagery to investigate rice crop growth mechanism and productivity,”</span> <em>Environmental Science and Pollution Research</em>, vol. 28, pp. 42001–42013, 2021, doi: <a href="https://doi.org/10.1007/s11356-021-13759-z">10.1007/s11356-021-13759-z</a>.</div>
</div>
<div id="ref-YANG2021112394" class="csl-entry" role="listitem">
<div class="csl-left-margin">[8] </div>
<div class="csl-right-inline">H. Yang, B. Pan, N. Li, W. Wang, J. Zhang, and X. Zhang, <span>“A systematic method for spatio-temporal phenology estimation of paddy rice using time series sentinel-1 images,”</span> <em>Remote Sensing of Environment</em>, vol. 259, p. 112394, 2021, doi: <a href="https://doi.org/10.1016/j.rse.2021.112394">10.1016/j.rse.2021.112394</a>.</div>
</div>
<div id="ref-mandal2020dual" class="csl-entry" role="listitem">
<div class="csl-left-margin">[9] </div>
<div class="csl-right-inline">D. Mandal <em>et al.</em>, <span>“Dual polarimetric radar vegetation index for crop growth monitoring using sentinel-1 SAR data,”</span> <em>Remote Sensing of Environment</em>, vol. 247, p. 111954, 2020, doi: <a href="https://doi.org/10.1016/j.rse.2020.111954">10.1016/j.rse.2020.111954</a>.</div>
</div>
<div id="ref-mandal2021radar" class="csl-entry" role="listitem">
<div class="csl-left-margin">[10] </div>
<div class="csl-right-inline">D. Mandal, A. Bhattacharya, and Y. S. Rao, <em><a href="https://doi.org/10.1007/978-981-16-4424-5">Radar remote sensing for crop biophysical parameter estimation</a></em>. Springer, 2021.</div>
</div>
<div id="ref-mandal2019sentinel" class="csl-entry" role="listitem">
<div class="csl-left-margin">[11] </div>
<div class="csl-right-inline">D. Mandal <em>et al.</em>, <span>“Sentinel-1 SLC preprocessing workflow for polarimetric applications: A generic practice for generating dual-pol covariance matrix elements in SNAP s-1 toolbox,”</span> 2019, doi: <a href="https://doi.org/10.20944/preprints201911.0393.v1">https://doi.org/10.20944/preprints201911.0393.v1</a>.</div>
</div>
<div id="ref-meier1997growth" class="csl-entry" role="listitem">
<div class="csl-left-margin">[12] </div>
<div class="csl-right-inline">U. Meier, <em>Growth stages of mono-and dicotyledonous plants</em>. Blackwell Wissenschafts-Verlag, 1997.</div>
</div>
<div id="ref-Simoes2021" class="csl-entry" role="listitem">
<div class="csl-left-margin">[13] </div>
<div class="csl-right-inline">R. Simoes <em>et al.</em>, <span>“Satellite image time series analysis for big earth observation data,”</span> <em>Remote Sensing</em>, vol. 13, no. 13, p. 2428, 2021, doi: <a href="https://doi.org/10.3390/rs13132428">10.3390/rs13132428</a>.</div>
</div>
<div id="ref-Ferreira2020" class="csl-entry" role="listitem">
<div class="csl-left-margin">[14] </div>
<div class="csl-right-inline">K. R. Ferreira <em>et al.</em>, <span>“Earth <span>Observation Data Cubes</span> for <span>Brazil</span>: <span>Requirements</span>, <span>Methodology</span> and <span>Products</span>,”</span> <em>Remote Sensing</em>, vol. 12, no. 24, p. 4033, 2020, doi: <a href="https://doi.org/10.3390/rs12244033">10.3390/rs12244033</a>.</div>
</div>
<div id="ref-data4030092" class="csl-entry" role="listitem">
<div class="csl-left-margin">[15] </div>
<div class="csl-right-inline">M. Appel and E. Pebesma, <span>“On-demand processing of data cubes from satellite image collections with the gdalcubes library,”</span> <em>Data</em>, vol. 4, no. 3, 2019, doi: <a href="https://doi.org/10.3390/data4030092">10.3390/data4030092</a>.</div>
</div>
<div id="ref-SITSBOOK" class="csl-entry" role="listitem">
<div class="csl-left-margin">[16] </div>
<div class="csl-right-inline">G. Camara <em>et al.</em>, <span>“Satellite image time series analysis on earth observation data cubes.”</span> 2024, [Online]. Available: <a href="https://e-sensing.github.io/sitsbook/">https://e-sensing.github.io/sitsbook/</a>.</div>
</div>
<div id="ref-Santos2021a" class="csl-entry" role="listitem">
<div class="csl-left-margin">[17] </div>
<div class="csl-right-inline">L. A. Santos, K. R. Ferreira, G. Camara, M. C. A. Picoli, and R. E. Simoes, <span>“Quality control and class noise reduction of satellite image time series,”</span> <em>ISPRS Journal of Photogrammetry and Remote Sensing</em>, vol. 177, pp. 75–88, 2021, doi: <a href="https://doi.org/10.1016/j.isprsjprs.2021.04.014">10.1016/j.isprsjprs.2021.04.014</a>.</div>
</div>
<div id="ref-RODRIGUEZGALIANO201293" class="csl-entry" role="listitem">
<div class="csl-left-margin">[18] </div>
<div class="csl-right-inline">V. F. Rodriguez-Galiano, B. Ghimire, J. Rogan, M. Chica-Olmo, and J. P. Rigol-Sanchez, <span>“An assessment of the effectiveness of a random forest classifier for land-cover classification,”</span> <em>ISPRS Journal of Photogrammetry and Remote Sensing</em>, vol. 67, pp. 93–104, 2012, doi: <a href="https://doi.org/10.1016/j.isprsjprs.2011.11.002">10.1016/j.isprsjprs.2011.11.002</a>.</div>
</div>
<div id="ref-breiman2001random" class="csl-entry" role="listitem">
<div class="csl-left-margin">[19] </div>
<div class="csl-right-inline">L. Breiman, <span>“Random forests,”</span> <em>Machine learning</em>, vol. 45, no. 1, pp. 5–32, 2001, doi: <a href="https://doi.org/10.1023/A:1010933404324">10.1023/A:1010933404324</a>.</div>
</div>
<div id="ref-James2013" class="csl-entry" role="listitem">
<div class="csl-left-margin">[20] </div>
<div class="csl-right-inline">G. James, D. Witten, T. Hastie, and R. Tibshirani, <em>An <span>Introduction</span> to <span>Statistical Learning</span>: With <span>Applications</span> in <span>R</span></em>. New York, EUA: Springer, 2013.</div>
</div>
<div id="ref-raschka2019python" class="csl-entry" role="listitem">
<div class="csl-left-margin">[21] </div>
<div class="csl-right-inline">S. Raschka and V. Mirjalili, <em>Python machine learning: Machine learning and deep learning with python, scikit-learn, and TensorFlow 2</em>. Packt Publishing Ltd, 2019.</div>
</div>
<div id="ref-SOKOLOVA2009427" class="csl-entry" role="listitem">
<div class="csl-left-margin">[22] </div>
<div class="csl-right-inline">M. Sokolova and G. Lapalme, <span>“A systematic analysis of performance measures for classification tasks,”</span> <em>Information Processing &amp; Management</em>, vol. 45, no. 4, pp. 427–437, 2009, doi: <a href="https://doi.org/10.1016/j.ipm.2009.03.002">10.1016/j.ipm.2009.03.002</a>.</div>
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./cy_indonesia.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Mapping crop phenology in Indonesia</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./cy_poland.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Yield forecasting in Poland</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">Edited by Gilberto Camara, Lorenzo de Simone and Ronald Jansen.</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">This book was built with <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>


</body></html>