<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Gilberto Camara, Lorenzo de Simone, Ronald Jansen">
<title>14&nbsp; Semantic Segmentation for Automatic Field Boundary Delineation – UN Handbook on Remote Sensing for Agricultural Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./crop_type_mapping.html" rel="next">
<link href="./th_alignment.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-931bd9de4a2e97c797357f31cd37fa94.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./theory.html">Foundations</a></li><li class="breadcrumb-item"><a href="./th_parcel_extraction.html"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Semantic Segmentation for Automatic Field Boundary Delineation</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">UN Handbook on Remote Sensing for Agricultural Statistics</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/FAO-EOSTAT/UN-Handbook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Welcome</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./howto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">How to use this handbook</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_remote_sensing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Remote sensing images: optical, SAR</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_data_sources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Earth observation big data sources</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_data_cubes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Earth observation data cubes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_lucc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Land cover and crop classification schemas</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_quality_control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Quality control of training sets for agricultural statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_machine_learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Machine learning algorithms for image time series</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_uncertainty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Spatial map uncertainty estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Map validation and use of maps for area estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_design_frames.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Remote Sensing in the Design of Sampling Frames</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_alignment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Alignment of field data collection to EO statistical requirements</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_parcel_extraction.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Semantic Segmentation for Automatic Field Boundary Delineation</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./crop_type_mapping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Use Cases in Crop Type Mapping</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_poland.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Crop monitoring with Sentinel-1 and Sentinel-2 images in Poland</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_mexico.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Crop classification in Mexico</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_zimbabwe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Crop classification in Zimbabwe</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_china.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Efficient and Reliable Paddy Rice Classification</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_chile.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Crop classification and land use mapping in Chile</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_digital_earth_africa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Agricultural Mapping with Digital Earth Africa</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./crop_yield_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Crop yield estimation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_finland.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Early-season crop yield mapping in Finland</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_indonesia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Mapping crop phenology in Indonesia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_colombia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Rice Phenology Mapping in Colombia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_poland.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Yield forecasting in Poland</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_china.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Remote Sensing Estimation of Soybean Yield Based on Multi-Scenario Simulation</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./crop_statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Extraction of crop statistics from crop type and crop yield maps</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./crop_statistics_area.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Crop Statistics using Weighted Area Estimators</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./crop_statistics_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Estimating crop statistics using survey-calibrated methods</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./crop_statistics_calibration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Estimating crop statistics for list frame data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./crop_statistics_ppi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Prediction-Powered Inference (PPI) for Agricultural Decision-Making</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./uav_agriculture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">UAV applications in agricultural statistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uav_field_parcels.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Field Parcel Identification Using UAV Imagery Based on the DCP-MTL Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uav_wheat_growth.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Application of UAV in Wheat Growth Monitoring</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uav_crop_growth.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Automated Monitoring of Crop Growth Index using UAV</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./disaster_response.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Remote Sensing for Agricultural Disaster Response</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dis_china_floods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">An Automated Flood Detection Algorithm for Post-Disaster Assessment</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./additional.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Additional Topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ad_world_cereal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">WorldCereal - A Global Effort for Crop Mapping</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ad_learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Personalised Learning Program for Training in the Use of Earth Observation for Agricultural Statistics</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">14.1</span> Introduction</a></li>
  <li>
<a href="#review-of-literature-on-semantic-segmenation" id="toc-review-of-literature-on-semantic-segmenation" class="nav-link" data-scroll-target="#review-of-literature-on-semantic-segmenation"><span class="header-section-number">14.2</span> Review of Literature on Semantic Segmenation</a>
  <ul class="collapse">
<li><a href="#model-architectures" id="toc-model-architectures" class="nav-link" data-scroll-target="#model-architectures"><span class="header-section-number">14.2.1</span> Model Architectures</a></li>
  <li><a href="#learning-strategies-leveraging-self-supervised-learning" id="toc-learning-strategies-leveraging-self-supervised-learning" class="nav-link" data-scroll-target="#learning-strategies-leveraging-self-supervised-learning"><span class="header-section-number">14.2.2</span> Learning Strategies: Leveraging Self-Supervised Learning</a></li>
  <li><a href="#transfer-learning-and-multi-source-training" id="toc-transfer-learning-and-multi-source-training" class="nav-link" data-scroll-target="#transfer-learning-and-multi-source-training"><span class="header-section-number">14.2.3</span> Transfer Learning and Multi-Source Training</a></li>
  <li><a href="#evaluation-metrics" id="toc-evaluation-metrics" class="nav-link" data-scroll-target="#evaluation-metrics"><span class="header-section-number">14.2.4</span> Evaluation Metrics</a></li>
  </ul>
</li>
  <li>
<a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><span class="header-section-number">14.3</span> Methods</a>
  <ul class="collapse">
<li><a href="#binary-semantic-segmentation" id="toc-binary-semantic-segmentation" class="nav-link" data-scroll-target="#binary-semantic-segmentation"><span class="header-section-number">14.3.1</span> Binary Semantic Segmentation</a></li>
  <li><a href="#data-acquisition-and-imagery-pre-and-post-processing" id="toc-data-acquisition-and-imagery-pre-and-post-processing" class="nav-link" data-scroll-target="#data-acquisition-and-imagery-pre-and-post-processing"><span class="header-section-number">14.3.2</span> Data Acquisition, and Imagery Pre and Post-processing</a></li>
  <li><a href="#manual-annotation-of-field-plots" id="toc-manual-annotation-of-field-plots" class="nav-link" data-scroll-target="#manual-annotation-of-field-plots"><span class="header-section-number">14.3.3</span> Manual Annotation of Field Plots</a></li>
  <li><a href="#effort-cost-and-workforce-dynamics" id="toc-effort-cost-and-workforce-dynamics" class="nav-link" data-scroll-target="#effort-cost-and-workforce-dynamics"><span class="header-section-number">14.3.4</span> Effort, Cost, and Workforce Dynamics</a></li>
  </ul>
</li>
  <li>
<a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">14.4</span> Results</a>
  <ul class="collapse">
<li><a href="#practical-aspects-of-implementation" id="toc-practical-aspects-of-implementation" class="nav-link" data-scroll-target="#practical-aspects-of-implementation"><span class="header-section-number">14.4.1</span> Practical Aspects of Implementation</a></li>
  <li><a href="#computational-infrastructure" id="toc-computational-infrastructure" class="nav-link" data-scroll-target="#computational-infrastructure"><span class="header-section-number">14.4.2</span> Computational Infrastructure</a></li>
  <li><a href="#training-times" id="toc-training-times" class="nav-link" data-scroll-target="#training-times"><span class="header-section-number">14.4.3</span> Training Times</a></li>
  <li><a href="#inference-times" id="toc-inference-times" class="nav-link" data-scroll-target="#inference-times"><span class="header-section-number">14.4.4</span> Inference Times</a></li>
  <li><a href="#sample-production-and-annotation" id="toc-sample-production-and-annotation" class="nav-link" data-scroll-target="#sample-production-and-annotation"><span class="header-section-number">14.4.5</span> Sample Production and Annotation</a></li>
  <li><a href="#effort-for-fine-tuning-models" id="toc-effort-for-fine-tuning-models" class="nav-link" data-scroll-target="#effort-for-fine-tuning-models"><span class="header-section-number">14.4.6</span> Effort for Fine-Tuning Models</a></li>
  <li><a href="#effectiveness-of-using-ssl-pre-training" id="toc-effectiveness-of-using-ssl-pre-training" class="nav-link" data-scroll-target="#effectiveness-of-using-ssl-pre-training"><span class="header-section-number">14.4.7</span> Effectiveness of Using SSL Pre-Training</a></li>
  </ul>
</li>
  <li>
<a href="#implications-for-national-agricultural-statistical-offices" id="toc-implications-for-national-agricultural-statistical-offices" class="nav-link" data-scroll-target="#implications-for-national-agricultural-statistical-offices"><span class="header-section-number">14.5</span> Implications for National Agricultural Statistical Offices</a>
  <ul class="collapse">
<li><a href="#crop-mapping-and-land-use-classification" id="toc-crop-mapping-and-land-use-classification" class="nav-link" data-scroll-target="#crop-mapping-and-land-use-classification"><span class="header-section-number">14.5.1</span> Crop Mapping and Land Use Classification</a></li>
  </ul>
</li>
  <li>
<a href="#crop-yield-estimation-and-production-projection" id="toc-crop-yield-estimation-and-production-projection" class="nav-link" data-scroll-target="#crop-yield-estimation-and-production-projection"><span class="header-section-number">14.6</span> Crop Yield Estimation and Production Projection</a>
  <ul class="collapse">
<li><a href="#continuous-monitoring-and-early-warning-systems" id="toc-continuous-monitoring-and-early-warning-systems" class="nav-link" data-scroll-target="#continuous-monitoring-and-early-warning-systems"><span class="header-section-number">14.6.1</span> Continuous Monitoring and Early Warning Systems</a></li>
  <li><a href="#addressing-limitations-and-future-directions" id="toc-addressing-limitations-and-future-directions" class="nav-link" data-scroll-target="#addressing-limitations-and-future-directions"><span class="header-section-number">14.6.2</span> Addressing Limitations and Future Directions</a></li>
  </ul>
</li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions"><span class="header-section-number">14.7</span> Conclusions</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/FAO-EOSTAT/UN-Handbook/edit/quarto/th_parcel_extraction.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/FAO-EOSTAT/UN-Handbook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./theory.html">Foundations</a></li><li class="breadcrumb-item"><a href="./th_parcel_extraction.html"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Semantic Segmentation for Automatic Field Boundary Delineation</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title">
<span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Semantic Segmentation for Automatic Field Boundary Delineation</span>
</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ian Nunes, Hugo Oliveira, Edemir Andrade, Octavio Costa de Oliveira </p>
          </div>
  </div>
    
  
    
  </div>
  


</header><section id="introduction" class="level2" data-number="14.1"><h2 data-number="14.1" class="anchored" data-anchor-id="introduction">
<span class="header-section-number">14.1</span> Introduction</h2>
<p>Over the past few decades, the accessibility of publicly available data from satellite constellations, such as Sentinel and Landsat, has transformed remote sensing (RS) into an indispensable tool for mapping and planning agricultural activities across continents [<span class="citation" data-cites="Liaghat2010"><a href="#ref-Liaghat2010" role="doc-biblioref">[1]</a></span>, <span class="citation" data-cites="Andrimont2023"><a href="#ref-Andrimont2023" role="doc-biblioref">[2]</a></span>, <span class="citation" data-cites="Garnot2021"><a href="#ref-Garnot2021" role="doc-biblioref">[3]</a></span>}. The ability to map harvest areas and pastures via RS serves as a input for a many applications. These include allocation of agricultural subsidies, adopting of best practices in crop rotation, supporting phenological studies, monitoring environmental impacts, predicting food prices, planning sustainable cultivation strategies, optimizing planting and harvesting dates, and ultimately, enhancing food security [<span class="citation" data-cites="Liaghat2010"><a href="#ref-Liaghat2010" role="doc-biblioref">[1]</a></span>, <span class="citation" data-cites="Garnot2021"><a href="#ref-Garnot2021" role="doc-biblioref">[3]</a></span>, <span class="citation" data-cites="pinto2024tradition"><a href="#ref-pinto2024tradition" role="doc-biblioref">[4]</a></span>, <span class="citation" data-cites="Gallo2021"><a href="#ref-Gallo2021" role="doc-biblioref">[5]</a></span>, <span class="citation" data-cites="Gallo2023"><a href="#ref-Gallo2023" role="doc-biblioref">[6]</a></span>, <span class="citation" data-cites="Andrimont2023"><a href="#ref-Andrimont2023" role="doc-biblioref">[2]</a></span>}. Each of these applications benefits from accurate and timely information on agricultural land use and field boundaries. Precise mapping of harvest areas can directly inform decisions on agricultural aid, optimizing resource distribution and preventing wastage. Monitoring crop rotation practices through satellite imagery can help ensure environmental sustainability and compliance with agricultural policies designed to preserve soil health and biodiversity. Phenological studies, which track the lifecycle of plants, become more accurate when precise field boundaries are known, allowing for more granular analysis of crop development stages. Furthermore, understanding the spatial extent of agricultural activity is critical for assessing environmental impacts, such as water usage, land degradation, or the impact of land conversion from natural ecosystems to agricultural fields. Economically, reliable estimates of planted areas contribute to more accurate predictions of food prices, which influence national and international markets. Planning for sustainable planting involves identifying suitable lands and optimizing resource allocation, tasks simplified by detailed field maps. The ability to predict optimal planting and harvesting dates based on regional climatic conditions, as observed through satellite data, can significantly improve agricultural productivity. Ensuring food security at a national level relies on comprehensive data regarding agricultural output, which begins with precise knowledge of where and what is being cultivated.</p>
<p>Manual analysis of large-scale remote sensing data presents a formidable challenge, primarily due to its inherent high cost and labor-intensive nature. A rigorous methodological study involving RS data typically requires specialized professionals, such as cartographers or agronomists, who possess the requisite training to interpret such images. These experts examine vast expanses of land to identify and delineate agricultural fields. This process is slow and prone to inconsistencies due to human fatigue and subjective interpretation. Furthermore, many tasks such as crop classification or yield estimation, cannot be addressed through remote satellite imagery alone; they need complementary information from field visits or the integration of auxiliary data, adding further complexity and cost. Consequently, human intervention is a bottleneck in large-scale satellite imagery studies, hindering the rapid and widespread adoption of remote sensing for agricultural monitoring. The volume of data generated by modern satellite constellations makes manual processing practically impossible for national-scale applications.</p>
<p>Machine Learning (ML) methods offer a promising solution to alleviate the analytical cost associated with large-scale RS data studies. Computational models enable the recognition of patterns relevant to specific tasks, such as land use mapping or the precise segmentation of planting regions. These models, trained on human-annotated data, can be applied to other areas lacking ground truth labels, automating a labour-intensive process. This automation speeds up data processing and ensures consistency and objectivity in the analysis.</p>
<p>Deep Learning (DL) methods are well-suited for such tasks <span class="citation" data-cites="Bengio2017"><a href="#ref-Bengio2017" role="doc-biblioref">[7]</a></span>. They have the capacity to learn from available labeled data, optimizing feature extraction and pattern learning. Unlike traditional ML algorithms that often require handcrafted features, DL models can automatically learn hierarchical representations from raw pixel data, capturing patterns and spatial relationships. This ability to learn complex, non-linear relationships makes them effective for field boundary delineation, where variations in terrain, lighting, crop types, and growth stages can influence visual appearance. However, the very characteristic that endows traditional DL models with their pattern recognition prowess—their data-driven nature—also restricts their applicability in real-world scenarios. Such models demand large accurately labeled data sets for effective learning, a requirement that can be a hurdle in many geographical contexts. Consequently, several active areas within ML and DL research are dedicated to reducing the reliance on human-produced labels for model training. These include supervised pretraining followed by transfer learning, domain adaptation, meta-learning, self-supervised learning (SSL), and foundational models in computer vision <span class="citation" data-cites="niu2021decade"><a href="#ref-Awais2023" role="doc-biblioref">[13]</a></span>. Among these, transfer learning and self-supervised learning have emerged as prominent due to their robust performance in remote sensing data, offering pathways to overcome the data scarcity challenge.</p>
<p>This chapter focuses on field boundary delineation, which involves identifying and outlining the perimeters of agricultural parcels. This task is fundamental for official statistical offices, as field boundaries underpin agricultural surveys, resource management, and environmental monitoring at regional and national scales. The following sections will detail the methodologies, practical considerations, and broader implications of automating this ]process through machine learning techniques, providing a roadmap for its implementation in large-scale agricultural monitoring.</p>
</section><section id="review-of-literature-on-semantic-segmenation" class="level2" data-number="14.2"><h2 data-number="14.2" class="anchored" data-anchor-id="review-of-literature-on-semantic-segmenation">
<span class="header-section-number">14.2</span> Review of Literature on Semantic Segmenation</h2>
<section id="model-architectures" class="level3" data-number="14.2.1"><h3 data-number="14.2.1" class="anchored" data-anchor-id="model-architectures">
<span class="header-section-number">14.2.1</span> Model Architectures</h3>
<p>The core of automated field boundary delineation relies on machine learning models, leveraging deep learning methodologies for the production of agricultural statistics. These computational methods produce detailed thematic maps of agricultural regions, enabling comprehensive area monitoring and crop production estimates.</p>
<p>Traditional machine learning models such as Random Forest, XGBoost and support vector machines are still much used in agricultural statistics. However, for more complex and large-scale applications, deep neural networks are indispensable. Convolutional Neural Networks (CNNs) <span class="citation" data-cites="Krizhevsky2012"><a href="#ref-Huang2017" role="doc-biblioref">[17]</a></span> and their numerous variations have demonstrated sufficient flexibility and power for solving intricate problems like image segmentation <span class="citation" data-cites="Long2015"><a href="#ref-He2017" role="doc-biblioref">[20]</a></span>. CNNs achieve this by learning hierarchical features through stacked convolutional layers, progressively extracting more abstract and meaningful representations from the raw pixel data.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-cnn-ibge" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-cnn-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/th_parcel_extraction/CNN.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cnn-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.1: Architecture of a traditional CNN for image classification. This example illustrates how an input image is processed through multiple convolutional blocks to extract features, which are then passed through fully connected layers to generate classification predictions.
</figcaption></figure>
</div>
</div>
</div>
<p>More recently, architectures based on the attention mechanism <span class="citation" data-cites="Vaswani2017"><a href="#ref-Vaswani2017" role="doc-biblioref">[21]</a></span>, originally proposed for natural language processing, were adapted for visual pattern recognition <span class="citation" data-cites="Dosovitskiy2020"><a href="#ref-Liu2021" role="doc-biblioref">[23]</a></span>. These Vision Transformers (ViTs) emerged as alternatives to CNNs by focusing on global relationships within an image. Introduced in 2020, Vision Transformers (ViTs) gained prominence in visual pattern recognition by exploring a global view of images rather than relying solely on the local receptive fields, as is done in convolutional operations. ViTs capture long-range dependencies and contextual information more effectively. Today, CNNs and ViTs are state-of-the-art architectures in computer vision, with their optimal application depending on the specific problem and dataset characteristics. Recent adaptations have also successfully brought ViTs to remote sensing pattern recognition tasks, demonstrating their potential for analyzing satellite imagery <span class="citation" data-cites="Tarasiou2023"><a href="#ref-Tarasiou2023" role="doc-biblioref">[24]</a></span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-vit-ibge" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-vit-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/th_parcel_extraction/ViT.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-vit-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.2: Architecture of a ViT (Vision Transformer) for image classification. The image is initially divided into a sequence of patches, which are then linearly projected and combined with positional embeddings. These tokens are fed into a Transformer Encoder, and the resulting representation for a special class token is used to derive a classification prediction.
</figcaption></figure>
</div>
</div>
</div>
<p>For segmentation applications of imagery for parcels delineation, several architectures are relevant, each offering unique advantages:</p>
<ol type="1">
<li>Fully Convolutional Networks (FCNs): These networks replace fully connected layers of traditional CNNs with convolutional layers, enabling end-to-end training and outputting dense pixel-level predictions directly <span class="citation" data-cites="Long2015"><a href="#ref-Long2015" role="doc-biblioref">[18]</a></span>. A key advantage of FCNs is their inherent ability to use pretrained CNNs (often from image classification tasks) as a base. FCNs enable knowledge transfer from sparse labeling tasks (e.g., object/scene classification) to dense labeling tasks (e.g., semantic segmentation) <span class="citation" data-cites="Long2015"><a href="#ref-Long2015" role="doc-biblioref">[18]</a></span>. FCNs utilize skip connections to merge high-level semantic information (from deeper layers) with high-resolution spatial details (from shallower layers), leading to more accurate and finely-detailed segmentation boundaries. This architecture ensures that both context and precise localization are considered.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-fcn-ibge" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-fcn-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/th_parcel_extraction/CNN_FCN.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fcn-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.3: Process of adapting a CNN to an FCN with or without transfer learning. Dense layers (fully connected) are replaced by one or more convolutional layers capable of producing a prediction map for multiple classes, thereby transforming a classification network into a segmentation network.
</figcaption></figure>
</div>
</div>
</div>
<ol start="2" type="1">
<li>Encoder-Decoder Architectures: These architectures, including UNet <span class="citation" data-cites="Ronneberger2015"><a href="#ref-Ronneberger2015" role="doc-biblioref">[19]</a></span> and SegNet <span class="citation" data-cites="Badrinarayanan2017"><a href="#ref-Badrinarayanan2017" role="doc-biblioref">[25]</a></span> extend the FCN concept with a more structured approach, composed of two distinct sub-modules: an Encoder and a Decoder. The Encoder progressively reduces spatial resolution while simultaneously encoding rich visual information into a large number of feature channels, capturing abstract semantic context. The Decoder then performs the inverse process, recovering spatial resolution and reducing channel resolution to reconstruct the segmentation map. Decoders, often composed of learnable transposed convolution layers, are highly effective at recovering original spatial resolution, frequently leading to higher quality segmentation of detailed objects compared to equivalent FCNs <span class="citation" data-cites="Ronneberger2015"><a href="#ref-Badrinarayanan2017" role="doc-biblioref">[25]</a></span>. Encoder-Decoder architectures commonly integrate skip connections at various points of their symmetric layers, directly connecting features from the encoder to corresponding layers in the decoder. This fosters the fusion of Global, high-level semantic information is combined with local, high-resolution spatial information. As result, encoder-decoder architectures can segment complex objects with intricate boundaries.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-encoder-ibge" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-encoder-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/th_parcel_extraction/Encoder_Decoder.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-encoder-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.4: Encoder-Decoder architecture for image segmentation. The Encoder path extracts features while reducing resolution, and the Decoder path reconstructs the segmentation map, often using skip connections to pass high-resolution details from the encoder to the decoder.
</figcaption></figure>
</div>
</div>
</div>
<ol start="3" type="1">
<li>High-Resolution Network (HRNet): This architecture has proven particularly suitable for field parcel segmentation in extensive exploratory experiments, consistently outperforming other semantic segmentation architectures <span class="citation" data-cites="Wang2020"><a href="#ref-Wang2020" role="doc-biblioref">[26]</a></span>. Its superior performance stems from three main advantages that are critically important for precise boundary delineation:</li>
</ol>
<ul>
<li><p>HRNet preserves high spatial information throughout the entire network rather than reducing it to a low-resolution bottleneck, which is a common characteristic of many other architectures. This design choice is useful for segmenting objects with fine details, such as narrow field boundaries, as it avoids the loss of crucial pixel-level information.</p></li>
<li><p>HRNet operates continuously in a multi-scale mode, simultaneously processing features at different resolutions. This inherent multi-scale processing forces the model to learn both global contextual characteristics and local fine-grained details simultaneously, leading to more comprehensive and accurate feature representations.</p></li>
<li><p>More modern versions of HRNet incorporate attention mechanisms. These mechanisms integrate global context with the local convolutions of the original architecture. By allowing the network to selectively focus on relevant parts of the image and aggregate information from distant pixels, attention further enhances the model’s ability to delineate complex field boundaries accurately, even in challenging environments.</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-hrnet-ibge" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-hrnet-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/th_parcel_extraction/HRNet.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hrnet-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.5: Simplified view of (a) a traditional image segmentation architecture containing a spatial bottleneck, where information is compressed and then expanded, and (b) the High-Resolution Network (HRNet) architecture, which maintains high-resolution representations throughout the network. Source: <span class="citation" data-cites="Wang2020"><a href="#ref-Wang2020" role="doc-biblioref">[26]</a></span>.
</figcaption></figure>
</div>
</div>
</div>
</section><section id="learning-strategies-leveraging-self-supervised-learning" class="level3" data-number="14.2.2"><h3 data-number="14.2.2" class="anchored" data-anchor-id="learning-strategies-leveraging-self-supervised-learning">
<span class="header-section-number">14.2.2</span> Learning Strategies: Leveraging Self-Supervised Learning</h3>
<p>While neural networks are powerful for visual recognition, their inherent reliance on large quantities of accurately labeled data presents a significant limitation <span class="citation" data-cites="Jing2020"><a href="#ref-Awais2023" role="doc-biblioref">[13]</a></span>. This constraint is particularly pertinent in remote sensing applications where manual annotation of vast geographical areas is expensive and time-consuming, and often infeasible for national-scale mapping. To address this, Representation learning strategies such as self-supervised learning (SSL) address this problem. SSL methods enable models to learn rich, meaningful representations from large volumes of readily available unlabeled data <span class="citation" data-cites="Jing2020"><a href="#ref-wang2022self" role="doc-biblioref">[28]</a></span>. This reduces the bottleneck of human annotation, opening up possibilities for leveraging massive archives of satellite imagery.</p>
<p>SSL pretrains neural networks using pretext tasks that can be derived directly and procedurally from the unlabeled data itself, without requiring explicit human labels <span class="citation" data-cites="Jing2020"><a href="#ref-Pathak2016" role="doc-biblioref">[31]</a></span>. Instead of directly learning a mapping from input data to human-annotated labels (a process that would demand extensive supervised datasets), an SSL model is initially pretrained to solve these pretext tasks. A model might be trained to predict the angle of rotation applied to an image, to reorder shuffled image patches, or to reconstruct degraded areas of an image. The model learns by generating a representation of the transformed image, which is then fed into a prediction head to produce a pseudo-label for the pretext task. A self-supervised loss function measures the discrepancy between the predicted pseudo-label and the true pseudo-label (derived procedurally from the transformation), guiding the pretraining process and forcing the model to learn semantically meaningful features <span class="citation" data-cites="Jing2020"><a href="#ref-Wang2021" role="doc-biblioref">[36]</a></span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-ssl-ibge" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-ssl-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/th_parcel_extraction/ssl_task.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ssl-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.6: Pipeline of a Self-Supervised Learning (SSL) model. The backbone is pretrained on a pretext task derived from unlabeled data, and then fine-tuned on a downstream target task with a small amount of labeled data.
</figcaption></figure>
</div>
</div>
</div>
<p>Within the realm of SSL, two major families exist: contrastive and non-contrastive similarity-based methods <span class="citation" data-cites="Chen2020"><a href="#ref-Bardes2022" role="doc-biblioref">[35]</a></span>. Contrastive methods typically approximate representations of different transformed views (augmented versions) of the same image as positive pairs, while simultaneously distancing them from views of other images in the same training batch (negative pairs) [<span class="citation" data-cites="Chen2020"><a href="#ref-Chen2020" role="doc-biblioref">[37]</a></span>, <span class="citation" data-cites="He2020"><a href="#ref-He2020" role="doc-biblioref">[38]</a></span>, <span class="citation" data-cites="Caron2020"><a href="#ref-Caron2020" role="doc-biblioref">[32]</a></span>}. This process encourages the backbone to generate representations with better discriminatory power between views of the same image (invariance) and views of different images (separability). The effect of this contrastive loss in the feature space is to simplify the separation surface between positive and negative pairs, leading to well-distributed and discriminative embeddings. Contrastive approaches are computationally expensive due to large batch sizes to ensure a sufficient number of negative pairs; they may sometimes artificially separate samples belonging to the same semantic class if they are too dissimilar in appearance <span class="citation" data-cites="wu2018unsupervised"><a href="#ref-Harwood2017" role="doc-biblioref">[40]</a></span>.</p>
<p>Non-contrastive SSL methods eliminate the need for negative pairs, making them less demanding in terms of GPU memory and generally more stable during training <span class="citation" data-cites="Chen2021"><a href="#ref-Bardes2022" role="doc-biblioref">[35]</a></span>. These methods, however, require additional regularization during training to prevent a trivial collaps where the model simply predicts the same representation for all inputs, resulting in meaningless features. Various regularization techniques have been proposed to mitigate this collapse, including bootstrapping latent representations, introducing asymmetry in Siamese network architectures, applying stop-gradient operations, and incorporating variance regularization <span class="citation" data-cites="Grill2020"><a href="#ref-Zbontar2021" role="doc-biblioref">[41]</a></span>. The absence of negative pairs not only reduces memory requirements but also makes these methods less sensitive to the specific choice of data augmentations.</p>
<p>For tasks requiring dense labeling, like image segmentation, specific modifications to general SSL strategies have emerged. While early SSL pretrainings were often optimized for image classification, more recent methods aim to improve performance for segmentation and detection tasks. This has led to the development of methods that focus on learning local representations by encouraging proximity in the internal embedding space between different views (augmentations) of images, recognizing that pixel-level consistency is crucial for dense prediction tasks <span class="citation" data-cites="Caron2020"><a href="#ref-Wang2021" role="doc-biblioref">[36]</a></span>.</p>
<p>Wang et al <span class="citation" data-cites="Wang2021"><a href="#ref-Wang2021" role="doc-biblioref">[36]</a></span> proposed a multi-view self-supervised approach to delineate field boundaries. This method learns local representations by integrating concepts from advanced non-contrastive SSL techniques, particularly adapted for image segmentation, being more conceptually related to DenseCL <span class="citation" data-cites="Wang2021"><a href="#ref-Wang2021" role="doc-biblioref">[36]</a></span>. Inspired by successful prior work, this approach has been empirically shown to significantly stabilize and regularize the training process, enhancing the model’s ability to learn robust features.</p>
<p>After this extensive self-supervised pretraining phase, the encoder component of the model, now equipped with semantically rich feature representations, can be fine-tuned using a relatively limited number of human-labeled samples for the specific target segmentation task (e.g., field boundary delineation). This strategy allows for performance levels comparable to fully supervised methods but with significantly less reliance on extensive human annotation, typically requiring only a small percentage (e.g., 1% or 10%) of labeled data <span class="citation" data-cites="Chen2020"><a href="#ref-Chen2020" role="doc-biblioref">[37]</a></span>. Qualitative evaluations demonstrate that representations generated by this self-supervised pretraining exhibit high uniformity within agricultural parcels and across different temporal observations, delineating object boundaries even for elements present in only some timestamps. This indicates the model’s robustness to temporal variability and partial data availability.</p>
<div class="cell" data-layout-nrow="2">
<div id="fig-patches-ibge" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-patches-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-patches-ibge" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-patches-ibge-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-patches-ibge-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/th_parcel_extraction/patch_pastis.png" class="img-fluid figure-img" style="width:60.0%" data-ref-parent="fig-patches-ibge">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-patches-ibge-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Patch of Pastis
</figcaption></figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-patches-ibge" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-patches-ibge-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-patches-ibge-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/th_parcel_extraction/patch_aiboundaries.png" class="img-fluid figure-img" style="width:60.0%" data-ref-parent="fig-patches-ibge">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-patches-ibge-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Patch of AIBoundaries
</figcaption></figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-patches-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.7: Examples of feature channels demonstrating uniformity in object representation for two image patches. Continuous areas, such as agricultural parcels or natural vegetation, are uniformly represented in the learned feature space, reinforcing the quality of the embeddings generated by the self-supervised pretraining and their semantic consistency.
</figcaption></figure>
</div>
</div>
<p>This approach has been shown to significantly improve the Average Recall (AR) of agricultural parcel segmentation, meaning fewer actual agricultural parcels are mistakenly classified as natural vegetation or urban areas, as shown in what follows. While this might lead to a marginal increase in false positives (FPs), these are less problematic for downstream applications and can often be filtered out in subsequent post-processing steps using ancillary information, such as time series of vegetation indices like EVI or NDVI. This makes the strategy robust and practical for large-scale agricultural mapping, where capturing all true parcels (high recall) is often prioritized over perfect precision in initial detection <span class="citation" data-cites="da2025lightweight"><a href="#ref-da2025lightweight" role="doc-biblioref">[42]</a></span>.</p>
</section><section id="transfer-learning-and-multi-source-training" class="level3" data-number="14.2.3"><h3 data-number="14.2.3" class="anchored" data-anchor-id="transfer-learning-and-multi-source-training">
<span class="header-section-number">14.2.3</span> Transfer Learning and Multi-Source Training</h3>
<p>Neural Networks are notoriously expensive to train, both in terms of cost (e.g., GPU hours) and the indirect temporal cost required for meticulous data annotation <span class="citation" data-cites="niu2021decade"><a href="#ref-niu2021decade" role="doc-biblioref">[8]</a></span>. Transfer learning is a widely adopted strategy in computer vision to mitigate these substantial costs by leveraging knowledge gained from training on related visual tasks <span class="citation" data-cites="niu2021decade"><a href="#ref-Ribani2019" role="doc-biblioref">[43]</a></span>. This typically involves using a pretrained neural network (e.g., a Vision Transformer or CNN) that has already learned general visual features from a very large, generic dataset (e.g., ImageNet <span class="citation" data-cites="Deng2009"><a href="#ref-Deng2009" role="doc-biblioref">[44]</a></span>, Pascal VOC <span class="citation" data-cites="Everingham2010"><a href="#ref-Everingham2010" role="doc-biblioref">[45]</a></span>, MS COCO <span class="citation" data-cites="Lin2014"><a href="#ref-Lin2014" role="doc-biblioref">[46]</a></span>) and then fine-tuning it with a smaller set of labeled samples from a new, target visual domain. Alternatively, the weights of the pretrained network can be used as a visual feature extractor combined with a simpler classifier (such as a Support Vector Machine <span class="citation" data-cites="Cortes1995"><a href="#ref-Cortes1995" role="doc-biblioref">[47]</a></span> or Random Forest <span class="citation" data-cites="Breiman2001"><a href="#ref-Breiman2001" role="doc-biblioref">[48]</a></span>).</p>
<p>While effective in many contexts, supervised pretraining followed by fine-tuning often proves problematic and incompatible with remote sensing images <span class="citation" data-cites="Ribani2019"><a href="#ref-Ribani2019" role="doc-biblioref">[43]</a></span>. The number of input channels for a neural network is typically an immutable architectural decision, meaning a network designed to receive only 3-channel RGB images cannot be easily adapted for multispectral images like those from Sentinel-2, which can have 10 or more spectral bands. Even when using only the RGB channels of a multispectral satellite image, the inherent characteristics of natural images (e.g., acquired by smartphones or consumer cameras, which often contain specific object distributions and lighting conditions) fundamentally differ from those of remote sensing images (e.g., top-down view, large-scale geographical features, diverse atmospheric conditions). This discrepancy in visual characteristics between source and target domains can lead to poor transfer learning performance, a phenomenon known as negative transfer, where the pretrained knowledge actually hinders performance on the new task <span class="citation" data-cites="Ribani2019"><a href="#ref-Ribani2019" role="doc-biblioref">[43]</a></span>.</p>
<p>In remote sensing, transfer learning usually relies on source datasets with publicly available labeled data from tasks that are inherently related to the target task and originate from the remote sensing domain itself. Supervised pretaining uses labeled data from remote sensing data rather than natural images, aiming to transfer the acquired knowledge to agricultural areas within the national territory. Candidate source datasets for this purpose include previously mentioned public datasets such as AI4Boundaries <span class="citation" data-cites="Andrimont2023"><a href="#ref-Andrimont2023" role="doc-biblioref">[2]</a></span>, PASTIS <span class="citation" data-cites="Garnot2021"><a href="#ref-Garnot2021" role="doc-biblioref">[3]</a></span>, LEM <span class="citation" data-cites="oldoni2020lem"><a href="#ref-oldoni2020lem" role="doc-biblioref">[49]</a></span>, and Campo Verde <span class="citation" data-cites="Sanches2018a"><a href="#ref-Sanches2018a" role="doc-biblioref">[50]</a></span>. These datasets, by virtue of originating from satellite imagery and focusing on agricultural or land cover tasks, provide a more suitable source domain for effective transfer learning.</p>
</section><section id="evaluation-metrics" class="level3" data-number="14.2.4"><h3 data-number="14.2.4" class="anchored" data-anchor-id="evaluation-metrics">
<span class="header-section-number">14.2.4</span> Evaluation Metrics</h3>
<p>Our experiments suggest that instead of following a sequential transfer learning paradigm (pretrain on source, then fine-tune on target), directly aggregating all available and relevant datasets into a single, comprehensive training set can yield superior segmentations. This multi-source supervised learning approach has demonstrated improved performance not only on data similar to the training domains but also on out-of-distribution data from geographically distinct regions. By exposing the model to a wider variety of landscapes, agricultural practices, and environmental conditions during its primary training phase, it develops more robust and generalizable features. This approach effectively minimizes the domain shift problem, making the trained model more resilient and applicable across diverse agricultural landscapes without the need for extensive, per-region fine-tuning, thereby streamlining the deployment process for national-scale mapping.</p>
<p>To assess the quality and performance of the segmentation models, we employ a range of quantitative metrics, broadly categorized into pixel-level and instance-level metrics. These metrics provide insights into a model’s strengths and weaknesses. Instance-level metrics are particularly informative and often prioritized for the context of field boundary delineation, as they analyze individual agricultural parcels, verifying if neighboring parcels are correctly separated and providing insights into over- or under-segmentation compared to human perception <span class="citation" data-cites="persello2009novel"><a href="#ref-persello2009novel" role="doc-biblioref">[51]</a></span>.</p>
<p>Pixel-Level metrics metrics provide a global assessment of classification accuracy at the pixel level and include the following approaches:</p>
<ul>
<li><p>Accuracy: This is the simplest metric, measuring the proportion of correctly classified pixels (both background and parcel interior) out of the total number of pixels in the image. While intuitive, it can be misleading in cases of highly imbalanced classes.</p></li>
<li><p>Jaccard Index (Intersection over Union - IoU): IoU quantifies the overlap between the predicted segmentation map and the ground truth map. It is a more robust metric for segmentation. There are two options to calculate it:</p></li>
<li><p>Jaccard-Weighted: A weighted average of the Jaccard index calculated for each class, where the weight is typically proportional to the number of pixels in that class. This provides a balanced measure that accounts for class imbalance.</p></li>
<li><p>Jaccard-Binary: The Jaccard index specifically computed for the binary classification task (parcel vs.&nbsp;background). It directly measures the ratio of the intersection area to the union area between the predicted and ground truth masks for the parcel class.</p></li>
<li><p>Area Under the Receiver Operating Characteristic Curve (AUC): The received-operating curve plots the true positive rate against the false positive rate at various threshold settings. The AUC measures the model’s overall ability to distinguish between classes, with higher values indicating better discriminatory power.</p></li>
</ul>
<p>While pixel-level metrics serve as proxies for segmentation performance and are useful for rapid iteration, they have a limited utility in distinguishing subtle model differences, especially regarding individual object integrity. They do not directly assess how well individual instances (parcels) are delimited. Instance-level metrics provide a more granular understanding of how well individual parcels are delineated, their shape, and their separation from neighboring objects. They are often more aligned with human perception of segmentation quality for discrete objects like agricultural fields. These metrics include:</p>
<ul>
<li><p>Global Over-Segmentation Score (GOS): GOS measures the general overlap between real (ground truth) and predicted instances. It evaluates how consistently segmented objects are represented, with higher GOS values generally suggesting more correct detections of object boundaries. It reflects how well the model avoids splitting a single true object into multiple predicted segments <span class="citation" data-cites="persello2009novel"><a href="#ref-persello2009novel" role="doc-biblioref">[51]</a></span>.</p></li>
<li><p>Global Under-Segmentation Score (GUS): GUS measures the occurrence of under-segmentation, indicating instances where multiple real parcels are erroneously grouped into a single predicted segment. A lower GUS is highly desirable, as it implies the model is effective at separating distinct fields <span class="citation" data-cites="persello2009novel"><a href="#ref-persello2009novel" role="doc-biblioref">[51]</a></span>.</p></li>
<li><p>Global Total Segmentation (GTS): GTS quantifies the mean squared error calculated using the GOS and GUS errors. The mean of the sum of squared errors can be interpreted as a balanced measure of performance, accounting for both over- and under-segmentation cases. A lower GTS indicates a better balance between these two types of errors, signifying more accurate overall segmentation <span class="citation" data-cites="persello2009novel"><a href="#ref-persello2009novel" role="doc-biblioref">[51]</a></span>.</p></li>
<li><p>Fragmentation Global Total (FGT): FGT quantifies the total error caused by the over-segmentation of instances. This metric is correlated with GOS but takes into consideration the quantity of instances that have a non-empty intersection with the reference instance. A lower FGT is preferable, indicating fewer unnecessary subdivisions of true parcels <span class="citation" data-cites="persello2009novel"><a href="#ref-persello2009novel" role="doc-biblioref">[51]</a></span>.</p></li>
<li><p>Average Precision (AP): AP is a common and robust metric widely used in object detection and instance segmentation benchmarks. It measures the precision of detections across various recall levels, providing a single summary of the precision-recall curve. Higher AP indicates better overall performance in correctly identifying, localizing, and classifying instances.</p></li>
<li><p>Average Recall (AR): AR measures the model’s ability to retrieve all relevant instances across different Intersection over Union (IoU) thresholds. A higher AR means fewer true parcels are missed by the model, which is crucial for comprehensive mapping.</p></li>
</ul>
<p>For field boundary delineation, false positives (e.g., misclassifying a non-field area as a field boundary, or a small over-segmentation) are less critical for agricultural statistics than false negatives (e.g., missing an actual agricultural field, leading to an undercount). Correcting false negatives is challenging and costly to address in post-processing or subsequent analyses. In this case, the Average Recall (AR) measure is the more informative of instance-level metrics. Models that incorporate advanced representation learning, particularly self-supervised methods, show notable improvements in AR, ensuring that fewer agricultural parcels are erroneously unrecognized.</p>
</section></section><section id="methods" class="level2" data-number="14.3"><h2 data-number="14.3" class="anchored" data-anchor-id="methods">
<span class="header-section-number">14.3</span> Methods</h2>
<p>The development of an automated system for field boundary delineation necessitates a well-defined methodology, encompassing problem modeling, strategic data acquisition and preprocessing, selection of appropriate model architectures, and advanced learning strategies. The primary goal is to achieve accurate and scalable segmentation of agricultural parcels from remote sensing imagery to support national agricultural statistics.</p>
<section id="binary-semantic-segmentation" class="level3" data-number="14.3.1"><h3 data-number="14.3.1" class="anchored" data-anchor-id="binary-semantic-segmentation">
<span class="header-section-number">14.3.1</span> Binary Semantic Segmentation</h3>
<p>Recognizing agricultural parcels is complex, especially when there is a geographical divergence between the regions used for model training and those used for testing or validation. Performing transfer learning across agricultural crops in different global regions is hard. It is challenging for models to generalize across diverse landscapes, climates, and farming practices. Given these complexities, particularly in multiclass segmentation of agricultural crops, we define our task as a binary semantic segmentation problem. The model distinguishes between two classes:</p>
<ol type="1">
<li><p>Class 0: Background – representing regions that do not belong to an agricultural parcel. This includes non-agricultural land cover such as urban areas, forests, water bodies, roads, and uncultivated barren land. The variability within this class can be quite high, ranging from natural landscapes to human-made infrastructures.</p></li>
<li><p>Class 1: Interior of Agricultural Parcel – representing the cultivated area of any crop type. This class aims to capture the core regions where agricultural activities are taking place, regardless of the specific crop planted, growth stage, or agricultural practice.</p></li>
</ol>
<p>This binary simplification is chosen for several reasons. It reduces the complexity of the labeling task, making it more feasible to generate large annotated datasets. It also allows models to generalize across diverse agricultural contexts, as the distinction between <code>field'' and</code>non-field’’ is more consistent than specific crop types. This addresses the challenge that detailed crop type labels may not be easily transferable across diverse geographical contexts or may require more specialized and resource-intensive annotation efforts. By simplifying the problem to binary segmentation, publicly available datasets like PASTIS <span class="citation" data-cites="Garnot2021"><a href="#ref-Garnot2021" role="doc-biblioref">[3]</a></span> and AI4Boundaries <span class="citation" data-cites="Andrimont2023"><a href="#ref-Andrimont2023" role="doc-biblioref">[2]</a></span> can be readily binarized and utilized as source datasets for supervised training, enabling subsequent transfer to target regions where detailed crop-specific labels might be scarce or non-existent. This streamlined approach allows for rapid prototyping and deployment of base models.</p>
<p>For the purpose of binarization, instance IDs of parcels from datasets that provide them (e.g., PASTIS <span class="citation" data-cites="Garnot2021"><a href="#ref-Garnot2021" role="doc-biblioref">[3]</a></span>) are converted to contain only the background class (Class 0) and a unified ``plantation plot’’ class (Class 1) encompassing all crop types. To ensure that neighboring parcels remain distinct, a common challenge in agricultural mapping for fields without clear physical boundaries, a morphological erosion operation is applied to each individual parcel as shown in <a href="#fig-parcels-ibge" class="quarto-xref">Figure&nbsp;<span>14.8</span></a>. This process transforms the narrow boundary regions between adjacent parcels into the background class. This explicit separation aids the model in learning clearer distinctions at parcel edges.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-parcels-ibge" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-parcels-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/th_parcel_extraction/parcel_labels.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-parcels-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.8: Representation of the problem modeling for a patch from the PASTIS dataset. The binary labels section shows the simplification to a binary problem (Background vs.&nbsp;Parcel), where parcel boundaries are converted to background pixels.
</figcaption></figure>
</div>
</div>
</div>
<p>Initial experiments with this binary modeling approach, where margins were encoded as background, faced a challenge: models often merged several distinct agricultural parcels into a single Class 1 area, effectively ignoring the subtle boundaries. This issue persisted regardless of hyperparameter choices or training strategies, including adaptive cost function weighting to address class imbalance. This problem is due to the high variability in the ``Background’’ class and the challenge of identifying narrow field boundaries when they are part of this diverse background. While our method focuses on binary segmentation, real-world implementations might require further refinements to address boundary complexities. Such refinements include multiclass definitions that enable better differentiation of parcel boundaries from general background areas and robust methods to handle highly fragmented landscapes.</p>
</section><section id="data-acquisition-and-imagery-pre-and-post-processing" class="level3" data-number="14.3.2"><h3 data-number="14.3.2" class="anchored" data-anchor-id="data-acquisition-and-imagery-pre-and-post-processing">
<span class="header-section-number">14.3.2</span> Data Acquisition, and Imagery Pre and Post-processing</h3>
<p>Access to satellite imagery across extensive geographical areas is a determining factor for accurate field boundary delineation. To ensure long-term sustainability and avoid dependency on commercial data vendors, we give preference to free, publicly accessible data sources. Our work uses data from Sentinel-1 (Synthetic Aperture Radar) and Sentinel-2 (Multispectral Optical) satellites.</p>
<p>To process large collections of Sentinel-1 and Sentinel-2 images, we use cloud-based platforms. Cloud computing platforms are designed for storing and processing vast satellite datasets, offering scalability for geospatial analysis <span class="citation" data-cites="Gorelick2017"><a href="#ref-Gorelick2017" role="doc-biblioref">[52]</a></span>. User-friendly interfaces provide a convenient environment for interactive data and algorithm development, significantly reducing the computational burden on local machines. Cloud platforms offer image processing capabilities to handle common issues such as cloud cover, atmospheric correction, and radiometric calibration <span class="citation" data-cites="Gorelick2017"><a href="#ref-Gorelick2017" role="doc-biblioref">[52]</a></span>. This integrated environment enables the efficient acquisition of high-quality images covering entire countries, enabling large-scale agricultural monitoring.</p>
<p>The initial phase of data collection involves gathering pre-existing datasets to be used in development and validation tasks. These datasets provide diverse geographical and temporal contexts, enriching the model’s training:</p>
<ol type="1">
<li><p>PASTIS: a globally recognized reference dataset specifically designed for panoptic and semantic segmentation of agricultural parcels derived from satellite time series <span class="citation" data-cites="Garnot2021"><a href="#ref-Garnot2021" role="doc-biblioref">[3]</a></span>. It includes a significant number of samples within a specific metropolitan territory (e.g., French metropolitan territory), complete with panoptic annotations (instance index + semantic label for each pixel). Each sample is a variable-length time series of Sentinel-2 multispectral images, offering rich temporal dynamics for crop analysis.</p></li>
<li><p>AI4Boundaries: a publicly available dataset created to improve the detection of agricultural field boundaries using deep learning <span class="citation" data-cites="Andrimont2023"><a href="#ref-Andrimont2023" role="doc-biblioref">[2]</a></span>. It tackles a major gap in the field by offering standardized images and labels for training and benchmarking models. The dataset includes two types of imagery — 10 m Sentinel-2 satellite composites and 1 m aerial orthophotos — combined with ground-truth data from seven European countries. These represent over 14.8 million field parcels, covering varied landscapes. With over 7,800 image samples and accompanying vector and raster labels, AI4Boundaries helps advance precision agriculture and supports applications like land monitoring and food security analysis.</p></li>
</ol>
<p>Additionally, large-scale annual mosaics covering entire states, encompassing hundreds of municipalities and hundreds of gigabytes of image data, can be acquired (e.g., for Goiás state, totaling 246 municipalities and 210GB of data). Given the wide variety of applications related to agricultural statistics, other datasets may be incorporated as algorithms evolve and adaptation needs arise.</p>
<p>The data acquisition and preparation process follows a three-step workflow to ensure data quality and organization:</p>
<ol type="1">
<li><p>Mosaic generation: This stage involves precise configurations to define the delimitations of municipalities, often utilizing the official municipal boundaries provided by national geographic institutes. It also includes the selection of specific spectral bands of interest from the Sentinel constellation (e.g., COPERNICUS/S1 GRD and COPERNICUS/S2 collections) and performing necessary pre-processing to minimize the presence of clouds in the final image mosaics. For each municipality, mosaics are extracted for specific temporal intervals (e.g., semi-annual mosaics corresponding to different agricultural seasons), enabling analysis of seasonal variations in agricultural activity. Such processing is done in cloud providers, allowing experts to focus on configuration and quality control for the final mosaic generation.</p></li>
<li><p>Post-processing: Due to file size limitations imposed by servers infrastructure, the mosaics obtained from the provider are fragmented into multiple smaller files. This critical step aggregates these fragments into a single, unified, and ready-to-use raster file for each municipality. In addition, to aid human annotators and visual inspection, we extract separate rasters with different band selections and derived spectral indices. Prominent subsets extracted for visual analysis include those calculated by the indexes shown below.</p></li>
</ol>
<ul>
<li>BSI (Builtup Area Index): (Red + SWIR) / (NIR + Blue)</li>
<li>NDWI (Normalized Difference Water Index): (Green - NIR) / (Green + NIR)</li>
<li>NDVI (Normalized Difference Vegetation Index): (NIR - Red) / (NIR + Red)</li>
<li>NDSI (Normalized Difference Snow Index): (Green - SWIR) / (Green + SWIR)</li>
<li>RGB (Red, Green, Blue): visible colour composite</li>
</ul>
<ol start="3" type="1">
<li>Highlighting Annotation Areas: For efficient and collaborative manual annotation as shown in <a href="#fig-qgis-ibge" class="quarto-xref">Figure&nbsp;<span>14.9</span></a>, large municipalities are systematically divided into smaller, manageable sub-regions (e.g., each with a maximum area of 1000 km<span class="math inline">\(^2\)</span>). This modular division facilitates the distribution of annotation tasks and ensures that no single annotator is overwhelmed by excessively large areas. This approach is beneficial in vast regions of significant economic impact, where precise annotation is critical.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-qgis-ibge" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-qgis-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/th_parcel_extraction/qgis-labelling.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-qgis-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.9: Example of the manual labeling process for one plot.
</figcaption></figure>
</div>
</div>
</div>
<p>At the end of these steps, we produce an output for each municipality of interest containing multiple raster files per temporal mosaic (e.g., 12 files for two temporal mosaics, representing two different seasons, plus 1 additional file related to the division of annotation areas), ready for consumption by annotators and machine learning models.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-qgis2-ibge" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-qgis2-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/th_parcel_extraction/qgis-total-labelling.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-qgis2-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.10: Example of annotation region division for a municipality, demonstrating how large areas are segmented into smaller, manageable units to facilitate collaborative manual annotation.
</figcaption></figure>
</div>
</div>
</div>
<p>For model input, we use three Sentinel-2 derived datasets representing different spectral and temporal characteristics:</p>
<ol type="1">
<li><p>RGB: This input consists of a composition of the Blue, Green, and Red bands, which represent the visible spectrum. These data have a spatial resolution of 10 meters per pixel, providing a straightforward visual representation of the Earth’s surface.</p></li>
<li><p>NIR: This input consists of a simple Near Infra-red band. For Sentinel-2 images have a spatial resolution of 10 meters per pixel.</p></li>
<li><p>Harmonic: This is a more complex input derived from a time series of images. It involves computing the NDVI from the time series and then creating a harmonic model to extract values such as phase and amplitude. These harmonic values, combined with the mean NDVI over the period, are organized into an HSV (Hue, Saturation, Value) space. This approach captures temporal patterns of vegetation growth, which are highly indicative of agricultural activity.</p></li>
</ol>
<p>Temporal series considerations for these inputs are crucial for capturing seasonal variations in agriculture. For instance, RGB data might utilize a specific range (e.g., March to August 2023) to capture a particular growing season, while Harmonic data might consider a broader time span (e.g., January 2022 to March 2024) to capture complete annual cycles and long-term phenological trends.</p>
<p>After model inference, we transform raster outputs (pixel-based predictions) into vector formats (polygon-based representations), which are more suitable for geospatial analysis and database integration. Subsequent filtering steps are then applied to refine these polygons. This includes removing outliers, such as small polygons whose areas are either smaller or larger than twice the standard deviation of other instances; these polygons are often artifacts of the vectorisation process, especially at municipality borders. Overlapping instances are then dissolved to avoid the creation of redundant or multi-part polygons. We remove polygons smaller than a predefined area (e.g., 2000 m<span class="math inline">\(^2\)</span>, equivalent to 20 pixels at Sentinel-2 resolution), as they often represent noise or insignificant features. Topological simplification, using algorithms like Douglas-Peucker, is then applied to each resulting instance to reduce the number of vertices and optimize the output vector file size, making the data more manageable for storage and analysis. The result is a consolidated, clean vector file for the entire region, ready for use in agricultural information systems.</p>
</section><section id="manual-annotation-of-field-plots" class="level3" data-number="14.3.3"><h3 data-number="14.3.3" class="anchored" data-anchor-id="manual-annotation-of-field-plots">
<span class="header-section-number">14.3.3</span> Manual Annotation of Field Plots</h3>
<p>The task of manually annotating field plots is essential for improving the performance of the tested models. Incorporating Brazilian annotations—alongside the public datasets led to an IoU (Jaccard index) gain of over 0.2. The creation of a national dataset, representing all Brazilian regions and encompassing plots with varied sizes, shapes, land uses, and management practices across diverse landscapes, significantly enhanced model accuracy. This quality improvement was directly related to the volume and pace of newly added annotations.</p>
<p>As detailed in the Results section, initial testing was conducted using Sentinel-2 imagery with approximately 450,000 manually annotated plots. We have reached approximately 1,150,000 annotated plots (<a href="#fig-brazil-ibge" class="quarto-xref">Figure&nbsp;<span>14.11</span></a>) and have begun testing with PlanetScope imagery, which offers a spatial resolution of 5 meters. Preliminary results suggest that smaller plots are now being delineated more effectively, enabling reliable data acquisition even for plots smaller than 1 hectare.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-brazil-ibge" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-brazil-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/th_parcel_extraction/Brazil.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-brazil-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.11: Label distribution throughout Brazilian territory (in yellow).
</figcaption></figure>
</div>
</div>
</div>
</section><section id="effort-cost-and-workforce-dynamics" class="level3" data-number="14.3.4"><h3 data-number="14.3.4" class="anchored" data-anchor-id="effort-cost-and-workforce-dynamics">
<span class="header-section-number">14.3.4</span> Effort, Cost, and Workforce Dynamics</h3>
<p>A critical factor to consider is the cost and labor required to carry out this task. In regions with regular polygon shapes, the annotation process proceeds more efficiently, with individual annotators achieving over 300 annotations daily. However, in areas with irregular polygons—such as floodplains, mountainous terrain, or smallholder properties—this rate drops to approximately 100 polygons per day. Thus, the annotation pace varies significantly depending on the mapped region. Annotating over 1.15 million plots required a dedicated team of 35 to 40 professionals working over a span of 11 months.</p>
<p>The annotation work relied on a infrastructure integrating GeoServer with a relational database and QGIS. The annotation team primarily consisted of professionals with a high school education, trained and supported by experts from various domains. The support staff included agronomists, IT specialists, and professionals in geoprocessing and cartography. Each annotator operated through secure network credentials and was authenticated to work remotely across more than 30 cities in Brazil—covering nearly all federative units. Local knowledge was recognized as a key advantage in ensuring annotation quality, alongside the strategic involvement of regional IBGE offices. This decentralized approach highlights the importance and relevance of mapping efforts for agricultural statistical production.</p>
<p>Given the institutional significance and high demands of this undertaking, active engagement and prioritization by participating institutions were crucial. Only through such coordinated effort was it possible to reach the volume of annotations necessary for the models to achieve the required level of accuracy to support targeted statistical operations.</p>
</section></section><section id="results" class="level2" data-number="14.4"><h2 data-number="14.4" class="anchored" data-anchor-id="results">
<span class="header-section-number">14.4</span> Results</h2>
<section id="practical-aspects-of-implementation" class="level3" data-number="14.4.1"><h3 data-number="14.4.1" class="anchored" data-anchor-id="practical-aspects-of-implementation">
<span class="header-section-number">14.4.1</span> Practical Aspects of Implementation</h3>
<p>The successful implementation of automated field boundary delineation on a large scale requires careful consideration of practical aspects, ranging from computational infrastructure to data annotation and model fine-tuning.</p>
</section><section id="computational-infrastructure" class="level3" data-number="14.4.2"><h3 data-number="14.4.2" class="anchored" data-anchor-id="computational-infrastructure">
<span class="header-section-number">14.4.2</span> Computational Infrastructure</h3>
<p>A robust and scalable infrastructure is absolutely essential for the efficient collection, processing, and storage of the massive volumes of geospatial data inherent in large-scale agricultural mapping projects. For centralized archiving and long-term retention of large volumes of processed data, Network-Attached Storage (NAS) systems play a crucial role. NAS systems need scalable capacity to accommodate the continuous growth of geospatial databases. In the long term, integrating more expansive and resilient cloud storage solutions is advisable. This ensures efficient and durable data persistence, eliminates the need for physical NAS hardware maintenance, and potentially reduces significant costs associated with large data volumes and on-premise infrastructure upkeep. To streamline data movement and reduce manual intervention, automated scripts are vital for seamless data synchronization, optimizing the overall workflow and minimizing the risk of human error.</p>
<p>For the intensive task of model training, significant computational power is a prerequisite. A capable consumer-grade setup might include an Intel Core i7-5930K CPU, an Nvidia Titan XP with 12GB VRAM, and 64GB of RAM. While such a setup can be functional, it is modest compared to modern, purpose-built deep learning configurations. Even with such hardware, models like the YOLOv11 <span class="citation" data-cites="yolo11_ultralytics"><a href="#ref-yolo11_ultralytics" role="doc-biblioref">[53]</a></span> (utilized in related work for object detection and segmentation tasks) can balance performance speed and prediction efficacy. For large-scale and high-throughput training, more powerful, professional-grade GPUs are necessary. Examples include the NVIDIA RTX 4090 (24 GB VRAM, 16384 CUDA cores) or, more optimally, an NVIDIA DGX A100 (80GB VRAM). The DGX A100, in particular, offers superior performance, accelerating both training and inference processes and enabling scaling for larger and more complex experiments.</p>
<p>To further optimize training efficiency and make the most of available hardware, advanced software strategies are employed. For instance, Automatic Mixed Precision (AMP) in PyTorch is used to save GPU memory by employing 16-bit floats (fp16) for weights, tensors, and gradients whenever possible, instead of the standard 32-bit floats (fp32). This strategy not only improves memory efficiency (allowing for larger batch sizes) but also leverages the fact that modern GPUs are highly optimized to perform matrix/tensorial operations on fp16 data, achieving higher Floating Point Operations Per Second (FLOPs) than the same operations in fp32.</p>
</section><section id="training-times" class="level3" data-number="14.4.3"><h3 data-number="14.4.3" class="anchored" data-anchor-id="training-times">
<span class="header-section-number">14.4.3</span> Training Times</h3>
<p>The duration of model training varies significantly depending on the model architecture, the size and complexity of the dataset, and the computational resources available. Supervised HRNet models, designed for direct supervised learning, tend to be comparatively lighter in terms of computational requirements than certain self-supervised counterparts. When trained across multiple public and private datasets (e.g., AI4Boundaries <span class="citation" data-cites="Andrimont2023"><a href="#ref-Andrimont2023" role="doc-biblioref">[2]</a></span>, PASTIS <span class="citation" data-cites="Garnot2021"><a href="#ref-Garnot2021" role="doc-biblioref">[3]</a></span>, and labeled data from 24 cities), the entire dataset, along with its quaternary masks, can be stored in approximately 40 GB of memory, pre-loaded to avoid disk access bottlenecks during training. Each training iteration with a batch size of 18 typically takes about 0.4 seconds. Consequently, a comprehensive training routine spanning 600 epochs for a supervised HRNet model can be completed in approximately 17 hours.</p>
<p>For self-supervised models, early iterations initially proved to be more computationally intensive, primarily due to inefficient pixel sampling strategies during pretraining. An iteration using a batch size of 10 could take around 1.5 seconds. This resulted in a longer pretraining duration, with approximately 39 hours required for 300 epochs. A critical optimization in the pixel sampling was transitioning from random point selection to a more efficient grid-based sampling approach within the self-supervised method. This approach reduced the computational cost of pretraining. With this improvement, each pretraining iteration for a batch size of 10 dropped to approximately 0.7 seconds. This optimization reduced the total pretraining time to around 18 hours for 300 epochs, making the self-supervised approach considerably more practical for large-scale applications.</p>
<p>The fine-tuning process, which adapts the pretrained models to specific downstream tasks using a smaller labeled dataset, incurs similar computational costs per iteration to supervised training. This means the fine-tuning phase is relatively quick compared to the initial self-supervised pretraining, capitalizing on the learned representations.</p>
</section><section id="inference-times" class="level3" data-number="14.4.4"><h3 data-number="14.4.4" class="anchored" data-anchor-id="inference-times">
<span class="header-section-number">14.4.4</span> Inference Times</h3>
<p>The computational cost of model inference (the forward pass of the model to generate predictions) remains the same once the model is trained. For large-scale inference, such as covering an entire state or national territory, the area is systematically divided into smaller, overlapping patches (e.g., 768x768 pixels with 50% overlap) that can fit into GPU memory. An erosion operation (e.g., using a 4x4 kernel) is applied per instance prediction to mitigate detection overlaps, especially near parcel borders.</p>
<p>The total inference time exhibits a near-linear relationship with the territorial extension of the area being processed, implying that doubling the area roughly doubles the processing time. For instance, on a high-end consumer GPU like an NVIDIA RTX 4090, processing smaller regions like Sergipe (approx. 22,000 km<span class="math inline">\(^2\)</span>) takes about 2.39 hours. Scaling up, the inference for the entire national territory (approx. 8.5 million km<span class="math inline">\(^2\)</span>) is estimated to take around 925.88 hours, or approximately 38.58 days. On a more powerful, professional-grade GPU such as an NVIDIA DGX A100, these times are significantly reduced due to superior processing capabilities; Sergipe would take about 0.45 hours, and the entire national territory could be processed in approximately 172.90 hours, or about 7.20 days. This difference highlights the importance of selecting appropriate hardware for large-scale production deployments.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-4090-ibge" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-4090-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/th_parcel_extraction/inference_time_plot_4090.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-4090-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.12: HRNet inference times for 24 cities, using an NVIDIA RTX 4090. The x-axis represents city size in km<span class="math inline">\(^2\)</span>, and the y-axis shows total inference times in seconds. The black line represents the best linear fit for this relationship, demonstrating the scalability of inference with area.
</figcaption></figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-A100-ibge" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-A100-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/th_parcel_extraction/inference_time_plot_A100.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-A100-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.13: HRNet inference times for 24 cities, using an NVIDIA DGX A100. The graph illustrates the significantly reduced processing times compared to the RTX 4090, emphasizing the benefits of professional-grade hardware for large-scale operations.
</figcaption></figure>
</div>
</div>
</div>
<div id="tbl-4090" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-4090-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;14.1: Execution time estimates for large-scale inferences across different territorial extensions using an RTX 4090 GPU
</figcaption><div aria-describedby="tbl-4090-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 24%">
<col style="width: 21%">
<col style="width: 26%">
</colgroup>
<thead><tr class="header">
<th>Region</th>
<th style="text-align: center;">Area (km<span class="math inline">\(^2\)</span>)</th>
<th style="text-align: center;">Est. Time~(h)</th>
<th style="text-align: center;">Est. Time~(days)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Sergipe</td>
<td style="text-align: center;">22,000</td>
<td style="text-align: center;">2.39</td>
<td style="text-align: center;">0.10</td>
</tr>
<tr class="even">
<td>Santa Catarina</td>
<td style="text-align: center;">96,000</td>
<td style="text-align: center;">10.42</td>
<td style="text-align: center;">0.43</td>
</tr>
<tr class="odd">
<td>Ceará</td>
<td style="text-align: center;">149,000</td>
<td style="text-align: center;">16.20</td>
<td style="text-align: center;">0.68</td>
</tr>
<tr class="even">
<td>Paraná</td>
<td style="text-align: center;">199,000</td>
<td style="text-align: center;">21.69</td>
<td style="text-align: center;">0.90</td>
</tr>
<tr class="odd">
<td>São Paulo</td>
<td style="text-align: center;">248,000</td>
<td style="text-align: center;">27.01</td>
<td style="text-align: center;">1.13</td>
</tr>
<tr class="even">
<td>Rio Grande do Sul</td>
<td style="text-align: center;">282,000</td>
<td style="text-align: center;">30.66</td>
<td style="text-align: center;">1.28</td>
</tr>
<tr class="odd">
<td>Bahia</td>
<td style="text-align: center;">560,000</td>
<td style="text-align: center;">60.92</td>
<td style="text-align: center;">2.54</td>
</tr>
<tr class="even">
<td>Minas Gerais</td>
<td style="text-align: center;">588,000</td>
<td style="text-align: center;">64.02</td>
<td style="text-align: center;">2.67</td>
</tr>
<tr class="odd">
<td>Brazil</td>
<td style="text-align: center;">8,500,000</td>
<td style="text-align: center;">925.88</td>
<td style="text-align: center;">38.58</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-A100" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-A100-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;14.2: Execution time estimates for large-scale inferences across different territorial extensions using a DGX A100 GPU.
</figcaption><div aria-describedby="tbl-A100-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 24%">
<col style="width: 21%">
<col style="width: 26%">
</colgroup>
<thead><tr class="header">
<th>Region</th>
<th style="text-align: center;">Area (km<span class="math inline">\(^2\)</span>)</th>
<th style="text-align: center;">Est. Time~(h)</th>
<th style="text-align: center;">Est. Time~(days)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Sergipe</td>
<td style="text-align: center;">22,000</td>
<td style="text-align: center;">0.45</td>
<td style="text-align: center;">0.02</td>
</tr>
<tr class="even">
<td>Santa Catarina</td>
<td style="text-align: center;">96,000</td>
<td style="text-align: center;">1.95</td>
<td style="text-align: center;">0.08</td>
</tr>
<tr class="odd">
<td>Ceará</td>
<td style="text-align: center;">149,000</td>
<td style="text-align: center;">3.03</td>
<td style="text-align: center;">0.13</td>
</tr>
<tr class="even">
<td>Paraná</td>
<td style="text-align: center;">199,000</td>
<td style="text-align: center;">4.05</td>
<td style="text-align: center;">0.17</td>
</tr>
<tr class="odd">
<td>São Paulo</td>
<td style="text-align: center;">248,000</td>
<td style="text-align: center;">5.04</td>
<td style="text-align: center;">0.21</td>
</tr>
<tr class="even">
<td>Rio Grande do Sul</td>
<td style="text-align: center;">282,000</td>
<td style="text-align: center;">5.72</td>
<td style="text-align: center;">0.24</td>
</tr>
<tr class="odd">
<td>Bahia</td>
<td style="text-align: center;">560,000</td>
<td style="text-align: center;">11.38</td>
<td style="text-align: center;">0.47</td>
</tr>
<tr class="even">
<td>Minas Gerais</td>
<td style="text-align: center;">588,000</td>
<td style="text-align: center;">11.95</td>
<td style="text-align: center;">0.50</td>
</tr>
<tr class="odd">
<td>Brazil</td>
<td style="text-align: center;">8,500,000</td>
<td style="text-align: center;">172.90</td>
<td style="text-align: center;">7.20</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>For large-scale predictions (state or national level) and production deployment, further optimizations are highly recommended beyond the current setup. These include:</p>
<ul>
<li><p>Quantization: Converting the trained models’ weights and activations to lower precision (e.g., 8-bit integers) can reduce model size and accelerate inference without substantial loss in accuracy.</p></li>
<li><p>ONNX (Open Neural Network Exchange): Exporting models to the ONNX format provides an open standard for representing machine learning models, enabling interoperability across different deep learning frameworks and hardware, thus streamlining deployment.</p></li>
<li><p>PyTorch Lightning: High-performance computational strategies provided by frameworks like PyTorch Lightning can further optimize training and inference pipelines, particularly for complex and large-scale deep learning models.</p></li>
</ul>
<p>These are considered industry standards for deploying neural network models in production and would ensure the system is both robust and efficient for continuous operation.</p>
</section><section id="sample-production-and-annotation" class="level3" data-number="14.4.5"><h3 data-number="14.4.5" class="anchored" data-anchor-id="sample-production-and-annotation">
<span class="header-section-number">14.4.5</span> Sample Production and Annotation</h3>
<p>The precision and generalization capabilities of field boundary delineation models are directly dependent on the quality and quantity of their training data. Manual annotation of remote sensing images, though resource-intensive, is a critical step in producing these high-quality labeled datasets that serve as ground truth for model training. This task is typically performed by trained professionals responsible for annotating data from various regions. These regions are selected based on the annotators’ existing geographical knowledge, familiarity with the local landscape and agricultural practices, and typical field sizes. Areas of high economic impact in the agribusiness sector are chosen for annotation due to the relative ease of identifying and delimiting planting areas, allowing for more precise annotation, which ultimately yields high-quality training data.</p>
<p>The labeling process combines geospatial software (such as QGIS) and pre-processed raster images. To observe temporal changes in vegetation, various timestamps are loaded, using RGB (Red, Green, Blue) composites and NDVI images. RGB images offer a familiar visual representation of the Earth’s surface, while NDVI provides quantitative insights into vegetation health, density, and vigor. These spectral indices aid annotators in their visual inspection, helping them to distinguish cultivated areas from other land covers.</p>
<p>After loading the imagery, the map is prepared for delimiting agricultural parcels using vector editing tools within the software. Annotators draw polygons that correspond to cultivation areas. It is crucial to delimit the parcel boundaries with extremely high precision, avoiding external areas such as roads, urban structures, natural forests, or non-cultivated vegetation. Such inclusions could introduce noise and inaccuracies into the training data, interfering with subsequent model learning and leading to erroneous predictions. The objective is to ensure that the separation of agricultural areas from non-agricultural ones is consistent with the reality observed in the imagery.</p>
<p>During the annotation process, NDVI images are particularly valuable as they offer a clear and quantitative view of vegetation health and density. This makes it significantly easier for annotators to identify the precise limits of agricultural parcels, especially when visual cues from RGB imagery are ambiguous (e.g., due to similar soil colors). RGB images, on the other hand, complement this analysis by providing a more intuitive visual representation of the landscape, making it easier to identify and exclude artificial structures (like buildings and roads) and non-vegetated areas that should not be part of the agricultural parcels.</p>
<p>Once parcels are delimited, annotators review and adjust polygon boundaries to ensure no inconsistencies or overlaps exist. The annotated parcels will serve as the ground truth for machine learning model training. The more accurately the data is labeled, the better the model will perform in real-world agricultural parceling scenarios, leading to higher confidence in its predictions.</p>
<p>The labeled dataset needs to be exported in a standardized format suitable for consumption by machine learning models. Before exporting, all non-essential information fields in the labeling data are removed, retaining only a unique identifier for each labeled polygon. This simplification is necessary as the primary objective is to convert the vector (polygon) result into a raster (pixel-grid) file for model training.</p>
<p>Information on the number of rows and columns (width and height in pixels) from the original reference images (e.g., RGB layers) are extracted. These dimensions are essential to ensure that the resulting raster file, which represents the labeled parcels, maintains the exact same spatial scale and proportion as the input imagery. This alignment is critical for accurate pixel-to-pixel correspondence during model training.</p>
<p>When converting the annotated polygons from vector to raster format, their unique <code>id</code> field is employed to assign the values of each polygon to corresponding pixels in the rasterization process. During this step, the width and height of the output raster image are set based on the previously extracted measures, ensuring that the final raster accurately reflects the municipality’s spatial extent. A data type like <code>UInt16</code> (unsigned 16-bit integer) is typically selected as the standard for the output image. This choice ensures efficient encoding of numerical polygon identifiers, providing a good balance between precision (allowing for many unique IDs) and storage economy, making it highly suitable for representing labeled agricultural areas in a computationally efficient manner.</p>
<p>Manual annotation is inherently resource-intensive. A trained annotator produces an average of 100-200 labelled polygons per day. Building labeled datasets necessary training high-performance field boundary models at a national scale requires time and effort. This work directly contributes to the model’s accuracy, as evidenced by its impact on evaluation metrics like Mean Intersection over Union (mIoU) and F1-score. Incorrectly delineated parcel borders or the accidental inclusion of non-agricultural elements, like roads or buildings, significantly reduce mIoU. Inadequate or inconsistent labeling lower the model’s precision and recall. Therefore, precise extraction of image dimensions and detailed, high-quality parcel labeling are paramount; they ensure that models are trained with accurate data. Good quality labels lead to improved generalization and reliability in real-world agricultural scenarios.</p>
</section><section id="effort-for-fine-tuning-models" class="level3" data-number="14.4.6"><h3 data-number="14.4.6" class="anchored" data-anchor-id="effort-for-fine-tuning-models">
<span class="header-section-number">14.4.6</span> Effort for Fine-Tuning Models</h3>
<p>Fine-tuning is an efficient strategy to adapt pretrained models to specific target domains where extensive labeled data might be scarce or too costly to acquire <span class="citation" data-cites="niu2021decade"><a href="#ref-Patel2015" role="doc-biblioref">[9]</a></span>. Unlike training a deep learning model from scratch, which requires massive computational resources and time to learn fundamental features, fine-tuning leverages a model that has already acquired general visual representations from a large source dataset (e.g., publicly available remote sensing datasets or vast amounts of unlabeled national imagery pretrained through self-supervised learning) <span class="citation" data-cites="Ribani2019"><a href="#ref-Ribani2019" role="doc-biblioref">[43]</a></span>. This makes it an efficient approach for applying general models to new geographical regions or specific agricultural contexts where only a small fraction of labeled samples is available, thereby reducing the annotation burden for new areas of interest.</p>
</section><section id="effectiveness-of-using-ssl-pre-training" class="level3" data-number="14.4.7"><h3 data-number="14.4.7" class="anchored" data-anchor-id="effectiveness-of-using-ssl-pre-training">
<span class="header-section-number">14.4.7</span> Effectiveness of Using SSL Pre-Training</h3>
<p>The fine-tuning process typically involves taking a neural network’s pretrained weights and making small, iterative adjustments to these weights using the new, smaller labeled dataset from the target domain. This can involve training only the final layers of the network (feature extractor approach) or training the entire network with a very low learning rate (end-to-end fine-tuning). For segmentation tasks, it is common practice to re-initialize the final segmentation head of the pretrained model with random weights and then train for a relatively short number of epochs (e.g., 60 epochs) with a learning rate that is significantly lower than that used during the initial pretraining phase. This strategy ensures that the model leverages its already learned robust and generalizable features while adapting to the specific characteristics and label distributions of the new region.</p>
<p>The computational effort for fine-tuning pretrained models is much lower than that required for the initial self-supervised pretraining or training from scratch. While the optimized self-supervised pretraining could take around 18 hours on a high-performance GPU, the fine-tuning phase is considerably quicker, often completed in a fraction of that time. Fine-tuning is a scalable and cost-effective method for applying field boundary delineation across various sub-regions or specific agricultural types within a national territory. It facilitates the continuous refinement and specialization of models, allowing for rapid deployment and adaptation to local conditions without the prohibitive cost of extensive new large-scale annotation efforts for every new area. This iterative adaptation is key to maintaining high performance in dynamic and diverse agricultural landscapes.</p>
<p><a href="#tbl-results" class="quarto-xref">Table&nbsp;<span>14.3</span></a> shows the results using public and private data for agricultural plot segmentation with: 1) supervised learning without SSL (wo/ SSL); and 2) SSL pre-training followed by fine-tuning (w/ SSL). In all cases, both AP and AR improved when SSL pre-training was incorporated. SSL pre-training proved effective for both pixel-level and instance-level metrics, achieving considerably higher values than the SSL-free baseline across all 5 cities. Therefore, the results presented in <a href="#tbl-results" class="quarto-xref">Table&nbsp;<span>14.3</span></a> are conclusive in favor of SSL pre-training as a valid strategy for large-scale mapping.</p>
<div id="tbl-results" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;14.3: Quantitative results achieved for some Brazilian municipalities, comparing the results obtained using SSL pretrained models with models trained from scratch. AUC: area under the curve; J-w: Jaccard-Weighted; J-b: for Jaccard-Binary; GOS: global over-segmentation score; GUS: global under-segmentation-score; GTS: global total segmentation; AP: average precision.
</figcaption><div aria-describedby="tbl-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<thead><tr class="header">
<th>City</th>
<th>State</th>
<th style="text-align: center;">Method</th>
<th style="text-align: center;">AUC</th>
<th style="text-align: center;">J-w</th>
<th style="text-align: center;">J-b</th>
<th style="text-align: center;">GOS</th>
<th style="text-align: center;">GUS</th>
<th style="text-align: center;">GTS</th>
<th style="text-align: center;">AP</th>
<th style="text-align: center;">AR</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Cândido</td>
<td>SP</td>
<td style="text-align: center;">wo/ SSL</td>
<td style="text-align: center;">.9236</td>
<td style="text-align: center;">.4084</td>
<td style="text-align: center;">.8726</td>
<td style="text-align: center;">.0649</td>
<td style="text-align: center;">.0643</td>
<td style="text-align: center;">.0738</td>
<td style="text-align: center;">.2177</td>
<td style="text-align: center;">.3383</td>
</tr>
<tr class="even">
<td>Cândido</td>
<td>SP</td>
<td style="text-align: center;">w/ SSL</td>
<td style="text-align: center;">.9447</td>
<td style="text-align: center;">.6161</td>
<td style="text-align: center;">.9185</td>
<td style="text-align: center;">.0521</td>
<td style="text-align: center;">.0426</td>
<td style="text-align: center;">.0540</td>
<td style="text-align: center;">.4063</td>
<td style="text-align: center;">.5793</td>
</tr>
<tr class="odd">
<td>Pitangueiras</td>
<td>SP</td>
<td style="text-align: center;">wo/ SSL</td>
<td style="text-align: center;">.9551</td>
<td style="text-align: center;">.6449</td>
<td style="text-align: center;">.8709</td>
<td style="text-align: center;">.0890</td>
<td style="text-align: center;">.0757</td>
<td style="text-align: center;">.0888</td>
<td style="text-align: center;">.5643</td>
<td style="text-align: center;">.6533</td>
</tr>
<tr class="even">
<td>Pitangueiras</td>
<td>SP</td>
<td style="text-align: center;">w/ SSL</td>
<td style="text-align: center;">.9689</td>
<td style="text-align: center;">.7576</td>
<td style="text-align: center;">.9148</td>
<td style="text-align: center;">.0490</td>
<td style="text-align: center;">.0505</td>
<td style="text-align: center;">.0557</td>
<td style="text-align: center;">.7416</td>
<td style="text-align: center;">.7876</td>
</tr>
<tr class="odd">
<td>U. Paulista</td>
<td>SP</td>
<td style="text-align: center;">wo/ SSL</td>
<td style="text-align: center;">.9207</td>
<td style="text-align: center;">.5374</td>
<td style="text-align: center;">.8620</td>
<td style="text-align: center;">.1099</td>
<td style="text-align: center;">.0732</td>
<td style="text-align: center;">.0990</td>
<td style="text-align: center;">.3892</td>
<td style="text-align: center;">.4988</td>
</tr>
<tr class="even">
<td>U. Paulista</td>
<td>SP</td>
<td style="text-align: center;">w/ SSL</td>
<td style="text-align: center;">.9443</td>
<td style="text-align: center;">.6945</td>
<td style="text-align: center;">.9150</td>
<td style="text-align: center;">.0483</td>
<td style="text-align: center;">.0511</td>
<td style="text-align: center;">.0561</td>
<td style="text-align: center;">.5607</td>
<td style="text-align: center;">.6778</td>
</tr>
<tr class="odd">
<td>Colorado</td>
<td>PR</td>
<td style="text-align: center;">wo/ SSL</td>
<td style="text-align: center;">.9470</td>
<td style="text-align: center;">.5131</td>
<td style="text-align: center;">.8509</td>
<td style="text-align: center;">.1201</td>
<td style="text-align: center;">.0697</td>
<td style="text-align: center;">.1072</td>
<td style="text-align: center;">.3540</td>
<td style="text-align: center;">.6062</td>
</tr>
<tr class="even">
<td>Colorado</td>
<td>PR</td>
<td style="text-align: center;">w/ SSL</td>
<td style="text-align: center;">.9635</td>
<td style="text-align: center;">.6043</td>
<td style="text-align: center;">.8801</td>
<td style="text-align: center;">.1107</td>
<td style="text-align: center;">.0503</td>
<td style="text-align: center;">.0931</td>
<td style="text-align: center;">.4789</td>
<td style="text-align: center;">.7390</td>
</tr>
<tr class="odd">
<td>Chorozinho</td>
<td>CE</td>
<td style="text-align: center;">wo/ SSL</td>
<td style="text-align: center;">.8038</td>
<td style="text-align: center;">.0756</td>
<td style="text-align: center;">.8509</td>
<td style="text-align: center;">.0762</td>
<td style="text-align: center;">.0680</td>
<td style="text-align: center;">.0800</td>
<td style="text-align: center;">.0066</td>
<td style="text-align: center;">.0162</td>
</tr>
<tr class="even">
<td>Chorozinho</td>
<td>CE</td>
<td style="text-align: center;">w/ SSL</td>
<td style="text-align: center;">.8537</td>
<td style="text-align: center;">.1393</td>
<td style="text-align: center;">.8824</td>
<td style="text-align: center;">.0186</td>
<td style="text-align: center;">.0615</td>
<td style="text-align: center;">.0501</td>
<td style="text-align: center;">.0193</td>
<td style="text-align: center;">.0474</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><a href="#fig-candido-ibge" class="quarto-xref">Figure&nbsp;<span>14.14</span></a> to <a href="#fig-choro-ibge" class="quarto-xref">Figure&nbsp;<span>14.18</span></a> present visual segmentation results for the 5 cities used to evaluate models pre-trained with SSL. In addition to the original image and annotations shown in the top row, the bottom row displays the predictions from the model without SSL model and the predictions from the model with SSL.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-candido-ibge" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-candido-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/th_parcel_extraction/results_ibge_ssl_3510104_v2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-candido-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.14: Visual results for Cândido (SP).
</figcaption></figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pitan-ibge" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-pitan-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/th_parcel_extraction/results_ibge_ssl_3539509_v2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pitan-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.15: Visual results for Pitangueiras (SP).
</figcaption></figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-uniao-ibge" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-uniao-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/th_parcel_extraction/results_ibge_ssl_3555703_v2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-uniao-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.16: Visual results for União Paulista (SP).
</figcaption></figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-colorado-ibge" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-colorado-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/th_parcel_extraction/results_ibge_ssl_4105904_v2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-colorado-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.17: Visual results for Colorado (PR).
</figcaption></figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-choro-ibge" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-choro-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/th_parcel_extraction/results_ibge_ssl_2303956_v2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-choro-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.18: Visual results for Chorozinho (CE).
</figcaption></figure>
</div>
</div>
</div>
<p>The model without SSL is susceptible to artifacts at the city borders due to missing data (black areas in the images) during the prediction process. These artifacts appear across all predictions without SSL, but are especially noticeable in the following cities: Cândido/SP (top of the predictions), União Paulista/SP (bottom-right and top corners), and Chorozinho/CE (around the city boundaries). SSL-based models, due to the pre-training process that encompassed a much larger portion of the national territory and a greater variety of regions and types of native vegetation, produced more robust results without artifacts.</p>
<p>When zoomed in, it is possible to observe the better capacity of SSL-trained models to separate neighboring plots, which are often incorrectly merged in the non-SSL model. SSL also enables the model to generate fewer ambiguous zones, allowing for more assertive and therefore accurate predictions after thresholding, with better adherence to plot boundaries. Another observable improvement is the SSL-enhanced ability to correctly identify more agricultural plots, boosting the model’s recall. This can be noticed in Cândido/SP (bottom-right portion of the city), Pitangueiras/SP (top portion), and Colorado/PR (left side).</p>
<p>These visual results are supported by the higher AR values shown in <a href="#tbl-results" class="quarto-xref">Table&nbsp;<span>14.3</span></a>. In some cases, SSL use led to improvements in metrics AP and AR. In the city of Cândido (SP), for example, AP and AR increased from 0.2177 and 0.3383 to 0.4063 and 0.5793 with SSL. This difference may be significant for implementing large-scale plot delineation operations, as illustrated in <a href="#fig-candido-ibge" class="quarto-xref">Figure&nbsp;<span>14.14</span></a>.</p>
<div class="cell" data-layout-nrow="2">
<div id="fig-sslseg-ibge" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-sslseg-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-sslseg-ibge" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-sslseg-ibge-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-sslseg-ibge-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/th_parcel_extraction/ssl_jaiba.png" class="img-fluid figure-img" style="width:90.0%" data-ref-parent="fig-sslseg-ibge">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-sslseg-ibge-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Jaíba (MG) municipality
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-sslseg-ibge" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-sslseg-ibge-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-sslseg-ibge-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/th_parcel_extraction/ssl_jaiba_no_ssl.png" class="img-fluid figure-img" style="width:90.0%" data-ref-parent="fig-sslseg-ibge">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-sslseg-ibge-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Without pre-training
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-sslseg-ibge" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-sslseg-ibge-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-sslseg-ibge-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/th_parcel_extraction/ssl_jaiba_ssl.png" class="img-fluid figure-img" style="width:90.0%" data-ref-parent="fig-sslseg-ibge">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-sslseg-ibge-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) Pre-trained
</figcaption></figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-sslseg-ibge" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-sslseg-ibge-4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-sslseg-ibge-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/th_parcel_extraction/ssl_campo_novo_part.png" class="img-fluid figure-img" style="width:90.0%" data-ref-parent="fig-sslseg-ibge">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-sslseg-ibge-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(d) Campo Novo do Parecis (MT) municipality
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-sslseg-ibge" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-sslseg-ibge-5" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-sslseg-ibge-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/th_parcel_extraction/ssl_campo_novo_no_ssl_part.png" class="img-fluid figure-img" style="width:90.0%" data-ref-parent="fig-sslseg-ibge">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-sslseg-ibge-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(e) Without pre-training
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-sslseg-ibge" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-sslseg-ibge-6" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-sslseg-ibge-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/th_parcel_extraction/ssl_campo_novo_ssl_part.png" class="img-fluid figure-img" style="width:90.0%" data-ref-parent="fig-sslseg-ibge">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-sslseg-ibge-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(f) Pre-trained
</figcaption></figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sslseg-ibge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.19: Plot segmentation results in regions of two Brazilian cities from the dataset obtained by IBGE. In addition to the images (a,d), the segmentation results are presented without (b,e) and with (c,f) pre-training using the Self-Supervised Training developed. The ellipses across the image highlight areas where there were considerable differences in plot segmentation with and without the use of developed method as pre-training. Zooming is recommended for image analysis.
</figcaption></figure>
</div>
</div>
</section></section><section id="implications-for-national-agricultural-statistical-offices" class="level2" data-number="14.5"><h2 data-number="14.5" class="anchored" data-anchor-id="implications-for-national-agricultural-statistical-offices">
<span class="header-section-number">14.5</span> Implications for National Agricultural Statistical Offices</h2>
<p>The automated delineation of field boundaries using remote sensing and machine learning offers profound implications for national agricultural statistical offices (NSOs), enabling more precise data collection, enhanced monitoring capabilities, and better-informed policy decisions. This technological shift promises to revolutionize how agricultural statistics are compiled and utilized, moving from traditional, often labor-intensive, methods to dynamic, data-driven approaches.</p>
<section id="crop-mapping-and-land-use-classification" class="level3" data-number="14.5.1"><h3 data-number="14.5.1" class="anchored" data-anchor-id="crop-mapping-and-land-use-classification">
<span class="header-section-number">14.5.1</span> Crop Mapping and Land Use Classification</h3>
<p>Automated field boundary delineation directly facilitates the creation of detailed thematic maps of agricultural regions. These maps are importanr for accurately identifying and differentiating various land uses and specific crop types across the national territory. By continuously updating these maps, official institutes can track granular changes in agricultural landscapes, monitor the expansion or contraction of cultivated areas, and assess the prevalence of different crops over time. This dynamic mapping capability provides a foundational layer for numerous agricultural statistics and planning activities, transforming static census data into a living, evolving record of agricultural activity. Key applications include:</p>
<ul>
<li><p>Agricultural Census Support: The highly accurate and frequently updated agricultural maps generated through this process can serve as a public reference for national agricultural mapping. They provide baseline data for upcoming agricultural censuses, enhancing their accuracy and efficiency. These maps can inform the census planning process by offering valuable, pre-survey insights into the density and distribution of agricultural properties. This spatial intelligence aids in the efficient allocation of human resources for fieldwork, directing surveyors to areas with high agricultural concentration by census sector, city, district, or enumeration areas. Furthermore, by identifying regions with concentrations of larger parcels versus those with smaller, more fragmented agricultural fields, these maps can serve as a powerful proxy for distinguishing areas dominated by large-scale commercial farming (latifundia) versus those characterized by family farming, providing critical socio-economic context for agricultural policies.</p></li>
<li><p>Land Use Change Detection: The inherent ability to monitor temporal changes in land use over recent years allows for significantly improved estimation and detection of shifts in cultivation practices, land conversion from natural areas to agriculture, and the overall dynamics of agricultural land use. This is vital for understanding environmental impacts, such as deforestation or land degradation directly linked to agricultural expansion. It also allows for tracking the adoption of new crops or changes in crop rotation patterns.</p></li>
<li><p>Policy Making and Resource Allocation: Accurate and frequently updated land use maps provide evidence-based data for policymakers. Such maps enable the development of targeted agricultural programs, better management of natural resources (e.g., water, soil), and the allocation of subsidies or support to farmers based on verified land use, agricultural activity, and environmental compliance.</p></li>
</ul>
<p>Our results show that traditional supervised models struggle to generalize effectively to challenging areas with highly irregular parcels, complex interfaces with urban environments, or dense native vegetation. This is due to the inherent domain shift between their training data and new, unseen geographical contexts. Self-supervised learning strategies, as discussed in the methodology section, considerably improve the generalization capabilities of segmentation models. By enabling models to learn from vast amounts of unlabeled remote sensing imagery, these techniques allow for their application as a robust large-scale pretraining across broad portions of the national territory. This initial pretraining, followed by supervised fine-tuning on specifically annotated regions, offers a highly resilient and effective strategy for agricultural mapping in future agricultural censuses and ongoing national surveys.</p>
</section></section><section id="crop-yield-estimation-and-production-projection" class="level2" data-number="14.6"><h2 data-number="14.6" class="anchored" data-anchor-id="crop-yield-estimation-and-production-projection">
<span class="header-section-number">14.6</span> Crop Yield Estimation and Production Projection</h2>
<p>While field boundary delineation is primarily a segmentation task focused on defining spatial units, it serves as a precursor for other kinds of analyses, including crop yield estimation and production projection. By precisely defining the boundaries of individual fields, agricultural institutes can unlock many downstream analytical capabilities:</p>
<ul>
<li><p>Area-Based Yield Calculation: With field area measurements derived from delineation, statistical and machine learning models can combine these area figures with other crucial data, such as real-time weather patterns, detailed soil types, historical yield records, and even satellite-derived vegetation indices. This approach allows estimating crop production with enhanced accuracy compared to traditional survey methods that rely on aggregated area data. This capability provides an input for national food security assessments, informing strategic food reserves, and for market analyses that guide import/export decisions.</p></li>
<li><p>Production Projection: A robust understanding of the exact extent of planted areas at various points in the growing season allows for more reliable and timely projection of future harvests. This information is invaluable for national economic planning, enabling governments and agricultural industries to manage food supply chains more effectively, anticipate potential surpluses or shortages, and thus mitigate market fluctuations. Early and accurate projections can prevent price volatility and ensure stable food availability.</p></li>
<li><p>Integration with Crop Type Information: A complete agricultural monitoring system needs to combine field boundary delineation with information on the crop types for each parcel during a given period. The literature highlights the effectiveness of using time series data and various spectral vegetation indices (e.g., Enhanced Vegetation Index (EVI), Normalized Difference Vegetation Index (NDVI)) combined with machine learning models, particularly those based on the attention mechanisms <span class="citation" data-cites="Yuan2022"><a href="#ref-Silva2024a" role="doc-biblioref">[57]</a></span>. These models, trained on the temporal patterns derived from multispectral satellite data (e.g., Sentinel-2), can classify the crop within each field. This integration transforms static boundary maps into dynamic tools for comprehensive agricultural monitoring, providing not just where fields are, but also what is being cultivated in them.</p></li>
</ul>
<section id="continuous-monitoring-and-early-warning-systems" class="level3" data-number="14.6.1"><h3 data-number="14.6.1" class="anchored" data-anchor-id="continuous-monitoring-and-early-warning-systems">
<span class="header-section-number">14.6.1</span> Continuous Monitoring and Early Warning Systems</h3>
<p>The automation of agricultural parcel recognition supports monitoring of agricultural activity at a temporal resolution unattainable through manual methods. This shift from periodic surveys to ongoing observation offers several advantages for national agricultural and geosciences institutes:</p>
<ul>
<li><p>Timely Detection of Changes: Continuous monitoring enables detection of subtle and significant changes in planting patterns, precise tracking of harvest progress, and early identification of agricultural anomalies. These anomalies could include emergence of crop diseases, onset of climate-induced stress (e.g., drought, excessive rainfall), or damage from pests. Early detection allows for rapid response and mitigation strategies, minimizing potential losses.</p></li>
<li><p>Support for Sample Surveys: Precisely delineated parcels, available in a digital and georeferenced format, can serve as a robust sampling frame for targeted agricultural surveys. Parcel boundaries improve the efficiency of surveys, ensuring consistency of data collection efforts and reducing the logistics of field sampling. Surveys can be more accurately stratified based on detected field characteristics.</p></li>
<li><p>Early Warning for Food Security: By integrating parcel data with real-time crop type information and other relevant environmental variables (such as precipitation, temperature, and soil moisture data), NSO can develop early warning systems. These systems can predict potential food shortages or surpluses, allowing for proactive interventions in food policy, trade, and aid distribution. This capability moves national food security planning from reactive to anticipatory.</p></li>
</ul>
<p>By transitioning to continuous, automated monitoring of parcels, NSOs can improve their data collection and information systems, thus being able to respond to challenges and opportunities in the agricultural sector.</p>
</section><section id="addressing-limitations-and-future-directions" class="level3" data-number="14.6.2"><h3 data-number="14.6.2" class="anchored" data-anchor-id="addressing-limitations-and-future-directions">
<span class="header-section-number">14.6.2</span> Addressing Limitations and Future Directions</h3>
<p>Despite advancements in field boundary delineation, the current strategies, while effective, still possess limitations that require research and development to improve performance and achieve widespread applicability:</p>
<ul>
<li><p>Generalization Across Diverse Regions: The generalization capacity of the neural networks used is constrained by the representativeness of their source data <span class="citation" data-cites="xu2022eyes"><a href="#ref-xu2022eyes" role="doc-biblioref">[58]</a></span>. Models trained on data from one geographical region or agricultural system may perform sub-optimally when applied to another distinct region due to differences in environmental conditions, farming practices, soil types, or even satellite sensor characteristics. To mitigate this effect, it is important to add different regions to the self-supervised pretraining. The subsequent supervised fine-tuning stage should also incorporate data from a wide array of annotated regions. Including training data from a diversity of geographical regions improves the models making them robust to variations encountered nationwide.</p></li>
<li><p>Detection of Small and Narrow Parcels: The spatial resolution of commonly used satellites like Sentinel-2, while adequate for large and medium-sized agricultural areas, has limitations in discerning narrow agricultural fields. This problem worsens in highly fragmented landscapes, typical of certain agricultural systems (e.e., family farming), or where residual natural vegetation or infrastructure overlap with small fields. To overcome this, NSO can use high-resolution data sources, such as Planet imagery (3-5 meters resolution) or other commercial satellite data. These higher-resolution inputs allow for more accurate delineation of smaller parcels. Specialized fine-tuning on subsets of data containing a higher proportion of small parcels could help models learn to recognize and segment these challenging features more effectively.</p></li>
<li><p>Filtering False Positives and Negatives: The output of segmentation models may contain spurious artifacts or false positive (FP) predictions (e.g., non-agricultural areas mistakenly identified as fields) and false negatives (FNs), where actual fields are missed. Morphological operations (e.g., opening, closing) can remove very small FPs, which are common byproducts of pixel-level semantic segmentation and are often noise. More sophisticated and context-aware filtering can be achieved by leveraging vegetation indices (e.g., EVI, EVI2, NDVI). By analyzing the temporal profile of these indices for detected parcels, one can identify and remove areas erroneously classified as positive if their vegetation patterns do not align with typical agricultural cycles. For false negatives, which are often more critical as they represent missed agricultural production, advanced data mining techniques like hard negative mining can be employed. These strategies incorporate hard examples (those the model performs poorly on) into the training process, thereby correcting collection biases <span class="citation" data-cites="Kalantidis2020"><a href="#ref-Robinson2020" role="doc-biblioref">[60]</a></span>.</p></li>
<li><p>Enhancements in Classification: Using complementary sources such as Planet or Synthetic Aperture Radar (SAR) can further increase detection precision. Incorporating multiple sources in the training set improves the model’s ability to identify subtle patterns in challenging areas. Augmented data sets can improve separation of small agricultural areas from similar-looking natural vegetation. Integrating advanced machine learning algorithms into the analysis pipeline, such as self-supervised learning methods, can further enhance segmentation accuracy and reduce errors. This approach, especially when combined with robust cross-validation and fine-tuning, allows for significant improvements in system precision at the cost of some additional processing time.</p></li>
<li><p>Reduction of Noise and Errors: Applying spatial and temporal filters can reduce false positives and minimize classification errors. Spatial filters discard small, isolated segmented areas that are not consistent with agricultural patterns. Temporal filters validate land cover changes over time, reducing the probability of including transient events like shadows, cloud edges, or atmospheric interference. Adjustments in the processing pipeline also help to reduce errors. This includes improvements in calibration of input data, validation of intermediate results at various stages, and automation of critical steps to ensure consistency throughout the workflow. Identifying artifacts in image mosaics from providers can prevent unreliable predictions. These improvements should be implemented iteratively, ensuring that the process evolves in response to observed challenges and new insights.</p></li>
<li><p>Alternative Data Sources: For long-term resilience and adaptability, NSOs could consider integrating sources beyond Sentinel-2 and Planet data. These could include older, publicly available datasets like Landsat, which are useful for historical analyses and serves as complement in areas of lower complexity. Commercial high-resolution data, while costly, offers sub-meter spatial resolution; these data sets can be employed in situations that demand superior precision, such as detailed mapping of specific small farms (potentially even using drone imagery for hyper-local applications). The recently launched Sentinel-1C, part of the Copernicus program, or Sentinel-1 SAR (Synthetic Aperture Radar) elevation data, can also be valuable, especially in regions with persistent cloud cover or high structural complexity (e.g., areas with dense vegetation or complex topography) where optical data is limited. Diversifying data sources and processing tools ensures continuity and quality of analyses even in scenarios of unavailability or limitations of the primary data sources.</p></li>
</ul></section></section><section id="conclusions" class="level2" data-number="14.7"><h2 data-number="14.7" class="anchored" data-anchor-id="conclusions">
<span class="header-section-number">14.7</span> Conclusions</h2>
<p>The technologies and methodologies developed for field boundary delineation offer a robust foundation for various phases of agricultural research and operational activities within national statistical and geosciences institutes. This outlines a strategic pathway for their sustained application and evolution:</p>
<ul>
<li><p>Short-Term Use (Immediate Application): The models developed can be immediately applied for large-scale agricultural mapping in regions that feature clearly delineated and relatively uniform agricultural parcels. This rapid deployment can provide quick and valuable insights for current agricultural surveys.</p></li>
<li><p>Medium-Term Use (Pre-Census Planning and Refinement): The proposed models can serve as a base for pre-segmentation during the planning stages of upcoming agricultural censuses. They offer insights into the density and spatial distribution of agricultural properties, which aid in the allocation of human resources for fieldwork. By incorporating additional annotated areas, the model’s performance can be improved and refined into a production-ready version. Inclusion of geographically diverse labeled data should considerably enhance the model’s generalization capabilities, especially for challenging regions with irregular agricultural parcels, bridging the gap between current performance and optimal nationwide coverage.</p></li>
<li><p>Long-Term Vision (Continuous Monitoring and Automation): The advanced strategy developed can be refined and scaled through future improvements in machine learning algorithms. This continuous refinement enables the proposed field segmentation pipeline to be integrated into an automated process for agricultural monitoring. This long-term vision includes the potential to incorporate metadata from sample surveys on agricultural production directly into the automated system. Once precise parcel delineation is paired with accurate information on crop types (which can be derived from subsequent classification models), it becomes feasible to monitor the planting, growth, and harvest of major agricultural crops at an unprecedented temporal frequency. This can leverage both publicly available satellite data (e.g., Sentinel-2) and/or higher-resolution private imagery (e.g., from Planet satellite constellations), providing dynamic, near real-time insights into agricultural dynamics.</p></li>
</ul>
<p>This holistic approach ensures that the developed methodologies and models evolve to meet the dynamic and increasingly complex needs of agricultural statistical production and national monitoring efforts, supporting sustainable agriculture and food security.</p>
</section><section id="references" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="references">References</h2>


<div id="refs" class="references csl-bib-body" data-entry-spacing="0" role="list">
<div id="ref-Liaghat2010" class="csl-entry" role="listitem">
<div class="csl-left-margin">[1] </div>
<div class="csl-right-inline">S. Liaghat and S. K. Balasundram, <span>“A review: The role of remote sensing in precision agriculture,”</span> <em>American Journal of Agricultural and Biological Sciences</em>, vol. 5, no. 1, pp. 50–55, 2010.</div>
</div>
<div id="ref-Andrimont2023" class="csl-entry" role="listitem">
<div class="csl-left-margin">[2] </div>
<div class="csl-right-inline">R. Andrimont <em>et al.</em>, <span>“AI4Boundaries: A dataset for agricultural field boundary delineation,”</span> <em>Scientific Data</em>, vol. 10, no. 1, pp. 1–12, 2023.</div>
</div>
<div id="ref-Garnot2021" class="csl-entry" role="listitem">
<div class="csl-left-margin">[3] </div>
<div class="csl-right-inline">V. S. F. Garnot, L. Landrieu, and N. Chehata, <span>“Multi-<span>Modal Temporal Attention Models</span> for <span>Crop Mapping</span> from <span>Satellite Time Series</span>,”</span> <em>arXiv:2112.07558 [cs, eess]</em>, 2021, Accessed: Mar. 14, 2022. [Online]. Available: <a href="https://arxiv.org/abs/2112.07558">https://arxiv.org/abs/2112.07558</a>.</div>
</div>
<div id="ref-pinto2024tradition" class="csl-entry" role="listitem">
<div class="csl-left-margin">[4] </div>
<div class="csl-right-inline">M. Pinto da Silva <em>et al.</em>, <span>“From tradition to transformation: Deep and self-supervised learning approaches for remote sensing in agriculture and environmental change,”</span> <em>Nunes, Ian and dos Santos, Jefersson Alex and N. Oliveira, Hugo, From Tradition to Transformation: Deep and Self-Supervised Learning Approaches for Remote Sensing in Agriculture and Environmental Change</em>, 2024.</div>
</div>
<div id="ref-Gallo2021" class="csl-entry" role="listitem">
<div class="csl-left-margin">[5] </div>
<div class="csl-right-inline">I. Gallo <em>et al.</em>, <span>“Crop type mapping using multi-temporal sentinel-2 data and deep learning,”</span> <em>Remote Sensing</em>, vol. 13, no. 11, p. 2050, 2021.</div>
</div>
<div id="ref-Gallo2023" class="csl-entry" role="listitem">
<div class="csl-left-margin">[6] </div>
<div class="csl-right-inline">I. Gallo <em>et al.</em>, <span>“Advanced deep learning methods for agricultural monitoring: A comprehensive survey,”</span> <em>IEEE Geoscience and Remote Sensing Magazine</em>, vol. 11, no. 1, pp. 2–35, 2023.</div>
</div>
<div id="ref-Bengio2017" class="csl-entry" role="listitem">
<div class="csl-left-margin">[7] </div>
<div class="csl-right-inline">Y. Bengio <em>et al.</em>, <span>“Deep learning,”</span> <em>Nature</em>, vol. 521, no. 7553, pp. 436–444, 2017.</div>
</div>
<div id="ref-niu2021decade" class="csl-entry" role="listitem">
<div class="csl-left-margin">[8] </div>
<div class="csl-right-inline">S. Niu, Y. Liu, J. Wang, and H. Song, <span>“A decade survey of transfer learning (2010–2020),”</span> <em>IEEE Transactions on Artificial Intelligence</em>, vol. 1, no. 2, pp. 151–166, 2021.</div>
</div>
<div id="ref-Patel2015" class="csl-entry" role="listitem">
<div class="csl-left-margin">[9] </div>
<div class="csl-right-inline">V. M. Patel <em>et al.</em>, <span>“Domain adaptation for visual applications: A comprehensive survey,”</span> <em>arXiv preprint arXiv:1702.05374</em>, 2015.</div>
</div>
<div id="ref-Hospedales2021" class="csl-entry" role="listitem">
<div class="csl-left-margin">[10] </div>
<div class="csl-right-inline">T. Hospedales <em>et al.</em>, <span>“Meta-learning in neural networks: A survey,”</span> <em>IEEE Transactions on Pattern Analysis and Machine Intelligence</em>, vol. 44, no. 9, pp. 5149–5169, 2021.</div>
</div>
<div id="ref-Jing2020" class="csl-entry" role="listitem">
<div class="csl-left-margin">[11] </div>
<div class="csl-right-inline">L. Jing and Y. Tian, <span>“Self-supervised visual feature learning with deep neural networks: A survey,”</span> <em>IEEE Transactions on Pattern Analysis and Machine Intelligence</em>, vol. 43, no. 11, pp. 4037–4058, 2020.</div>
</div>
<div id="ref-Balestriero2023" class="csl-entry" role="listitem">
<div class="csl-left-margin">[12] </div>
<div class="csl-right-inline">R. Balestriero <em>et al.</em>, <span>“A <span>Cookbook</span> of <span>Self-Supervised Learning</span>.”</span> arXiv, 2023, doi: <a href="https://doi.org/10.48550/arXiv.2304.12210">10.48550/arXiv.2304.12210</a>.</div>
</div>
<div id="ref-Awais2023" class="csl-entry" role="listitem">
<div class="csl-left-margin">[13] </div>
<div class="csl-right-inline">M. Awais <em>et al.</em>, <span>“Foundational models in computer vision: A comprehensive review,”</span> <em>International Journal of Computer Vision</em>, vol. 131, no. 4, pp. 1–32, 2023.</div>
</div>
<div id="ref-Krizhevsky2012" class="csl-entry" role="listitem">
<div class="csl-left-margin">[14] </div>
<div class="csl-right-inline">A. Krizhevsky <em>et al.</em>, <span>“ImageNet classification with deep convolutional neural networks,”</span> <em>Advances in Neural Information Processing Systems</em>, vol. 25, pp. 1–9, 2012.</div>
</div>
<div id="ref-Simonyan2014" class="csl-entry" role="listitem">
<div class="csl-left-margin">[15] </div>
<div class="csl-right-inline">K. Simonyan and A. Zisserman, <span>“Very deep convolutional networks for large-scale image recognition,”</span> <em>arXiv preprint arXiv:1409.1556</em>, 2014.</div>
</div>
<div id="ref-He2016" class="csl-entry" role="listitem">
<div class="csl-left-margin">[16] </div>
<div class="csl-right-inline">K. He, X. Zhang, S. Ren, and J. Sun, <span>“Deep <span>Residual Learning</span> for <span>Image Recognition</span>,”</span> in <em>2016 <span>IEEE Conference</span> on <span>Computer Vision</span> and <span>Pattern Recognition</span> (<span>CVPR</span>)</em>, 2016, pp. 770–778, doi: <a href="https://doi.org/10.1109/CVPR.2016.90">10.1109/CVPR.2016.90</a>.</div>
</div>
<div id="ref-Huang2017" class="csl-entry" role="listitem">
<div class="csl-left-margin">[17] </div>
<div class="csl-right-inline">G. Huang <em>et al.</em>, <span>“Densely connected convolutional networks,”</span> <em>Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition</em>, pp. 4700–4708, 2017.</div>
</div>
<div id="ref-Long2015" class="csl-entry" role="listitem">
<div class="csl-left-margin">[18] </div>
<div class="csl-right-inline">J. Long <em>et al.</em>, <span>“Fully convolutional networks for semantic segmentation,”</span> <em>Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition</em>, pp. 3431–3440, 2015.</div>
</div>
<div id="ref-Ronneberger2015" class="csl-entry" role="listitem">
<div class="csl-left-margin">[19] </div>
<div class="csl-right-inline">O. Ronneberger <em>et al.</em>, <span>“U-net: Convolutional networks for biomedical image segmentation,”</span> <em>Medical Image Computing and Computer-Assisted Intervention</em>, pp. 234–241, 2015.</div>
</div>
<div id="ref-He2017" class="csl-entry" role="listitem">
<div class="csl-left-margin">[20] </div>
<div class="csl-right-inline">K. He <em>et al.</em>, <span>“Mask r-CNN,”</span> <em>Proceedings of the IEEE International Conference on Computer Vision</em>, pp. 2961–2969, 2017.</div>
</div>
<div id="ref-Vaswani2017" class="csl-entry" role="listitem">
<div class="csl-left-margin">[21] </div>
<div class="csl-right-inline">A. Vaswani <em>et al.</em>, <span>“Attention is <span>All</span> you <span>Need</span>,”</span> in <em>Advances in <span>Neural Information Processing Systems</span></em>, 2017, vol. 30, Accessed: Mar. 14, 2022. [Online].</div>
</div>
<div id="ref-Dosovitskiy2020" class="csl-entry" role="listitem">
<div class="csl-left-margin">[22] </div>
<div class="csl-right-inline">A. Dosovitskiy <em>et al.</em>, <span>“An image is worth 16x16 words: Transformers for image recognition at scale,”</span> <em>arXiv preprint arXiv:2010.11929</em>, 2020.</div>
</div>
<div id="ref-Liu2021" class="csl-entry" role="listitem">
<div class="csl-left-margin">[23] </div>
<div class="csl-right-inline">J. Liu, J. Yan, L. Wang, L. Huang, H. He, and H. Liu, <span>“Remote <span>Sensing Time Series Classification Based</span> on <span>Self-Attention Mechanism</span> and <span>Time Sequence Enhancement</span>,”</span> <em>Remote Sensing</em>, vol. 13, no. 9, p. 1804, 2021, doi: <a href="https://doi.org/10.3390/rs13091804">10.3390/rs13091804</a>.</div>
</div>
<div id="ref-Tarasiou2023" class="csl-entry" role="listitem">
<div class="csl-left-margin">[24] </div>
<div class="csl-right-inline">M. Tarasiou, E. Chavez, and S. Zafeiriou, <span>“<span>ViTs</span> for <span>SITS</span>: <span>Vision Transformers</span> for <span>Satellite Image Time Series</span>.”</span> arXiv, 2023, doi: <a href="https://doi.org/10.48550/arXiv.2301.04944">10.48550/arXiv.2301.04944</a>.</div>
</div>
<div id="ref-Badrinarayanan2017" class="csl-entry" role="listitem">
<div class="csl-left-margin">[25] </div>
<div class="csl-right-inline">V. Badrinarayanan <em>et al.</em>, <span>“SegNet: A deep convolutional encoder-decoder architecture for image segmentation,”</span> <em>IEEE Transactions on Pattern Analysis and Machine Intelligence</em>, vol. 39, no. 12, pp. 2481–2495, 2017.</div>
</div>
<div id="ref-Wang2020" class="csl-entry" role="listitem">
<div class="csl-left-margin">[26] </div>
<div class="csl-right-inline">S. Wang, T. H. McCormick, and J. T. Leek, <span>“Methods for correcting inference based on outcomes predicted by machine learning,”</span> <em>Proceedings of the National Academy of Sciences</em>, vol. 117, no. 48, pp. 30266–30275, 2020, doi: <a href="https://doi.org/10.1073/pnas.2001238117">10.1073/pnas.2001238117</a>.</div>
</div>
<div id="ref-Astruc2024" class="csl-entry" role="listitem">
<div class="csl-left-margin">[27] </div>
<div class="csl-right-inline">D. Astruc <em>et al.</em>, <span>“Self-supervised learning for remote sensing: Recent advances and future directions,”</span> <em>IEEE Geoscience and Remote Sensing Magazine</em>, vol. 12, no. 1, pp. 2–28, 2024.</div>
</div>
<div id="ref-wang2022self" class="csl-entry" role="listitem">
<div class="csl-left-margin">[28] </div>
<div class="csl-right-inline">Y. Wang, C. M. Albrecht, N. A. A. Braham, L. Mou, and X. X. Zhu, <span>“Self-supervised learning in remote sensing: A review,”</span> <em>IEEE Geoscience and Remote Sensing Magazine</em>, vol. 10, no. 4, pp. 213–247, 2022.</div>
</div>
<div id="ref-Gidaris2018" class="csl-entry" role="listitem">
<div class="csl-left-margin">[29] </div>
<div class="csl-right-inline">S. Gidaris <em>et al.</em>, <span>“Unsupervised representation learning by predicting image rotations,”</span> <em>International Conference on Learning Representations</em>, 2018.</div>
</div>
<div id="ref-Noroozi2016" class="csl-entry" role="listitem">
<div class="csl-left-margin">[30] </div>
<div class="csl-right-inline">M. Noroozi and P. Favaro, <span>“Unsupervised learning of visual representations by solving jigsaw puzzles,”</span> <em>European Conference on Computer Vision</em>, pp. 69–84, 2016.</div>
</div>
<div id="ref-Pathak2016" class="csl-entry" role="listitem">
<div class="csl-left-margin">[31] </div>
<div class="csl-right-inline">D. Pathak <em>et al.</em>, <span>“Context encoders: Feature learning by inpainting,”</span> <em>Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition</em>, pp. 2536–2544, 2016.</div>
</div>
<div id="ref-Caron2020" class="csl-entry" role="listitem">
<div class="csl-left-margin">[32] </div>
<div class="csl-right-inline">M. Caron <em>et al.</em>, <span>“Unsupervised learning of visual features by contrasting cluster assignments,”</span> <em>Advances in Neural Information Processing Systems</em>, vol. 33, pp. 9912–9924, 2020.</div>
</div>
<div id="ref-Chen2021" class="csl-entry" role="listitem">
<div class="csl-left-margin">[33] </div>
<div class="csl-right-inline">S. Chen <em>et al.</em>, <span>“Monitoring temperate forest degradation on <span>Google Earth Engine</span> using <span>Landsat</span> time series analysis,”</span> <em>Remote Sensing of Environment</em>, vol. 265, p. 112648, 2021, doi: <a href="https://doi.org/10.1016/j.rse.2021.112648">10.1016/j.rse.2021.112648</a>.</div>
</div>
<div id="ref-Grill2020" class="csl-entry" role="listitem">
<div class="csl-left-margin">[34] </div>
<div class="csl-right-inline">J. B. Grill <em>et al.</em>, <span>“Bootstrap your own latent: A new approach to self-supervised learning,”</span> <em>Advances in Neural Information Processing Systems</em>, vol. 33, pp. 21271–21284, 2020.</div>
</div>
<div id="ref-Bardes2022" class="csl-entry" role="listitem">
<div class="csl-left-margin">[35] </div>
<div class="csl-right-inline">A. Bardes <em>et al.</em>, <span>“VICReg: Variance-invariance-covariance regularization for self-supervised learning,”</span> <em>International Conference on Learning Representations</em>, 2022.</div>
</div>
<div id="ref-Wang2021" class="csl-entry" role="listitem">
<div class="csl-left-margin">[36] </div>
<div class="csl-right-inline">X. Wang <em>et al.</em>, <span>“Dense contrastive learning for self-supervised visual pre-training,”</span> <em>Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition</em>, pp. 3024–3033, 2021.</div>
</div>
<div id="ref-Chen2020" class="csl-entry" role="listitem">
<div class="csl-left-margin">[37] </div>
<div class="csl-right-inline">T. Chen <em>et al.</em>, <span>“A simple framework for contrastive learning of visual representations,”</span> <em>International Conference on Machine Learning</em>, pp. 1597–1607, 2020.</div>
</div>
<div id="ref-He2020" class="csl-entry" role="listitem">
<div class="csl-left-margin">[38] </div>
<div class="csl-right-inline">K. He <em>et al.</em>, <span>“Momentum contrast for unsupervised visual representation learning,”</span> <em>Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition</em>, pp. 9729–9738, 2020.</div>
</div>
<div id="ref-wu2018unsupervised" class="csl-entry" role="listitem">
<div class="csl-left-margin">[39] </div>
<div class="csl-right-inline">Z. Wu, Y. Xiong, S. X. Yu, and D. Lin, <span>“Unsupervised feature learning via non-parametric instance discrimination,”</span> in <em>Proceedings of the IEEE conference on computer vision and pattern recognition</em>, 2018, pp. 3733–3742.</div>
</div>
<div id="ref-Harwood2017" class="csl-entry" role="listitem">
<div class="csl-left-margin">[40] </div>
<div class="csl-right-inline">B. Harwood <em>et al.</em>, <span>“Smart mining for deep metric learning,”</span> <em>Proceedings of the IEEE International Conference on Computer Vision</em>, pp. 2821–2829, 2017.</div>
</div>
<div id="ref-Zbontar2021" class="csl-entry" role="listitem">
<div class="csl-left-margin">[41] </div>
<div class="csl-right-inline">J. Zbontar <em>et al.</em>, <span>“Barlow twins: Self-supervised learning via redundancy reduction,”</span> <em>International Conference on Machine Learning</em>, pp. 12310–12320, 2021.</div>
</div>
<div id="ref-da2025lightweight" class="csl-entry" role="listitem">
<div class="csl-left-margin">[42] </div>
<div class="csl-right-inline">M. P. Da Silva, L. Vieira, C. T. De Santana, I. M. Nunes, J. A. Dos Santos, and H. N. Oliveira, <span>“A lightweight pipeline for crop time-series parcel classification via self-supervision,”</span> <em>IEEE Geoscience and Remote Sensing Letters</em>, 2025.</div>
</div>
<div id="ref-Ribani2019" class="csl-entry" role="listitem">
<div class="csl-left-margin">[43] </div>
<div class="csl-right-inline">R. Ribani and M. Marengoni, <span>“A survey of transfer learning for convolutional neural networks,”</span> <em>IEEE Transactions on Neural Networks and Learning Systems</em>, vol. 30, no. 5, pp. 1–19, 2019.</div>
</div>
<div id="ref-Deng2009" class="csl-entry" role="listitem">
<div class="csl-left-margin">[44] </div>
<div class="csl-right-inline">J. Deng, W. Dong, R. Socher, L.-J. Li, K. Li, and L. Fei-Fei, <span>“<span>ImageNet</span>: <span>A</span> large-scale hierarchical image database,”</span> in <em>2009 <span>IEEE Conference</span> on <span>Computer Vision</span> and <span>Pattern Recognition</span></em>, 2009, pp. 248–255, doi: <a href="https://doi.org/10.1109/CVPR.2009.5206848">10.1109/CVPR.2009.5206848</a>.</div>
</div>
<div id="ref-Everingham2010" class="csl-entry" role="listitem">
<div class="csl-left-margin">[45] </div>
<div class="csl-right-inline">M. Everingham <em>et al.</em>, <span>“The pascal visual object classes (VOC) challenge,”</span> <em>International Journal of Computer Vision</em>, vol. 88, no. 2, pp. 303–338, 2010.</div>
</div>
<div id="ref-Lin2014" class="csl-entry" role="listitem">
<div class="csl-left-margin">[46] </div>
<div class="csl-right-inline">T. Y. Lin <em>et al.</em>, <span>“Microsoft COCO: Common objects in context,”</span> <em>European Conference on Computer Vision</em>, pp. 740–755, 2014.</div>
</div>
<div id="ref-Cortes1995" class="csl-entry" role="listitem">
<div class="csl-left-margin">[47] </div>
<div class="csl-right-inline">C. Cortes and V. Vapnik, <span>“Support-vector networks,”</span> <em>Machine learning</em>, vol. 20, no. 3, pp. 273–297, 1995.</div>
</div>
<div id="ref-Breiman2001" class="csl-entry" role="listitem">
<div class="csl-left-margin">[48] </div>
<div class="csl-right-inline">L. Breiman, <span>“Random <span>Forests</span>,”</span> <em>Machine Learning</em>, vol. 45, no. 1, pp. 5–32, 2001, doi: <a href="https://doi.org/10.1023/A:1010933404324">10.1023/A:1010933404324</a>.</div>
</div>
<div id="ref-oldoni2020lem" class="csl-entry" role="listitem">
<div class="csl-left-margin">[49] </div>
<div class="csl-right-inline">L. V. Oldoni, I. D. Sanches, M. C. A. Picoli, R. M. Covre, and J. G. Fronza, <span>“LEM+ dataset: For agricultural remote sensing applications,”</span> <em>Data in Brief</em>, vol. 33, p. 106553, 2020.</div>
</div>
<div id="ref-Sanches2018a" class="csl-entry" role="listitem">
<div class="csl-left-margin">[50] </div>
<div class="csl-right-inline">I. D. Sanches <em>et al.</em>, <span>“Campo verde database: Seeking to improve agricultural remote sensing of tropical areas,”</span> <em>IEEE Geoscience and Remote Sensing Letters</em>, vol. 15, no. 3, pp. 369–373, 2018.</div>
</div>
<div id="ref-persello2009novel" class="csl-entry" role="listitem">
<div class="csl-left-margin">[51] </div>
<div class="csl-right-inline">C. Persello and L. Bruzzone, <span>“A novel protocol for accuracy assessment in classification of very high resolution images,”</span> <em>IEEE Transactions on Geoscience and Remote Sensing</em>, vol. 48, no. 3, pp. 1232–1244, 2009.</div>
</div>
<div id="ref-Gorelick2017" class="csl-entry" role="listitem">
<div class="csl-left-margin">[52] </div>
<div class="csl-right-inline">N. Gorelick, M. Hancher, M. Dixon, S. Ilyushchenko, D. Thau, and R. Moore, <span>“Google <span>Earth Engine</span>: <span class="nocase">Planetary-scale</span> geospatial analysis for everyone,”</span> <em>Remote Sensing of Environment</em>, vol. 202, pp. 18–27, 2017.</div>
</div>
<div id="ref-yolo11_ultralytics" class="csl-entry" role="listitem">
<div class="csl-left-margin">[53] </div>
<div class="csl-right-inline">G. Jocher and J. Qiu, <span>“Ultralytics YOLO11.”</span> 2024, [Online]. Available: <a href="https://github.com/ultralytics/ultralytics">https://github.com/ultralytics/ultralytics</a>.</div>
</div>
<div id="ref-Yuan2022" class="csl-entry" role="listitem">
<div class="csl-left-margin">[54] </div>
<div class="csl-right-inline">Y. Yuan, L. Lin, Q. Liu, R. Hang, and Z.-G. Zhou, <span>“<span>SITS-Former</span>: <span>A</span> pre-trained spatio-spectral-temporal representation model for <span>Sentinel-2</span> time series classification,”</span> <em>International Journal of Applied Earth Observation and Geoinformation</em>, vol. 106, p. 102651, 2022, doi: <a href="https://doi.org/10.1016/j.jag.2021.102651">10.1016/j.jag.2021.102651</a>.</div>
</div>
<div id="ref-Srisailam2024" class="csl-entry" role="listitem">
<div class="csl-left-margin">[55] </div>
<div class="csl-right-inline">G. Srisailam <em>et al.</em>, <span>“Temporal transformers for crop classification using satellite image time series,”</span> <em>ISPRS Journal of Photogrammetry and Remote Sensing</em>, vol. 197, pp. 1–15, 2024.</div>
</div>
<div id="ref-Xu2024" class="csl-entry" role="listitem">
<div class="csl-left-margin">[56] </div>
<div class="csl-right-inline">W. Xu <em>et al.</em>, <span>“Mapping Fruit-Tree Plantation Using Sentinel-1/2 Time Series Images with Multi-Index Entropy Weighting Dynamic Time Warping Method,”</span> <em>Remote Sensing</em>, vol. 16, no. 18, p. 3390, Sep. 2024, doi: <a href="https://doi.org/10.3390/rs16183390">10.3390/rs16183390</a>.</div>
</div>
<div id="ref-Silva2024a" class="csl-entry" role="listitem">
<div class="csl-left-margin">[57] </div>
<div class="csl-right-inline">H. F. Silva <em>et al.</em>, <span>“Crop type classification using transformer networks and multi-temporal sentinel-2 imagery,”</span> <em>Remote Sensing of Environment</em>, vol. 280, p. 113214, 2024.</div>
</div>
<div id="ref-xu2022eyes" class="csl-entry" role="listitem">
<div class="csl-left-margin">[58] </div>
<div class="csl-right-inline">M. Xu, M. Wu, K. Chen, C. Zhang, and J. Guo, <span>“The eyes of the gods: A survey of unsupervised domain adaptation methods based on remote sensing data,”</span> <em>Remote Sensing</em>, vol. 14, no. 17, p. 4380, 2022.</div>
</div>
<div id="ref-Kalantidis2020" class="csl-entry" role="listitem">
<div class="csl-left-margin">[59] </div>
<div class="csl-right-inline">Y. Kalantidis <em>et al.</em>, <span>“Hard negative mixing for contrastive learning,”</span> <em>Advances in Neural Information Processing Systems</em>, vol. 33, pp. 1–12, 2020.</div>
</div>
<div id="ref-Robinson2020" class="csl-entry" role="listitem">
<div class="csl-left-margin">[60] </div>
<div class="csl-right-inline">J. Robinson, C.-Y. Chuang, S. Sra, and S. Jegelka, <span>“Contrastive learning with hard negative samples,”</span> <em>arXiv preprint arXiv:2010.04592</em>, 2020.</div>
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/FAO-EOSTAT\.github\.io\/UN-Handbook\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./th_alignment.html" class="pagination-link" aria-label="Alignment of field data collection to EO statistical requirements">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Alignment of field data collection to EO statistical requirements</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./crop_type_mapping.html" class="pagination-link" aria-label="Use Cases in Crop Type Mapping">
        <span class="nav-page-text">Use Cases in Crop Type Mapping</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>Edited by Gilberto Camara, Lorenzo de Simone and Ronald Jansen.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/FAO-EOSTAT/UN-Handbook/edit/quarto/th_parcel_extraction.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/FAO-EOSTAT/UN-Handbook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>


</body></html>