<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Gilberto Camara, Lorenzo de Simone, Ronald Jansen">
<title>33&nbsp; Integrating UAV Imagery into Agricultural Statistics in the Cook Islands – UN Handbook on Remote Sensing for Agricultural Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./disaster_response.html" rel="next">
<link href="./uav_crop_growth.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-931bd9de4a2e97c797357f31cd37fa94.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="site_libs/kePrint-0.0.1/kePrint.js"></script><link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./uav_agriculture.html">UAV applications in agricultural statistics</a></li><li class="breadcrumb-item"><a href="./uav_agriculture_cook_islands.html"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Integrating UAV Imagery into Agricultural Statistics in the Cook Islands</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">UN Handbook on Remote Sensing for Agricultural Statistics</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/FAO-EOSTAT/UN-Handbook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Welcome</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./howto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">How to use this handbook</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_remote_sensing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Remote sensing images: optical, SAR</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_data_sources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Earth observation big data sources</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_data_cubes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Earth observation data cubes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_lucc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Land cover and crop classification schemas</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_quality_control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Quality control of training sets for agricultural statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_machine_learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Machine learning algorithms for image time series</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_uncertainty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Spatial map uncertainty estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Map validation and use of maps for area estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_design_frames.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Remote Sensing in the Design of Sampling Frames</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_alignment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Alignment of field data collection to EO statistical requirements</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_parcel_extraction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Semantic Segmentation for Automatic Field Boundary Delineation</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./crop_type_mapping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Use Cases in Crop Type Mapping</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_poland.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Crop monitoring with Sentinel-1 and Sentinel-2 images in Poland</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_mexico.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Crop classification in Mexico</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_zimbabwe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Crop classification in Zimbabwe</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_china.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Efficient and Reliable Paddy Rice Classification</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_chile.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Crop classification and land use mapping in Chile</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_digital_earth_africa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Agricultural Mapping with Digital Earth Africa</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./crop_yield_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Crop yield estimation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_finland.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Early-season crop yield mapping in Finland</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_indonesia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Mapping crop phenology in Indonesia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_colombia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Rice Phenology Mapping in Colombia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_poland.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Yield forecasting in Poland</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_china.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Remote Sensing Estimation of Soybean Yield Based on Multi-Scenario Simulation</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./crop_statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Extraction of crop statistics from crop type and crop yield maps</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./crop_statistics_area.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Crop Statistics using Weighted Area Estimators</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./crop_statistics_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Survey – Maize acreage estimation in Zimbabwe</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./crop_statistics_calibration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Estimating crop statistics for list frame data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./crop_statistics_ppi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Prediction-Powered Inference (PPI) for Agricultural Decision-Making</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./uav_agriculture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">UAV applications in agricultural statistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uav_field_parcels.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Field Parcel Identification Using UAV Imagery Based on the DCP-MTL Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uav_wheat_growth.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Application of UAV in Wheat Growth Monitoring</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uav_crop_growth.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Automated Monitoring of Crop Growth Index using UAV</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uav_agriculture_cook_islands.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Integrating UAV Imagery into Agricultural Statistics in the Cook Islands</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./disaster_response.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Remote Sensing for Agricultural Disaster Response</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dis_china_floods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">An Automated Flood Detection Algorithm for Post-Disaster Assessment</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./additional.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Additional Topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ad_world_cereal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">WorldCereal - A Global Effort for Crop Mapping</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ad_learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Personalised Learning Program for Training in the Use of Earth Observation for Agricultural Statistics</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">33.1</span> Introduction</a></li>
  <li><a href="#study-area" id="toc-study-area" class="nav-link" data-scroll-target="#study-area"><span class="header-section-number">33.2</span> Study Area</a></li>
  <li><a href="#uav-image-acquisition-and-processing" id="toc-uav-image-acquisition-and-processing" class="nav-link" data-scroll-target="#uav-image-acquisition-and-processing"><span class="header-section-number">33.3</span> UAV Image Acquisition and Processing</a></li>
  <li><a href="#agricultural-plot-delineation" id="toc-agricultural-plot-delineation" class="nav-link" data-scroll-target="#agricultural-plot-delineation"><span class="header-section-number">33.4</span> Agricultural Plot Delineation</a></li>
  <li><a href="#data-and-software-requirements" id="toc-data-and-software-requirements" class="nav-link" data-scroll-target="#data-and-software-requirements"><span class="header-section-number">33.5</span> Data and Software Requirements</a></li>
  <li>
<a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">33.6</span> Results</a>
  <ul class="collapse">
<li><a href="#environment-setup-and-data-loading" id="toc-environment-setup-and-data-loading" class="nav-link" data-scroll-target="#environment-setup-and-data-loading"><span class="header-section-number">33.6.1</span> Environment Setup and Data Loading</a></li>
  <li><a href="#coordinate-reference-system-harmonization" id="toc-coordinate-reference-system-harmonization" class="nav-link" data-scroll-target="#coordinate-reference-system-harmonization"><span class="header-section-number">33.6.2</span> Coordinate Reference System Harmonization</a></li>
  <li><a href="#initial-visualization" id="toc-initial-visualization" class="nav-link" data-scroll-target="#initial-visualization"><span class="header-section-number">33.6.3</span> Initial Visualization</a></li>
  <li><a href="#area-of-study-and-plot-boundaries" id="toc-area-of-study-and-plot-boundaries" class="nav-link" data-scroll-target="#area-of-study-and-plot-boundaries"><span class="header-section-number">33.6.4</span> Area of Study and Plot boundaries</a></li>
  <li><a href="#visualization-of-ndvi-values" id="toc-visualization-of-ndvi-values" class="nav-link" data-scroll-target="#visualization-of-ndvi-values"><span class="header-section-number">33.6.5</span> Visualization of NDVI values</a></li>
  <li><a href="#calculating-plot-level-ndvi-statistics" id="toc-calculating-plot-level-ndvi-statistics" class="nav-link" data-scroll-target="#calculating-plot-level-ndvi-statistics"><span class="header-section-number">33.6.6</span> Calculating Plot-Level NDVI Statistics</a></li>
  <li><a href="#resolution-comparison-uav-vs.-satellite-imagery" id="toc-resolution-comparison-uav-vs.-satellite-imagery" class="nav-link" data-scroll-target="#resolution-comparison-uav-vs.-satellite-imagery"><span class="header-section-number">33.6.7</span> Resolution Comparison: UAV vs.&nbsp;Satellite Imagery</a></li>
  <li><a href="#quantifying-resolution-differences" id="toc-quantifying-resolution-differences" class="nav-link" data-scroll-target="#quantifying-resolution-differences"><span class="header-section-number">33.6.8</span> Quantifying Resolution Differences</a></li>
  <li><a href="#mixed-pixel-problem" id="toc-mixed-pixel-problem" class="nav-link" data-scroll-target="#mixed-pixel-problem"><span class="header-section-number">33.6.9</span> Mixed Pixel Problem</a></li>
  </ul>
</li>
  <li>
<a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">33.7</span> Discussion</a>
  <ul class="collapse">
<li><a href="#operational-challenges-using-uav-for-agricultural-statistics" id="toc-operational-challenges-using-uav-for-agricultural-statistics" class="nav-link" data-scroll-target="#operational-challenges-using-uav-for-agricultural-statistics"><span class="header-section-number">33.7.1</span> <strong>Operational Challenges using UAV for agricultural statistics</strong></a></li>
  <li><a href="#strategies-for-effective-integration-of-uav-imagery-into-agricultural-statistics" id="toc-strategies-for-effective-integration-of-uav-imagery-into-agricultural-statistics" class="nav-link" data-scroll-target="#strategies-for-effective-integration-of-uav-imagery-into-agricultural-statistics"><span class="header-section-number">33.7.2</span> <strong>Strategies for Effective Integration of UAV imagery into agricultural statistics</strong></a></li>
  </ul>
</li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">33.8</span> Conclusion</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/FAO-EOSTAT/UN-Handbook/edit/quarto/uav_agriculture_cook_islands.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/FAO-EOSTAT/UN-Handbook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./uav_agriculture.html">UAV applications in agricultural statistics</a></li><li class="breadcrumb-item"><a href="./uav_agriculture_cook_islands.html"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Integrating UAV Imagery into Agricultural Statistics in the Cook Islands</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title">
<span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Integrating UAV Imagery into Agricultural Statistics in the Cook Islands</span>
</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Takaaki Masaki, Anthony D. Burgard </p>
          </div>
  </div>
    
  
    
  </div>
  


</header><section id="introduction" class="level2" data-number="33.1"><h2 data-number="33.1" class="anchored" data-anchor-id="introduction">
<span class="header-section-number">33.1</span> Introduction</h2>
<p>Accurate land area estimates form the foundation of reliable agricultural statistics, providing critical inputs for estimating crop production, calculating yield, and informing key agricultural policy decisions. Traditional ground surveys where these data are collected, however, face significant resource constraints, especially in the Pacific Islands, where environmental conditions, physical distance between islands, and natural barriers can make data collection cost-prohibitive.</p>
<p>In 2022, the Asian Development Bank (ADB), in collaboration with the Cook Islands Ministry of Agriculture (MOA), conducted a post-enumeration survey on the island of Rarotonga to validate agricultural area estimates using global positioning systems (GPS) reported in the 2021 Cook Islands Census of Agriculture. The study revealed that farmers generally underestimated their agricultural land areas by approximately 13% relative to objective GPS measurements, with larger plots (&gt;2,000 m²) more likely underestimated and smaller plots slightly overestimated <span class="citation" data-cites="AsianDevelopmentBank2024"><a href="#ref-AsianDevelopmentBank2024" role="doc-biblioref">[1]</a></span>. This discrepancy highlights the significance of non-sampling errors, specifically measurement error, that can systematically bias national agricultural production estimates.</p>
<p>In a follow-up activity conducted in 2023, the ADB team with the MOA employed Unmanned Aerial Vehicles (UAVs) to capture high-resolution imagery and measure agricultural land areas, aiming to reduce resource intensity of field surveys in environmentally challenging terrain. While initial resource constraints may be higher, high-resolution imagery captured by UAV enabled precise plot boundary delineation and area measurements. UAVs were found to be particularly suitable for the Pacific context, where frequent cloud cover, fragmented land plots, and difficult terrain require flexible, localized, and detailed data collection methods.</p>
<p>Drawing on the 2023 Cook Islands UAV survey of a census enumeration area on Rarotonga, this chapter has two aims: (i) to provide a reproducible, end-to-end workflow in R — from loading orthophotos and vector boundaries, harmonizing CRS, and visualizing imagery to computing plot-level zonal statistics — and (ii) to demonstrate, through a worked case study, how very high-resolution data (≈1.6-cm GSD) enables agricultural statistics that are difficult or impossible with 10–30 m satellite sensors. Using RGB and multispectral imagery, we quantify plot areas and derive vegetation indicators such as Normalized Difference Vegetation Index (NDVI) (mean, min–max, and within-plot coefficient of variation), revealing fine-scale patterns in crop vigor and heterogeneity that are obscured at coarser resolutions. We then contrast these plot-level metrics with Sentinel-2 and Landsat-8 views to illustrate mixed-pixel effects and the implications for area estimation, monitoring, and operational decision-making.</p>
<p>This chapter provides an analytical framework for working with UAV imagery in R to produce agricultural statistics. Specific objectives include importing and harmonizing raster layers (RGB and NDVI orthophotos) and vector boundaries (study area and plot polygons) to a common coordinate reference system, extracting agricultural statistics through zonal analysis of NDVI values for individual plots, calculating plot areas, and comparing spatial resolution across UAV, Sentinel-2, and Landsat-8 imagery to quantify the mixed-pixel effect and its implications for area estimation accuracy.</p>
<p>By the end of this chapter, you will be able to:</p>
<ul>
<li><p>Understand the UAV imagery workflow from flight planning to mapping output</p></li>
<li><p>Load and visualize RGB (true color) and NDVI UAV imagery in R</p></li>
<li><p>Load and manage vector data in R</p></li>
<li><p>Extract plot-level zonal statistics from UAV imagery</p></li>
<li><p>Compare spatial resolutions of UAV versus publicly available satellite imagery</p></li>
</ul></section><section id="study-area" class="level2" data-number="33.2"><h2 data-number="33.2" class="anchored" data-anchor-id="study-area">
<span class="header-section-number">33.2</span> Study Area</h2>
<p>The study area comprises a single census enumeration area located on the northeastern coast of Rarotonga island in the Cook Islands encompassing 17.6 hectares. This area was selected to enable cross-validation with area estimates from the 2022 Agriculture Census and post-Agriculture Census enumeration survey. The terrain in the study area is characterized by flat topography extending from inland residential areas to the beach and ocean along the eastern boundary. Land use is mixed, including residential, sports facilities (i.e., rugby field), and fragmented agricultural plots scattered throughout the area.</p>
</section><section id="uav-image-acquisition-and-processing" class="level2" data-number="33.3"><h2 data-number="33.3" class="anchored" data-anchor-id="uav-image-acquisition-and-processing">
<span class="header-section-number">33.3</span> UAV Image Acquisition and Processing</h2>
<p>UAV imagery of the study area was captured on 28 August 2023 at midday. Two flight missions were conducted: the first using an RGB camera captured 347 aerial images (<a href="ad_world_cereal.html#fig-1" class="quarto-xref">Figure&nbsp;<span>35.1</span></a>), while the second using a multispectral sensor captured 318 images. Flight missions were planned using DJI Flight Planner software, where operators specified resolution requirements by setting flight height (~100 meters) and image overlap percentages (~80 percent) to ensure adequate coverage.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/uav_agriculture_cook_islands/flight-path.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;33.1: Position of 347 RGB aerial images
</figcaption></figure>
</div>
</div>
</div>
<p>The processing of these raw aerial images was conducted in <a href="https://opendronemap.org">OpenDroneMap</a>, a free and open-source photogrammetry software that stitches overlapping raw UAV images into a geometrically corrected single image known as an orthophoto. The software first uses a Structure-from-Motion (SfM) method (<span class="citation" data-cites="Valorie2023"><a href="#ref-Valorie2023" role="doc-biblioref">[2]</a></span>), which identifies thousands of common feature points across the aerial images to reconstruct the camera’s position for each photo and build an initial three-dimensional model of the terrain and its features (<a href="ad_world_cereal.html#fig-2" class="quarto-xref">Figure&nbsp;<span>35.2</span></a>).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/uav_agriculture_cook_islands/3dmodel.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;33.2: 3D model of Study Area constructed from RGB aerial images
</figcaption></figure>
</div>
</div>
</div>
<p>Prior to the flights, operators surveyed the area to establish 23 Ground Control Points (GCPs), a centimeter-level precision point geographic coordinates distributed throughout the study area. The coordinates of these markers were measured using high-precision Global Navigation Satellite System (GNSS) receivers. During processing in OpenDroneMap, these GCPs are overlaid in the UAV imagery. The software then warps the 3D model to fit these known coordinates, correcting geometric distortions and ensuring the final orthophoto is accurately georeferenced. This step is critical for calculating reliable area calculations as it ensures the orthophoto is not biased by any distortions within the image.</p>
<p>The combination of the three-dimensional model and ground control points produces of an orthophoto, a geometrically corrected single image of the study area. This process is repeated for both our RGB and multispectral imagery, resulting in two orthophotos of the same study area taken by two camera sensors.</p>
<p>In addition to orthophotos, we also utilize OpenDroneMap to calculate crop health indicators for crop health analysis. The platform calculates 23 spectral indices from the multispectral orthophoto (<a href="ad_world_cereal.html#fig-3" class="quarto-xref">Figure&nbsp;<span>35.3</span></a>), and their calculations are documented on the OpenDroneMap github repository <a href="https://github.com/OpenDroneMap/WebODM/blob/master/app/api/fields.py">here</a>. These indices include the NDVI, which assesses plant vigor and photosynthetic activity. Additional indices enable detection of water stress, estimation of biomass, and soil reflectance in fallow areas.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-3" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/uav_agriculture_cook_islands/spectralindices/slides-combined.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;33.3: Crop Health Algorithms in OpenDroneMap
</figcaption></figure>
</div>
</div>
</div>
</section><section id="agricultural-plot-delineation" class="level2" data-number="33.4"><h2 data-number="33.4" class="anchored" data-anchor-id="agricultural-plot-delineation">
<span class="header-section-number">33.4</span> Agricultural Plot Delineation</h2>
<p>Using the RGB orthophoto as a basemap, a subject matter expert from the Cook Islands Ministry of Agriculture manually digitized plot boundaries as polygon features in QGIS based on visual inspection of land use and plot boundaries of areas cultivated for crops. This digitization process produced 36 individual agricultural plots polygons.</p>
</section><section id="data-and-software-requirements" class="level2" data-number="33.5"><h2 data-number="33.5" class="anchored" data-anchor-id="data-and-software-requirements">
<span class="header-section-number">33.5</span> Data and Software Requirements</h2>
<p>The analysis utilizes four primary datasets:</p>
<ul>
<li><p><strong>RGB Orthophoto</strong>: A true-color raster image stitched using OpenDroneMap from 347 images captured on 28 August 2023 with a DJI Matrice 210.</p></li>
<li><p><strong>NDVI Orthophoto</strong>: A raster image with the NDVI (values from -1 to 1) stitched and calculated in OpenDroneMap from 318 multispectral sensor images captured on 28 August 2023.</p></li>
<li><p><strong>Study Area Boundary</strong>: A vector shapefile representing the boundary of a census enumeration area in Rarotonga, Cook Islands. The boundary covers an area of ~ 17.6 hectares.</p></li>
<li><p><strong>Plot Boundaries</strong>: 36 individual agricultural plot polygons digitized by a subject matter expert from the Cook Islands Ministry of Agriculture using the RGB Orthophoto as a basemap.</p></li>
</ul>
<p>To implement the examples in this chapter we use:</p>
<ul>
<li><p><strong>R</strong> (version 4.0+) and <strong>RStudio</strong></p></li>
<li><p><strong>R packages</strong>: <code>terra (1.8-70)</code>, <code>sf 1.0-21</code>, <code>ggplot2 4.0.0</code>, <code>tmap 4.2</code>, <code>dplyr 1.1.4</code></p></li>
<li><p><strong>Data files</strong>: RGB orthophoto, NDVI raster, boundary shapefiles (provided as an R project)</p></li>
</ul>
<!-- **Important**: Open the provided files as an R project in RStudio to ensure proper file paths and organization. --><!-- All exercises include complete code examples. Basic R familiarity is helpful but not required.  --></section><section id="results" class="level2" data-number="33.6"><h2 data-number="33.6" class="anchored" data-anchor-id="results">
<span class="header-section-number">33.6</span> Results</h2>
<section id="environment-setup-and-data-loading" class="level3" data-number="33.6.1"><h3 data-number="33.6.1" class="anchored" data-anchor-id="environment-setup-and-data-loading">
<span class="header-section-number">33.6.1</span> Environment Setup and Data Loading</h3>
<p>To work with both raster and vector data in this chapter, we will use the <strong>terra</strong> package for raster analysis (UAV imagery) and <strong>sf</strong> for vector data (boundary and plot polygons). For data manipulation and visualization, we will use <strong>dplyr</strong>, <strong>ggplot2</strong>, and <strong>tmap</strong>.</p>
<p>Next, we load the 2023 Cook Islands UAV survey data. The files for this exercise are provided in an R project file, which automatically sets the working directory to the project folder upon opening.</p>
<p>Let’s begin with the <code>rgb</code> UAV orthomosiac image</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">rgb</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatRaster 
size        : 33927, 43962, 4  (nrow, ncol, nlyr)
resolution  : 1.503361e-07, 1.503361e-07  (x, y)
extent      : -159.7378, -159.7312, -21.22726, -21.22216  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 (EPSG:4326) 
source      : Map1_Orthomosaic_export_WedAug30060354143404.tif 
names       : Map1_Or~43404_1, Map1_Or~43404_2, Map1_Or~43404_3, Map1_Or~43404_4 
min values  :               0,               0,               0,              ?  
max values  :             255,             255,             255,              ?  </code></pre>
</div>
</div>
<p>The <code>print(rgb)</code> output shows the RGB orthophoto contains 33,927 rows and 43,962 columns across 4 layers (red, green, blue, and alpha transparency). The resolution of 1.503361e-07 degrees per pixel corresponds to approximately 1.6 centimeters ground sample distance. The data uses the WGS 84 geographic coordinate system (EPSG:4326) with coordinates in decimal degrees.</p>
<p>Now print the <code>ndvi</code> raster details. What differences do you observe compared to the <code>rgb</code> raster?</p>
<p>Next, examine the <code>plots</code> vector file.</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">plots</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 36 features and 1 field
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: -159.7374 ymin: -21.22671 xmax: -159.7324 ymax: -21.22302
Geodetic CRS:  WGS 84
First 10 features:
   id                       geometry
1   1 POLYGON ((-159.7353 -21.224...
2   2 POLYGON ((-159.7353 -21.224...
3   3 POLYGON ((-159.7353 -21.224...
4   4 POLYGON ((-159.7353 -21.224...
5   5 POLYGON ((-159.7357 -21.224...
6   6 POLYGON ((-159.7364 -21.225...
7   7 POLYGON ((-159.7358 -21.225...
8   8 POLYGON ((-159.7363 -21.225...
9   9 POLYGON ((-159.7365 -21.225...
10 10 POLYGON ((-159.7366 -21.226...</code></pre>
</div>
</div>
<p>The <code>print(plots)</code> output shows the shapefile contains 36 individual agricultural plots, each stored as polygon geometry with one attribute field (<code>id</code> or plot ID). The bounding box indicates the geographic extent in decimal degrees, and the data uses the WGS 84 coordinate system consistent with the orthophoto.</p>
<p>Now examine the <code>study_area</code> shapefile using the same approach.</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">study_area</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 1 feature and 4 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: -159.7376 ymin: -21.22684 xmax: -159.7318 ymax: -21.22273
Geodetic CRS:  WGS 84
  eaid          ea_name cdid gid                       geometry
1 1202 matavera central   12   1 POLYGON ((-159.7326 -21.226...</code></pre>
</div>
</div>
</section><section id="coordinate-reference-system-harmonization" class="level3" data-number="33.6.2"><h3 data-number="33.6.2" class="anchored" data-anchor-id="coordinate-reference-system-harmonization">
<span class="header-section-number">33.6.2</span> Coordinate Reference System Harmonization</h3>
<p>Before conducting any further analysis, all layers must use compatible coordinate reference systems (CRS). Mismatched coordinate systems may cause misaligned layers and incorrect area calculations.</p>
<p>First, verify that all layers use the same coordinate reference system:</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Check coordinate reference systems</span></span>
<span><span class="fu">crs</span><span class="op">(</span><span class="va">rgb</span>, describe<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span><span class="op">$</span><span class="va">code</span>      <span class="co"># rgb (raster)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "4326"</code></pre>
</div>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">crs</span><span class="op">(</span><span class="va">ndvi</span>, describe<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span><span class="op">$</span><span class="va">code</span>     <span class="co"># ndvi (raster)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "32704"</code></pre>
</div>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">st_crs</span><span class="op">(</span><span class="va">study_area</span><span class="op">)</span><span class="op">$</span><span class="va">epsg</span>           <span class="co"># study area (vector)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4326</code></pre>
</div>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">st_crs</span><span class="op">(</span><span class="va">plots</span><span class="op">)</span><span class="op">$</span><span class="va">epsg</span>                <span class="co"># agriculture plots (vector)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4326</code></pre>
</div>
</div>
<p>Notice the NDVI raster uses WGS 84 / UTM Zone 4S (EPSG:32704) with units in meters, while other layers use WGS 84 geographic coordinates (EPSG:4326) with units in degrees. It is reccomended to first reproject all layers to UTM Zone 4S. This coordinate system is recommended for the Cook Islands because the islands fall within the geographic boundaries of this zone in the Universal Transverse Mercator coordinate system, and for the purposes of this analysis, distance measurements are provided in meters.</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Define target projection</span></span>
<span><span class="va">target_crs</span> <span class="op">&lt;-</span> <span class="st">"EPSG:32704"</span></span>
<span></span>
<span><span class="co"># Transform vector data to UTM Zone 4S</span></span>
<span><span class="va">study_area</span> <span class="op">&lt;-</span> <span class="fu">st_transform</span><span class="op">(</span><span class="va">study_area</span>, <span class="va">target_crs</span><span class="op">)</span></span>
<span><span class="va">plots</span> <span class="op">&lt;-</span> <span class="fu">st_transform</span><span class="op">(</span><span class="va">plots</span>, <span class="va">target_crs</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Transform RGB and NDVI raster to UTM Zone 4S</span></span>
<span><span class="va">rgb</span> <span class="op">&lt;-</span> <span class="fu">project</span><span class="op">(</span><span class="va">rgb</span>, <span class="va">target_crs</span>, method<span class="op">=</span><span class="st">"bilinear"</span><span class="op">)</span></span>
<span><span class="va">ndvi</span> <span class="op">&lt;-</span> <span class="fu">project</span><span class="op">(</span><span class="va">ndvi</span>, <span class="va">target_crs</span>, method<span class="op">=</span><span class="st">"bilinear"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>After reprojection, the resolution of the RGB orthophoto is expressed in meters (approximately 0.016 m) and spatial extents use UTM coordinates in meters rather than degrees.</p>
</section><section id="initial-visualization" class="level3" data-number="33.6.3"><h3 data-number="33.6.3" class="anchored" data-anchor-id="initial-visualization">
<span class="header-section-number">33.6.3</span> Initial Visualization</h3>
<p>To confirm spatial alignment of the RGB raster and vector files, we will first create a map displaying all data layers. This visualization verifies that the orthophoto, plot boundaries, and study area boundary are properly aligned following reprojection to the common coordinate reference system:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">plotRGB</span><span class="op">(</span><span class="va">rgb</span><span class="op">)</span> <span class="co"># Add RGB orthophoto</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu">st_geometry</span><span class="op">(</span><span class="va">plots</span><span class="op">)</span>, add <span class="op">=</span> <span class="cn">TRUE</span>, border <span class="op">=</span> <span class="st">"white"</span>, lwd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="co"># Add Plots</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu">st_geometry</span><span class="op">(</span><span class="va">study_area</span><span class="op">)</span>, add <span class="op">=</span> <span class="cn">TRUE</span>, border <span class="op">=</span> <span class="st">"yellow"</span>, lwd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="co"># Add Study Area</span></span>
<span></span>
<span><span class="fu">sbar</span><span class="op">(</span><span class="fl">200</span>, type <span class="op">=</span> <span class="st">"line"</span>, xy <span class="op">=</span> <span class="st">"bottom"</span>, divs <span class="op">=</span> <span class="fl">8</span>, below <span class="op">=</span> <span class="st">"meters"</span>, col <span class="op">=</span> <span class="st">"black"</span><span class="op">)</span></span>
<span><span class="fu">north</span><span class="op">(</span>type <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="co"># Add scalebar and compass</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-ortho-rgb" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-ortho-rgb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="uav_agriculture_cook_islands_files/figure-html/fig-ortho-rgb-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ortho-rgb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;33.4: RGB Orthophoto showing the study area boundary (yellow) and individual agricultural plot boundaries (white).
</figcaption></figure>
</div>
</div>
</div>
</section><section id="area-of-study-and-plot-boundaries" class="level3" data-number="33.6.4"><h3 data-number="33.6.4" class="anchored" data-anchor-id="area-of-study-and-plot-boundaries">
<span class="header-section-number">33.6.4</span> Area of Study and Plot boundaries</h3>
<p>To quantify the extent of the study area and plot boundaries, we calculate their areas:</p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Calculate study area size</span></span>
<span><span class="va">study_area_m2</span> <span class="op">&lt;-</span> <span class="fu">st_area</span><span class="op">(</span><span class="va">study_area</span><span class="op">)</span></span>
<span><span class="va">study_area_ha</span> <span class="op">&lt;-</span> <span class="va">study_area_m2</span> <span class="op">/</span> <span class="fl">10000</span>  <span class="co"># Convert to hectares</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, calculate the area for each of the 36 digitized plot boundaries in square meters, examine summary statistics across all plots, and visualize the distribution of plot sizes using a histogram:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Calculate area for each plot in square meters</span></span>
<span><span class="va">plots</span><span class="op">$</span><span class="va">area_m2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="fu">st_area</span><span class="op">(</span><span class="va">plots</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Summary statistics in square meters</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">plots</span><span class="op">$</span><span class="va">area_m2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  47.69  492.87  888.42  873.47 1200.68 1615.68 </code></pre>
</div>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Figure: Visualize distribution of plot sizes</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/hist.html">hist</a></span><span class="op">(</span><span class="va">plots</span><span class="op">$</span><span class="va">area_m2</span>, </span>
<span>     breaks <span class="op">=</span> <span class="fl">15</span>,</span>
<span>     main <span class="op">=</span> <span class="st">"Distribution of Plot Sizes"</span>,</span>
<span>     xlab <span class="op">=</span> <span class="st">"Area (square meters)"</span>,</span>
<span>     col  <span class="op">=</span> <span class="st">"lightblue"</span>,</span>
<span>     border <span class="op">=</span> <span class="st">"white"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-hist-sizes" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-hist-sizes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="uav_agriculture_cook_islands_files/figure-html/fig-hist-sizes-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hist-sizes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;33.5: Distribution of plot sizes (square meters) in study area
</figcaption></figure>
</div>
</div>
</div>
</section><section id="visualization-of-ndvi-values" class="level3" data-number="33.6.5"><h3 data-number="33.6.5" class="anchored" data-anchor-id="visualization-of-ndvi-values">
<span class="header-section-number">33.6.5</span> Visualization of NDVI values</h3>
<p>We now turn to the NDVI raster of the study area. NDVI ranges from -1 to 1, where values below 0 typically indicate water or bare soil, values between 0.2 and 0.4 indicate sparse or stressed vegetation, values between 0.4 and 0.6 indicate moderate vegetation vigor, and values above 0.6 indicate dense, healthy vegetation. Monitoring NDVI enables identification of crop stress from water deficit, nutrient deficiencies, pests, or disease. It distinguishes vegetated areas from bare soil, water, or built structures, and monitoring changes over time reveals agricultural cycles, drought impacts, deforestation, or vegetation regrowth patterns.</p>
<p>Higher NDVI values, however, do not necessarily indicate better crop health, as dense weeds, overgrown vegetation, or mature crops can also produce higher NDVI values. Interpreting NDVI requires careful consideration of local conditions and validation with ground observations. It is not a standalone measure of crop health and can be misleading without contextual information about land use, crop types, and agricultural practices.</p>
<p>Next, create a map using the NDVI raster as the basemap to visualize vegetation health patterns. The color gradient transitions from red (low vegetation/bare soil) to green (high vegetation vigor), with plot boundaries (white) and study area boundary (black) overlaid.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Create NDVI color scheme</span></span>
<span><span class="va">ndvi_colors</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/grDevices/colorRamp.html">colorRampPalette</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  <span class="st">"#8B0000"</span>,  <span class="co"># Dark red (very low NDVI)</span></span>
<span>  <span class="st">"#FF0000"</span>,  <span class="co"># Bright red (low NDVI)</span></span>
<span>  <span class="st">"#FF6B00"</span>,  <span class="co"># Orange (low-medium NDVI)</span></span>
<span>  <span class="st">"#FFFF00"</span>,  <span class="co"># Yellow (medium NDVI)</span></span>
<span>  <span class="st">"#9ACD32"</span>,  <span class="co"># Yellow-green (medium-high NDVI)</span></span>
<span>  <span class="st">"#228B22"</span>,  <span class="co"># Forest green (high NDVI)</span></span>
<span>  <span class="st">"#006400"</span>   <span class="co"># Dark green (very high NDVI)</span></span>
<span><span class="op">)</span><span class="op">)</span><span class="op">(</span><span class="fl">100</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Figure: NDVI Orthophoto Showing Plot Boundaries and Study Area</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">ndvi</span>, </span>
<span>     col<span class="op">=</span><span class="va">ndvi_colors</span>,</span>
<span>     main<span class="op">=</span><span class="st">"NDVI Orthophoto Showing Plot Boundaries and Study Area"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu">st_geometry</span><span class="op">(</span><span class="va">plots</span><span class="op">)</span>, add <span class="op">=</span> <span class="cn">TRUE</span>, border <span class="op">=</span> <span class="st">"white"</span>, lwd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu">st_geometry</span><span class="op">(</span><span class="va">study_area</span><span class="op">)</span>, add <span class="op">=</span> <span class="cn">TRUE</span>, border <span class="op">=</span> <span class="st">"black"</span>, lwd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">sbar</span><span class="op">(</span><span class="fl">200</span>, type <span class="op">=</span> <span class="st">"line"</span>, xy <span class="op">=</span> <span class="st">"bottom"</span>, divs <span class="op">=</span> <span class="fl">8</span>, below <span class="op">=</span> <span class="st">"meters"</span>, col <span class="op">=</span> <span class="st">"black"</span><span class="op">)</span></span>
<span><span class="fu">north</span><span class="op">(</span>type <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-ortho-ndvi" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-ortho-ndvi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="uav_agriculture_cook_islands_files/figure-html/fig-ortho-ndvi-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ortho-ndvi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;33.6: NDVI Orthophoto Showing Plot Boundaries and Study Area
</figcaption></figure>
</div>
</div>
</div>
</section><section id="calculating-plot-level-ndvi-statistics" class="level3" data-number="33.6.6"><h3 data-number="33.6.6" class="anchored" data-anchor-id="calculating-plot-level-ndvi-statistics">
<span class="header-section-number">33.6.6</span> Calculating Plot-Level NDVI Statistics</h3>
<p>With the NDVI map, we can calculate statistics based on NDVI pixel values within each plot using zonal statistics functions. Satellite and UAV sensors divide the landscape into a grid of pixels, each representing a specific area on the ground. Problems arise at boundaries between land uses where pixels straddling these edges capture information from both surfaces. Instead of recording pure crop reflectance, these boundary pixels record a blend of signals from the crop and the adjacent road. To minimize edge effects from mixed pixels at plot boundaries, a 0.5-meter negative buffer is applied to each plot polygon before extraction. Mixed pixels occur at boundary edges where a single pixel captures reflectance from multiple land cover types, such as roads and vegetation, or different crop types. The negative buffer shrinks each polygon inward by 0.5 meters, excluding these edge pixels from analysis and ensuring that extracted NDVI values represent only the interior of each agricultural plot:</p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Apply negative buffer to reduce edge contamination</span></span>
<span><span class="va">plots_buffered</span> <span class="op">&lt;-</span> <span class="fu">st_buffer</span><span class="op">(</span><span class="va">plots</span>, dist <span class="op">=</span> <span class="op">-</span><span class="fl">0.5</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, calculate NDVI statistics for each plot, including mean, standard deviation, minimum, maximum, and coefficient of variation.</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Extract mean NDVI for each buffered plot</span></span>
<span><span class="va">plot_ndvi</span> <span class="op">&lt;-</span> <span class="fu">terra</span><span class="fu">::</span><span class="fu"><a href="https://rspatial.github.io/terra/reference/extract.html">extract</a></span><span class="op">(</span><span class="va">ndvi</span>, <span class="va">plots_buffered</span>, fun<span class="op">=</span><span class="va">mean</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">plots</span><span class="op">$</span><span class="va">ndvi_mean</span> <span class="op">&lt;-</span> <span class="va">plot_ndvi</span><span class="op">[</span>,<span class="fl">2</span><span class="op">]</span></span>
<span></span>
<span><span class="co"># Calculate additional summmary statistics (min, max, sd) for each buffered plot</span></span>
<span><span class="va">plot_ndvi_sd</span> <span class="op">&lt;-</span> <span class="fu">terra</span><span class="fu">::</span><span class="fu"><a href="https://rspatial.github.io/terra/reference/extract.html">extract</a></span><span class="op">(</span><span class="va">ndvi</span>, <span class="va">plots_buffered</span>, fun<span class="op">=</span><span class="va">sd</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">plot_ndvi_min</span> <span class="op">&lt;-</span> <span class="fu">terra</span><span class="fu">::</span><span class="fu"><a href="https://rspatial.github.io/terra/reference/extract.html">extract</a></span><span class="op">(</span><span class="va">ndvi</span>, <span class="va">plots_buffered</span>, fun<span class="op">=</span><span class="va">min</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">plot_ndvi_max</span> <span class="op">&lt;-</span> <span class="fu">terra</span><span class="fu">::</span><span class="fu"><a href="https://rspatial.github.io/terra/reference/extract.html">extract</a></span><span class="op">(</span><span class="va">ndvi</span>, <span class="va">plots_buffered</span>, fun<span class="op">=</span><span class="va">max</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">plots</span><span class="op">$</span><span class="va">ndvi_sd</span> <span class="op">&lt;-</span> <span class="va">plot_ndvi_sd</span><span class="op">[</span>,<span class="fl">2</span><span class="op">]</span></span>
<span><span class="va">plots</span><span class="op">$</span><span class="va">ndvi_min</span> <span class="op">&lt;-</span> <span class="va">plot_ndvi_min</span><span class="op">[</span>,<span class="fl">2</span><span class="op">]</span></span>
<span><span class="va">plots</span><span class="op">$</span><span class="va">ndvi_max</span> <span class="op">&lt;-</span> <span class="va">plot_ndvi_max</span><span class="op">[</span>,<span class="fl">2</span><span class="op">]</span></span>
<span></span>
<span><span class="co"># Calculate coefficient of variation (CV)</span></span>
<span><span class="va">plots</span><span class="op">$</span><span class="va">ndvi_cv</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">plots</span><span class="op">$</span><span class="va">ndvi_sd</span> <span class="op">/</span> <span class="va">plots</span><span class="op">$</span><span class="va">ndvi_mean</span><span class="op">)</span> <span class="op">*</span> <span class="fl">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now that summary statistics have been calculated for each plot, we will visualize the mean NDVI values across plots the study area. Plots with consistently low NDVI (red-orange) may indicate recently harvested areas, fallow land, or crop stress, while high NDVI plots (green) indicate dense vegetation. Examine the map to identify which plots exhibit the lowest and highest NDVI values.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">tm_shape</span><span class="op">(</span><span class="va">plots</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">tm_fill</span><span class="op">(</span>fill <span class="op">=</span> <span class="st">"ndvi_mean"</span>, </span>
<span>          fill.scale <span class="op">=</span> <span class="fu">tm_scale</span><span class="op">(</span>values <span class="op">=</span> <span class="st">"brewer.rd_yl_gn"</span><span class="op">)</span>, </span>
<span>          fill.legend <span class="op">=</span> <span class="fu">tm_legend</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Mean NDVI"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">tm_text</span><span class="op">(</span>text <span class="op">=</span> <span class="st">"id"</span>, size <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">tm_scalebar</span><span class="op">(</span>position <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"center"</span>, <span class="st">"bottom"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">tm_compass</span><span class="op">(</span>position <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"right"</span>, <span class="st">"top"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">tm_title</span><span class="op">(</span><span class="st">"Mean NDVI by Plot"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-ndvi-mean" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-ndvi-mean-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="uav_agriculture_cook_islands_files/figure-html/fig-ndvi-mean-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ndvi-mean-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;33.7: Mean NDVI by Plot
</figcaption></figure>
</div>
</div>
</div>
<p>Next, visualize the coefficient of variation (CV) for each plot. The CV map highlights plots with high internal NDVI variability (yellow-green) versus uniform plots (red-orange). High variability might indicate mixed cropping systems, uneven crop growth, patchy vegetation coverage, varying soil conditions within a plot, or potential issues with plot boundary delineation, while low CV suggests more uniform vegetation across the plot.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">tm_shape</span><span class="op">(</span><span class="va">plots</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">tm_fill</span><span class="op">(</span>fill <span class="op">=</span> <span class="st">"ndvi_cv"</span>, </span>
<span>          fill.scale <span class="op">=</span> <span class="fu">tm_scale</span><span class="op">(</span>values <span class="op">=</span> <span class="st">"brewer.rd_yl_gn"</span><span class="op">)</span>, </span>
<span>          fill.legend <span class="op">=</span> <span class="fu">tm_legend</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"CV (%)"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">tm_text</span><span class="op">(</span>text <span class="op">=</span> <span class="st">"id"</span>, size <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">tm_scalebar</span><span class="op">(</span>position <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"center"</span>, <span class="st">"bottom"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">tm_compass</span><span class="op">(</span>position <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"right"</span>, <span class="st">"top"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">tm_title</span><span class="op">(</span><span class="st">"Coefficient of Variation by Plot"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-cov-plot" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-cov-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="uav_agriculture_cook_islands_files/figure-html/fig-cov-plot-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cov-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;33.8: Coefficient of Variation by Plot
</figcaption></figure>
</div>
</div>
</div>
</section><section id="resolution-comparison-uav-vs.-satellite-imagery" class="level3" data-number="33.6.7"><h3 data-number="33.6.7" class="anchored" data-anchor-id="resolution-comparison-uav-vs.-satellite-imagery">
<span class="header-section-number">33.6.7</span> Resolution Comparison: UAV vs.&nbsp;Satellite Imagery</h3>
<p>An advantage of UAV imagery for agricultural statistics is its spatial resolution compared to publicly available satellite sources. This section demonstrates these differences by comparing the same study area captured at three resolutions: UAV imagery at 1.6 cm, Sentinel-2 satellite imagery at 10 m, and Landsat-8 satellite imagery at 30 m resolution. Understanding these resolution differences is necessary for selecting appropriate imagery sources for agricultural monitoring tasks, particularly in landscapes with small, fragmented plots.</p>
<p>However, higher resolution is not always better and involves important tradeoffs. UAV and high-resolution commercial satellite imagery require greater financial costs, larger storage capacity, and more computational resources for processing. The appropriate tool depends on the analytical objective and spatial scale.</p>
<p>Satellite imagery is well-suited for large-scale regional or national agricultural monitoring where broad area coverage and frequent temporal revisits are priorities. UAVs are more appropriate for targeted interventions requiring detailed plot-level analysis, validation of satellite-based estimates, or monitoring of small, fragmented agricultural landscapes where coarser resolution would produce unacceptable mixed-pixel effects.</p>
<p>Let’s begin by loading in satellite imagery from Sentinel-2 (10 meters), and Landsat-8 (30 meters) into R.</p>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Load satellite imagery</span></span>
<span><span class="va">sen2</span> <span class="op">&lt;-</span> <span class="fu">rast</span><span class="op">(</span><span class="st">"data/uav_agriculture_cook_islands/satellite-images/sentinel2_10m_Oct.tif"</span><span class="op">)</span></span>
<span><span class="va">landsat8</span> <span class="op">&lt;-</span> <span class="fu">rast</span><span class="op">(</span><span class="st">"data/uav_agriculture_cook_islands/satellite-images/landsat8_30m_Oct.tif"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Reproject to common CRS using bilinear interpolation</span></span>
<span><span class="va">sen2</span> <span class="op">&lt;-</span> <span class="fu">project</span><span class="op">(</span><span class="va">sen2</span>, <span class="va">target_crs</span>, method <span class="op">=</span> <span class="st">"bilinear"</span><span class="op">)</span></span>
<span><span class="va">landsat8</span> <span class="op">&lt;-</span> <span class="fu">project</span><span class="op">(</span><span class="va">landsat8</span>, <span class="va">target_crs</span>, method <span class="op">=</span> <span class="st">"bilinear"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="sentinel-2-10-m-resolution" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="sentinel-2-10-m-resolution">Sentinel-2 (10 m resolution)</h4>
<p>Sentinel-2 provides 10-meter resolution, which is suitable for larger agricultural fields but struggles with small, fragmented plots. While broad agricultural patterns are visible, plot-level detail is limited. At this resolution, each pixel covers 100 m², which exceeds the size of many individual plots in the study area, making accurate boundary delineation and individual plot identification difficult.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">plotRGB</span><span class="op">(</span><span class="va">sen2</span>, r <span class="op">=</span> <span class="fl">1</span>, g <span class="op">=</span> <span class="fl">2</span>, b <span class="op">=</span> <span class="fl">3</span>, stretch <span class="op">=</span> <span class="st">"lin"</span>, main <span class="op">=</span> <span class="st">"Sentinel-2 True Color Image"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu">st_geometry</span><span class="op">(</span><span class="va">plots</span><span class="op">)</span>, add <span class="op">=</span> <span class="cn">TRUE</span>, border <span class="op">=</span> <span class="st">"white"</span>, lwd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu">st_geometry</span><span class="op">(</span><span class="va">study_area</span><span class="op">)</span>, add <span class="op">=</span> <span class="cn">TRUE</span>, border <span class="op">=</span> <span class="st">"yellow"</span>, lwd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">sbar</span><span class="op">(</span><span class="fl">200</span>, type <span class="op">=</span> <span class="st">"line"</span>, xy <span class="op">=</span> <span class="st">"bottom"</span>, divs <span class="op">=</span> <span class="fl">8</span>, below <span class="op">=</span> <span class="st">"meters"</span>, col <span class="op">=</span> <span class="st">"yellow"</span><span class="op">)</span></span>
<span><span class="fu">north</span><span class="op">(</span>type<span class="op">=</span><span class="fl">1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-s2-tc" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-s2-tc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="uav_agriculture_cook_islands_files/figure-html/fig-s2-tc-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-s2-tc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;33.9: Sentinel-2 True Color Image (10 meters)
</figcaption></figure>
</div>
</div>
</div>
</section><section id="landsat-8-30-m-resolution" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="landsat-8-30-m-resolution">Landsat-8 (30 m resolution)</h4>
<p>Finally, compare the same area against Landsat-8’s 30-meter resolution (900 m² per pixel). At this scale, individual plot delineation is impractical, though the imagery remains useful for identifying broad agricultural zones and land use patterns across larger regions.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">plotRGB</span><span class="op">(</span><span class="va">landsat8</span>, r <span class="op">=</span> <span class="fl">1</span>, g <span class="op">=</span> <span class="fl">2</span>, b <span class="op">=</span> <span class="fl">3</span>, stretch <span class="op">=</span> <span class="st">"lin"</span>, main <span class="op">=</span> <span class="st">"Landsat-8 True Color Image"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu">st_geometry</span><span class="op">(</span><span class="va">plots</span><span class="op">)</span>, add <span class="op">=</span> <span class="cn">TRUE</span>, border <span class="op">=</span> <span class="st">"white"</span>, lwd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu">st_geometry</span><span class="op">(</span><span class="va">study_area</span><span class="op">)</span>, add <span class="op">=</span> <span class="cn">TRUE</span>, border <span class="op">=</span> <span class="st">"yellow"</span>, lwd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">sbar</span><span class="op">(</span><span class="fl">200</span>, type <span class="op">=</span> <span class="st">"line"</span>, xy <span class="op">=</span> <span class="st">"bottom"</span>, divs <span class="op">=</span> <span class="fl">8</span>, below <span class="op">=</span> <span class="st">"meters"</span>, col <span class="op">=</span> <span class="st">"yellow"</span><span class="op">)</span></span>
<span><span class="fu">north</span><span class="op">(</span>type <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-l8-tc" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-l8-tc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="uav_agriculture_cook_islands_files/figure-html/fig-l8-tc-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-l8-tc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;33.10: Landsat-8 True Color Image (30 meters)
</figcaption></figure>
</div>
</div>
</div>
</section></section><section id="quantifying-resolution-differences" class="level3" data-number="33.6.8"><h3 data-number="33.6.8" class="anchored" data-anchor-id="quantifying-resolution-differences">
<span class="header-section-number">33.6.8</span> Quantifying Resolution Differences</h3>
<p>To objectively demonstrate the resolution difference between sensors, we’ll count how many pixels fall within each agricultural plot for each imagery source.</p>
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Count pixels per plot for each sensor</span></span>
<span><span class="va">pixel_counts_rgb</span> <span class="op">&lt;-</span> <span class="fu">terra</span><span class="fu">::</span><span class="fu"><a href="https://rspatial.github.io/terra/reference/extract.html">extract</a></span><span class="op">(</span><span class="va">rgb</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span>, <span class="va">plots</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">plots</span><span class="op">$</span><span class="va">pixel_count_rgb</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">pixel_counts_rgb</span><span class="op">$</span><span class="va">ID</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">pixel_counts_sen2</span> <span class="op">&lt;-</span> <span class="fu">terra</span><span class="fu">::</span><span class="fu"><a href="https://rspatial.github.io/terra/reference/extract.html">extract</a></span><span class="op">(</span><span class="va">sen2</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span>, <span class="va">plots</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">plots</span><span class="op">$</span><span class="va">pixel_count_sen2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">pixel_counts_sen2</span><span class="op">$</span><span class="va">ID</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">pixel_counts_landsat</span> <span class="op">&lt;-</span> <span class="fu">terra</span><span class="fu">::</span><span class="fu"><a href="https://rspatial.github.io/terra/reference/extract.html">extract</a></span><span class="op">(</span><span class="va">landsat8</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span>, <span class="va">plots</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">plots</span><span class="op">$</span><span class="va">pixel_count_landsat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">pixel_counts_landsat</span><span class="op">$</span><span class="va">ID</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Calculate resolution in appropriate units</span></span>
<span><span class="va">UAV_res_m</span> <span class="op">&lt;-</span> <span class="fu">res</span><span class="op">(</span><span class="va">rgb</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span></span>
<span><span class="va">UAV_res_cm</span> <span class="op">&lt;-</span> <span class="va">UAV_res_m</span> <span class="op">*</span> <span class="fl">100</span></span>
<span></span>
<span><span class="co"># Create comparison data frame</span></span>
<span><span class="va">comparison</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  Sensor <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"UAV RGB"</span>, <span class="st">"Sentinel-2"</span>, <span class="st">"Landsat-8"</span><span class="op">)</span>,</span>
<span>  Resolution <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">UAV_res_cm</span>, <span class="fl">2</span><span class="op">)</span>, <span class="st">"cm"</span><span class="op">)</span>,</span>
<span>    <span class="st">"10 m"</span>,</span>
<span>    <span class="st">"30 m"</span></span>
<span>  <span class="op">)</span>,</span>
<span>  Min_Pixels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">plots</span><span class="op">$</span><span class="va">pixel_count_rgb</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">plots</span><span class="op">$</span><span class="va">pixel_count_sen2</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">plots</span><span class="op">$</span><span class="va">pixel_count_landsat</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span>
<span>  <span class="op">)</span>,</span>
<span>  Mean_Pixels_per_Plot <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">plots</span><span class="op">$</span><span class="va">pixel_count_rgb</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">plots</span><span class="op">$</span><span class="va">pixel_count_sen2</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">plots</span><span class="op">$</span><span class="va">pixel_count_landsat</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span>
<span>  <span class="op">)</span>,</span>
<span>  Max_Pixels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">plots</span><span class="op">$</span><span class="va">pixel_count_rgb</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">plots</span><span class="op">$</span><span class="va">pixel_count_sen2</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">plots</span><span class="op">$</span><span class="va">pixel_count_landsat</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">comparison</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div id="tbl-sensors-pixels" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sensors-pixels-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;33.1: Comparison of Pixel Counts per Plot Across Different Sensors
</figcaption><div aria-describedby="tbl-sensors-pixels-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-hover do-not-create-environment cell caption-top table-sm small" data-quarto-postprocess="true">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Sensor</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Resolution</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Min Pixels</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean Pixels</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Max Pixels</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">UAV RGB</td>
<td style="text-align: left;">1.6 cm</td>
<td style="text-align: right;">185736</td>
<td style="text-align: right;">3401651.4</td>
<td style="text-align: right;">6292073</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sentinel-2</td>
<td style="text-align: left;">10 m</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">9.8</td>
<td style="text-align: right;">18</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Landsat-8</td>
<td style="text-align: left;">30 m</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.9</td>
<td style="text-align: right;">4</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>This table reveals differences in pixel density between sensors. UAV imagery provides thousands of pixels per plot, enabling detailed analysis and supporting advanced machine learning applications, such as convolutional neural networks for object detection. Sentinel-2 provides tens to hundreds of pixels per plot, while Landsat-8 provides only a handful.</p>
</section><section id="mixed-pixel-problem" class="level3" data-number="33.6.9"><h3 data-number="33.6.9" class="anchored" data-anchor-id="mixed-pixel-problem">
<span class="header-section-number">33.6.9</span> Mixed Pixel Problem</h3>
<p>A major source of error in satellite-based area measurement is the mixed pixel problem, which occurs when a single pixel covers multiple land cover types. For example, a 30-meter Landsat pixel at a field edge might contain crop, bare soil, and pathway within the same pixel. This creates significant challenges for area estimation, particularly in Pacific Island contexts where agricultural landscapes are dominated by small, irregularly shaped plots. Classifying a mixed pixel as crop overestimates crop area, while classifying it as non-crop underestimates it. These classification errors introduce systematic uncertainty and bias into agricultural area statistics.</p>
<p>Selecting appropriate imagery depends on the scale, budget, and objectives of the agricultural monitoring task. The table below compares key characteristics of satellite and UAV imagery to help determine suitability for different agricultural statistics applications. Satellite imagery excels in large-scale regional monitoring with frequent temporal coverage, while UAV imagery is optimal for targeted plot-level analysis where boundary precision is critical.</p>
<div class="cell">
<div id="tbl-sensor-characteristics" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sensor-characteristics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;33.2: Sensor characteristics and applications
</figcaption><div aria-describedby="tbl-sensor-characteristics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-hover do-not-create-environment cell caption-top table-sm small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Characteristic</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Satellite Imagery</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">UAV Imagery</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Spatial resolution</td>
<td style="text-align: left;">Commercial: ~30 cm<br>
Public: 10 m (Sentinel-2) to 1 km (MODIS)</td>
<td style="text-align: left;">1-5 cm (dependent on flight altitude and sensor)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Spectral resolution</td>
<td style="text-align: left;">Multispectral, SAR (radar)<br>
Sentinel-2: 13 bands (visible to SWIR)<br>
Landsat-8: 11 bands</td>
<td style="text-align: left;">RGB (standard); multispectral (5-10 bands), thermal, LiDAR possible with specialized sensors</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Temporal resolution</td>
<td style="text-align: left;">Sentinel-2: 5 days<br>
Landsat: 16 days<br>
MODIS: daily</td>
<td style="text-align: left;">User-controlled (on-demand)<br>
Practical frequency: 2-4 flights/season due to cost/logistics</td>
</tr>
<tr class="even">
<td style="text-align: left;">Coverage area</td>
<td style="text-align: left;">Large area coverage<br>
(e.g., Sentinel-2: 290 km swath)</td>
<td style="text-align: left;">Limited: 5-50 hectares per flight<br>
Battery-constrained: 15-25 min per flight</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Geometric accuracy</td>
<td style="text-align: left;">Sentinel-2: ~10-20 m absolute<br>
Landsat-8: ~12-30 m absolute<br>
Commercial: ~3-5 m</td>
<td style="text-align: left;">With GCPs: ±5-10 cm<br>
With RTK: ±2-5 cm<br>
Without GCPs: ±2-5 m</td>
</tr>
<tr class="even">
<td style="text-align: left;">Radiometric quality</td>
<td style="text-align: left;">High (well-calibrated, multi-date consistent)<br>
Surface reflectance products available</td>
<td style="text-align: left;">Variable (requires calibration panel)<br>
Sensitive to illumination conditions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cloud cover</td>
<td style="text-align: left;">Major limitation in tropical regions<br>
May wait weeks for cloud-free scenes</td>
<td style="text-align: left;">Flies below clouds (300-400 m typical cloud base)<br>
Sensitive to wind/rain</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cost</td>
<td style="text-align: left;">Public sources: free<br>
Commercial: $10-30/km²</td>
<td style="text-align: left;">Initial investment: $2,000-$40,000<br>
Operational: ~$500-2,000 per survey day</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Data volume</td>
<td style="text-align: left;">Moderate per unit area<br>
Sentinel-2 scene: ~1 GB</td>
<td style="text-align: left;">Very large: RGB 3 GB, multispectral 1.7 GB raw per survey<br>
Orthophotos: 2-3 GB total</td>
</tr>
<tr class="even">
<td style="text-align: left;">Processing complexity</td>
<td style="text-align: left;">Low to moderate<br>
Pre-processed products available</td>
<td style="text-align: left;">Moderate to high: requires photogrammetry expertise<br>
3-8 hours on consumer laptop</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Use cases</td>
<td style="text-align: left;">National/regional crop mapping<br>
Temporal monitoring<br>
Broad land use classification<br>
Change detection</td>
<td style="text-align: left;">Plot delineation<br>
Ground truthing<br>
High-detail crop assessment<br>
Infrastructure mapping</td>
</tr>
<tr class="even">
<td style="text-align: left;">Advantages</td>
<td style="text-align: left;">Broad coverage<br>
Regular monitoring<br>
Historical archives (40+ years)<br>
Consistent calibration</td>
<td style="text-align: left;">Very high detail<br>
Flexible timing<br>
Below-cloud operations<br>
Multi-sensor integration possible</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Limitations</td>
<td style="text-align: left;">Coarse resolution for small plots<br>
Cloud interference<br>
Fixed revisit schedules<br>
Coarse for sub-field patterns</td>
<td style="text-align: left;">Limited coverage<br>
Weather sensitive<br>
Regulatory constraints<br>
Processing intensive<br>
Requires field operations</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section></section><section id="discussion" class="level2" data-number="33.7"><h2 data-number="33.7" class="anchored" data-anchor-id="discussion">
<span class="header-section-number">33.7</span> Discussion</h2>
<p>While UAV imagery offers substantial advantages for agricultural monitoring in fragmented landscapes, successful integration into operational statistical systems requires careful consideration of practical constraints and strategic implementation approaches. This section examines operational challenges associated with UAV deployment and proposes strategies for effective integration into agricultural statistics workflows.</p>
<section id="operational-challenges-using-uav-for-agricultural-statistics" class="level3" data-number="33.7.1"><h3 data-number="33.7.1" class="anchored" data-anchor-id="operational-challenges-using-uav-for-agricultural-statistics">
<span class="header-section-number">33.7.1</span> <strong>Operational Challenges using UAV for agricultural statistics</strong>
</h3>
<p><strong>Limited scalability</strong>: Consumer-grade rotary UAVs are constrained by battery capacity and line-of-sight regulations requiring visual contact with the UAV. Multiple batteries and extended field time are needed for larger areas, increasing logistical burden and operational costs.</p>
<p><strong>High costs</strong>: Beyond UAV hardware, agencies must budget for accessories (batteries, sensors, ground control equipment), software licenses, operator training, insurance, and maintenance.</p>
<p><strong>Regulatory barriers</strong>: Operations are subject to national aviation and privacy laws, which vary significantly. Common requirements include operator licenses, altitude limits, visual line-of-sight rules, and restrictions near sensitive locations.</p>
<p><strong>Privacy concerns</strong>: Community engagement and transparent communication about flight paths and coverage areas are essential, even where operations are legally permitted.</p>
<p><strong>Technical capacity gaps</strong>: Operating UAVs and processing imagery requires skilled personnel—licensed operators for flight operations and trained analysts for data processing and interpretation.</p>
</section><section id="strategies-for-effective-integration-of-uav-imagery-into-agricultural-statistics" class="level3" data-number="33.7.2"><h3 data-number="33.7.2" class="anchored" data-anchor-id="strategies-for-effective-integration-of-uav-imagery-into-agricultural-statistics">
<span class="header-section-number">33.7.2</span> <strong>Strategies for Effective Integration of UAV imagery into agricultural statistics</strong>
</h3>
<p><strong>Build local analytical capacity</strong>: Start with small-scale applications using free, open-source software. Leverage publicly available satellite imagery first to understand its capabilities and limitations before investing in UAV technology.</p>
<p><strong>Match UAV use to operational scale</strong>: UAVs are best suited for applications requiring high spatial detail over small areas, validation exercises, or monitoring specific zones. Full coverage mapping across large dispersed areas may be impractical due to flight time, battery limits, and processing demands.</p>
<p><strong>Use sample-based validation</strong>: Focus on statistically selected units rather than complete coverage. UAV-based measurements can validate farmer-reported data to assess bias, verify crop types, or identify stressed vegetation indicating lower yields.</p>
<p><strong>Follow local regulations</strong>: Understand national UAV regulations and establish clear operating protocols. Coordinate with civil aviation authorities, develop field safety procedures, and implement community engagement protocols.</p>
<p><strong>Document methodologies</strong>: As UAV technologies and analytical techniques evolve, documenting use cases supports broader adoption, encourages innovation, and improves data quality.</p>
</section></section><section id="conclusion" class="level2" data-number="33.8"><h2 data-number="33.8" class="anchored" data-anchor-id="conclusion">
<span class="header-section-number">33.8</span> Conclusion</h2>
<p>This study highlights the potential of UAV imagery for modernizing agricultural statistics. A primary barrier to widespread adoption by national statistics offices has been the lack of documented, end-to-end use cases on the use of the technology. By providing a reproducible workflow in R using a case study from Rarotonga, Cook Islands, this work addresses that gap. Practical demonstrations are essential for establishing standards and methodologies required to integrate UAV-derived data into official agricultural statistics production. More specifically, the findings demonstrate that UAV technology provides a solution to persistent challenges of accurate area estimation in landscapes with small, fragmented agricultural plots, where traditional ground surveys are resource-intensive and satellite imagery too coarse for reliable plot-level measurement.</p>
<p>The key findings underscore the potential of this approach. First, the centimeter-level resolution (~1.6 cm) of the UAV imagery effectively reducing the mixed-pixel problem compared to coarser satellite sensors like Sentinel-2 (10 m) and Landsat-8 (30 m). By capturing thousands of data points within even the smallest plots, UAVs enable precise boundary delineation and reduce the measurement error that can bias national production estimates. Second, our analysis demonstrated the extraction of detailed, plot-level vegetation metrics, including mean NDVI and its coefficient of variation, which reveal fine-scale patterns of crop health and heterogeneity that are invisible at satellite resolutions. These metrics provide agricultural stakeholders with actionable insights for monitoring and management that were previously unattainable.</p>
<p>By presenting this workflow using free and open-source tools like R and OpenDroneMap, we demonstrate a reproducible and cost-effective framework for use of UAV imagery for the production of agricultural statistics, and ultimately more reliable agricultural data for evidence-based policy, improved food security, and sustainable resource management in the Pacific and beyond.</p>


<div id="refs" class="references csl-bib-body" data-entry-spacing="0" role="list">
<div id="ref-AsianDevelopmentBank2024" class="csl-entry" role="listitem">
<div class="csl-left-margin">[1] </div>
<div class="csl-right-inline">
<em><a href="https://doi.org/10.22617/tcs240326-2">Plotting from above: Enhancing agricultural mapping in asia and the pacific</a></em>. Asian Development Bank, 2024.</div>
</div>
<div id="ref-Valorie2023" class="csl-entry" role="listitem">
<div class="csl-left-margin">[2] </div>
<div class="csl-right-inline">V. Marie, A. Zaiats, R. Wickersham, and T. T. Caughlin, <span>“Open drone map: Structure-from-motion workflow.”</span> University of Idaho, 2023, doi: <a href="https://doi.org/10.7923/92HF-GP09">10.7923/92HF-GP09</a>.</div>
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/FAO-EOSTAT\.github\.io\/UN-Handbook\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./uav_crop_growth.html" class="pagination-link" aria-label="Automated Monitoring of Crop Growth Index using UAV">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Automated Monitoring of Crop Growth Index using UAV</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./disaster_response.html" class="pagination-link" aria-label="Remote Sensing for Agricultural Disaster Response">
        <span class="nav-page-text">Remote Sensing for Agricultural Disaster Response</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>Edited by Gilberto Camara, Lorenzo de Simone and Ronald Jansen.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/FAO-EOSTAT/UN-Handbook/edit/quarto/uav_agriculture_cook_islands.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/FAO-EOSTAT/UN-Handbook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>


</body></html>