<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Gilberto Camara, Lorenzo de Simone, Ronald Jansen">
<title>UN Handbook on Remote Sensing for Agricultural Statistics - 30&nbsp; Field Parcel Identification Using UAV Imagery Based on the DCP-MTL Model</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./uav_wheat_growth.html" rel="next">
<link href="./uav_agriculture.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./uav_agriculture.html">UAV applications in agricultural statistics</a></li><li class="breadcrumb-item"><a href="./uav_field_parcels.html"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Field Parcel Identification Using UAV Imagery Based on the DCP-MTL Model</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">UN Handbook on Remote Sensing for Agricultural Statistics</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/FAO-EOSTAT/UN-Handbook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Welcome</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./howto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">How to use this handbook</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_remote_sensing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Remote sensing images: optical, SAR</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_data_sources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Earth observation big data sources</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_data_cubes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Earth observation data cubes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_lucc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Land cover and crop classification schemas</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_quality_control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Quality control of training sets for agricultural statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_machine_learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Machine learning algorithms for image time series</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_uncertainty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Spatial map uncertainty estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Map validation and use of maps for area estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_design_frames.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Remote Sensing in the Design of Sampling Frames</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_alignment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Alignment of field data collection to EO statistical requirements</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./th_parcel_extraction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Semantic Segmentation for Automatic Field Boundary Delineation</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./crop_type_mapping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Use Cases in Crop Type Mapping</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_poland.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Crop monitoring with Sentinel-1 and Sentinel-2 images in Poland</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_mexico.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Crop classification in Mexico</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_zimbabwe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Crop classification in Zimbabwe</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_china.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Efficient and Reliable Paddy Rice Classification</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_chile.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Crop classification and land use mapping in Chile</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ct_digital_earth_africa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Agricultural Mapping with Digital Earth Africa</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./crop_yield_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Crop yield estimation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_finland.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Early-season crop yield mapping in Finland</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_indonesia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Mapping crop phenology in Indonesia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_colombia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Rice Phenology Mapping in Colombia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_poland.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Yield forecasting in Poland</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cy_china.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Remote Sensing Estimation of Soybean Yield Based on Multi-Scenario Simulation</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./crop_statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Extraction of crop statistics from crop type and crop yield maps</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./crop_statistics_area.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Crop Statistics using Weigthed Area Estimators</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./crop_statistics_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Estimating crop statistics using survey-calibrated methods</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./crop_statistics_calibration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Estimating crop statistics for list frame data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./crop_statistics_ppi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Prediction-Powered Inference (PPI) for Agricultural Decision-Making</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./uav_agriculture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">UAV applications in agricultural statistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uav_field_parcels.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Field Parcel Identification Using UAV Imagery Based on the DCP-MTL Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uav_wheat_growth.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Application of UAV in Wheat Growth Monitoring</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./uav_crop_growth.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Automated Monitoring of Crop Growth Index using UAV</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./disaster_response.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Remote Sensing for Agricultural Disaster Response</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dis_china_floods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">An Automated Flood Detection Algorithm for Post-Disaster Assessment</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./additional.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Additional Topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ad_world_cereal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">WorldCereal - A Global Effort for Crop Mapping</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ad_governance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Data Governance for Agricultural Statistics</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">30.1</span> Introduction</a></li>
  <li><a href="#experimental-area-and-data" id="toc-experimental-area-and-data" class="nav-link" data-scroll-target="#experimental-area-and-data"><span class="header-section-number">30.2</span> Experimental Area and Data</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><span class="header-section-number">30.3</span> Methods</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">30.4</span> Results</a></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions"><span class="header-section-number">30.5</span> Conclusions</a></li>
  <li><a href="#code-and-data-availability" id="toc-code-and-data-availability" class="nav-link" data-scroll-target="#code-and-data-availability"><span class="header-section-number">30.6</span> Code and data availability</a></li>
  <li><a href="#about-the-author" id="toc-about-the-author" class="nav-link" data-scroll-target="#about-the-author"><span class="header-section-number">30.7</span> About the author</a></li>
  </ul><div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/FAO-EOSTAT/UN-Handbook/edit/quarto/uav_field_parcels.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/FAO-EOSTAT/UN-Handbook/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">
<span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Field Parcel Identification Using UAV Imagery Based on the DCP-MTL Model</span>
</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jingshui Zhang </p>
          </div>
  </div>
    
  
    
  </div>
  

</header><section id="introduction" class="level2" data-number="30.1"><h2 data-number="30.1" class="anchored" data-anchor-id="introduction">
<span class="header-section-number">30.1</span> Introduction</h2>
<p>Agricultural Cultivation Field Parcels (CFP) refer to areas within a specific land boundary where a single type of crop is cultivated during each agricultural production cycle. They are the smallest units for farmers to carry out agricultural activities such as sowing, management, and harvesting, and also serve as the fundamental units for implementing precision agriculture. In theory, they should be regarded as the minimum units for crop area statistics and yield estimation. Traditional CFP mapping primarily relies on field survey methods to collect location information followed by manual digitization, which is costly and inefficient. With the rapid development of remote sensing technology, especially the widespread application of high-resolution data and continuous advancements in imagery interpretation techniques, the efficient and automated extraction of CFP information has become increasingly feasible. However, previous studies have mainly depended on pixel-level classification methods and object-level analysis techniques based on imagery segmentation (such as superpixel regions), which generally lack agricultural semantics and are difficult to achieve a one-to-one correspondence with actual CFP. An end-to-end boundary-field multi-task learning CFP vectorization framework (Cultivated Parcel Vectorization Framework, CPVF) proposed based on ultra-high-resolution imagery not only enables precise correspondence with real CFP but also addresses current research challenges in finer CFP extraction (especially from aerial imagery).</p>
</section><section id="experimental-area-and-data" class="level2" data-number="30.2"><h2 data-number="30.2" class="anchored" data-anchor-id="experimental-area-and-data">
<span class="header-section-number">30.2</span> Experimental Area and Data</h2>
<p>Jilin Province is located in the northeast region of China (between 121°38′ to 131°19′ E and 40°50′ to 46°19′ N), characterized by a temperate continental monsoon climate with four distinct seasons, an annual precipitation ranging from 400 to 900 mm, an annual average temperature of 2–6 ℃, and average summer temperatures exceeding 23 ℃. The topography generally slopes from southeast to northwest, with the main landform types including mountains in the east and plains in the central and western regions, where the plains are primarily represented by the Songnen Plain and the Liaohe Plain. The major grain crops in Jilin Province include maize, rice, soybean, and wheat. Among them, maize is mainly cultivated in the central and western regions, with a sowing period from late April to early May and a harvesting period in mid-to-late September; rice is primarily cultivated in areas such as Jilin City and Yanbian Prefecture, generally transplanted in mid-to-late May and harvested in mid-to-late September; soybean is an important grain crop in the western regions of Jilin Province, usually sown from late April to early May and reaching maturity from late September to early October.</p>
<p>The steps involved in data processing are the following:</p>
<ol type="1">
<li><p>Data preparation. Acquire UAV imagery datasets and prepare vector parcel samples for label generation.</p></li>
<li><p>Data resampling. Resample the original imagery from 0.05 m resolution to 0.2 m, and then convert the digitized vector parcel data into raster format consistent with the resampled imagery, including both parcel regions and parcel boundaries: on the one hand, shrink the vector parcel polygons inward to generate parcel region masks and rasterize them to obtain region labels; on the other hand, convert the vector polygons into line data, buffer them with a width of 0.4 m to form boundary bands, and rasterize them to obtain boundary labels.</p></li>
<li><p>Image–label pair generation. Apply a sliding-window algorithm with a stride of 128 pixels to crop the original imagery into 1024 × 1024-pixel patches, producing a total of 14,034 image–label pairs. For imagery from other provinces, due to smaller data volumes, adopt non-overlapping cropping at 512 × 512 pixels. Meanwhile, to ensure data validity, remove image patches in which parcel area proportion is less than 10%, and exclude large numbers of no-value regions at the UAV image edges.</p></li>
<li><p>Euclidean distance map generation. Based on the above labels, generate Euclidean distance maps to represent the distance from each interior pixel of a parcel to the nearest boundary, thereby constructing four-tuple label sets of image–parcel region–parcel boundary–distance map.</p></li>
</ol>
<p>The dataset constructed in this case is shown in <a href="#tbl-1-fields">Table&nbsp;<span>30.1</span></a>. Among them, Jilin Province serves as the main region for training and evaluation, while nine other provinces (Hebei, Tianjin, Henan, Shanxi, Anhui, Zhejiang, Yunnan, Guangxi, and Hainan) are used to test the model’s generalization capability. Zhejiang includes summer middle-season/late rice samples (Zhejiang 1) and early spring early-season rice samples (Zhejiang 2), collectively covering diverse parcel morphologies, crop types, boundary characteristics, and topographic–climatic conditions. In addition, 360 independent UAV images not involved in training or validation are selected as a separate test set to ensure objectivity and reliability in model evaluation. The relevant parameters of the UHR-CFP dataset are detailed in <a href="#tbl-1-fields">Table&nbsp;<span>30.1</span></a>.</p>
<div id="tbl-1-fields" class="anchored">
<table class="table">
<caption>Table&nbsp;30.1: Dataset parameters</caption>
<colgroup>
<col style="width: 15%">
<col style="width: 10%">
<col style="width: 23%">
<col style="width: 13%">
<col style="width: 25%">
<col style="width: 12%">
</colgroup>
<thead><tr class="header">
<th>Area</th>
<th>Size</th>
<th>Resolution（Meter）</th>
<th>Account</th>
<th>Train/Validation/Test</th>
<th>Date</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Jilin</td>
<td>1024</td>
<td>0.2</td>
<td>14034</td>
<td>8530/2131/3553</td>
<td>2023.7</td>
</tr>
<tr class="even">
<td>Hebei</td>
<td>512</td>
<td>0.2</td>
<td>310</td>
<td>0/0/310</td>
<td>2023.7</td>
</tr>
<tr class="odd">
<td>Tianjin</td>
<td>512</td>
<td>0.2</td>
<td>396</td>
<td>0/0/396</td>
<td>2024.8</td>
</tr>
<tr class="even">
<td>Shanxi</td>
<td>512</td>
<td>0.2</td>
<td>267</td>
<td>0/0/267</td>
<td>2024.7</td>
</tr>
<tr class="odd">
<td>Jiangsu</td>
<td>512</td>
<td>0.2</td>
<td>251</td>
<td>0/0/251</td>
<td>2022.8</td>
</tr>
<tr class="even">
<td>Yunnan</td>
<td>512</td>
<td>0.2</td>
<td>174</td>
<td>0/0/174</td>
<td>2024.7</td>
</tr>
<tr class="odd">
<td>Guangxi</td>
<td>512</td>
<td>0.2</td>
<td>151</td>
<td>0/0/151</td>
<td>2023.8</td>
</tr>
<tr class="even">
<td>Henan</td>
<td>512</td>
<td>0.2</td>
<td>139</td>
<td>0/0/139</td>
<td>2022.4</td>
</tr>
<tr class="odd">
<td>Anhui</td>
<td>512</td>
<td>0.2</td>
<td>100</td>
<td>0/0/100</td>
<td>2022.6</td>
</tr>
<tr class="even">
<td>Hainan</td>
<td>512</td>
<td>0.2</td>
<td>93</td>
<td>0/0/93</td>
<td>2023.9</td>
</tr>
<tr class="odd">
<td>Zhejiang1</td>
<td>512</td>
<td>0.2</td>
<td>452</td>
<td>0/0/452</td>
<td>2022.8</td>
</tr>
<tr class="even">
<td>Zhejiang2</td>
<td>512</td>
<td>0.2</td>
<td>1800</td>
<td>1200/240/360</td>
<td>2023.3</td>
</tr>
</tbody>
</table>
</div>
</section><section id="methods" class="level2" data-number="30.3"><h2 data-number="30.3" class="anchored" data-anchor-id="methods">
<span class="header-section-number">30.3</span> Methods</h2>
<p>This section describes the steps for generating CFPs using the CPVF method. Based on the dataset preparation method described in the previous section, we builtimage–parcel region–parcel boundary–distance map quadruple label sets for the study area. Then, we trained the PVF model to extract parcel regions and boundaries. The DCP-MTL model (Drone-Based Cultivation Parcel Extraction Multitask Learning, DCP-MTL) is employed to accurately extract the regions and boundaries of CFPs from UAV imagery. Subsequently, a Universal Vectorization Module (UVM) is utilized to generate vectorized instances of CFPs, thereby achieving the Ready-To-Use (RTU) application objective.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-1-uav-fields" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="./images/uav_field_parcels/image1.jpeg" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;30.1: Architecture of the DCP-MTL model.</figcaption></figure>
</div>
</div>
</div>
<p>In the DCP-MTL model, a Discrete Cosine Transform (DCT) module is introduced for frequency-domain feature extraction, specifically decoupling high-frequency features to enhance the representation capability of parcel boundaries. Then, combined with deep supervision techniques, a Dual-Branch Attention Module (DBAM) and an Uncertainty Perception Module for Transition Regions (UPMTR) are designed to address issues in multi-scale CFPs, such as incomplete extraction of large parcels, failure to separately extract small or fragmented parcels, and adhesion between parcels. Finally, together with the Field Boundary Connectivity Module (FBCM), they form an integrated decoding module aimed at enhancing the connectivity of blurred parcel boundaries and improving the separability of densely adhered parcel regions.</p>
<p>After running DCP-MTL, we perform inference on the test sets using the trained model. Then, we converted the raster data of regions and boundaries obtained from the DCP-MTL model into vector parcel data through post-processing, in order to obtain RTU (Ready-to-Use) data.</p>
</section><section id="results" class="level2" data-number="30.4"><h2 data-number="30.4" class="anchored" data-anchor-id="results">
<span class="header-section-number">30.4</span> Results</h2>
<p><a href="#tbl-2-fields">Table&nbsp;<span>30.2</span></a> presents the quantitative evaluation results of the DCP-MTL model on the UHR-CFP dataset, including pixel-level accuracy for both parcel regions and parcel boundaries. In the table, P denotes Precision, R denotes Recall, F1 represents the F1 score, IoU refers to the Intersection over Union, mIoU indicates the mean IoU, BF1 represents the boundary F1 score, BIoU refers to the boundary IoU, and BmIoU denotes the mean boundary IoU. The results demonstrate that the DCP-MTL model achieves satisfactory identification performance on both parcel regions and parcel boundaries, confirming that compared to single-task semantic segmentation approaches, modeling parcel region segmentation and parcel boundary segmentation as two interrelated tasks within a multitask framework can significantly enhance the overall performance of the model.</p>
<div id="tbl-2-fields" class="anchored">
<table class="table">
<caption>Table&nbsp;30.2: Accuracy results of DCP-MTL model for regions and boundaries.</caption>
<colgroup>
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 12%">
</colgroup>
<thead><tr class="header">
<th>Method</th>
<th>Region</th>
<th></th>
<th></th>
<th></th>
<th></th>
<th>Boundary</th>
<th></th>
<th></th>
</tr></thead>
<tbody>
<tr class="odd">
<td></td>
<td>P (%)</td>
<td>R (%)</td>
<td>F1 (%)</td>
<td>IoU (%)</td>
<td>mIoU (%)</td>
<td>BF1 (%)</td>
<td>BIoU (%)</td>
<td>BmIoU (%)</td>
</tr>
<tr class="even">
<td>DCP-MTL</td>
<td>95.09</td>
<td>94.11</td>
<td>94.33</td>
<td>92.88</td>
<td>82.72</td>
<td>70.57</td>
<td>60.94</td>
<td>78.15</td>
</tr>
</tbody>
</table>
</div>
<p><a href="#tbl-3-fields">Table&nbsp;<span>30.3</span></a> presents the accuracy evaluation results of the DCP-MTL model at both pixel-level and object-level. Here, GUC denotes the Global Under-Classification error, GTC denotes the Global Total-Classification error, and GOC denotes the Global Over-Classification error. The results show that the DCP-MTL model achieves satisfactory performance across all pixel-level evaluation metrics, demonstrating a clear advantage in parcel boundary identification. The improved boundary accuracy facilitates the separation of adjacent, previously conjoined parcels, thereby enhancing the object-level identification outcomes.</p>
<div id="tbl-3-fields" class="anchored">
<table class="table">
<caption>Table&nbsp;30.3: Accuracy results of DCP-MTL model for pixels and objects</caption>
<colgroup>
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<thead><tr class="header">
<th>Method</th>
<th>Pixel-class</th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th>Object-class</th>
<th></th>
<th></th>
</tr></thead>
<tbody>
<tr class="odd">
<td></td>
<td>Region</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>Boundary</td>
<td></td>
<td>Region</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>P (%)</td>
<td>R (%)</td>
<td>F1 (%)</td>
<td>IoU (%)</td>
<td>mIoU (%)</td>
<td>BF1 (%)</td>
<td>BIoU (%)</td>
<td>GOC (%)</td>
<td>GUC (%)</td>
<td>GTC (%)</td>
</tr>
<tr class="odd">
<td>DCP-MTL</td>
<td>95.09</td>
<td>94.11</td>
<td>94.33</td>
<td>92.88</td>
<td>82.72</td>
<td>70.57</td>
<td>60.94</td>
<td>17.5</td>
<td>20.7</td>
<td>19.2</td>
</tr>
</tbody>
</table>
</div>
<p><a href="#fig-2-uav-fields">Figure&nbsp;<span>30.2</span></a> illustrates the identification details of the DCP-MTL model. The first row shows the true color imagery, the second row displays the ground truth labels, the third row presents the parcel identification results, and the fourth row shows the boundary identification results. The results indicate that in scenes where the interior of the parcels is relatively homogeneous and the boundaries are clear, the DCP-MTL model achieves accurate parcel area identification. Although the boundary extraction performance is moderate, the discontinuity of the boundary lines—especially when the boundary width is narrow—often leads to boundaries being misclassified as parcel areas, resulting in noticeable adhesion, which is particularly evident in the first and third columns. In scenes where the parcels are narrow, densely distributed, and have blurred boundaries (as in the fourth column), both parcel and boundary identification perform relatively better. The imagery in the fifth column is darker, with complex background regions and heterogeneous parcel interiors, yet the DCP-MTL model still achieves satisfactory identification results. Overall, across diverse scenes, the outputs of the DCP-MTL model closely approximate the ground truth, exhibiting excellent performance in both parcel area accuracy and boundary detail extraction.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-2-uav-fields" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="./images/uav_field_parcels/image2.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;30.2: Visualization of DCT-MTL model results.</figcaption></figure>
</div>
</div>
</div>
<p><a href="#fig-3-uav-fields">Figure&nbsp;<span>30.3</span></a> shows the vector parcel results of two complete images (vector data shown in yellow). In each UAV image, two typical subregions were selected as examples. The results of individual parcels were obtained by performing connectivity analysis on the region data generated by the DCP-MTL model. In subregions (a) and (b), parcels are independent and exhibit no adhesion; whereas in subregions (c) and (d), varying degrees of parcel adhesion occur—adhesion in (c) is mainly caused by incomplete boundary extraction, while in (d) it results from missing boundaries.</p>
<p>To further resolve issues of parcel adhesion or unclosed boundaries, boundary refinement is applied through post-processing algorithms, thereby obtaining complete and closed vector parcel data. Compared with raster results, the vectorized results are smoother and more regular, effectively reducing over-segmentation and under-segmentation problems caused by blurred or broken parcel boundaries.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-3-uav-fields" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="./images/uav_field_parcels/image3.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;30.3: Field parcels detected by vectorization.</figcaption></figure>
</div>
</div>
</div>
</section><section id="conclusions" class="level2" data-number="30.5"><h2 data-number="30.5" class="anchored" data-anchor-id="conclusions">
<span class="header-section-number">30.5</span> Conclusions</h2>
<p>The CPVF approach enables end-to-end acquisition of vectorized instance-level CFP results from ultra-high spatial resolution imagery, without being constrained by specific geographic regions, terrain types (such as plains, hills, or mountains), or parcel distribution density, thus demonstrating applicability across various complex farmland scenes.</p>
<p>The DCP-MTL model innovatively incorporates a DCT module for frequency-domain feature extraction, and its integrated sub-decoder module constructed with deep supervision exhibits generalizable feature learning and multi-task synergy capabilities. Notably, the DBAM and UPMTR modules enhance fine-grained boundary representation and improve the separability of parcel areas, which can be extended to various instance-level object extraction tasks characterized by blurred boundaries or adhered targets. The Universal Vectorization Module (UVM) contributes to improved boundary continuity and enables efficient RTU vectorized delineation, making it suitable for vectorization scenes that require preserving the geometric regularity and topological independence of objects, beyond just CFP extraction.</p>
<p>Experimental results on the UHR-CFP dataset have validated the superiority of the DCP-MTL model, while its stable performance across different farmland scenes further demonstrates that the core concept of the CPVF approach can adapt to ultra-high spatial resolution imagery acquired by various sensors. This provides a universally applicable and complete solution for efficient instance-level object extraction and vectorization. Such generality underscores its significant application value and broad prospects for promotion in the fine-scale management of agricultural, land, ecological, and other domains.</p>
</section><section id="code-and-data-availability" class="level2" data-number="30.6"><h2 data-number="30.6" class="anchored" data-anchor-id="code-and-data-availability">
<span class="header-section-number">30.6</span> Code and data availability</h2>
<p>The code for the model and experiment is available in <a href="https://github.com/BNU-RS/UHR-CFP">Github</a>.</p>
</section><section id="about-the-author" class="level2" data-number="30.7"><h2 data-number="30.7" class="anchored" data-anchor-id="about-the-author">
<span class="header-section-number">30.7</span> About the author</h2>
<p>Jinshui Zhang (email: zhangjs@bnu.edu.cn) is a researcher at the Institute of Remote Sensing Science and Engineering，Faculty of Geographical Science，Beijing Normal University，Beijing，China. His research interests are Remote Sensing, Spatial Statistics, Satellite Image Analysis and Geospatial Science.</p>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./uav_agriculture.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">UAV applications in agricultural statistics</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./uav_wheat_growth.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Application of UAV in Wheat Growth Monitoring</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">Edited by Gilberto Camara, Lorenzo de Simone and Ronald Jansen.</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">This book was built with <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>


</body></html>